# Generated by Django 6.0 on 2026-03-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.studentprofile'),
        ),
    ]
