# Generated by Django 5.2.8 on 2026-04-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedExamConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='Daily Assessment', max_length=255)),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('subjects', models.JSONField(default=list)),
                ('duration', models.IntegerField(default=60)),
                ('passing_strategy', models.CharField(default='percentage', max_length=50)),
                ('requirement', models.IntegerField(default=50)),
                ('question_count', models.IntegerField(default=25)),
                ('marks_per_question', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
