# Generated by Django 6.0.4 on 2026-06-02 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='browser_lock_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='final_verdict',
            field=models.CharField(default='Safe', max_length=50),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AcademicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_requirement', models.CharField(default='PDF, ZIP, Images, Videos, Source code', max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(default='PYTHON', max_length=50)),
                ('duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('total_marks', models.IntegerField(default=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('browser_lock_required', models.BooleanField(default=True)),
                ('webcam_proctoring_required', models.BooleanField(default=True)),
                ('max_violations_allowed', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('APTITUDE', 'Quantitative Aptitude'), ('REASONING', 'Logical Reasoning'), ('ENGLISH', 'Verbal English'), ('PYTHON', 'Python Programming'), ('JAVA', 'Java Developer'), ('SQL', 'SQL Database'), ('REACT', 'React JS Development'), ('DJANGO', 'Django Backend'), ('SPRINGBOOT', 'Spring Boot'), ('CLOUD', 'Cloud Computing')], default='PYTHON', max_length=50)),
                ('topic', models.CharField(blank=True, help_text='e.g., Arrays, OOP, Joins, Hooks', max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='mcq', max_length=20)),
                ('marks', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaperQuestionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='myapp.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('TAB_SWITCH', 'Tab Switching / Focus Loss'), ('FULLSCREEN_EXIT', 'Exited Fullscreen Mode'), ('FACE_MISSING', 'No Face Detected'), ('MULTIPLE_FACE', 'Multiple Faces Detected'), ('PHONE_DETECTED', 'Mobile Phone Detected'), ('COPY_ATTEMPT', 'Copy/Paste/Right Click attempt')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity_score', models.IntegerField(default=5)),
                ('image_snapshot', models.TextField(blank=True, help_text='Base64 or url of violation image', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='myapp.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('ai_generated_summary', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('portfolio_url', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_projects', models.ManyToManyField(blank=True, to='myapp.project')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('description', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myapp.academictask')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('feedback', models.TextField()),
                ('rubric_scores', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='myapp.tasksubmission')),
            ],
        ),
    ]
