# Generated by Django migration to create initial users
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_initial_users(apps, schema_editor):
    User = apps.get_model('myapp', 'User')
    
    users_data = [
        {
            'username': 'admin',
            'email': 'admin@example.com',
            'password': make_password('admin123')
        },
        {
            'username': 'student',
            'email': 'student@example.com', 
            'password': make_password('student123')
        },
        {
            'username': 'test',
            'email': 'test@example.com',
            'password': make_password('test123')
        }
    ]
    
    for user_data in users_data:
        if not User.objects.filter(username=user_data['username']).exists():
            User.objects.create(**user_data)

class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_users),
    ]
