# Generated by Django 5.2.8 on 2026-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Personal', 'Personal'), ('Academic', 'Academic'), ('Family', 'Family'), ('Other', 'Other')], default='Medical', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
