# Generated by Django 5.2.8 on 2026-03-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_email_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginemaillog',
            new_name='myapp_login_user_id_17a05b_idx',
            old_name='myapp_login_user_id_sent_at_idx',
        ),
        migrations.RenameIndex(
            model_name='loginemaillog',
            new_name='myapp_login_is_dele_a6b0b4_idx',
            old_name='myapp_login_is_deleted_sent_at_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
