# Generated by Django 5.2.8 on 2026-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_automatedexamconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Process'), ('accepted', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='automatedexamconfig',
            name='duration',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='automatedexamconfig',
            name='marks_per_question',
            field=models.IntegerField(default=2),
        ),
    ]
