# Generated by Django 6.0 on 2026-03-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_project_student'),
        ('myapp', '0002_alter_skill_student'),
    ]

    operations = [
    ]
