# Generated by Django 6.0 on 2026-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exam_examattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
