# Generated by Django 6.0 on 2026-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_automatedexamconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexamconfig',
            name='duration',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='automatedexamconfig',
            name='marks_per_question',
            field=models.IntegerField(default=2),
        ),
    ]
