# Generated by Django 6.0.4 on 2026-06-02 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_examsession_browser_lock_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('daily', 'Daily Exam'), ('weekly', 'Weekly Exam'), ('monthly', 'Monthly Exam'), ('placement', 'Placement Assessment'), ('mock', 'Mock Interview Test'), ('certification', 'Certification Test')], default='daily', max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=30)),
                ('total_marks', models.IntegerField(default=30)),
                ('pass_marks', models.IntegerField(default=15)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marks', models.FloatField(default=0.0)),
                ('departments', models.JSONField(default=list, help_text="e.g. ['CSE', 'IT']")),
                ('years', models.JSONField(default=list, help_text="e.g. ['2nd Year', '3rd Year']")),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_required', models.BooleanField(default=True)),
                ('fullscreen_required', models.BooleanField(default=True)),
                ('tab_switch_limit', models.IntegerField(default=3)),
                ('face_detection', models.BooleanField(default=True)),
                ('multi_face_detection', models.BooleanField(default=True)),
                ('screenshot_interval', models.IntegerField(default=30)),
                ('auto_submit', models.BooleanField(default=True)),
                ('risk_threshold', models.IntegerField(default=50)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='myapp.placementexam')),
            ],
        ),
    ]
