# Generated by Django 6.0.4 on 2026-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_placementexam_placementexamsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='webcam_proctoring_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='webcam_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placementexamsettings',
            name='webcam_required',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WebcamSnapshot',
        ),
    ]
