# Generated by Django 5.2.8 on 2026-03-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_initial_users'),
        ('myapp', '0003_playground'),
    ]

    operations = [
    ]
