# Generated by Django 6.0 on 2026-03-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_exam_score_exam_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('marks', models.PositiveIntegerField(default=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='myapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], max_length=10)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong', 'Wrong Answer'), ('error', 'Runtime Error'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.codingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('time_limit_seconds', models.PositiveIntegerField(default=60)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='myapp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='myapp.codingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mcqquestion')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
