# Generated by Django 6.0 on 2026-04-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_appliedjob_status_and_more'),
        ('myapp', '0003_alter_automatedexamconfig_duration_and_more'),
    ]

    operations = [
    ]
