# Generated by Django 5.2.8 on 2026-04-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_appliedjob_status_and_more'),
        ('myapp', '0003_alter_automatedexamconfig_duration_and_more'),
    ]

    operations = [
    ]
