# Generated by Django 6.0 on 2026-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20260320_1730'),
    ]

    operations = [
        # Field already exists in DB, operation cleared to prevent Duplicate Column Error
    ]
