# Generated by Django 6.0 on 2026-03-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20260320_1730'),
        ('myapp', '0004_examattempt_exam_type'),
    ]

    operations = [
    ]
