# Generated by Django 6.0 on 2026-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_codingquestion_codesubmission_mcqquestion_testcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding'), ('both', 'MCQ + Coding')], default='mcq', max_length=10),
        ),
    ]
