# Generated by Django 6.0 on 2026-03-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_studentprofile_education_studentprofile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=50),
        ),
    ]
