# Generated by Django 6.0 on 2026-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20260320_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='exam_type',
            field=models.CharField(default='daily', max_length=50),
        ),
    ]
