# Generated by Django 5.2.8 on 2026-03-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_exam_examattempt'),
        ('myapp', '0005_codesnippet_codetemplate_executionsession'),
    ]

    operations = [
    ]
