# Generated by Django 6.0 on 2026-03-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20260320_1928'),
        ('myapp', '0006_examattempt_exam_type'),
    ]

    operations = [
    ]
