# Generated by Django 5.2.8 on 2026-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_password_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
