# Generated by Django 6.0 on 2026-03-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_studentprofile_student_id'),
        ('myapp', '0004_job_jobapplication'),
        ('myapp', '0005_exam_exam_type'),
        ('myapp', '0006_merge_20260311_1031'),
    ]

    operations = [
    ]
