# Generated by Django 6.0.4 on 2026-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_studentprofile_student_id_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_student', 'New Student Registration'), ('new_faculty', 'New Faculty Registration'), ('system', 'System Alert'), ('leave', 'Leave Request')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_username', models.CharField(blank=True, max_length=150, null=True)),
                ('related_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_admin_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
