# Generated by Django 5.2.8 on 2026-03-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_20260311_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
    ]
