# Generated by Django 5.2.8 on 2026-03-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_merge_20260321_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave / Medical Leave'), ('EL', 'Earned Leave / Privilege Leave'), ('PTO', 'Paid Time Off'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('BL', 'Bereavement Leave'), ('CO', 'Compensatory Off'), ('PH', 'Public Holidays'), ('LWP', 'Loss of Pay / Leave Without Pay'), ('WFH', 'Work From Home / Remote Leave'), ('SAB', 'Sabbatical Leave'), ('MRL', 'Marriage Leave'), ('STL', 'Study / Examination Leave')], default='SL', max_length=20),
        ),
    ]
