# Generated by Django 6.0 on 2026-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_email_password_encrypted'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='loginemaillog',
        #     name='myapp_login_is_dele_a6b0b4_idx',
        # ),
        migrations.AddIndex(
            model_name='loginemaillog',
            index=models.Index(fields=['email_address', '-sent_at'], name='myapp_login_email_a_bf2618_idx'),
        ),
    ]
