# Generated by Django 5.2.8 on 2026-03-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_examattempt_exam_delete_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=20)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=40)),
                ('time_taken', models.IntegerField(help_text='Time taken in seconds')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('terminated', 'Terminated')], default='completed', max_length=20)),
                ('random_id', models.CharField(blank=True, max_length=4, null=True)),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('answers_json', models.TextField(blank=True, null=True)),
                ('questions_json', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='myapp.user')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
    ]
