# Generated by Django 6.0 on 2026-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_loginemaillog_myapp_login_is_dele_a6b0b4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
