# Generated by Django 6.0.4 on 2026-07-21 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_job_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='is_eligible_for_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
