# Generated by Django 5.2.8 on 2026-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_job_eligibility_job_experience_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
