# Generated by Django 6.0 on 2026-04-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_loginemaillog_myapp_login_is_dele_a6b0b4_idx_and_more'),
    ]

    operations = [
    ]
