# Generated by Django 6.0 on 2026-03-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_course_courseenrollment_coursetopic_and_more'),
        ('myapp', '0009_job_description_alter_job_responsibilities'),
    ]

    operations = [
    ]
