# Generated by Django 5.2.8 on 2026-03-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_job_description_alter_job_responsibilities'),
        ('myapp', '0010_emailconfiguration'),
    ]

    operations = [
    ]
