# Generated by Django 6.0 on 2026-03-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_emailconfiguration'),
        ('myapp', '0010_merge_20260326_1547'),
    ]

    operations = [
    ]
