# Generated by Django 6.0 on 2026-04-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_loginemaillog_myapp_login_is_dele_a6b0b4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_application_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
