# Generated by Django 6.0.4 on 2026-07-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_liveclasssession'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('video', 'Video Lecture'), ('material', 'Study Material / PDF'), ('notes', 'Class Notes')], default='material', max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='Link to PDF / Material', max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Link to recorded lecture', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='myapp.batch')),
            ],
        ),
    ]
