# Generated by Django 6.0 on 2026-03-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_merge_20260326_1559'),
        ('myapp', '0011_merge_20260326_1600'),
    ]

    operations = [
    ]
