# Generated by Django 6.0.4 on 2026-07-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_batch_faculty_exam_batch_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
