# Generated by Django 6.0 on 2026-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_add_course_to_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
