# Generated by Django 6.0.4 on 2026-07-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_login_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_materials',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
