# Generated by Django 6.0 on 2026-04-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('awarding_organization', models.CharField(blank=True, max_length=200)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='faculty_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_faculty_achievement',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='FacultyCourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('co_instructor', 'Co-Instructor'), ('assistant', 'Teaching Assistant'), ('guest', 'Guest Lecturer')], default='instructor', max_length=20)),
                ('student_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_faculty_course_history',
                'ordering': ['-year', '-semester'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='faculty_avatars/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, default=list, null=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('specialization', models.JSONField(blank=True, default=list, null=True)),
                ('education', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('publications', models.JSONField(blank=True, default=list, null=True)),
                ('research_interests', models.JSONField(blank=True, default=list, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('courses_taught', models.IntegerField(default=0)),
                ('students_mentored', models.IntegerField(default=0)),
                ('publications_count', models.IntegerField(default=0)),
                ('experience_years', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'myapp_faculty_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('research_type', models.CharField(choices=[('publication', 'Publication'), ('project', 'Research Project'), ('thesis', 'Thesis'), ('presentation', 'Presentation')], default='publication', max_length=20)),
                ('journal_or_conference', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('doi', models.URLField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='faculty_research/')),
                ('collaborators', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'myapp_faculty_research',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='external_application_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultycoursehistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultycoursehistory',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='myapp.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultyachievement',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='myapp.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultyresearch',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='myapp.facultyprofile'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['user'], name='myapp_facul_user_id_b78667_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['department'], name='myapp_facul_departm_f7f7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['designation'], name='myapp_facul_designa_d374b2_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['-created_at'], name='myapp_facul_created_f87267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facultycoursehistory',
            unique_together={('faculty_profile', 'course', 'semester', 'year')},
        ),
    ]
