# Generated by Django 6.0 on 2026-04-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_facultyachievement_facultycoursehistory_and_more'),
    ]

    operations = [
#        migrations.RemoveIndex(
#            model_name='loginemaillog',
#            name='myapp_login_is_dele_a6b0b4_idx',
#        ),
        migrations.RemoveField(
            model_name='job',
            name='external_application_link',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
