# Generated by Django 6.0.7 on 2026-07-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_course_study_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id_val', models.CharField(blank=True, max_length=100, null=True)),
                ('action_type', models.CharField(choices=[('registration', 'Registration'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('created', 'Account Created'), ('updated', 'Profile Updated'), ('course_assigned', 'Course Assigned'), ('status_toggled', 'Status Toggled'), ('deleted', 'Account Deleted')], default='updated', max_length=50)),
                ('action_title', models.CharField(max_length=255)),
                ('performed_by', models.CharField(default='System', max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'myapp_student_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
