# Generated by Django 6.0.7 on 2026-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_studentauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchresource',
            name='file_url',
            field=models.TextField(blank=True, help_text='Link or base64 data URL for PDF / Material', null=True),
        ),
        migrations.AlterField(
            model_name='batchresource',
            name='video_url',
            field=models.TextField(blank=True, help_text='Link or base64 data URL for recorded lecture', null=True),
        ),
    ]
