# Generated by Django 6.0 on 2026-04-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_loginemaillog_myapp_login_is_dele_a6b0b4_idx_and_more'),
        ('myapp', '0017_alter_facultyprofile_name_fields'),
    ]

    operations = [
    ]
