# Generated by Django 5.2.8 on 2026-04-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_add_user_to_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='total_marks',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='total_questions',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='facultyachievement',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='myapp.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='facultycoursehistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='facultycoursehistory',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='myapp.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyresearch',
            name='faculty_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='myapp.facultyprofile'),
        ),
    ]
