"""
Django settings for placement project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Configure PyMySQL to act as mysqlclient
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIR = BASE_DIR / 'templates'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-enil$!t5ru!52i$u(2+flpeyar2v_&n7wpvk14$t9i2f#et+km'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# 🛡️ 1000% SECURE NETWORK TRUST (LAN/WAN MODE)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]

# Dynamically add all network/LAN interface IPs to trusted origins
import socket
try:
    hostname = socket.gethostname()
    local_ips = socket.gethostbyname_ex(hostname)[2]
    for ip in local_ips:
        CSRF_TRUSTED_ORIGINS.append(f"http://{ip}:5173")
        CSRF_TRUSTED_ORIGINS.append(f"http://{ip}:5174")
except Exception:
    pass

# Trust the global VM IP
CSRF_TRUSTED_ORIGINS.extend([
    "http://40.192.98.128:5173",
    "http://40.192.98.128:5174",
])

# Accept all origins for local development to avoid 403 on different laptop hostnames
CSRF_ALLOW_WILD_CARD = True 


AUTH_USER_MODEL = 'myapp.User'


# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Overridden below for SMTP
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myapp',
    'corsheaders',
    'django_ratelimit',
]

ALLOWED_HOSTS = ['*']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Global Exception Handling Middleware
    'myapp.middleware.ExceptionMiddleware',
]

ROOT_URLCONF = 'placement.urls'

# Templates moved to end of file

WSGI_APPLICATION = 'placement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Detect if running inside Docker
IS_DOCKER = os.path.exists('/.dockerenv') or os.environ.get('DOCKER_CONTAINER') == 'true'

# Local development defaults:
# - inside Docker container: connect to service name `db` on port 3306
# - outside Docker with a native MySQL install: connect to localhost on port 3306
# - outside Docker with the compose MySQL container mapped to host: use DB_PORT=3307
DB_HOST = os.environ.get('DB_HOST', 'db' if IS_DOCKER else '127.0.0.1')
DB_PORT = os.environ.get('DB_PORT', '3306')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'placementdb'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '2004'),
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
        }
    }
}

# Email settings moved or defined below

# Email configuration constants
ADMIN_EMAIL = 'sssitprojectteam3@gmail.com'
PLATFORM_NAME = 'SSSIT Placement Portal'
PLATFORM_URL = os.environ.get('PLATFORM_URL', 'http://localhost')

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Configuration driven by environment or defaults
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'sssitprojectteam3@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'yogu cqnr qfjj mftb')

# Dynamic Host Selection Logic
def get_email_host(user_email):
    env_host = os.environ.get('EMAIL_HOST')
    if env_host:
        return env_host
    
    domain = user_email.split('@')[-1].lower()
    if domain == 'gmail.com':
        return 'smtp.gmail.com'
    elif domain in ['outlook.com', 'hotmail.com', 'sssit.info']:
        return 'smtp.office365.com'
    # Default fallback
    return 'smtp.gmail.com'

EMAIL_HOST = get_email_host(EMAIL_HOST_USER)
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '30'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# SMTP safety: TLS and SSL cannot be enabled at the same time.
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    EMAIL_USE_SSL = False



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # ── Rate Limiting (Throttling) ──────────────────────────────────────
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',   # unauthenticated users
        'rest_framework.throttling.UserRateThrottle',   # authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',   # 30 requests/min for guests (login, register)
        'user': '200/minute',  # 200 requests/min for logged-in students/faculty
        'login': '10/minute',  # custom scope for login endpoint
        'exam': '60/minute',   # custom scope for exam submission endpoints
    },
}

# JWT settings merged below

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Templates
# https://docs.djangoproject.com/en/6.0/topics/templates/

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Email settings consolidated above in dynamic selection logic
LEAVE_EMAIL_ENABLED = os.environ.get('LEAVE_EMAIL_ENABLED', 'True').lower() == 'true'

# Login email auto‑cleanup (env‑driven to keep it dynamic)
LOGIN_EMAIL_AUTO_DELETE_ENABLED = os.environ.get('LOGIN_EMAIL_AUTO_DELETE_ENABLED', 'True').lower() == 'true'
LOGIN_EMAIL_MAX_ACTIVE = int(os.environ.get('LOGIN_EMAIL_MAX_ACTIVE', '30'))
LOGIN_EMAIL_DELETE_BATCH = int(os.environ.get('LOGIN_EMAIL_DELETE_BATCH', os.environ.get('LOGIN_EMAIL_MAX_ACTIVE', '30')))
LOGIN_EMAIL_SUBJECT_KEYWORD = os.environ.get('LOGIN_EMAIL_SUBJECT_KEYWORD', 'Login Confirmation')
LOGIN_EMAIL_MAILBOX = os.environ.get('LOGIN_EMAIL_MAILBOX', 'INBOX')
LOGIN_EMAIL_IMAP_TIMEOUT = int(os.environ.get('LOGIN_EMAIL_IMAP_TIMEOUT', '10'))
LOGIN_EMAIL_IMAP_ENABLED = os.environ.get('LOGIN_EMAIL_IMAP_ENABLED', 'True').lower() == 'true'
LOGIN_EMAIL_IMAP_USERNAME = os.environ.get('LOGIN_EMAIL_IMAP_USERNAME', EMAIL_HOST_USER)
LOGIN_EMAIL_IMAP_PASSWORD = os.environ.get('LOGIN_EMAIL_IMAP_PASSWORD', EMAIL_HOST_PASSWORD)


# ── Cache (used by rate limiting) ──────────────────────────────────────────
# Uses local memory by default — no Redis needed for single-server deployments.
# Switch to RedisCache if you scale to multiple EC2 instances.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'placement-ratelimit-cache',
    }
}

# ── Rate Limit Config (django-ratelimit) ───────────────────────────────────
RATELIMIT_ENABLE = True          # Set False in tests to disable globally
RATELIMIT_USE_CACHE = 'default'  # Which cache backend to use
RATELIMIT_FAIL_OPEN = False      # If cache fails, DENY requests (secure default)

# Silence django-ratelimit system check errors for using LocMemCache
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

