"""
Django settings for placement project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES_DIR = BASE_DIR / 'templates'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-enil$!t5ru!52i$u(2+flpeyar2v_&n7wpvk14$t9i2f#et+km'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# 🛡️ 1000% SECURE NETWORK TRUST (LAN MODE)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]
# Accept all origins for local development to avoid 403 on different laptop hostnames
CSRF_ALLOW_WILD_CARD = True 


AUTH_USER_MODEL = 'myapp.User'


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myapp',
    'corsheaders',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Global Exception Handling Middleware
    'myapp.middleware.ExceptionMiddleware',
]

ROOT_URLCONF = 'placement.urls'

# Templates moved to end of file

WSGI_APPLICATION = 'placement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'placementdb',
        'USER': 'root',
        'PASSWORD': '2004',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Email settings moved or defined below

# Email configuration constants
ADMIN_EMAIL = 'admin@sssit.info'
PLATFORM_NAME = 'SSSIT Placement Portal'
PLATFORM_URL = 'http://localhost:5174'



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT settings merged below

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Templates
# https://docs.djangoproject.com/en/6.0/topics/templates/

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Email
# Fill these values directly if you want the leave-request backend to use SMTP
# without setting environment variables.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'admin@sssit.info')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'oxda ouau iwli zefd')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '30'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'admin@sssit.info')
LEAVE_EMAIL_ENABLED = os.environ.get('LEAVE_EMAIL_ENABLED', 'True').lower() == 'true'

# Login email auto‑cleanup (env‑driven to keep it dynamic)
LOGIN_EMAIL_AUTO_DELETE_ENABLED = os.environ.get('LOGIN_EMAIL_AUTO_DELETE_ENABLED', 'True').lower() == 'true'
LOGIN_EMAIL_MAX_ACTIVE = int(os.environ.get('LOGIN_EMAIL_MAX_ACTIVE', '30'))
LOGIN_EMAIL_DELETE_BATCH = int(os.environ.get('LOGIN_EMAIL_DELETE_BATCH', os.environ.get('LOGIN_EMAIL_MAX_ACTIVE', '30')))
LOGIN_EMAIL_SUBJECT_KEYWORD = os.environ.get('LOGIN_EMAIL_SUBJECT_KEYWORD', 'Login Confirmation')
LOGIN_EMAIL_MAILBOX = os.environ.get('LOGIN_EMAIL_MAILBOX', 'INBOX')
LOGIN_EMAIL_IMAP_TIMEOUT = int(os.environ.get('LOGIN_EMAIL_IMAP_TIMEOUT', '10'))
LOGIN_EMAIL_IMAP_ENABLED = os.environ.get('LOGIN_EMAIL_IMAP_ENABLED', 'True').lower() == 'true'
LOGIN_EMAIL_IMAP_USERNAME = os.environ.get('LOGIN_EMAIL_IMAP_USERNAME', EMAIL_HOST_USER)
LOGIN_EMAIL_IMAP_PASSWORD = os.environ.get('LOGIN_EMAIL_IMAP_PASSWORD', EMAIL_HOST_PASSWORD)



