from .auth_views import *
from .profile_views import *
from .exam_views import *
from .examreports_views import *
from .playground_views import *
from .job_views import *

# Module imports for urls.py
from . import course_views
from . import html_views
from . import css_views
from . import javascript_views
from . import bootstrap_views
from . import oracle_views
from . import java_views
from . import react_views
from . import django_views
from . import python_views

# NEW SUBJECTS
from . import Hibernate_views
from . import JDBC_views
from . import Pandas_views
from . import Reports_views
from . import Spring_views
from . import ai_concepts_views
from . import android_views
from . import api_testing_views
from . import asp_net_mvc_views
from . import augmented_reality_views
from . import big_data_tools_views
from . import c_data_structures_views
from . import c_sharp_views
from . import ci_cd_views
from . import cloud_basics_views
from . import computer_fundamentals_views
from . import dashboards_views
from . import data_handling_views
from . import data_modeling_views
from . import ui_views
from . import backend_views
from . import data_visualization_views
from . import database_basics_views
from . import deep_learning_views
from . import deployment_views
from . import docker_views
from . import ec2_s3_views
from . import ethereum_views
from . import ethical_hacking_views
from . import etl_pipelines_views
from . import excel_views
from . import express_js_views
from . import flutter_react_native_views
from . import generative_ai_views
from . import git_github_views
from . import google_cloud_views
from . import iam_views
from . import ios_swift_views
from . import power_query_views
from . import claude_views
from . import kubernetes_basics_views
from . import machine_learning_views
from . import microsoft_azure_views
from . import mongodb_views
from . import DAX_views
from . import gpt_views
from . import ms_office_views
from . import ms_word_views
from . import network_security_views
from . import node_js_views
from . import numpy_views
from . import oops_cpp_views
from . import penetration_testing_views
from . import powerpoint_views
from . import programming_basics_views
from . import python_data_science_views
from . import qa_processes_views
from . import selenium_views
from . import smart_contracts_views
from . import virtual_reality_views
from . import web3_views
from . import web_apis_views
from . import springboot_views
