import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_aiconcepts_api(request):
    questions_pool = [
        {"id": 1, "question": "What does 'AI' stand for?", "options": ["Artificial Intelligence", "Advanced Integration", "Automatic Information", "None"], "correct": 0},
        {"id": 2, "question": "What is the primary goal of AI?", "options": ["Creating faster hardware", "Simulating human intelligence in machines", "A type of table", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Turing Test'?", "options": ["A test for internet speed", "A test to determine if a machine's behavior is indistinguishable from a human", "A security log", "None"], "correct": 1},
        {"id": 4, "question": "Who is considered the father of AI?", "options": ["Alan Turing", "John McCarthy", "Bill Gates", "Both A and B"], "correct": 1},
        {"id": 5, "question": "What is 'Narrow AI' (Weak AI)?", "options": ["A very thin machine", "AI specifically trained for a single task (e.g. Chess, Siri)", "AI that can do everything", "None"], "correct": 1},
        {"id": 6, "question": "What is 'General AI' (AGI / Strong AI)?", "options": ["AI that can understand or learn any intellectual task a human can", "AI for general stores", "A type of chart", "None"], "correct": 0},
        {"id": 7, "question": "What is 'Super AI' (ASI)?", "options": ["A superhero in AI", "Speculative AI that surpasses human intelligence in every way", "Neither", "Both"], "correct": 1},
        {"id": 8, "question": "What is 'Machine Learning' (ML)?", "options": ["Learning how to build a machine", "A subset of AI where systems learn Patterns from data", "Neither", "Both"], "correct": 1},
        {"id": 9, "question": "What is 'Deep Learning'?", "options": ["Deep thinking", "ML based on artificial neural networks with multiple layers", "None", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Natural Language Processing' (NLP)?", "options": ["Learning languages for people", "The ability of machines to understand, interpret, and generate human language", "A search tool", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Computer Vision'?", "options": ["Better glasses for programmers", "Allowing machines to identify and process visual information like images/videos", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'Expert System'?", "options": ["A system for experts", "A software designed to simulate human expert decision-making in specific domains", "Both", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Robotics' in AI context?", "options": ["Building physical machines (robots) that can perform tasks semi-autonomously", "Deleting code", "Both", "None"], "correct": 0},
        {"id": 14, "question": "What is 'Neural Network'?", "options": ["A set of interconnected nodes (neurons) that process data like a brain", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What's the meaning of 'Bias' in AI?", "options": ["Prejudice or unfairness in AI output due to training data or algorithm design", "A mathematical result", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'AI Ethics'?", "options": ["Principles used to ensure AI is developed and used responsibly and safely", "Rules for users", "None", "None"], "correct": 0},
        {"id": 17, "question": "What is 'Generative AI' (GenAI)?", "options": ["Creating new content (images, text, audio) using patterns from existing data", "Generating power", "Both", "None"], "correct": 0},
        {"id": 18, "question": "Which of these is a famous AI chatbot?", "options": ["ChatGPT", "Claude", "Gemini", "All of the above"], "correct": 3},
        {"id": 19, "question": "What's 'Heuristic' in AI problem solving?", "options": ["A rule of thumb or shortcut to find a good enough solution quickly", "A formal proof", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Search Algorithm' in AI?", "options": ["An algorithm used to find the best path/solution (e.g. A*, BFS, DFS)", "Searching for files", "Both", "None"], "correct": 0},
        {"id": 21, "question": "What is 'AI hallucination'?", "options": ["Seeing ghosts in movies", "When an AI (like an LLM) generates confident but incorrect/nonsensical info", "Neither", "Both"], "correct": 1},
        {"id": 22, "question": "What is 'Prompt'?", "options": ["The input or instruction given to an AI model to get a specific output", "A fast computer speed", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What's 'Feature' in AI data context?", "options": ["An individual measurable property used to represent an object", "A special part of an app", "Both", "None"], "correct": 0},
        {"id": 24, "question": "What is 'Reinforcement' in learning?", "options": ["Rewarding or punishing a model based on its actions to improve performance", "Reinforcing a house", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What's the role of 'Big Data' in AI?", "options": ["Providing the massive datasets needed for models to learn accurately", "A very large computer brand", "Both", "None"], "correct": 0},
        {"id": 26, "question": "What is 'Cognitive Computing'?", "options": ["AI that mimics human thought processes for problem solving and interaction", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Singularity' in speculative AI?", "options": ["A mathematical point", "The hypothetical point where AI exceeds human intelligence beyond control", "Both", "None"], "correct": 1},
        {"id": 28, "question": "What is 'AI as a Service' (AIaaS)?", "options": ["Paying for someone to do AI for you", "Offering AI capabilities via cloud-based APIs to other businesses", "None", "None"], "correct": 1},
        {"id": 29, "question": "Which constant is used to denote uncertainty in some AI models?", "options": ["Probability", "Fuzzy Logic", "Both", "Neither"], "correct": 0},
        {"id": 30, "question": "Which of these industries uses AI for better performance?", "options": ["Healthcare", "Finance", "Transportation", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Explainable AI' (XAI)?", "options": ["AI that can explain how it arrived at a decision to humans", "AI with a help guide", "Both", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Autonomous' system?", "options": ["A system for cars only", "A system capable of operating and making decisions without human intervention", "Neither", "Both"], "correct": 1},
        {"id": 33, "question": "What is 'Swarm Intelligence'?", "options": ["Thinking like a swarm of bees", "Collective behavior of decentralized, self-organized AI systems", "Both", "None"], "correct": 1},
        {"id": 34, "question": "What is 'Genetic Algorithm' in AI?", "options": ["Learning about human genes", "A search-based heuristic inspired by the process of natural selection", "None", "None"], "correct": 1},
        {"id": 35, "question": "What is 'Fuzzy Logic'?", "options": ["A logic for people with bad memory", "A mathematical logic representing degrees of truth (rather than 0 or 1)", "Neither", "Both"], "correct": 1},
        {"id": 36, "question": "What's the meaning of 'Knowledge Representation'?", "options": ["Storing info in a way machine can use to solve complex tasks (e.g. ontologies)", "Drawing charts", "Both", "None"], "correct": 0},
        {"id": 37, "question": "What is 'Ontology' in AI context?", "options": ["A set of concepts and categories representing a domain of interest", "A book name", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is an 'Agent'?", "options": ["A person in charge", "An autonomous entity that observes and acts upon an environment to achieve goals", "A security log", "None"], "correct": 1},
        {"id": 39, "question": "What's 'Augmented Intelligence' different from AI?", "options": ["AI that assists humans rather than replacing them", "Fast thinking", "Both", "None"], "correct": 0},
        {"id": 40, "question": "What is 'LLM' (Large Language Model)?", "options": ["Large List Mode", "AI trained on massive text to understand and generate human-like language", "Both", "None"], "correct": 1},
        {"id": 41, "question": "What is 'Fine-Tuning'?", "options": ["Tuning a radio", "Adapting a pre-trained model on a smaller, specific dataset for special tasks", "Neither", "Both"], "correct": 1},
        {"id": 42, "question": "What is 'Transfer Learning' in AI?", "options": ["Passing knowledge from one model to another related task to save time", "Moving files", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Emotion AI' (Affective Computing)?", "options": ["AI with artificial feelings", "Studying and developing systems that recognize and interpret human emotions", "Neither", "Both"], "correct": 1},
        {"id": 44, "question": "What is 'Facial Recognition'?", "options": ["Identifying faces in images/videos using AI", "Better glasses", "Both", "None"], "correct": 0},
        {"id": 45, "question": "What is 'Object Detection' in computer vision?", "options": ["Identifying objects and their locations within a digital image/video", "Deleting objects", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's 'Semantic Segmentation'?", "options": ["Splitting a large book", "Classifying each pixel in an image to belong to a specific object/category", "Neither", "Both"], "correct": 1},
        {"id": 47, "question": "What is 'Recommendation Engine' (e.g. Netflix, Amazon)?", "options": ["AI providing personalized content based on user history and behavior", "A search tool", "Both", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Collaborative Filtering'?", "options": ["Recommending items by identifying similar users and groups", "Deleting data", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's 'Edge AI'?", "options": ["AI on the edge of a mountain", "Running AI models locally on a device (phone, sensor) instead of the cloud", "Neither", "Both"], "correct": 1},
        {"id": 50, "question": "What's 'Privacy-Preserving AI'?", "options": ["AI that keeps data secret during training (e.g. federated learning)", "Deleting privacy", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Federated Learning'?", "options": ["Learning in a federation", "Training models across decentralized servers holding local data samples", "Both", "None"], "correct": 1},
        {"id": 52, "question": "What is 'Symbolic AI' (GOFAI)?", "options": ["AI using high-level symbols to represent knowledge and logical rules", "Using icons only", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Sub-symbolic AI'?", "options": ["Learning through brain-like neural network connections (connectionism)", "A secret icon", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'Self-Supervised Learning'?", "options": ["Learning without any help", "Training a model by having it predict parts of its own unlabeled data", "Neither", "Both"], "correct": 1},
        {"id": 55, "question": "What is 'Zero-Shot Learning'?", "options": ["Zero chance of learning", "The ability of a model to recognize concepts it has never seen during training", "Both", "None"], "correct": 1},
        {"id": 56, "question": "What is 'Few-Shot Learning'?", "options": ["Learning with very few examples", "A quick lesson", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's 'Tokenization' in NLP?", "options": ["Splitting text into individual units (tokens) like words or characters", "Giving out coins", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Word Embedding'?", "options": ["Assigning words to a dictionary", "Mapping words into vectors of numbers based on their meanings/context", "Neither", "Both"], "correct": 1},
        {"id": 59, "question": "What is 'Sequence-to-Sequence' (Seq2Seq)?", "options": ["Translating one sequence to another (e.g. Google Translate)", "A type of chart", "Both", "None"], "correct": 0},
        {"id": 60, "question": "What is an 'Attention Mechanism' in neural networks?", "options": ["Paying attention to the user", "Directing focus to specific parts of input data during processing", "Neither", "Both"], "correct": 1},
        {"id": 61, "question": "What is a 'Transformer' architecture (e.g. BERT, GPT)?", "options": ["A robotic toy only", "State-of-the-art model type based purely on attention mechanisms", "Both", "None"], "correct": 1},
        {"id": 62, "question": "What's 'Perception' in AI context?", "options": ["The ability of an agent to receive and interpret sensory data", "Thinking really hard", "Both", "None"], "correct": 0},
        {"id": 63, "question": "What is 'Planning' in AI?", "options": ["Planning a party", "Choosing a sequence of actions that leads from a current state to a goal", "A routing name", "None"], "correct": 1},
        {"id": 64, "question": "What is 'Probabilistic AI'?", "options": ["Dealing with uncertainty using probability theory and statistics", "Calculating results", "None", "None"], "correct": 0},
        {"id": 65, "question": "What is 'A* Search'?", "options": ["A highly efficient pathfinding and graph traversal algorithm", "A star in the sky", "Both", "None"], "correct": 0},
        {"id": 66, "question": "What's the meaning of 'State Space'?", "options": ["Space in a country", "The set of all possible configurations or states in a search problem", "Both", "None"], "correct": 1},
        {"id": 67, "question": "What is the 'Backpropagation'?", "options": ["Updating home address", "The core algorithm used to adjust weights in a neural network during training", "Both", "None"], "correct": 1},
        {"id": 68, "question": "What is status of 'DeepBlue' in AI history?", "options": ["IBM's computer that defeated Garry Kasparov at chess in 1997", "A video game", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'AlphaGo'?", "options": ["Googles program that defeated the world champion in Go", "A fast car", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's 'Chatbot'?", "options": ["A person who likes to talk", "A program designed to communicate via text or voice and simulate conversation", "None", "None"], "correct": 1},
        {"id": 71, "question": "What is 'Virtual Assistant' (e.g. Alexa, Siri)?", "options": ["An AI agent that performs tasks or services for an individual", "Better office", "Both", "None"], "correct": 0},
        {"id": 72, "question": "What is 'AI Alignment'?", "options": ["Aligning physical machines", "The research goal of ensuring AI systems match human values and goals", "Both", "None"], "correct": 1},
        {"id": 73, "question": "What's 'Dark Data'?", "options": ["Hidden or unanalyzed data within organizations that could contain AI value", "Secret files", "Both", "None"], "correct": 0},
        {"id": 74, "question": "What is 'AI democratizing'?", "options": ["Making AI accessible to everyone, not just large tech companies", "Electing AI", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Bias detection'?", "options": ["Identifying unfairness in datasets or outputs using tools and audits", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Which of these is used for image generation?", "options": ["Stable Diffusion", "Midjourney", "DALL-E", "All of the above"], "correct": 3},
        {"id": 77, "question": "What's the result of 'AI safety'?", "options": ["A framework for preventing unintended/harmful consequences from AI", "A password", "Both", "None"], "correct": 0},
        {"id": 78, "question": "What is the 'Chinese Room' argument?", "options": ["A thought experiment about machine intelligence and understanding", "A physical room in China", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which of these is an AI framework?", "options": ["TensorFlow", "PyTorch", "Hugging Face", "All of the above"], "correct": 3},
        {"id": 80, "question": "Which of these is a popular tool for building GenAI applications?", "options": ["LangChain", "LlamaIndex", "Both A and B", "Neither"], "correct": 2},
        {"id": 81, "question": "What is 'Neural Network'?", "options": ["Computing system inspired by biological neural networks", "Network of nerves", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Deep Learning'?", "options": ["Machine learning with artificial neural networks", "Learning deeply", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Computer Vision'?", "options": ["AI field for visual data processing", "Computer vision problems", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Natural Language Processing'?", "options": ["AI field for human language processing", "Language processing", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Reinforcement Learning'?", "options": ["Learning through rewards and punishments", "Learning by reinforcement", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Supervised Learning'?", "options": ["Learning with labeled data", "Learning with supervision", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Unsupervised Learning'?", "options": ["Learning with unlabeled data", "Learning without supervision", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Transfer Learning'?", "options": ["Using pre-trained models for new tasks", "Learning transfer", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Feature Engineering'?", "options": ["Creating features for machine learning", "Engineering features", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Overfitting'?", "options": ["Model performing well on training data but poorly on test data", "Fitting too much", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Underfitting'?", "options": ["Model performing poorly on both training and test data", "Fitting too little", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Cross Validation'?", "options": ["Technique for evaluating model performance", "Validating cross", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Ensemble Learning'?", "options": ["Combining multiple models for better performance", "Learning ensemble", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Random Forest'?", "options": ["Ensemble learning method using decision trees", "Forest with random trees", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Support Vector Machine'?", "options": ["Classification and regression algorithm", "Support vector machine", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'K-Means Clustering'?", "options": ["Unsupervised clustering algorithm", "Clustering with K means", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Principal Component Analysis'?", "options": ["Dimensionality reduction technique", "Principal components", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Gradient Descent'?", "options": ["Optimization algorithm for ML models", "Descent gradient", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Backpropagation'?", "options": ["Algorithm for training neural networks", "Backward propagation", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Convolutional Neural Network'?", "options": ["Neural network for image processing", "Convolution network", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
