import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_android_api(request):
    questions_pool = [
        {"id": 1, "question": "What is the primary OS for Android development?", "options": ["Windows", "Linux (Android is based on it)", "iOS", "None"], "correct": 1},
        {"id": 2, "question": "What is the official IDE for Android development?", "options": ["Xcode", "Android Studio", "IntelliJ IDEA", "Eclipse"], "correct": 1},
        {"id": 3, "question": "Which language is currently preferred for modern Android apps?", "options": ["Java", "Kotlin", "Swift", "Dart"], "correct": 1},
        {"id": 4, "question": "What is 'Activity' in Android?", "options": ["A physical exercise", "A single, focused thing that a user can do (a screen)", "A type of table", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Fragment'?", "options": ["A part of a screen or UI that can be reused in different activities", "A broken piece of code", "None of the above", "None"], "correct": 0},
        {"id": 6, "question": "What is 'Intent' in Android context?", "options": ["A thought by the developer", "A messaging object used to request an action from another app component", "A technical manual", "None"], "correct": 1},
        {"id": 7, "question": "What is 'AndroidManifest.xml' used for?", "options": ["Storing media files", "Providing essential information about the app to the Android system", "Designing UI", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Layout' in Android?", "options": ["A design color", "A visual structure for a user interface (defined in XML)", "A list of strings", "None"], "correct": 1},
        {"id": 9, "question": "What is 'String resources' (strings.xml) for?", "options": ["Defining variable names", "Storing text used in the app for easy localization", "A type of database", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Gradle' for Android?", "options": ["A design tool", "The build automation system used by Android Studio", "A technical specification", "None"], "correct": 1},
        {"id": 11, "question": "What's the difference between a 'Service' and an 'Activity'?", "options": ["Activity is UI-based; Service runs in the background without UI", "Both are the same", "None of the above", "None"], "correct": 0},
        {"id": 12, "question": "What is 'Content Provider' used for?", "options": ["Watching movies", "Managing and sharing access to a structured set of data locally", "An internet provider", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Broadcast Receiver'?", "options": ["A radio component", "A component that responds to system-wide broadcast announcements", "A security feature", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Dalvik Virtual Machine' (DVM)?", "options": ["An old Android runtime", "A modern Android runtime", "Both A and B", "Neither"], "correct": 0},
        {"id": 15, "question": "What is 'ART' (Android Runtime)?", "options": ["A drawing app", "The modern runtime used since Android 4.4/5.0 to replace Dalvik", "None of the above", "None"], "correct": 1},
        {"id": 16, "question": "What's a 'View' in Android context?", "options": ["A web page", "The fundamental building block for user interface components", "A type of database query", "None"], "correct": 1},
        {"id": 17, "question": "What is an 'Adapter' for a list/ListView?", "options": ["A physical power adapter", "A bridge between an AdapterView and the underlying data for that view", "A network tool", "None"], "correct": 1},
        {"id": 18, "question": "What is 'SharedPreferences' used for?", "options": ["Storing large video files", "Storing small amounts of data like user settings in key-value pairs", "A security log", "None"], "correct": 1},
        {"id": 19, "question": "Which component is used for persistent data storage using a structured database?", "options": ["SQLite", "Room", "Both A and B", "Neither"], "correct": 2},
        {"id": 20, "question": "What is 'RecyclerView'?", "options": ["A type of loop", "A flexible and efficient version of ListView for displaying large datasets", "A technical manual", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Jetpack Compose'?", "options": ["A jet engine feature", "Google's modern, declarative UI toolkit for building Android apps", "None of the above", "None"], "correct": 1},
        {"id": 22, "question": "What are 'Permissions' in Android?", "options": ["Rules for users", "Granting an app access to restricted data or system features (e.g., Camera)", "Both A and B", "None"], "correct": 1},
        {"id": 23, "question": "What is 'ANR' in Android context?", "options": ["A type of internet speed", "Application Not Responding (an error when an app is too busy for user input)", "Advanced Network Response", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Logcat'?", "options": ["A place where cats hang out", "A tool to view system logs for debugging and analysis", "A technical specification", "None"], "correct": 1},
        {"id": 25, "question": "What's the meaning of 'APK' file?", "options": ["Android Package Kit", "Advanced Programming Kit", "Alpha Processing Key", "None"], "correct": 0},
        {"id": 26, "question": "What is 'AAB' (Android App Bundle)?", "options": ["A new installer format that optimizes app downloads for users", "A backup system", "A type of table", "None"], "correct": 0},
        {"id": 27, "question": "Which of these is a popular third-party library for network calls?", "options": ["Retrofit", "Volley", "OkHttp", "All of the above"], "correct": 3},
        {"id": 28, "question": "What is 'Material Components' library for?", "options": ["A set of guidelines and UI components that follow Material Design", "Deleting code", "None", "None"], "correct": 0},
        {"id": 29, "question": "How do you handle background tasks without blocking the UI thread?", "options": ["Using main thread for everything", "Using background threads, Coroutines, or AsyncTask (deprecated)", "None of the above", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Android Studio Profiler'?", "options": ["A personal profile for users", "A tool for real-time monitoring of app performance (CPU, Memory, Network)", "None", "None"], "correct": 1},
        {"id": 31, "question": "What is 'OnCreate()' method in Activity?", "options": ["The method specifically where initial setup for the activity happens", "Changing a file", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What represents the 'Activity Lifecycle'?", "options": ["A set of states specifically an activity goes through (Started, Resumed, Paused, etc.)", "The time a person uses the app", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Explicit Intent'?", "options": ["An intent specifically used to launch a specific component (e.g. another activity)", "A rude thought", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Implicit Intent'?", "options": ["Request specifically for an action that can be performed by multiple apps (e.g. open web)", "A hidden meaning", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents specific 'Drawable' in Android?", "options": ["Graphic resources specifically like images, XML shapes, or colors", "A types of pen", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What's the meaning of 'dp' (Density-independent Pixels)?", "options": ["Abstract unit specifically used for layout dimensions to support different screens", "Double pixels", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's the meaning of 'sp' (Scale-independent Pixels)?", "options": ["Unit specifically for font sizes that scales according to user's settings", "Small pixels", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What represents 'View Binding'?", "options": ["A feature specifically that makes it easier to write code that interacts with UI views", "Gluing a screen", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What represents 'Data Binding'?", "options": ["A library specifically that allows tying UI components directly to data sources", "Combining files", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'ViewModel' in Jetpack?", "options": ["Designed specifically to store and manage UI-related data in a lifecycle-conscious way", "A types of computer screen", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'LiveData'?", "options": ["Observable data specifically class that is lifecycle-aware", "Seeing live news", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What represents a 'Flow' in Kotlin/Android?", "options": ["A stream specifically of values that can be computed asynchronously", "A types of river", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'Coroutine' primarily for?", "options": ["Simplifying asynchronous specifically programming by moving long tasks off-thread", "A types of engine", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What represents 'Room' Persistence Library?", "options": ["An abstraction specifically over SQLite to make database work easier", "A types of house part", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What represents 'Dagger/Hilt' in Android?", "options": ["Frameworks specifically for dependency injection to improve modularity", "A types of weapon", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's the meaning of 'Context' in Android?", "options": ["The current status specifically of an application or activity with system access", "A textbook content", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What represents the 'WebView' component?", "options": ["A view specifically that allows displaying web pages inside an Android app", "A types of browser", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What represents 'TabLayout' UI component?", "options": ["A horizontal layout specifically for displaying selectable tabs", "A list of tables", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's 'Toolbar' in modern Android app?", "options": ["The newer specifically replacement for the old ActionBar with more flexibility", "A box of tools", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What represents 'Navigation Drawer'?", "options": ["A sliding panel specifically for main navigation of the app", "A kitchen drawer", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What represents specific 'Notification' in Android?", "options": ["A message specifically displayed outside the app's normal UI (e.g. status bar)", "Sending an email", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What represents 'PendingIntent'?", "options": ["A token specifically allowing an external app (like Notification) to perform action", "A delayed thought", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'WorkManager' used for?", "options": ["Scheduling specifically background tasks that must run reliably (e.g. uploads)", "A boss in an office", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What represents the 'AAR' file library?", "options": ["Android Archive specifically for sharing Android libraries across projects", "A types of sound", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents 'Proguard' or 'R8'?", "options": ["Tool specifically to shrink, optimize and obfuscate app code for release", "A types of code guard", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's the meaning of 'Obfuscation'?", "options": ["Making specifically your source code harder to read for reversed engineering", "Hiding something", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "How to register a Broadcast Receiver in code?", "options": ["Using registerReceiver() method specifically", "Adding to settings", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "How to start a Service in Android?", "options": ["Using startService() specifically or bindService() methods", "Starting a car", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What represents 'Bound Service'?", "options": ["A service specifically that allows components to interact with it synchronously", "A service with limits", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What represents 'Foreground Service'?", "options": ["A service specifically that must show a persistence notification to the user", "A service at front", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What represents 'Inflation' for Android UI?", "options": ["Converting specifically an XML layout file into the actual View objects", "Prices going up", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What represents 'LayoutInflater'?", "options": ["The class specifically used to instantiate XML layout files", "A pump for air", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'View Holder' pattern for?", "options": ["Optimizing specifically list performance by caching view references in RecyclerView", "Someone holding a screen", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What represents the 'Backstack' in navigation?", "options": ["A history specifically of the screens (activities/fragments) the user has visited", "A pile of books", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What represents 'CardView' UI element?", "options": ["A frame specifically with rounded corners and elevation for displaying content", "A types of playing card", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents 'FloatingActionButton' (FAB)?", "options": ["A circular button specifically that appears above the main content to promote action", "A button on water", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents 'Snackbar' in Android?", "options": ["A small popup specifically at the bottom of the screen for brief feedback", "A place to buy food", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents 'Toast' in Android?", "options": ["A simple specifically and small popup that disappears after a short time", "Bread for breakfast", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents 'Vector Asset'?", "options": ["Defining specifically graphics using XML code instead of raw pixel images", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents the 'ADB' (Android Debug Bridge)?", "options": ["A command-line specifically tool to communicate with a connected Android device", "A types of physical bridge", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "How can you view a real device screen on PC?", "options": ["Using 'Scrcpy' specifically or Android Studio's built-in feature", "With a mirror", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents 'Emulators' in Android?", "options": ["Virtual specifically devices used to test apps without physical hardware", "A types of game", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents specific 'Build Variant'?", "options": ["Different specifically versions of the app (e.g. debug vs release)", "A types of car model", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents specific 'Flavors' in Gradle?", "options": ["Allowing specifically to create different versions (e.g. free vs pro) from same app", "Different food tastes", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What represents 'Keystore' in Android publishing?", "options": ["A file containing specifically the cryptographic keys used to sign the APK/AAB", "A shop for keys", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents 'App Signing'?", "options": ["The process specifically of identifying the author of the app for security", "Writing a name on a book", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents 'Play Store'?", "options": ["Google's official specifically app distribution platform for Android", "A store for toys", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents 'Firebase Cloud Messaging' (FCM)?", "options": ["Sending specifically push notifications to Android devices", "Chatting on a cloud", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents 'AdMob' in Android apps?", "options": ["Google's platform specifically for displaying ads and monetizing apps", "A types of crowd", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Android development a great career choice?", "options": ["Huge market share specifically and open ecosystem for developers worldwide", "Because it uses more RAM", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Android Jetpack'?", "options": ["Set of Android components and tools", "A jet pack for Android", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Android Architecture Components'?", "options": ["Set of libraries for Android architecture", "Components for building", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Android Data Binding'?", "options": ["Library for binding UI to data", "Binding data manually", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Android Room Database'?", "options": ["Persistence library for SQLite", "Room for Android", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Android WorkManager'?", "options": ["Library for background work", "Managing work", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Android Navigation Component'?", "options": ["Framework for app navigation", "Navigation in Android", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Android Paging Library'?", "options": ["Library for pagination", "Paging in Android", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Android ViewModel'?", "options": ["UI data storage class", "View model pattern", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Android LiveData'?", "options": ["Observable data holder", "Live data", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Android Coroutine'?", "options": ["Asynchronous programming", "Coroutines in Android", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Android Flow'?", "options": ["Asynchronous data stream", "Flow in Android", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Android Dagger'?", "options": ["Dependency injection framework", "Dagger tool", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Android Hilt'?", "options": ["Dependency injection library", "Hilt tool", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Android Retrofit'?", "options": ["HTTP client library", "Retrofit tool", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Android OkHttp'?", "options": ["HTTP client implementation", "HTTP client", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Android Glide'?", "options": ["Image loading library", "Glide tool", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Android Picasso'?", "options": ["Image loading library", "Picasso tool", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Android Coil'?", "options": ["Image loading library", "Coil tool", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Android Lottie'?", "options": ["Animation library", "Lottie tool", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Android Shimmer'?", "options": ["Shimmer effect library", "Shimmer tool", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
