import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_apitesting_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'API Testing'?", "options": ["Testing a physical phone", "Testing an application programming interface for functionality and security", "None of the above", "None"], "correct": 1},
        {"id": 2, "question": "What does a 'REST API' rely on for communication?", "options": ["HTTP protocols", "FTP protocols", "A separate server", "None"], "correct": 0},
        {"id": 3, "question": "Which of these is a popular tool for manual API testing?", "options": ["Postman", "Insomnia", "Advanced Rest Client", "All of the above"], "correct": 3},
        {"id": 4, "question": "What does a '200 OK' status code indicate?", "options": ["Success", "Error", "Not Found", "Unauthorized"], "correct": 0},
        {"id": 5, "question": "What does a '404 Not Found' status code indicate?", "options": ["Success", "The server couldn't find the requested resource", "A technical specification", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Rest Assured'?", "options": ["A state of mind", "A popular Java library for automated REST API testing", "A type of table", "None"], "correct": 1},
        {"id": 7, "question": "Which HTTP method is used for 'GET'?", "options": ["Retrieving information from a server", "Deleting information", "Updating information", "None"], "correct": 0},
        {"id": 8, "question": "Which HTTP method is used for 'POST'?", "options": ["Updating data", "Submitting new data to a server", "A security feature", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Endpoint' in API testing?", "options": ["An exit point for a server", "A specific URL being tested in an API", "A type of chart", "None"], "correct": 1},
        {"id": 10, "question": "What is 'JSON' commonly used for in API responses?", "options": ["Storing media files", "Lightweight data exchange between client and server", "A type of database", "None"], "correct": 1},
        {"id": 11, "question": "What does 'Statelessness' mean in REST APIs?", "options": ["The server stores data", "The server does not preserve any client state between requests", "A technical manual", "None"], "correct": 1},
        {"id": 12, "question": "What is 'OAuth' primarily used for?", "options": ["Authorization Protocol", "Authentication only", "Both A and B", "Neither"], "correct": 2},
        {"id": 13, "question": "What is an 'Assertion' in API automation?", "options": ["Renaming a variable", "A validation check that compares the actual result with the expected result", "None of the above", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Base URL'?", "options": ["The first part of a physical address", "The shared part of a URL for all endpoints in an API", "A tech spec", "None"], "correct": 1},
        {"id": 15, "question": "What does '401 Unauthorized' mean?", "options": ["Server error", "The request lacks valid authentication credentials for the resource", "A type of chart", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Payload' or 'Request Body'?", "options": ["The data sent from a client to a server", "A list of cookies", "A type of backup", "None"], "correct": 0},
        {"id": 17, "question": "What is 'Query Parameter' in a URL?", "options": ["A password", "Variables added to a URL preceded by a '?' to provide specific info", "A type of error", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Path Parameter'?", "options": ["A specific file path", "A parameter that is actually part of the URL path itself", "A type of log", "None"], "correct": 1},
        {"id": 19, "question": "Which status code represents 'Internal Server Error'?", "options": ["200", "400", "401", "500"], "correct": 3},
        {"id": 20, "question": "What is 'Schema Validation' in API testing?", "options": ["Formatting a document", "Checking if the API response structure matches an expected JSON/XML schema", "A security feature", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Regression Testing' for APIs?", "options": ["Finding new bugs only", "Verifying that existing functionality wasn't broken by new changes", "None of the above", "None"], "correct": 1},
        {"id": 22, "question": "What's the difference between a SOAP and REST API?", "options": ["SOAP is usually over HTTP; REST is only over XML", "SOAP is protocol; REST is architectural style (lighter, uses JSON)", "Neither", "Both"], "correct": 1},
        {"id": 23, "question": "What is 'Header' in an HTTP request?", "options": ["The top of a physical disk", "Information like content-type, authorization, and cookies sent with a request", "A decorative text", "None"], "correct": 1},
        {"id": 24, "question": "What is 'SOAP' (Simple Object Access Protocol)?", "options": ["A messaging protocol for XML data exchange", "A type of database", "A brand of soap", "None"], "correct": 0},
        {"id": 25, "question": "What is the purpose of 'Postman Collections'?", "options": ["Group and organize related API requests together for testing", "A type of database indexing", "Sharing code", "None"], "correct": 0},
        {"id": 26, "question": "What is 'Mocking' in API testing?", "options": ["Making fun of code", "Simulating the behavior of an API or service for testing purposes", "None of the above", "None"], "correct": 1},
        {"id": 27, "question": "Which function in Postman allows running many tests sequentially automatically?", "options": ["Test Runner", "Mock Server", "API Monitor", "None"], "correct": 0},
        {"id": 28, "question": "What is 'Idempotency' in GET requests?", "options": ["Making the same request multiple times doesn't change the state", "Each request must be unique", "None of the above", "None"], "correct": 0},
        {"id": 29, "question": "In API testing, what does 'CRUD' stand for?", "options": ["Create, Read, Update, Delete", "Copy, Replace, Update, Design", "None of the above", "None"], "correct": 0},
        {"id": 30, "question": "What is 'Swagger' (now OpenAPI Specification)?", "options": ["A style guide for UI", "A specification for documenting and designing RESTful APIs", "A type of chart", "None"], "correct": 1},
        {"id": 31, "question": "What is 'PUT' method primarily used for?", "options": ["Replacing specifically an existing resource with a new version", "Deleting a resource", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'PATCH' method usefulness?", "options": ["Making partial specifically updates to an existing resource", "Changing the whole app", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What does a '201 Created' status code mean?", "options": ["The request specifically was successful and a new resource was created", "Request was bad", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What does a '204 No Content' status code mean?", "options": ["Success specifically but the response body is empty", "An error occurred", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What does a '400 Bad Request' code indicate?", "options": ["The server specifically cannot process the request due to client error", "The server is down", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What does a '403 Forbidden' status code mean?", "options": ["The server specifically understands the request but refuses to authorize it", "The user is not logged in", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What does a '503 Service Unavailable' code mean?", "options": ["The server is specifically currently unable to handle the request (overloaded/down)", "A types of website link", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What represents the 'API Gateway'?", "options": ["A server specifically that acts as an entry point for a group of microservices", "A physical gate", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Rate Limiting' in APIs?", "options": ["Limiting specifically the number of requests a client can make in a time period", "Limiting internet speed", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's the meaning of 'Throttling'?", "options": ["Intentionally specifically slowing down API responses to control traffic", "Breaking a machine", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'API Documentation' primarily for?", "options": ["Explaining specifically how to use the API (endpoints, params, responses)", "A marketing book", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "Which of these is a popular API documentation tool?", "options": ["Swagger UI", "Redoc", "Both A and B", "Neither"], "correct": 2},
        {"id": 43, "question": "What is 'GraphQL'?", "options": ["A query language specifically for APIs that allows clients to request specific data", "A types of graph", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "How's GraphQL different from REST?", "options": ["GraphQL specifically uses a single endpoint and allows flexible queries", "They are the same", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What represents 'XML' (Extensible Markup Language)?", "options": ["A markup language specifically used for storing and transporting data in SOAP", "A types of music", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's the purpose of 'API Keys'?", "options": ["Identifying specifically the calling program or user for authentication", "Keys for a physical door", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'JWT' (JSON Web Token)?", "options": ["A compact, URL-safe specifically means of representing claims between parties", "A types of script", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "Where is a JWT usually sent in an API request?", "options": ["In the 'Authorization' specifically header as a Bearer token", "In the URL only", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'API Security Testing' focus?", "options": ["Finding specifically vulnerabilities like unauthorized access or data leaks", "Checking button colors", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What's 'Fuzz Testing' for APIs?", "options": ["Sending random specifically or invalid data to find crashes/vulnerabilities", "Testing soft toys", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What represents the 'Serialization'?", "options": ["Process specifically of converting an object into a format like JSON/XML", "Sorting a list", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What represents specific 'Deserialization'?", "options": ["Converting specifically JSON/XML back into a programming object", "Deleting data", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What represents the 'Round Trip Time' (RTT)?", "options": ["The time taken specifically for a request to reach server and response to return", "A trip around a city", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'Microservices' relationship to APIs?", "options": ["Microservices specifically communicate with each other primarily via APIs", "They are small PCs", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents specific 'Service Level Agreement' (SLA)?", "options": ["A formal contract specifically defining expected API uptime and performance", "A simple hello", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'API Monitoring' role?", "options": ["Continuously specifically checking API health and performance in production", "Watching a TV", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Data-Driven Testing' in API automation?", "options": ["Running same specifically tests multiple times with different input data sets", "Testing for data only", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What represents specific 'Parameterization'?", "options": ["Replacing specifically hard-coded values in tests with variables from a data file", "Drawing a map", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Environment Virtualization' in Postman?", "options": ["Setting specifically different values for variables (like URL) for Dev/QA/Prod", "Creating a new OS", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'API Performance Testing' goal?", "options": ["Measuring specifically how the API handles load, stress, and high traffic", "Testing how many UI buttons it has", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What's 'Load Testing' for APIs?", "options": ["Testing specifically the API with an expected number of concurrent users", "Testing a truck", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'Stress Testing' for APIs?", "options": ["Testing specifically the API beyond its limits until it fails", "Being worried", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What represents specific 'Latency' in API context?", "options": ["The delay specifically between sending a request and receiving the response", "Large data", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What represents the 'Throughput'?", "options": ["The number specifically of requests an API can handle in a given time period", "Going through a door", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'CORS' (Cross-Origin Resource Sharing)?", "options": ["A security specifically feature that allows/restricts cross-site requests in browsers", "A types of error", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents 'preflight' request (OPTIONS)?", "options": ["A browser specifically check before actual request to see if CORS is allowed", "Booking a flight", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents specific 'Content-Type' header?", "options": ["Tells the server specifically what format the request body is (e.g. application/json)", "A types of book", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents 'Accept' header specifically?", "options": ["Tells the server specifically what format the client wants for the response", "Accepting a call", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "How to handle API Versioning?", "options": ["Using version specifically numbers in the URL (e.g. /v1/users) or headers", "Replacing the old API", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents the 'HATEOAS'?", "options": ["A principle specifically where API responses provide links to further actions", "A types of food", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What represents 'Newman' in Postman ecosystem?", "options": ["A command-line specifically tool to run Postman collections in CI/CD", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's 'Karate' framework used for?", "options": ["An open-source specifically bdd-style tool for API testing and performance", "A martial art", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents 'Pact' for contract testing?", "options": ["Testing specifically the compatibility between API provider and consumer", "A types of agreement", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'API Chaining'?", "options": ["Using the output specifically of one API request as input for the next one", "A physical chain", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What represents 'Global Variables' in Postman?", "options": ["Variables specifically available across all environments and requests", "Variables in a function", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Pre-request Script' in Postman?", "options": ["JavaScript code specifically executed before a request is sent", "A types of exam", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Test Script' in Postman?", "options": ["JavaScript code specifically executed after a response is received for validation", "A book of scripts", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents 'Status-Line' in HTTP response?", "options": ["Contains the specifically HTTP version, status code, and reason phrase", "A line of people", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents the 'Cookie' header?", "options": ["Sending specifically stored session data back to the server with requests", "A snacks description", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is API Testing critical in modern software?", "options": ["Because specifically APIs are the foundation of integrated and mobile apps", "Because it is easier than UI testing", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'API Contract Testing'?", "options": ["Testing API against its specification", "Testing contracts", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'API Performance Testing'?", "options": ["Testing API speed and responsiveness", "Testing API performance", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'API Load Testing'?", "options": ["Testing API under heavy load", "Loading API", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'API Stress Testing'?", "options": ["Testing API beyond normal load", "Stressing API", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'API Security Testing'?", "options": ["Testing API security vulnerabilities", "Security testing", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'API Documentation Testing'?", "options": ["Testing API documentation accuracy", "Document testing", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'API Integration Testing'?", "options": ["Testing API integration with other systems", "Integration testing", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'API End-to-End Testing'?", "options": ["Testing complete API workflows", "End testing", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'API Regression Testing'?", "options": ["Testing API after changes", "Regression testing", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'API Monitoring'?", "options": ["Monitoring API performance and availability", "API watching", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'API Mocking'?", "options": ["Creating fake API responses", "Making fun of API", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'API Virtualization'?", "options": ["Creating virtual API services", "Virtual API", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'API Versioning'?", "options": ["Managing multiple API versions", "API version control", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'API Rate Limiting'?", "options": ["Limiting API request frequency", "API speed limits", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'API Throttling'?", "options": ["Controlling API request rate", "API throttling", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'API Caching'?", "options": ["Storing API responses", "API cache", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'API Pagination'?", "options": ["Splitting large API responses", "API pages", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'API Filtering'?", "options": ["Filtering API response data", "API filters", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'API Sorting'?", "options": ["Sorting API response data", "API sorting", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'API Searching'?", "options": ["Searching API data", "API search", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
