from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_aptitude_api(request):
    questions_pool = [
        {"id": 1, "question": "What is the average of first five multiples of 3?", "options": ["9", "12", "15", "18"], "correct": 0},
        {"id": 2, "question": "A fraction which bears the same ratio to 1/27 as 3/11 does to 5/9 is equal to:", "options": ["1/11", "3/11", "1/55", "55"], "correct": 2},
        {"id": 3, "question": "The average of 20 numbers is zero. Of them, at the most, how many may be greater than zero?", "options": ["0", "1", "10", "19"], "correct": 3},
        {"id": 4, "question": "If 20% of a = b, then b% of 20 is the same as:", "options": ["4% of a", "5% of a", "20% of a", "None of these"], "correct": 0},
        {"id": 5, "question": "A person crosses a 600 m long street in 5 minutes. What is his speed in km per hour?", "options": ["3.6", "7.2", "8.4", "10"], "correct": 1},
        {"id": 6, "question": "If an angle is its own complementary angle, then its measure is:", "options": ["30 degrees", "45 degrees", "60 degrees", "90 degrees"], "correct": 1},
        {"id": 7, "question": "The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:", "options": ["15", "16", "18", "25"], "correct": 1},
        {"id": 8, "question": "In a flight of 600 km, an aircraft was slowed down due to bad weather. Its average speed for the trip was reduced by 200 km/hr and the time of flight increased by 30 minutes. The duration of the flight is:", "options": ["1 hour", "2 hours", "3 hours", "4 hours"], "correct": 0},
        {"id": 9, "question": "A sum of money at simple interest amounts to Rs. 815 in 3 years and to Rs. 854 in 4 years. The sum is:", "options": ["Rs. 650", "Rs. 690", "Rs. 698", "Rs. 700"], "correct": 2},
        {"id": 10, "question": "A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, then the fraction of the work that is left is:", "options": ["1/4", "1/10", "7/15", "8/15"], "correct": 3},
        {"id": 11, "question": "A sum of money is to be distributed among A, B, C, D in the proportion of 5 : 2 : 4 : 3. If C gets Rs. 1000 more than D, what is B's share?", "options": ["Rs. 500", "Rs. 1500", "Rs. 2000", "Rs. 2500"], "correct": 2},
        {"id": 12, "question": "If 10% of x is the same as 20% of y, then x : y is equal to:", "options": ["1 : 2", "2 : 1", "3 : 1", "5 : 1"], "correct": 1},
        {"id": 13, "question": "Find the greatest number that will divide 43, 91 and 183 so as to leave the same remainder in each case.", "options": ["4", "7", "9", "13"], "correct": 0},
        {"id": 14, "question": "The H.C.F. of two numbers is 11 and their L.C.M. is 7700. If one of the numbers is 275, then the other is:", "options": ["279", "283", "308", "318"], "correct": 2},
        {"id": 15, "question": "A boat can travel with a speed of 13 km/hr in still water. If the speed of the stream is 4 km/hr, find the time taken by the boat to go 68 km downstream.", "options": ["2 hours", "3 hours", "4 hours", "5 hours"], "correct": 2},
        {"id": 16, "question": "A, B and C can do a piece of work in 20, 30 and 60 days respectively. In how many days can A do the work if he is assisted by B and C on every third day?", "options": ["12 days", "15 days", "16 days", "18 days"], "correct": 1},
        {"id": 17, "question": "A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?", "options": ["120 metres", "150 metres", "180 metres", "324 metres"], "correct": 1},
        {"id": 18, "question": "The ratio between the speeds of two trains is 7 : 8. If the second train runs 400 km in 4 hours, then the speed of the first train is:", "options": ["70 km/hr", "75 km/hr", "84 km/hr", "87.5 km/hr"], "correct": 3},
        {"id": 19, "question": "The difference between simple and compound interest on a principal of Rs. 10,000 in 2 years at 4% per annum is:", "options": ["Rs. 8", "Rs. 16", "Rs. 20", "Rs. 40"], "correct": 1},
        {"id": 20, "question": "A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?", "options": ["3", "4", "5", "6"], "correct": 2},
        {"id": 21, "question": "The percentage increase in the area of a rectangle, if each of its sides is increased by 20% is:", "options": ["40%", "42%", "44%", "46%"], "correct": 2},
        {"id": 22, "question": "The product of two consecutive even numbers is 288. Find the numbers.", "options": ["12, 14", "14, 16", "16, 18", "18, 20"], "correct": 2},
        {"id": 23, "question": "If log 27 = 1.431, then the value of log 9 is:", "options": ["0.934", "0.945", "0.954", "0.958"], "correct": 2},
        {"id": 24, "question": "How many seconds will a 500-metre long train take to cross a man walking with a speed of 3 km/hr in the direction of the moving train if the speed of the train is 63 km/hr?", "options": ["25 sec", "30 sec", "40 sec", "45 sec"], "correct": 1},
        {"id": 25, "question": "Find the odd man out of the series: 3, 5, 7, 12, 17, 19.", "options": ["19", "17", "12", "5"], "correct": 2},
        {"id": 26, "question": "A pump can fill a tank with water in 2 hours. Because of a leak, it took 2.33 hours to fill the tank. The leak can drain all the water of the tank in:", "options": ["7 hours", "8 hours", "12 hours", "14 hours"], "correct": 3},
        {"id": 27, "question": "A present worth of Rs. 1150 due in 3 years at 5% simple interest per annum is:", "options": ["Rs. 950", "Rs. 1000", "Rs. 1050", "Rs. 1100"], "correct": 1},
        {"id": 28, "question": "A man's speed with the current is 15 km/hr and the speed of the current is 2.5 km/hr. The man's speed against the current is:", "options": ["8.5 km/hr", "9 km/hr", "10 km/hr", "12.5 km/hr"], "correct": 2},
        {"id": 29, "question": "A sum of money placed at compound interest doubles itself in 5 years. It will amount to eight times itself in:", "options": ["10 years", "12 years", "15 years", "20 years"], "correct": 2},
        {"id": 30, "question": "The area of a triangle is 150 sq cm and the ratio of its base to height is 3:4. What is its height?", "options": ["10 cm", "15 cm", "20 cm", "25 cm"], "correct": 2},
        {"id": 31, "question": "What is the unit digit in the product (3^65 * 6^59 * 7^71)?", "options": ["1", "2", "4", "6"], "correct": 2},
        {"id": 32, "question": "In how many ways can the letters of the word 'LEADER' be arranged?", "options": ["72", "144", "360", "720"], "correct": 2},
        {"id": 33, "question": "From a pack of 52 cards, two cards are drawn together at random. What is the probability that both the cards are kings?", "options": ["1/15", "1/221", "35/256", "257/5200"], "correct": 1},
        {"id": 34, "question": "Out of 7 consonants and 4 vowels, how many words of 3 consonants and 2 vowels can be formed?", "options": ["24400", "21300", "25200", "26000"], "correct": 2},
        {"id": 35, "question": "The speed of a boat in still water is 15 km/hr and the rate of current is 3 km/hr. The distance travelled downstream in 12 minutes is:", "options": ["1.2 km", "1.8 km", "2.4 km", "3.6 km"], "correct": 3},
        {"id": 36, "question": "Two numbers are in the ratio 3 : 5. If 9 is subtracted from each, the new numbers are in the ratio 12 : 23. The smaller number is:", "options": ["27", "33", "49", "55"], "correct": 1},
        {"id": 37, "question": "The price of petrol is increased by 25%. By how much percent a user must reduce his consumption so that expenditure on petrol remains constant?", "options": ["18%", "20%", "22%", "25%"], "correct": 1},
        {"id": 38, "question": "An error 2% in excess is made while measuring the side of a square. The percentage error in the calculated area of the square is:", "options": ["2%", "4%", "4.04%", "8.08%"], "correct": 2},
        {"id": 39, "question": "A metallic sheet is of rectangular shape with dimensions 48 m x 36 m. From each one of its corners, a square of 8 m is cutoff. An open box is made of the remaining sheet. Find the volume of the box.", "options": ["5120 cu m", "4800 cu m", "5200 cu m", "5500 cu m"], "correct": 0},
        {"id": 40, "question": "The difference between a two-digit number and the number obtained by interchanging the positions of its digits is 36. What is the difference between the two digits of that number?", "options": ["3", "4", "5", "6"], "correct": 1},
        {"id": 41, "question": "Evaluate: (0.337 * 0.337 - 0.126 * 0.126) / (0.337 - 0.126)", "options": ["0.211", "0.463", "0.5", "0.6"], "correct": 1},
        {"id": 42, "question": "A sum of money compounded annually doubles itself in 6 years. In how many years will it become 8 times itself?", "options": ["12 years", "15 years", "18 years", "24 years"], "correct": 2},
        {"id": 43, "question": "What least number must be added to 1056 so that the sum is completely divisible by 23?", "options": ["2", "3", "5", "18"], "correct": 0},
        {"id": 44, "question": "What is the probability of getting a sum 9 from two throws of a dice?", "options": ["1/6", "1/8", "1/9", "1/12"], "correct": 2},
        {"id": 45, "question": "The average of 5 consecutive numbers is n. If the next two numbers are also included, the average will:", "options": ["increase by 1", "remain the same", "increase by 1.4", "increase by 2"], "correct": 0},
        {"id": 46, "question": "If 15 men can reap a field in 35 days, in how many days will 21 men reap the same field?", "options": ["20 days", "22 days", "25 days", "27 days"], "correct": 2},
        {"id": 47, "question": "In how many different ways can the letters of the word 'DETAIL' be arranged such that the vowels must occupy only the odd positions?", "options": ["32", "36", "48", "60"], "correct": 1},
        {"id": 48, "question": "A and B invest in a business in the ratio 3 : 2. If 5% of the total profit goes to charity and A's share is Rs. 855, the total profit is:", "options": ["Rs. 1425", "Rs. 1500", "Rs. 1575", "Rs. 1600"], "correct": 1},
        {"id": 49, "question": "If a quarter kg of potato costs 60 paise, how many paise will 200 gm cost?", "options": ["48 paise", "50 paise", "52 paise", "54 paise"], "correct": 0},
        {"id": 50, "question": "The diagonal of a rectangle is √41 cm and its area is 20 sq cm. What is the perimeter of the rectangle?", "options": ["13 cm", "14 cm", "18 cm", "20 cm"], "correct": 2},
        {"id": 51, "question": "A train 125 m long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is:", "options": ["45 km/hr", "50 km/hr", "54 km/hr", "55 km/hr"], "correct": 1},
        {"id": 52, "question": "A clock strikes once at 1 o'clock, twice at 2 o'clock, thrice at 3 o'clock and so on. How many times will it strike in 24 hours?", "options": ["78", "136", "156", "300"], "correct": 2},
        {"id": 53, "question": "A can finish a work in 18 days and B can do the same work in half the time taken by A. Then, working together, what part of the same work they can finish in a day?", "options": ["1/6", "1/9", "2/5", "2/7"], "correct": 0},
        {"id": 54, "question": "How many times do the hands of a clock coincide in a day?", "options": ["20", "21", "22", "24"], "correct": 2},
        {"id": 55, "question": "If the numbers from 1 to 50 which are divisible by 4 are written in descending order, which number will be at the 7th place?", "options": ["20", "24", "28", "32"], "correct": 1},
        {"id": 56, "question": "The population of a town was 1,60,000 three years ago. If it increased by 3%, 2.5% and 5% respectively in the last three years, the present population is:", "options": ["1,77,000", "1,77,366", "1,77,500", "1,78,000"], "correct": 1},
        {"id": 57, "question": "Three unbiased coins are tossed. What is the probability of getting at least 2 heads?", "options": ["1/4", "3/8", "1/2", "5/8"], "correct": 2},
        {"id": 58, "question": "By selling 45 lemons for Rs. 40, a man loses 20%. How many should he sell for Rs. 24 to gain 20% in the transaction?", "options": ["15", "18", "20", "22"], "correct": 1},
        {"id": 59, "question": "If A = x% of y and B = y% of x, then which of the following is true?", "options": ["A is smaller than B", "A is greater than B", "Relationship cannot be determined", "A is equal to B"], "correct": 3},
        {"id": 60, "question": "A library has an average of 510 visitors on Sundays and 240 on other days. The average number of visitors per day in a month of 30 days beginning with a Sunday is:", "options": ["250", "276", "280", "285"], "correct": 2},
        {"id": 61, "question": "A container contains 40 litres of milk. From this container, 4 litres of milk was taken out and replaced by water. This process was repeated further two times. How much milk is now contained by the container?", "options": ["26.34 litres", "27.36 litres", "29.16 litres", "30 litres"], "correct": 2},
        {"id": 62, "question": "A sum of money lent at compound interest for 2 years at 10% per annum. If the interest is payable half-yearly, the effective rate of interest is:", "options": ["10%", "10.25%", "10.5%", "10.75%"], "correct": 1},
        {"id": 63, "question": "The ratio between the length and the perimeter of a rectangular plot is 1 : 3. What is the ratio between the length and breadth of the plot?", "options": ["2 : 1", "3 : 2", "1 : 2", "None of these"], "correct": 0},
        {"id": 64, "question": "How many prime numbers are there between 20 and 50?", "options": ["6", "7", "8", "9"], "correct": 1},
        {"id": 65, "question": "Two numbers are 20% and 50% more than a third number respectively. The ratio of the two numbers is:", "options": ["2 : 5", "3 : 5", "4 : 5", "5 : 4"], "correct": 2},
        {"id": 66, "question": "If log10 2 = 0.3010, then the number of digits in 2^64 is:", "options": ["18", "19", "20", "21"], "correct": 2},
        {"id": 67, "question": "The ratio of the area of a square to that of the square-drawn on its diagonal is:", "options": ["1 : 1", "1 : 2", "1 : 3", "1 : 4"], "correct": 1},
        {"id": 68, "question": "A bag contains 6 black and 8 white balls. One ball is drawn at random. What is the probability that the ball drawn is white?", "options": ["3/4", "4/7", "1/8", "3/7"], "correct": 1},
        {"id": 69, "question": "In a laboratory, two bottles of equal capacity contain mixture of acid and water in the ratio 2:5 and 7:3 respectively. If both are emptied into a single vessel, the ratio of acid to water in the vessel is:", "options": ["17:35", "69:71", "3:5", "4:7"], "correct": 1},
        {"id": 70, "question": "In how many ways can a group of 5 men and 2 women be made out of 7 men and 3 women?", "options": ["45", "63", "90", "126"], "correct": 1},
        {"id": 71, "question": "If x/y = 4/5, then the value of (3x + 4y) / (4x + 3y) is:", "options": ["16/31", "32/31", "31/32", "15/16"], "correct": 1},
        {"id": 72, "question": "The average age of 10 students and their teacher is 20 years. If the teacher's age is excluded, the average age decreases by 2 years. Find the teacher's age.", "options": ["38 years", "40 years", "42 years", "44 years"], "correct": 1},
        {"id": 73, "question": "What mathematical operation must be done to calculate the area of a circle with radius r?", "options": ["2 * pi * r", "pi * r^2", "pi * d", "4/3 * pi * r^3"], "correct": 1},
        {"id": 74, "question": "If 12 boys can earn Rs. 240 in 5 days, how much will 15 boys earn in 6 days?", "options": ["Rs. 300", "Rs. 360", "Rs. 400", "Rs. 420"], "correct": 1},
        {"id": 75, "question": "What is the speed of a train that covers 450 miles in 5 hours?", "options": ["80 mph", "90 mph", "100 mph", "110 mph"], "correct": 1},
        {"id": 76, "question": "A sum of money triples itself in 10 years at simple interest. The rate of interest per annum is:", "options": ["10%", "15%", "20%", "25%"], "correct": 2},
        {"id": 77, "question": "Evaluate: 1 + 2 + 3 + ... + 100.", "options": ["5000", "5050", "5100", "5150"], "correct": 1},
        {"id": 78, "question": "Find the compound interest on Rs. 8000 at 15% per annum for 2 years 4 months, compounded annually.", "options": ["Rs. 2900", "Rs. 3000", "Rs. 3109", "Rs. 3200"], "correct": 2},
        {"id": 79, "question": "If log 2 = 0.3010 and log 3 = 0.4771, find log 6.", "options": ["0.7781", "0.8012", "0.9123", "0.9542"], "correct": 0},
        {"id": 80, "question": "Which number is divisible by 11?", "options": ["123456", "234567", "4832718", "987654"], "correct": 2},
        {"id": 81, "question": "A and B can do a work in 12 days, B and C in 15 days, C and A in 20 days. If A, B and C work together, they will complete the work in:", "options": ["5 days", "8 days", "10 days", "12 days"], "correct": 2},
        {"id": 82, "question": "A train 100 m long is running at the speed of 30 km/hr. Find the time taken by it to pass a man standing near the railway line.", "options": ["10 sec", "12 sec", "15 sec", "18 sec"], "correct": 1},
        {"id": 83, "question": "If 8 men can reap 80 hectares of land in 24 days, how many hectares can 36 men reap in 30 days?", "options": ["400 hectares", "450 hectares", "500 hectares", "550 hectares"], "correct": 1},
        {"id": 84, "question": "The ratio of the speed of a boat in still water to the stream speed is 5:1. If downstream speed is 24 km/hr, find the upstream speed.", "options": ["12 km/hr", "16 km/hr", "18 km/hr", "20 km/hr"], "correct": 1},
        {"id": 85, "question": "What is the H.C.F. of 108, 288 and 360?", "options": ["18", "36", "72", "108"], "correct": 1},
        {"id": 86, "question": "The base and height of a right-angled triangle are 8 cm and 6 cm respectively. Its hypotenuse is:", "options": ["9 cm", "10 cm", "11 cm", "12 cm"], "correct": 1},
        {"id": 87, "question": "In a mixture of 60 litres, the ratio of milk and water is 2:1. If this ratio is to be 1:2, then the quantity of water to be further added is:", "options": ["20 litres", "30 litres", "40 litres", "60 litres"], "correct": 3},
        {"id": 88, "question": "If log x + log y = log (x + y), then:", "options": ["x = y", "x = y / (y - 1)", "y = x / (x - 1)", "x = y / (y + 1)"], "correct": 1},
        {"id": 89, "question": "At what time between 4 and 5 o'clock will the hands of a watch be together?", "options": ["21 9/11 min past 4", "22 min past 4", "23 2/11 min past 4", "24 min past 4"], "correct": 0},
        {"id": 90, "question": "If the length of a rectangle is increased by 10% and breadth is decreased by 10%, the change in area is:", "options": ["1% increase", "1% decrease", "no change", "2% decrease"], "correct": 1},
        {"id": 91, "question": "Find the odd number in the series: 8, 27, 64, 100, 125, 216.", "options": ["27", "64", "100", "125"], "correct": 2},
        {"id": 92, "question": "The perimeter of a circle is equal to the perimeter of a square. The ratio of their areas is:", "options": ["11 : 14", "14 : 11", "22 : 7", "7 : 22"], "correct": 1},
        {"id": 93, "question": "A coin is tossed twice. Find the probability of getting at most one head.", "options": ["1/4", "1/2", "3/4", "1"], "correct": 2},
        {"id": 94, "question": "If (a/b) = (4/3), then the value of (3a + 2b) / (3a - 2b) is:", "options": ["2", "3", "4", "5"], "correct": 1},
        {"id": 95, "question": "What is the L.C.M. of 12, 18, and 24?", "options": ["48", "72", "96", "120"], "correct": 1},
        {"id": 96, "question": "If x% of 250 is 100, then x is:", "options": ["20", "30", "40", "50"], "correct": 2},
        {"id": 97, "question": "A train 300 m long crosses a platform 200 m long in 25 seconds. Find the speed of the train in km/hr.", "options": ["50 km/hr", "60 km/hr", "72 km/hr", "80 km/hr"], "correct": 2},
        {"id": 98, "question": "A tank can be filled by Pipe A in 5 hours and emptied by Pipe B in 10 hours. If both pipes are opened, the tank is filled in:", "options": ["6 hours", "8 hours", "10 hours", "12 hours"], "correct": 2},
        {"id": 99, "question": "The compound interest on a sum of Rs. 4000 for 2 years at 10% per annum is:", "options": ["Rs. 800", "Rs. 820", "Rs. 840", "Rs. 860"], "correct": 1},
        {"id": 100, "question": "The ratio of the ages of two persons is 4 : 7 and the age of one of them is greater than that of the other by 30 years. Find the sum of their ages.", "options": ["110 years", "120 years", "130 years", "140 years"], "correct": 0}
    ]
    return Response({"success": True, "data": questions_pool})
