import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_aspnetmvc_api(request):
    questions_pool = [
        {"id": 1, "question": "What does MVC stand for in ASP.NET?", "options": ["Model View Controller", "Main Video Center", "Model Visual Code", "None"], "correct": 0},
        {"id": 2, "question": "What is the purpose of the 'Model' in MVC?", "options": ["Handle the UI", "Interact with the database and handle business logic", "Route the request", "None"], "correct": 1},
        {"id": 3, "question": "What is the purpose of the 'View' in MVC?", "options": ["Process input", "Handle user interface and data display", "Store data", "None"], "correct": 1},
        {"id": 4, "question": "What is the purpose of the 'Controller' in MVC?", "options": ["Display data", "Handle user interactions and coordinate between Model and View", "Define table schema", "None"], "correct": 1},
        {"id": 5, "question": "Which file is the entry point for routing in ASP.NET MVC?", "options": ["RouteConfig.cs", "Global.asax", "web.config", "None"], "correct": 0},
        {"id": 6, "question": "What is Razor in ASP.NET MVC?", "options": ["A hardware tool", "A markup syntax for embedding server-based code into web pages", "A type of database", "None"], "correct": 1},
        {"id": 7, "question": "What is the default routing pattern in ASP.NET MVC?", "options": ["{action}/{controller}/{id}", "{controller}/{action}/{id}", "{id}/{controller}/{action}", "None"], "correct": 1},
        {"id": 8, "question": "What is 'TempData' used for?", "options": ["Storing data permanently", "Storing data for only the next request", "Caching pages", "None"], "correct": 1},
        {"id": 9, "question": "What is 'ViewData'?", "options": ["A dictionary for passing data from controller to view", "A strongly typed object", "A database record", "None"], "correct": 0},
        {"id": 10, "question": "What is 'ViewBag'?", "options": ["A static class", "A dynamic property for passing data from controller to view", "A type of list", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Action Method' in a Controller?", "options": ["A public method that handles HTTP requests", "A private method for logic", "A constructor", "None"], "correct": 0},
        {"id": 12, "question": "What is 'Action Result'?", "options": ["The final count of actions", "The base class for all return types of action methods", "A type of error", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Partial View'?", "options": ["A view without a layout", "A reusable view that can be rendered inside another view", "Both A and B", "Neither"], "correct": 2},
        {"id": 14, "question": "What is 'Layout' in ASP.NET MVC?", "options": ["A template for common UI elements (like headers/footers)", "A routing rule", "A database table", "None"], "correct": 0},
        {"id": 15, "question": "What is 'BundleConfig' for?", "options": ["Managing database connections", "Optimizing CSS and JavaScript files by grouping and minifying them", "Setting up routes", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Model Binding'?", "options": ["Connecting to a database", "Mapping HTTP request data to action method parameters or model objects", "A type of layout", "None"], "correct": 1},
        {"id": 17, "question": "What is 'DataAnnotations' used for?", "options": ["Styling text", "Defining validation rules on model properties", "Mapping routes", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Html.ActionLink'?", "options": ["A link to an external site", "A helper that generates an anchor tag for a specific action", "A button", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Area' in ASP.NET MVC project structure?", "options": ["A physical location", "A way to organize large applications into smaller functional units", "A type of database", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Filter' in ASP.NET MVC (e.g. [Authorize])?", "options": ["A way to clean data", "Attributes that inject logic before or after action method execution", "A search tool", "None"], "correct": 1},
        {"id": 21, "question": "Which version of .NET introduced ASP.NET MVC?", "options": [".NET Core", ".NET Framework 3.5", ".NET 5", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Scaffolding'?", "options": ["Building physical structures", "Automatic generation of code for CRUD operations based on a model", "A type of error", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Dependency Injection' (DI) in ASP.NET Core MVC?", "options": ["Manually creating objects", "A design pattern to achieve Inversion of Control between classes and their dependencies", "A compiler feature", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Strongly Typed View'?", "options": ["A view with bold text", "A view that is associated with a specific model type", "A read-only view", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Entity Framework'? ", "options": ["An interface for UI", "An Object-Relational Mapper (ORM) for .NET", "A routing engine", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Web API' vs MVC?", "options": ["MVC is for UI; Web API is for data/services", "They are identical", "Web API is only for mobile", "None"], "correct": 0},
        {"id": 27, "question": "What is 'ViewEngine'?", "options": ["Responsible for rendering the view into HTML", "A browser component", "A database engine", "None"], "correct": 0},
        {"id": 28, "question": "What is the result of '@Html.BeginForm()'?", "options": ["Starts a table", "Generates an opening <form> tag", "Ends a section", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Anti-Forgery Token' used for?", "options": ["Preventing XSS", "Preventing Cross-Site Request Forgery (CSRF) attacks", "Encrypting data", "None"], "correct": 1},
        {"id": 30, "question": "What is the full form of LINQ?", "options": ["Language Integrated Query", "List Integrated Quality", "Linked Internal Query", "None"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'ValidModelState' property used for?", "options": ["Checking database connectivity", "Checking if the model data complies with validation rules", "Deleting a record", "None"], "correct": 1},
        {"id": 32, "question": "What is 'RedirectToAction'?", "options": ["Stops the program", "Returns an HTTP 302 response to redirect to another action method", "A type of view", "None"], "correct": 1},
        {"id": 33, "question": "What is the result of 'JsonResult'?", "options": ["Returns data in JSON format for AJAX calls", "A type of error", "A physical file", "None"], "correct": 0},
        {"id": 34, "question": "What is 'ViewResult'?", "options": ["A result that renders a partial view", "A result that renders a full view to the response", "A database record", "None"], "correct": 1},
        {"id": 35, "question": "What is 'ContentResult'?", "options": ["A result that returns raw text or a string", "A result that returns an image", "None of the above", "None"], "correct": 0},
        {"id": 36, "question": "What is 'FileResult'?", "options": ["A result that deletes a file", "A result that allows downloading a file as a response", "A routing rule", "None"], "correct": 1},
        {"id": 37, "question": "Which of these is a valid filter in ASP.NET MVC?", "options": ["ActionFilter", "ResultFilter", "ExceptionFilter", "All of the above"], "correct": 3},
        {"id": 38, "question": "What is 'OutputCache' filter for?", "options": ["Deleting history", "Caching the output of an action method to improve performance", "Formatting text", "None"], "correct": 1},
        {"id": 39, "question": "What is 'Global Filter'?", "options": ["A filter applied to all action methods in an application", "A filter for one controller", "A security token", "None"], "correct": 0},
        {"id": 40, "question": "What is 'DisplayMode' for?", "options": ["Setting the screen resolution", "Selecting different views based on the device type (mobile vs desktop)", "A design tool", "None"], "correct": 1},
        {"id": 41, "question": "What is 'Section' in Razor layout?", "options": ["A part of a database", "Placeholder in a layout that can be filled by individual views", "A routing module", "None"], "correct": 1},
        {"id": 42, "question": "Which method is used to render a section in the layout?", "options": ["@RenderBody()", "@RenderSection()", "@Html.Action()", "None"], "correct": 1},
        {"id": 43, "question": "Which method is used to render the main content of a view in the layout?", "options": ["@RenderBody()", "@RenderSection()", "@Html.Display()", "None"], "correct": 0},
        {"id": 44, "question": "What is 'ChildActionOnly' attribute?", "options": ["Allows any user to call it", "Ensures the action can only be called from within a view (via Html.Action)", "Hides it from the UI", "None"], "correct": 1},
        {"id": 45, "question": "What is 'NonAction' attribute?", "options": ["Marks a public method so it cannot be reached as an URL action", "Sets a method for math only", "None of the above", "None"], "correct": 0},
        {"id": 46, "question": "What is 'Authorize' attribute?", "options": ["An action to delete users", "Restricts an action or controller to authorized users only", "Sets the font weight", "None"], "correct": 1},
        {"id": 47, "question": "What is 'AllowAnonymous' attribute?", "options": ["Requires a login", "Allows access to an action even if the controller has [Authorize]", "A type of table", "None"], "correct": 1},
        {"id": 48, "question": "What is 'Remote' validation?", "options": ["Validating on another computer", "Performing validation on the server side via an AJAX call from the client", "A routing engine", "None"], "correct": 1},
        {"id": 49, "question": "Which of these is a standard ActionResult in ASP.NET Core?", "options": ["OkResult", "NotFoundResult", "BadRequestResult", "All of the above"], "correct": 3},
        {"id": 50, "question": "What is 'Middleware' in ASP.NET Core MVC?", "options": ["Software that handles database connections", "Software assembled into an application pipeline to handle requests/responses", "A type of view", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Kestrel'?", "options": ["A mobile phone", "A cross-platform web server for ASP.NET Core", "A routing protocol", "None"], "correct": 1},
        {"id": 52, "question": "What is 'Startup.cs' used for in ASP.NET Core?", "options": ["To start the server only", "To configure services and the request pipeline", "To store data", "None"], "correct": 1},
        {"id": 53, "question": "What is 'appsettings.json'?", "options": ["A file for HTML templates", "A file for storing configuration settings in JSON format", "A type of database", "None"], "correct": 1},
        {"id": 54, "question": "What is 'CORS'?", "options": ["Cross-Origin Resource Sharing (controls which domains can access your API)", "A computer programming language", "None of the above", "None"], "correct": 0},
        {"id": 55, "question": "What is 'AutoMapper'?", "options": ["A tool for maps", "A library used to map data from one object type to another (e.g. Entity to DTO)", "A routing rule", "None"], "correct": 1},
        {"id": 56, "question": "What is 'DTO' (Data Transfer Object)?", "options": ["A database table", "An object specifically designed to carry data between subsystems", "A type of chart", "None"], "correct": 1},
        {"id": 57, "question": "What is 'Unit of Work' pattern?", "options": ["Managing hours of code", "Ensuring that multiple repository operations use a single database transaction", "A design tool", "None"], "correct": 1},
        {"id": 58, "question": "What is 'Repository Pattern'?", "options": ["Where you store code on GitHub", "An abstraction layer between the domain and data mapping layers", "A type of layout", "None"], "correct": 1},
        {"id": 59, "question": "What is 'Seeding' in database context?", "options": ["Growing plants in a data center", "Initial population of a database with predefined data during development", "None of the above", "None"], "correct": 1},
        {"id": 60, "question": "What is 'Migration' in Entity Framework?", "options": ["Moving to another office", "A way to evolve the database schema as the model changes", "A type of backup", "None"], "correct": 1},
        {"id": 61, "question": "Which command-line tool is used for migrations in .NET Core?", "options": ["dotnet run", "dotnet ef migrations add <name>", "dotnet build", "None"], "correct": 1},
        {"id": 62, "question": "What is 'Lazy Loading' in Entity Framework?", "options": ["Slow database connections", "Delaying the loading of related data until it is specifically requested", "None of the above", "None"], "correct": 1},
        {"id": 63, "question": "What is 'Eager Loading'?", "options": ["Fast database connections", "Loading related data along with the main data in a single query", "A security flow", "None"], "correct": 1},
        {"id": 64, "question": "What is 'Explicit Loading'?", "options": ["Manually loading related data for an object through an explicit request", "Calculating math results", "None of the above", "None"], "correct": 0},
        {"id": 65, "question": "What is 'Fluent API' in EF Core?", "options": ["A way to write fast code", "Advanced way to configure your model/database mapping using code", "A design language", "None"], "correct": 1},
        {"id": 66, "question": "What is 'Queryable' vs 'List'?", "options": ["Queryable is for server-side evaluation; List is in-memory", "They are identical", "List is faster for big data", "None"], "correct": 0},
        {"id": 67, "question": "What is 'IEnumerable'?", "options": ["A list that cannot be changed", "An interface for forward-only iteration over a collection", "A type of error", "None"], "correct": 1},
        {"id": 68, "question": "What is 'IQueryable'?", "options": ["Same as IEnumerable", "An interface that inherits from IEnumerable and provides query execution on a provider", "None of the above", "None"], "correct": 1},
        {"id": 69, "question": "What is 'Action Descriptor'?", "options": ["A description of a video", "An object containing information about a controller action for the framework", "A routing name", "None"], "correct": 1},
        {"id": 70, "question": "What is 'Value Provider' in model binding?", "options": ["A source of data for model binding (like query strings, form fields)", "A database table", "None of the above", "None"], "correct": 0},
        {"id": 71, "question": "What is '@Html.EditorFor'?", "options": ["A tool for editing code", "A helper that generates UI based on the data type of the model property", "A button", "None"], "correct": 1},
        {"id": 72, "question": "What is '@Html.ValidationSummary'?", "options": ["A list of all users", "Displays a list of validation errors for the entire model", "A type of chart", "None"], "correct": 1},
        {"id": 73, "question": "What is 'AreaRegistration.RegisterAllAreas()'?", "options": ["Mapping all routes", "Method called to register all area-specific routing at startup", "Managing files", "None"], "correct": 1},
        {"id": 74, "question": "Which of these is a benefit of MVC?", "options": ["Separation of concerns", "Testability", "Reusable views", "All of the above"], "correct": 3},
        {"id": 75, "question": "What is 'HandleError' attribute?", "options": ["A manual error fix", "An attribute to provide a custom view when an exception occurs", "Stops the program", "None"], "correct": 1},
        {"id": 76, "question": "What is 'Self-hosting' for Web API?", "options": ["Hosting without a provider", "Capability to host your API in a custom process (like Console app)", "Both A and B", "Neither"], "correct": 1},
        {"id": 77, "question": "What is 'Attribute Routing'?", "options": ["Mapping routes via symbols", "Defining routes directly on controllers/actions using attributes", "A computer language", "None"], "correct": 1},
        {"id": 78, "question": "What is the result of 'Html.Partial' vs 'Html.RenderPartial'?", "options": ["Partial returns a string; RenderPartial writes directly to the response", "RenderPartial is slower", "They are identical", "None"], "correct": 0},
        {"id": 79, "question": "What is 'ModelMetadata'?", "options": ["Data about the model (e.g. constraints, display name) used for UI", "A list of files", "None of the above", "None"], "correct": 0},
        {"id": 80, "question": "Which command is used to update the database to the latest migration?", "options": ["dotnet build", "dotnet ef database update", "dotnet run", "None"], "correct": 1},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
