import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_augmentedreality_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Augmented Reality' (AR)?", "options": ["A completely virtual world", "An interactive experience where digital information is overlaid on the real world", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "What is the primary difference between AR and VR?", "options": ["AR enhances the real world; VR replaces it", "AR is more expensive", "VR is only for mobile apps", "None"], "correct": 0},
        {"id": 3, "question": "Which of these is a famous AR game?", "options": ["Minecraft", "Pokemon Go", "SimCity", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Marker-based' AR?", "options": ["Using a pen to draw stuff", "AR that identifies a specific visual marker (like a QR code) to display content", "AR with no markers", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Markerless' AR?", "options": ["AR without markers", "AR that uses GPS or gyroscope to display position-based content", "Both A and B", "Neither"], "correct": 2},
        {"id": 6, "question": "What is 'Projection-based' AR?", "options": ["Projecting light on physical objects to create illusions/information", "Watching a movie in a theater", "A type of screen", "None"], "correct": 0},
        {"id": 7, "question": "What is 'Superimposition-based' AR?", "options": ["Merging two databases", "Replacing the original view of an object with an augmented one", "A type of chart", "None"], "correct": 1},
        {"id": 8, "question": "What is 'ARCore'?", "options": ["Apple's AR tool", "Google's platform for building augmented reality experiences", "A hardware component", "None"], "correct": 1},
        {"id": 9, "question": "What is 'ARKit'?", "options": ["Google's AR tool", "Apple's platform for building augmented reality experiences for iOS", "A tech spec", "None"], "correct": 1},
        {"id": 10, "question": "Which industry uses AR for maintenance and training?", "options": ["Manufacturing", "Healthcare", "Education", "All of the above"], "correct": 3},
        {"id": 11, "question": "What is 'Mixed Reality' (MR)?", "options": ["A mixture of sound and video", "A blend of real and virtual worlds where physical and digital objects co-exist", "A type of game", "None"], "correct": 1},
        {"id": 12, "question": "What are 'Smart Glasses'?", "options": ["Glasses that make you smarter", "Wearable heads-up displays that overlay information onto lenses", "A type of database", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Haptic Feedback' in AR context?", "options": ["A sound alarm", "Using tactile sensations like vibrations to provide feedback in interactive apps", "A color design", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Field of View' (FoV)?", "options": ["The size of a farm field", "The extent of the observable world seen through an AR/VR device", "A technical specification", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Latency' in AR systems?", "options": ["The speed of light", "The delay between a user action and the system's reaction", "Both A and B", "Neither"], "correct": 1},
        {"id": 16, "question": "What's the meaning of 'Object Recognition' in AR?", "options": ["The ability of AR software to identify physical objects and overlay data", "Identifying people in a photo", "None of the above", "None"], "correct": 0},
        {"id": 17, "question": "What is 'Spatial Mapping'?", "options": ["Mapping stars in the sky", "Creating a detailed 3D model of a real-world environment for MR systems", "A search engine", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Occlusion' in AR?", "options": ["Hiding a secret", "When a virtual object is hidden by a real-world object (or vice versa)", "A type of table", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Unity' commonly used for in AR development?", "options": ["Unity of a team", "A popular game engine for building cross-platform AR/VR experiences", "A security feature", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Vuforia'?", "options": ["A type of flower", "A popular software development kit for augmented reality", "A decorative part of code", "None"], "correct": 1},
        {"id": 21, "question": "What's the role of 'Gyroscope' in mobile AR?", "options": ["Measures gravity", "Detecting device orientation and rotation for accurate tracking", "A technical manual", "None"], "correct": 1},
        {"id": 22, "question": "What's the role of 'Accelerometer'?", "options": ["Measures acceleration", "Measuring the movement and velocity of a device", "A type of graph", "None"], "correct": 0},
        {"id": 23, "question": "What is 'HUD' (Heads-Up Display)?", "options": ["A transparent display that presents data without users looking away", "A hat for gamers", "None of the above", "None"], "correct": 0},
        {"id": 24, "question": "Which of these is a major hardware player in AR?", "options": ["Microsoft HoloLens", "Magic Leap", "Google Glass", "All of the above"], "correct": 3},
        {"id": 25, "question": "What is 'Augmented Human'?", "options": ["A very tall person", "The concept of integrating technology to enhance physical or cognitive abilities", "A tech spec", "None"], "correct": 1},
        {"id": 26, "question": "What's a 'Virtual Object'?", "options": ["A physical item", "A digital asset that appears as part of an AR experience", "A type of memory", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Depth Sensing' camera?", "options": ["A camera that sees deep water", "A camera type that measures the distance between the device and physical objects", "A security log", "None"], "correct": 1},
        {"id": 28, "question": "What's the relationship between '5G' and AR?", "options": ["5G provides the low latency and high bandwidth needed for high-quality AR", "5G makes AR cheaper", "None for now", "None"], "correct": 0},
        {"id": 29, "question": "What is 'Location-based' AR?", "options": ["AR tied to a specific GPS location (like Pokemon Go)", "AR in a server room", "Both A and B", "Neither"], "correct": 0},
        {"id": 30, "question": "What's the primary benefit of AR in E-commerce?", "options": ["Allowing customers to see products (like furniture) in their homes", "Deleting all data", "Buying items automatically", "None"], "correct": 0},
        {"id": 31, "question": "What is 'SLAM'?", "options": ["Simultaneous Localization and Mapping specifically used for AR tracking", "Hitting a door", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What represents the 'Avatar' in AR context?", "options": ["A digital representation specifically of a user in a virtual or augmented space", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Augmented Reality' vs 'Virtual Reality'?", "options": ["AR adds to real world specifically whereas VR replaces it with a virtual environment", "They are the same", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the meaning of 'Wearable Device'?", "options": ["A physical gadget specifically like glasses or watch used for AR", "A types of clothes", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents specific 'Hand Tracking'?", "options": ["The ability of AR software specifically to detect and follow user hand movements", "Following a person", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents specific 'Eye Tracking'?", "options": ["The ability of AR software specifically to detect exactly where the user is looking", "Staring at someone", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's the purpose of 'Anchoring' virtual objects?", "options": ["Fixing a digital object specifically to a specific real-world location", "Buying a boat", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What represents the 'Digital Twin'?", "options": ["A digital replica specifically of a physical object used for AR analysis", "A types of brother", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Telepresence'?", "options": ["A set specifically of technologies allowing a person to feel present in remote place", "Talking on a phone", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's the meaning of 'Extended Reality' (XR)?", "options": ["An umbrella term specifically including AR, VR, and MR together", "Extra reality", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "Which of these is a major AR framework for Web?", "options": ["AR.js", "Three.js", "Both A and B", "Neither"], "correct": 2},
        {"id": 42, "question": "What represents specific 'Plane Detection'?", "options": ["The ability of AR software specifically to identify flat surfaces like tables/floors", "Finding an airplane", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'WebAR' significance?", "options": ["Running AR experiences specifically directly in a browser without an app", "A types of internet", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What represents the 'Light Estimation'?", "options": ["Matching specifically the lighting of virtual objects with the real environment", "Counting lights", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's 'Spatial Audio'?", "options": ["A 3D audio experience specifically where sound seems to come from specific locations", "Audio in space", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What represents the 'Magic Leap' device?", "options": ["A wearable AR computer specifically designed for high-end spatial computing", "A types of jump", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Hololens' developed by?", "options": ["Microsoft", "Google", "Apple", "Facebook"], "correct": 0},
        {"id": 48, "question": "What represents specific 'Snapchat Lenses'?", "options": ["A popular consumer application specifically using AR for facial filters", "Glasses for photos", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's the meaning of 'Environment Probes'?", "options": ["Capturing specifically physical environment data to create realistic reflections", "A types of weather tool", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What represents 'LiDAR' sensor functionality?", "options": ["Light Detection specifically and Ranging for high-precision 3D environmental mapping", "A types of radar", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What represents safe 'Interaction' in AR?", "options": ["Using simple gestures specifically and voice commands to control virtual content", "Shaking hands", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Raycasting' in AR development?", "options": ["A method specifically used to detect where a user is pointing in a 3D space", "Casting a fishing line", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What represents 'Asset' in AR app design?", "options": ["Digital models, specifically textures, or sounds used in the augmented scene", "A bank account", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's the significance of 'Frame Rate' in AR?", "options": ["The frequency specifically at which digital images are updated to ensure smoothness", "The speed of a car", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents specific 'Gesture Recognition'?", "options": ["The ability specifically to identify and interpret human hand or body motions", "Recognizing a person", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Augmented Reality' in maintenance commonly used for?", "options": ["Displaying repair instructions specifically on top of complex machinery", "Cleaning a room", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What represents 'Interior Design' AR apps?", "options": ["Visualizing specifically how furniture or paint looks in a real room", "Painting a wall", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Outdoor AR' challenges?", "options": ["Varying light conditions specifically and GPS accuracy issues", "Getting wet in rain", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What represents the 'Field of Interest'?", "options": ["A specific area specifically in an AR scene where user attention is directed", "A types of a hobby", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How do you start an AR experience usually?", "options": ["Scanning specifically a physical area or a marker using a camera", "Pressing a physical button", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What represents 'Real-time Video Feed'?", "options": ["The live view specifically from a camera used as the background for AR content", "A recorded movie", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What represents specific 'User Interface' in AR?", "options": ["Designing labels, specifically buttons and menus that exist in 3D space", "A types of monitor", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What represents 'Tracking' failure symptoms?", "options": ["Virtual objects specifically drifting or disappearing from their intended location", "A types of illness", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What represents the 'Latency' goal?", "options": ["Achieving specifically very low delay to prevent motion sickness for users", "A types of slow speed", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What represents 'C#', for AR development?", "options": ["The primary programming language specifically for scripting in Unity for AR", "A types of music note", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents specific '6DOF' (Six Degrees of Freedom)?", "options": ["Tracking specifically both position and orientation of a device in 3D space", "A types of physics", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's '3DOF' limitation?", "options": ["Only tracking specifically the rotation of a device (not movement in space)", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents the 'Calibration' process?", "options": ["Setting specifically initial parameters for sensors to ensure accurate tracking", "Buying a new phone", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents 'Augmented Reality' in navigation?", "options": ["Displaying specifically digital arrows and directions on the physical road view", "Reading a map", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'ARCore' developed by?", "options": ["Google", "Apple", "Microsoft", "Meta"], "correct": 0},
        {"id": 71, "question": "What is 'ARKit' developed by?", "options": ["Apple", "Google", "Samsung", "Amazon"], "correct": 0},
        {"id": 73, "question": "What represents specific 'Surface Detection'?", "options": ["The ability specifically of an AR app to identify floors or walls automatically", "Finding a door", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents the 'Persistence' in AR?", "options": ["Saving specifically the position of virtual objects for future sessions", "Being patient", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents 'Cloud Anchors'?", "options": ["Allowing specifically multiple users to share a single AR experience in same space", "Anchors in sea", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What counts as 'Multi-user AR'?", "options": ["Collaborative experiences specifically where many people see and interact with same AR", "Using many phones", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents 'Industrial AR'?", "options": ["Using AR specifically to guide workers through complex manual processes", "A types of machine", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents specific 'Remote Assistance'?", "options": ["An expert guiding specifically someone in a different location using an AR view", "Talking on Skype", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What counts as 'Consumer AR'?", "options": ["AR apps specifically designed for everyday entertainment or information for anyone", "A shopping trip", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents 'Vulkan' or 'Metal' in AR context?", "options": ["Low-level specifically graphics APIs used for high-performance AR rendering", "Types of heavy metal", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is AR transforming the future of work?", "options": ["By bridging specifically the gap between digital data and physical action", "Because it uses more internet", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'SLAM' (Simultaneous Localization and Mapping)?", "options": ["Technology for tracking camera position and building maps in real-time", "A cleaning method", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Computer Vision' in AR?", "options": ["Enabling devices to understand and interpret visual information", "Making computers see", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Hand Tracking' in AR?", "options": ["Following hand position and gestures for interaction", "Tracking hand movement", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Eye Tracking' in AR?", "options": ["Following gaze to control interfaces", "Tracking eye movement", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Plane Detection' in AR?", "options": ["Identifying flat surfaces for placing virtual objects", "Finding flat areas", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Occlusion' in AR?", "options": ["Understanding when virtual objects are blocked by real-world objects", "Understanding blockage", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Light Estimation' in AR?", "options": ["Calculating how real-world lighting affects virtual objects", "Estimating light", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Persistent Tracking' in AR?", "options": ["Maintaining object positions and states across sessions", "Remembering positions", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Cloud Anchors' in AR?", "options": ["Virtual reference points fixed in real-world space", "Cloud storage", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'World Tracking' in AR?", "options": ["Mapping virtual content to real-world coordinates", "Following locations", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Spatial Audio' in AR?", "options": ["3D positional sound in AR environments", "Audio in space", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Haptic Feedback' in AR?", "options": ["Vibration and touch responses in AR controllers", "Sound feedback", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Multi-user' Collaboration' in AR?", "options": ["Multiple users interacting with same AR space simultaneously", "Working together", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'AR Cloud'?", "options": ["Cloud-based processing and storage for AR applications", "AR in clouds", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'WebAR'?", "options": ["AR experiences delivered through web browsers without apps", "AR on websites", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is '6DOF' vs '3DOF' tracking?", "options": ["6 degrees of freedom vs 3 degrees (more natural movement)", "They are the same", "None", "None"], "correct": 0},
        {"id": 97, "question": "What is 'Passthrough' AR?", "options": ["See-through view of real world through headset", "Passing through AR", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Foveated Rendering'?", "options": ["High-detail rendering where user looks", "Focused rendering", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Mixed Reality' (MR)?", "options": ["Combining VR/AR with real world view", "Mixed reality", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Neural Rendering'?", "options": ["Using AI to generate and optimize AR graphics", "AI for graphics", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
