import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_bigdatatools_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Big Data'?", "options": ["Small amount of information", "Large and complex datasets that traditional tools can't process", "A very big computer", "None"], "correct": 1},
        {"id": 2, "question": "Which of these is considered one of the 'Vs' of Big Data?", "options": ["Volume", "Velocity", "Variety", "All of the above"], "correct": 3},
        {"id": 3, "question": "What is 'Apache Hadoop'?", "options": ["A types of elephant", "An open-source framework for distributed storage and processing", "A web browser", "None"], "correct": 1},
        {"id": 4, "question": "What is 'HDFS' in Hadoop?", "options": ["Hadoop Distributed File System", "Hadoop Data Fast System", "High-speed Data File Stream", "None"], "correct": 0},
        {"id": 5, "question": "What is 'MapReduce' in Hadoop?", "options": ["A way to draw maps", "A programming model for processing large data in parallel across clusters", "A type of chart", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Apache Spark'?", "options": ["An engine for data processing", "A high-speed engine specifically for large-scale data and machine learning", "A type of battery", "None"], "correct": 1},
        {"id": 7, "question": "Why is 'Spark' generally faster than Hadoop MapReduce?", "options": ["It uses in-memory processing", "It is smaller", "It is written in Python", "None"], "correct": 0},
        {"id": 8, "question": "What is 'Apache Kafka' used for?", "options": ["Listening to music", "A distributed streaming platform for real-time data ingestion", "A type of table", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Apache Cassandra'?", "options": ["A person's name", "A distributed NoSQL database designed for high availability and scalability", "A technical specification", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Apache Hive' for Hadoop?", "options": ["Where Hadoop bees live", "A data warehouse software built on Hadoop using SQL-like queries", "A design tool", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Apache Pig' used for?", "options": ["Raising farm animals", "A high-level platform for creating MapReduce programs (script-like)", "None", "None"], "correct": 1},
        {"id": 12, "question": "What is 'YARN' (Yet Another Resource Negotiator)?", "options": ["A type of wool", "A resource-management platform responsible for clusters in Hadoop", "A security feature", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Apache HBase'?", "options": ["A database company", "A column-oriented NoSQL database running on top of HDFS", "A type of table", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Elasticsearch' used for?", "options": ["Searching for real items", "A distributed, RESTful search and analytics engine for Big Data", "A type of backup", "None"], "correct": 1},
        {"id": 15, "question": "What is 'MongoDB' in Big Data context?", "options": ["A NoSQL document-oriented database for unstructured data", "A relational database", "None", "None"], "correct": 0},
        {"id": 16, "question": "What is 'Data Visualization' tool for Big Data?", "options": ["Tableau", "Power BI", "Grafana", "All of the above"], "correct": 3},
        {"id": 17, "question": "What is 'Apache Flink' for?", "options": ["Connecting two clusters", "A framework for distributed, high-performance stream processing", "A tech spec", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Apache Storm' for?", "options": ["A weather monitor", "A system for real-time data processing and stream computing", "None of the above", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Splunk'?", "options": ["A decorative name", "A platform for searching, monitoring, and analyzing machine-generated big data", "A type of chart", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Apache Zookeeper' for?", "options": ["Keeping animals in a zoo", "A centralized service for coordination and managing cluster configuration", "A security log", "None"], "correct": 1},
        {"id": 21, "question": "What's the meaning of 'Scalability'?", "options": ["A type of measurement", "The ability for a system to process more work by adding hardware (cluster nodes)", "A technical manual", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Fault Tolerance'?", "options": ["Accepting bad behavior", "The ability for a system to continue operating when one or more components fail", "A design tool", "None"], "correct": 1},
        {"id": 23, "question": "What is 'ETL' (Extract, Transform, Load) for Big Data?", "options": ["Doing it once a year", "The process of getting and preparing data for Big Data warehouses", "None of the above", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Terabyte' (TB) in data storage context?", "options": ["1024 GB", "1024 MB", "1000 Bytes", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Petabyte' (PB) in data storage context?", "options": ["1024 TB", "1024 GB", "1000 Bytes", "None"], "correct": 0},
        {"id": 26, "question": "What is 'Data Ingestion'?", "options": ["Eating data", "The process of importing and collecting raw data into a database or lake", "None of the above", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Data Mining' for Big Data?", "options": ["Digging for physical gold", "The process of discovering patterns in large datasets using ML and stats", "Both A and B", "Neither"], "correct": 1},
        {"id": 28, "question": "Which of these is a cloud-based Big Data tool?", "options": ["AWS EMR", "Google BigQuery", "Azure HDInsight", "All of the above"], "correct": 3},
        {"id": 29, "question": "What is 'Unstructured Data'?", "options": ["Structured data only", "Data that doesn't follow a pre-defined model (e.g. text, images, videos)", "A tech spec", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Presto'?", "options": ["A magic trick", "A distributed SQL query engine for Big Data analytics", "None of the above", "None"], "correct": 1},
        {"id": 31, "question": "What represents specific 'Exabyte' (EB)?", "options": ["1024 Petabytes (PB)", "1024 Terabytes (TB)", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Zettabyte' (ZB)?", "options": ["1024 Exabytes (EB)", "1024 Pentabytes", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What's the meaning of 'Velocity' in Big Data?", "options": ["The speed specifically at which new data is generated and collected", "The distance travel", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the meaning of 'Veracity'?", "options": ["The accuracy specifically and reliability of the data", "The amount of data", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What's the meaning of 'Value' for Big Data?", "options": ["The usefulness specifically and benefits derived from analyzing the data", "The price of data", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents 'Semi-Structured Data'?", "options": ["Data that has some organizational properties like tags (e.g. JSON, XML)", "A broken table", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What represents specific 'Structured Data'?", "options": ["Data that follows a rigid, formal model specifically (e.g. SQL tables)", "A box of items", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Apache Druid' for?", "options": ["Real-time analytics specifically on large datasets with low latency", "Drawing objects", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Apache Solr' used for?", "options": ["Enterprise search platform specifically built on Apache Lucene", "Solar energy monitor", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's the purpose of 'Apache Airflow'?", "options": ["Orchestrating specifically and scheduling complex data pipelines/workflows", "Monitoring wind", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Apache Beam' used for?", "options": ["A unified model specifically for defining and executing data processing pipelines", "A beam of light", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's 'Dag' in Airflow context?", "options": ["Directed Acyclic Graph specifically to represent workflow task dependencies", "A sharp tool", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'Spark SQL' component?", "options": ["Module specifically for working with structured data using SQL queries in Spark", "A faster SQL", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Spark Streaming'?", "options": ["Enables specifically processing of live data streams in small batches", "Streaming a movie", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What represents the 'Graph Processing' (e.g. Spark GraphX)?", "options": ["Analyzing specifically data with complex relationships like social networks", "Drawing a graph", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'NoSQL' primarily?", "options": ["Broad class specifically of database systems that are non-relational", "Databases with zero SQL", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What represents 'Columnar Storage'?", "options": ["Storing data specifically by column instead of row for better query speed", "Putting things in columns", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's 'Key-Value' store example?", "options": ["Redis", "Memcached", "Both A and B", "Neither"], "correct": 2},
        {"id": 49, "question": "What's 'Document Store' example?", "options": ["MongoDB", "CouchDB", "Both A and B", "Neither"], "correct": 2},
        {"id": 50, "question": "What represents specific 'Data Center'?", "options": ["Centralized physical facility specifically to house computers and data servers", "A city center", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What represents 'Commodity Hardware'?", "options": ["Standard, inexpensive computers specifically used in large clusters", "Selling hardware", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's the meaning of 'Cluster'?", "options": ["A group specifically of interconnected computers working together as a single system", "A bunch of trees", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's the effect of 'Load Balancing'?", "options": ["Distributing specifically work among multiple nodes to optimize and scale", "Balancing a weight", "Neither", "Both"], "correct": 1},
        {"id": 54, "question": "What represents 'Replication' for Big Data?", "options": ["Storing specifically multiple copies of data across different nodes for safety", "Making a document copy", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents specific 'Data Locality'?", "options": ["Processing specifically data on the node where it is stored to avoid network delay", "Finding a place", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Data Integration'?", "options": ["Combining data specifically from different sources for a unified view", "Merging files", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What represents the 'Data Governance'?", "options": ["Policies specifically for managing the availability, usability and security of data", "Government rules", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's the meaning of 'Data Silo'?", "options": ["A collection of data specifically that is separate from and inaccessible to others", "A grain silo", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Snowflake' in cloud context?", "options": ["A popular fully managed cloud-based data warehouse service", "A types of ice", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What represents the 'Databricks'?", "options": ["A Unified Data Analytics Platform specifically based on Apache Spark", "Building with bricks", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Parquet' file format?", "options": ["An open-source columnar specifically storage format for high performance tasks", "A wooden floor", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Avro' format?", "options": ["A row-based specifically data serialization system for Hadoop", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What represents the 'ELT' (Extract, Load, Transform)?", "options": ["Loading data specifically to target before performing transformations", "Same as ETL", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Big Data Analytics'?", "options": ["Examining large data specifically to uncover hidden patterns and correlations", "Counting items", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What represents 'Predictive Analytics'?", "options": ["Using specifically data and historical patterns to predict future outcomes", "Telling the future", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's the purpose of 'Machine Learning' in Big Data?", "options": ["Using algorithms specifically that learn from large data to make predictions", "Teaching a person", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents 'In-Memory Analytics'?", "options": ["Querying specifically data that resides in RAM for extreme speed", "Remembering data", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents specific 'Dark Data'?", "options": ["Data that is collected specifically but not used or analyzed for insights", "Black colored data", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents 'Data Provenance'?", "options": ["The record specifically of where data came from and its transformation history", "A home address", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's the meaning of 'Sharding'?", "options": ["Horizontal partitioning specifically of data across multiple servers/databases", "A sharp shard", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's 'Hot Data' vs 'Cold Data'?", "options": ["Frequently accessed specifically vs rarely accessed data", "Temperature of PC", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents 'HDFS NameNode'?", "options": ["The master node specifically that manages the file system namespace and metadata", "A types of name", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents 'HDFS DataNode'?", "options": ["Nodes specifically responsible for storing the actual data blocks in Hadoop", "A node with info", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Rack Awareness' in Hadoop?", "options": ["Policy specifically to ensure data is mirrored across different hardware racks", "Knowing where stuff is", "Neither", "Both"], "correct": 1},
        {"id": 75, "question": "What represents 'Apache Ambari'?", "options": ["Open-source tool specifically for provisioning and managing Hadoop clusters", "A types of color", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Apache Mahout'?", "options": ["A library specifically for scalable machine learning on Hadoop", "A types of hat", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Apache Tez'?", "options": ["Framework specifically for executing complex DAGs of tasks in Hadoop", "A types of tea", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents specific 'Data Scientist' role?", "options": ["Professional specifically who cleans, analyzes and interprets complex data", "A types of doctor", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents specific 'Data Engineer' role?", "options": ["Professional specifically who builds and maintains data architecture/pipelines", "A person who builds bridges", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Big Data important for modern enterprises?", "options": ["Enables data-driven specifically decision making and competitive advantage", "Because it is popular", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Data Lake'?", "options": ["Centralized repository for storing raw structured and unstructured data", "A lake with data", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'ETL' in Big Data?", "options": ["Extract, Transform, Load process for data warehousing", "Electronic Transfer Load", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Data Warehouse'?", "options": ["Central repository of integrated data from multiple sources", "A storage building", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Hadoop Distributed File System' (HDFS)?", "options": ["Distributed file system designed for storing very large files", "A file system", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'MapReduce'?", "options": ["Programming model for processing large datasets in parallel", "A map reduction tool", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Apache Spark'?", "options": ["Unified analytics engine for large-scale data processing", "A firework tool", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Apache Kafka'?", "options": ["Distributed streaming platform for real-time data feeds", "A writer", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Apache Flink'?", "options": ["Stream processing framework for distributed computations", "A link tool", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Data Pipeline'?", "options": ["Series of data processing steps", "A pipe for data", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Schema Registry' in data governance?", "options": ["Central repository for managing data schemas", "A list of schemas", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Master Data Management' (MDM)?", "options": ["Process of creating single trusted view of data", "Managing master data", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Data Quality'?", "options": ["Degree to which data meets requirements for its intended use", "How good data is", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Data Governance'?", "options": ["Overall management of data availability, usability, security, and compliance", "Ruling data", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Data Lineage'?", "options": ["Tracking data's origin and movement through systems", "Family history of data", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Data Virtualization'?", "options": ["Creating virtual versions of data for testing", "Making data virtual", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Streaming Analytics'?", "options": ["Real-time processing and analysis of data streams", "Watching data streams", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Batch Processing'?", "options": ["Processing data in large groups rather than individually", "Processing in batches", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Real-time Analytics'?", "options": ["Immediate analysis of data as it arrives", "Fast analytics", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Predictive Analytics'?", "options": ["Using historical data to predict future outcomes", "Guessing analytics", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Prescriptive Analytics'?", "options": ["Recommending actions based on data analysis", "Writing prescriptions", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
