import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_c_data_structures_api(request):
    questions_pool = [
        {"id": 1, "question": "Who is the father of C language?", "options": ["Bjarne Stroustrup", "Dennis Ritchie", "James Gosling", "Guido van Rossum"], "correct": 1},
        {"id": 2, "question": "What is the result of 'printf(\"%d\", 5/2)' in C?", "options": ["2.5", "2", "3", "Error"], "correct": 1},
        {"id": 3, "question": "Which of these is used for multi-line comments in C?", "options": ["//", "/* */", "#", "--"], "correct": 1},
        {"id": 4, "question": "What is 'int *ptr;' in C?", "options": ["A pointer to an integer", "An integer variable", "A list of strings", "None"], "correct": 0},
        {"id": 5, "question": "What is 'malloc()' used for?", "options": ["Static memory allocation", "Dynamic memory allocation (heap)", "Deleting data", "None"], "correct": 1},
        {"id": 6, "question": "What is 'free()' in C?", "options": ["Deallocating previously allocated memory", "Making code run faster", "A type of loop", "None"], "correct": 0},
        {"id": 7, "question": "What is a 'Struct' in C?", "options": ["A way to group different data types for a complex object", "A routing module", "A type of array", "None"], "correct": 0},
        {"id": 8, "question": "What is 'Data Structure'?", "options": ["A physical computer part", "A way of organizing and storing data efficiently", "A list of files", "None"], "correct": 1},
        {"id": 9, "question": "What is a 'Linked List'?", "options": ["A set of connected strings", "A collection of nodes containing data and a reference to the next node", "A database record", "None"], "correct": 1},
        {"id": 10, "question": "What is the time complexity of searching in a balanced BST?", "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"], "correct": 2},
        {"id": 11, "question": "What is 'Stack'?", "options": ["A group of servers", "A linear data structure following Last In First Out (LIFO)", "A type of table", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Queue'?", "options": ["A line for users", "A linear data structure following First In First Out (FIFO)", "A routing engine", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Bubble Sort' complexity?", "options": ["O(n)", "O(log n)", "O(n^2)", "None"], "correct": 2},
        {"id": 14, "question": "What is the full form of ADT?", "options": ["Advanced Data Type", "Abstract Data Type", "Allocated Data Table", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Binary Search' complexity?", "options": ["O(n)", "O(log n)", "O(1)", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Recursion' in C?", "options": ["Calling a function within itself to solve smaller problems", "Deleting errors", "Both A and B", "Neither"], "correct": 0},
        {"id": 17, "question": "Which of these is a linear data structure?", "options": ["Trees", "Graphs", "Arrays", "Heaps"], "correct": 2},
        {"id": 18, "question": "Which of these is a non-linear data structure?", "options": ["Stacks", "Queues", "Linked Lists", "Trees"], "correct": 3},
        {"id": 19, "question": "What is 'Graph' in data structure?", "options": ["A mathematical chart", "A set of nodes (vertices) connected by edges", "A type of table", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Hash Table' used for?", "options": ["Creating data", "Efficiently storing and retrieving data using keys", "Sorting a list", "None"], "correct": 1},
        {"id": 21, "question": "What does '&' operator do in C?", "options": ["Logical AND", "Gets the address of a variable", "Bitwise AND", "None"], "correct": 1},
        {"id": 22, "question": "What does '*' operator do when defining a variable?", "options": ["De-referencing", "Declaring a pointer", "A comment symbol", "None"], "correct": 1},
        {"id": 23, "question": "What is the size of 'char' in C?", "options": ["1 bit", "1 byte", "2 bytes", "4 bytes"], "correct": 1},
        {"id": 24, "question": "What happens if you access an array out of bounds in C?", "options": ["Syntax error", "Undefined behavior", "Compilation error", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Header File' in C?", "options": ["A file for icons", "A file with .h extension for declarations and definitions", "A routing name", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Union' in C?", "options": ["A group of people", "A way to share the same memory location between different data types", "A type of link", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Enum' in C?", "options": ["An acronym for enumeration", "A user-defined type for a set of named integer constants", "Both A and B", "None"], "correct": 1},
        {"id": 28, "question": "What is 'NULL' pointer?", "options": ["A pointer that doesn't point to any memory location", "A type of error", "A decorative text", "None"], "correct": 0},
        {"id": 29, "question": "What is 'Call-by-Value'?", "options": ["Passing the value of a variable to a function as an argument", "Passing the memory address", "None of the above", "None"], "correct": 0},
        {"id": 30, "question": "What is 'Call-by-Reference'?", "options": ["Passing the value", "Passing the memory address of the variable to a function", "None of the above", "None"], "correct": 1},
        {"id": 31, "question": "What is 'Time Complexity'?", "options": ["The time spent by developer on code", "The study of efficiency of an algorithm by the amount of time it takes to run", "None of the above", "None"], "correct": 1},
        {"id": 32, "question": "What is 'Space Complexity'?", "options": ["The size of a laptop", "The amount of memory needed by an algorithm during execution", "None", "None"], "correct": 1},
        {"id": 33, "question": "What is the difference between Array and Linked List?", "options": ["Array has fixed size; Linked List has dynamic size", "Array stores data in contiguous memory; Linked List doesn't", "Both A and B", "Neither"], "correct": 2},
        {"id": 34, "question": "What is the best case complexity of 'Quick Sort'?", "options": ["O(n)", "O(n log n)", "O(n^2)", "None"], "correct": 1},
        {"id": 35, "question": "What is 'Worst Case' complexity of Quick Sort?", "options": ["O(n)", "O(n^2)", "O(n log n)", "None"], "correct": 1},
        {"id": 36, "question": "What is the complexity of 'Merge Sort'?", "options": ["O(n log n)", "O(n^2)", "O(1)", "None"], "correct": 0},
        {"id": 37, "question": "Which sorting algorithm is most efficient for small datasets?", "options": ["Quick Sort", "Insertion Sort", "Merge Sort", "None"], "correct": 1},
        {"id": 38, "question": "What is 'Tail Recursion'?", "options": ["A type of error", "Recursive call made at the end of the function without any logic after it", "A design language", "None"], "correct": 1},
        {"id": 39, "question": "What is the result of 'pow(2, 3)' in math.h?", "options": ["5", "6", "8", "9"], "correct": 2},
        {"id": 40, "question": "What is 'String' in C?", "options": ["A special data type", "An array of characters terminated by a null character ('\\0')", "A type of table", "None"], "correct": 1},
        {"id": 41, "question": "Which function is used to find the length of a string in C?", "options": ["len()", "strlen()", "size()", "None"], "correct": 1},
        {"id": 42, "question": "Which function is used to compare two strings in C?", "options": ["compare()", "strcmp()", "match()", "None"], "correct": 1},
        {"id": 43, "question": "Which function is used to copy a string in C?", "options": ["copy()", "strcpy()", "dup()", "None"], "correct": 1},
        {"id": 44, "question": "Which function is used to concatenate strings in C?", "options": ["cat()", "strcat()", "join()", "None"], "correct": 1},
        {"id": 45, "question": "What is 'File Handling' in C?", "options": ["Wiping physical disks", "Managing reading and writing data to files on the persistent disk", "A security log", "None"], "correct": 1},
        {"id": 46, "question": "What is 'FILE *fp;'?", "options": ["A pointer for memory", "A pointer for a file object", "A list of strings", "None"], "correct": 1},
        {"id": 47, "question": "Which function is used to open a file in C?", "options": ["op()", "fopen()", "start()", "None"], "correct": 1},
        {"id": 48, "question": "Which function is used to close an open file in C?", "options": ["close()", "fclose()", "end()", "None"], "correct": 1},
        {"id": 49, "question": "What is the result of 'sizeof(int)' on a typical 64-bit machine?", "options": ["2 bytes", "4 bytes", "8 bytes", "None"], "correct": 1},
        {"id": 50, "question": "What is 'Big O' notation used for?", "options": ["Calculating math results", "Representing the upper bound of time/space complexity", "None of the above", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Double Linked List'?", "options": ["Two lists together", "A linked list where each node has references to both next and previous nodes", "A type of table", "None"], "correct": 1},
        {"id": 52, "question": "What is 'Circular Linked List'?", "options": ["A list with no end", "A linked list where the last node points back to the first node", "A technical specification", "None"], "correct": 1},
        {"id": 53, "question": "What is 'AVL Tree'?", "options": ["A decorative tree", "A self-balancing binary search tree", "A type of graph", "None"], "correct": 1},
        {"id": 54, "question": "What is 'Primary Memory' vs 'Secondary Memory'?", "options": ["RAM vs Disk", "Disk vs RAM", "They are identical", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Bitwise' operator used for?", "options": ["Logic for strings", "Performing bit-level operations (AND, OR, NOT, XOR, Shift)", "None of the above", "None"], "correct": 1},
        {"id": 56, "question": "What is the result of '5 << 1' (Left Shift)?", "options": ["2", "10", "25", "None"], "correct": 1},
        {"id": 57, "question": "What is the result of '5 >> 1' (Right Shift)?", "options": ["10", "2", "1", "None"], "correct": 1},
        {"id": 58, "question": "What is 'Dangling Pointer'?", "options": ["A pointer that is not used", "A pointer that points to a memory location that has been deleted", "A type of table", "None"], "correct": 1},
        {"id": 59, "question": "What is 'Memory Leak'?", "options": ["A physical computer leaking oil", "When allocated memory is not deallocated when it is no longer needed", "A security bug", "None"], "correct": 1},
        {"id": 60, "question": "What is 'Heap' vs 'Stack' memory?", "options": ["Heap is dynamic; Stack is static/local", "Stack is dynamic; Heap is static", "Nothing", "None"], "correct": 0},
        {"id": 61, "question": "What is 'Macros' in C (#define)?", "options": ["A large version of an app", "A rule for substitution of text before compilation", "A technical specification", "None"], "correct": 1},
        {"id": 62, "question": "What is 'Pre-processor'?", "options": ["The program that runs before compilation to handle macros and directives", "A new computer CPU", "None of the above", "None"], "correct": 0},
        {"id": 63, "question": "What is 'Static' keyword for variables?", "options": ["A variable that never changes", "A variable whose value persists between multiple function calls", "None of the above", "None"], "correct": 1},
        {"id": 64, "question": "What is 'External' variable (extern)?", "options": ["A variable outside a file, used for multiple files", "A secret variable", "A type of table", "None"], "correct": 0},
        {"id": 65, "question": "What is 'Auto' variable?", "options": ["Automatically deleting a variable", "Default storage class for local variables", "None of the above", "None"], "correct": 1},
        {"id": 66, "question": "What is 'Register' storage class?", "options": ["Storing data in a book", "Advising the compiler to store a variable in a CPU register for speed", "A design tool", "None"], "correct": 1},
        {"id": 67, "question": "What is 'Breadth First Search' (BFS) for graphs?", "options": ["Traversing deep first", "Traversing layer-by-layer (layer first)", "Sorting a list", "None"], "correct": 1},
        {"id": 68, "question": "What is 'Depth First Search' (DFS)?", "options": ["Traversing layer-by-layer", "Traversing deep into a branch as far as possible first", "None of the above", "None"], "correct": 1},
        {"id": 69, "question": "What is 'Dijkstra's Algorithm' used for?", "options": ["Sorting a simple list", "Finding the shortest path between nodes in a graph", "Deleting a database", "None"], "correct": 1},
        {"id": 70, "question": "What is 'Spanning Tree'?", "options": ["A tree that spans multiple years", "A subgraph that contains all vertices of a graph and is a tree", "None", "None"], "correct": 1},
        {"id": 71, "question": "What is 'Minimum Spanning Tree' (MST)?", "options": ["A spanning tree with the least total weight of edges", "A small graph", "A decorative design", "None"], "correct": 0},
        {"id": 72, "question": "Which algorithm finds the MST of a graph?", "options": ["Kruskal's", "Prim's", "Both A and B", "None"], "correct": 2},
        {"id": 73, "question": "What is 'Dynamic Programming'?", "options": ["Writing fast code", "Breaking a problem into overlapping subproblems and storing results", "A decorative design", "None"], "correct": 1},
        {"id": 74, "question": "What is 'Greedy Algorithm'?", "options": ["Taking all data at once", "An algorithm that makes the locally optimal choice at each stage", "Both A and B", "Neither"], "correct": 1},
        {"id": 75, "question": "What is 'Matrix' in C?", "options": ["A movie name", "A 2D array of elements", "A type of table", "None"], "correct": 1},
        {"id": 76, "question": "What is 'Trie' data structure?", "options": ["A tree used for efficient string retrieval (prefix tree)", "Drawing a chart", "None of the above", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Skip List'?", "options": ["A list meant to skip people", "A probabilistic data structure that allows fast search within an ordered sequence", "None", "None"], "correct": 1},
        {"id": 78, "question": "What is the complexity of inserting into a Heap?", "options": ["O(1)", "O(n)", "O(log n)", "O(n^2)"], "correct": 2},
        {"id": 79, "question": "What is 'Priority Queue'?", "options": ["A queue where items have priorities and higher priority items are served first", "A regular list", "A security log", "None"], "correct": 0},
        {"id": 80, "question": "Which function is used for getting user input in C?", "options": ["printf()", "scanf()", "put()", "None"], "correct": 1},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
