import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_c_sharp_api(request):
    questions_pool = [
        {"id": 1, "question": "What is C#?", "options": ["A types of car", "A modern, object-oriented programming language developed by Microsoft", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "What is 'Namespace' in C#?", "options": ["A name for a project", "A way to organize related classes and resources together", "A type of chart", "None"], "correct": 1},
        {"id": 3, "question": "What is a 'Class' in C#?", "options": ["A social group", "A blueprint for creating objects (data + methods)", "A type of table", "None"], "correct": 1},
        {"id": 4, "question": "What is an 'Object'?", "options": ["A physical item", "An instance of a class", "A code record", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Inheritance' in C#?", "options": ["Inheriting money", "The mechanism where one class inherits behavior from another", "A type of chart", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Polymorphism'?", "options": ["A game", "The ability of different classes to be treated as a common base", "A type of error", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Encapsulation'?", "options": ["Hiding complexity by bundling data and methods within a class", "Sharing all data", "A type of view", "None"], "correct": 0},
        {"id": 8, "question": "What is 'CLR' (Common Language Runtime)?", "options": ["A physical speaker", "The execution engine that handles running C# code", "A design language", "None"], "correct": 1},
        {"id": 9, "question": "What is '.NET Framework'?", "options": ["A development platform for building web and desktop apps", "A routing engine", "A mobile OS", "None"], "correct": 0},
        {"id": 10, "question": "What is 'Value Type' vs 'Reference Type'?", "options": ["Value type stores data directly; Reference type stores memory location", "They are identical", "Reference type is faster for big data", "None"], "correct": 0},
        {"id": 11, "question": "What is 'Struct' in C#?", "options": ["A type of data key", "A lightweight value type similar to a class", "A list of strings", "None"], "correct": 1},
        {"id": 12, "question": "What is an 'Interface' in C#?", "options": ["A decorative screen", "A contract defining a group of related functionalities", "A type of view", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Abstract Class'?", "options": ["A class for drawings", "A class that cannot be instantiated and is used as a base class", "A type of table", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Property' in C#?", "options": ["A house name", "A member that provides flexible mechanism to read/write/compute value of a private field", "A type of file", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Delegate'?", "options": ["A person in charge", "A type representing references to methods with a particular parameter list/return type", "None of the above", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Event' in C#?", "options": ["A party", "A special kind of multicast delegate that can only be invoked within the class where it is declared", "A security token", "None"], "correct": 1},
        {"id": 17, "question": "What is 'LINQ' (Language Integrated Query)?", "options": ["A list management app", "A set of features providing uniform syntax for data queries", "A decorative text", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Garbage Collection' (GC) in .NET?", "options": ["Cleaning up a physical room", "Automated memory management that reclaims unused memory locations", "Deleting records", "None"], "correct": 1},
        {"id": 19, "question": "What is 'async' and 'await'?", "options": ["Keywords for multi-threading", "Keywords for writing asynchronous code to avoid blocking UI", "Both A and B", "Neither"], "correct": 1},
        {"id": 20, "question": "What is 'Exception Handling' in C#?", "options": ["Handling errors using try, catch, finally blocks", "Ignoring errors", "Starting a program", "None"], "correct": 0},
        {"id": 21, "question": "What is '.NET Core' vs .NET Framework?", "options": [".NET Core is for modern, cross-platform apps", ".NET Framework is legacy for Windows apps", "Both A and B", "Neither"], "correct": 2},
        {"id": 22, "question": "What is 'Entity Framework Core'?", "options": ["A modern ORM for .NET Core", "A database engine", "None of the above", "None"], "correct": 0},
        {"id": 23, "question": "What is 'C# Partial Class'?", "options": ["A class for parts", "A way to split class definitions into multiple files", "A routing module", "None"], "correct": 1},
        {"id": 24, "question": "What is 'C# Static Class'?", "options": ["A class that never changes", "A class that cannot be instantiated and all its members must be static", "Both A and B", "None"], "correct": 1},
        {"id": 25, "question": "Which operator is the 'Null-coalescing' operator in C#?", "options": ["==", "??", "||", "&&"], "correct": 1},
        {"id": 26, "question": "What is 'C# Array'?", "options": ["A collection of random objects", "A fixed-size collection of elements of same type in contiguous memory", "A type of table", "None"], "correct": 1},
        {"id": 27, "question": "What is 'C# List'?", "options": ["A static list", "A dynamic-sized collection of elements", "A tech spec", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Dictionary' in C#?", "options": ["A book of definitions", "A collection of key-value pairs for efficient retrieval", "A security log", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Reflection' in C#?", "options": ["Seeing your face in code", "A mechanism to inspect metadata and interact with types at runtime", "A decorative part of an app", "None"], "correct": 1},
        {"id": 30, "question": "What is 'C# Attribute'?", "options": ["A characteristic of a variable", "A declarative tag used to convey information about behavior to the CLR", "A type of table", "None"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is the entry point of a C# console application?", "options": ["Start()", "Main()", "Init()", "Run()"], "correct": 1},
        {"id": 32, "question": "What is 'Nullable' type in C#?", "options": ["A type that cannot be zero", "A value type that can also represent a null value", "None of the above", "None"], "correct": 1},
        {"id": 33, "question": "What is 'Boxing'?", "options": ["Sports with code", "Converting a value type into a reference type (object)", "A type of chart", "None"], "correct": 1},
        {"id": 34, "question": "What is 'Unboxing'?", "options": ["Opening a digital box", "Converting a reference type back into a value type", "Both A and B", "Neither"], "correct": 1},
        {"id": 35, "question": "What is 'Readonly' keyword for a field?", "options": ["A secret field", "A field whose value can only be set in the constructor", "A tech spec", "None"], "correct": 1},
        {"id": 36, "question": "What is 'Const' keyword for a variable?", "options": ["A variable with fixed value set during compile-time", "A variable for constants", "Both A and B", "Neither"], "correct": 2},
        {"id": 37, "question": "What is 'Enum' in C#?", "options": ["A distinct type that consists of a set of named constants", "A number list", "A security token", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Tuple' in C#?", "options": ["A group of items", "A lightweight data structure for a finite sequence of elements", "A design tool", "None"], "correct": 1},
        {"id": 39, "question": "What's the meaning of 'Generics' in C#?", "options": ["A type of brand", "A feature allowing templates for components that can handle any data type", "None of the above", "None"], "correct": 1},
        {"id": 40, "question": "Which keyword is used to inherit a class or interface?", "options": [":", "->", "=>", "ext"], "correct": 0},
        {"id": 41, "question": "What is 'Base' keyword for?", "options": ["Accessing members of a parent (base) class", "Setting a new computer base", "A security feature", "None"], "correct": 0},
        {"id": 42, "question": "What is 'This' keyword for?", "options": ["Referring to the current instance of a class", "Pointing at a person", "A type of variable", "None"], "correct": 0},
        {"id": 43, "question": "What is 'Yield' keyword for?", "options": ["Stopping code", "Providing an iterator for a collection in a sequence", "None of the above", "None"], "correct": 1},
        {"id": 44, "question": "What is 'Var' keyword?", "options": ["Implicitly typed local variable", "Explicitly typed variable", "Both A and B", "Neither"], "correct": 0},
        {"id": 45, "question": "What is 'Dynamic' keyword in C# 4.0+?", "options": ["A dynamic variable", "Allows operations to bypass compile-time checks and be resolved at runtime", "A type of chart", "None"], "correct": 1},
        {"id": 46, "question": "What is 'Extension Method'?", "options": ["Extending a phone line", "A way to add new methods to existing types without modifying the original code", "A design tool", "None"], "correct": 1},
        {"id": 47, "question": "What is 'Lambda Expression' in C#?", "options": ["An anonymous function defined with '=>' symbol", "An error code", "A type of file", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Expression Bodied Member'?", "options": ["A decorative code snippet", "A concise syntax for defining members (like properties/methods) using '=>'", "A type of table", "None"], "correct": 1},
        {"id": 49, "question": "What is 'String Interpolation'?", "options": ["Joining strings", "A feature for embedding variables within string literals ($'Name is {name}')", "A type of database", "None"], "correct": 1},
        {"id": 50, "question": "What is 'Lock' keyword used for?", "options": ["Locking a home door", "To ensure that one thread doesn't enter a critical section while another is in it", "Starting a database", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Monitor' class used for?", "options": ["Watching the computer screen", "A advanced version of lock with more control features", "None of the above", "None"], "correct": 1},
        {"id": 52, "question": "What is 'Mutex' in C# multi-threading?", "options": ["Mutual exclusion across multiple processes", "A type of file", "A technical manual", "None"], "correct": 0},
        {"id": 53, "question": "What is 'Semaphore'?", "options": ["A signaling device", "A multi-threading tool that limits the number of threads accessing a resource", "None of the above", "None"], "correct": 1},
        {"id": 54, "question": "What's 'TPL' (Task Parallel Library)?", "options": ["A set of APIs for writing parallel and concurrent code in .NET", "A list of developers", "A design tool", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Task' specifically?", "options": ["A unit of work that can be executed asynchronously", "A physical project", "A type of chart", "None"], "correct": 0},
        {"id": 56, "question": "What is 'PLINQ'?", "options": ["A parallel version of LINQ to Objects", "A decorative text", "None of the above", "None"], "correct": 0},
        {"id": 57, "question": "What is 'C# Indexer'?", "options": ["A tool for book indexes", "Allows instances of a class to be indexed like an array", "A tech spec", "None"], "correct": 1},
        {"id": 58, "question": "What's 'Enum.Parse' used for?", "options": ["Converting a string to its corresponding enum value", "Deleting an enum", "A routing name", "None"], "correct": 0},
        {"id": 59, "question": "Which of these is a valid C# access modifier?", "options": ["Public", "Internal", "Protected", "All of the above"], "correct": 3},
        {"id": 60, "question": "What is the result of '10 / 3' in integer context?", "options": ["3.33", "3", "4", "Error"], "correct": 1},
        {"id": 61, "question": "What is 'Params' keyword?", "options": ["Parameters list", "Allows passing a variable number of arguments of a specific type to a method", "Both", "None"], "correct": 1},
        {"id": 62, "question": "What is 'Out' parameter?", "options": ["Output parameter only", "Allows passing variables by reference for returning multiple values from a method", "A decorative part of code", "None"], "correct": 1},
        {"id": 63, "question": "What is 'Ref' parameter?", "options": ["Reference to an object only", "Indicates that the variable is passed by reference (must be initialized before)", "None of the above", "None"], "correct": 1},
        {"id": 64, "question": "What's 'Struct vs Class' performance-wise?", "options": ["Class is faster for objects", "Struct is faster for small, simple data as it lives on Stack", "None of the above", "None"], "correct": 1},
        {"id": 65, "question": "What is 'C# Generic Constraint' (where T : class)?", "options": ["Limiting T to only be a class type", "Formatting text", "A type of chart", "None"], "correct": 0},
        {"id": 66, "question": "What is 'C# Finalizer' (~ClassName)?", "options": ["A method for closing files", "A special method called by the GC to clean up unmanaged resources", "Both", "None"], "correct": 1},
        {"id": 67, "question": "What is 'IDisposable' interface?", "options": ["For objects that are no longer usable", "Defines a mechanism for releasing unmanaged resources explicitly", "None of the above", "None"], "correct": 1},
        {"id": 68, "question": "What's the meaning of 'Using' block for IDisposable?", "options": ["Adding a new file", "Ensures that Dispose() is called automatically at the end of the block", "A routing name", "None"], "correct": 1},
        {"id": 69, "question": "What is 'C# 9.0 Records'?", "options": ["Database records", "Reference types with value-based equality behavior", "Both A and B", "Neither"], "correct": 1},
        {"id": 70, "question": "What is 'Init-only property' (C# 9.0)?", "options": ["Property that can only be set during object initialization", "Property for integers", "A tech spec", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Pattern Matching' (is, switch)?", "options": ["Finding matching designs", "A powerful way to check types and properties of objects in C#", "None of the above", "None"], "correct": 1},
        {"id": 72, "question": "What's the result of 'String.IsNullOrEmpty'?", "options": ["True if null or has zero length", "True if null only", "False always", "None"], "correct": 0},
        {"id": 73, "question": "What is 'C# Extension Method' syntax requirements?", "options": ["Static method in a static class with 'this' first parameter", "A simple method", "A security feature", "None"], "correct": 0},
        {"id": 74, "question": "What is 'Dynamic binding' vs 'Static binding'?", "options": ["Resolved at runtime vs Resolved at compile-time", "Same", "No meaning in C#", "None"], "correct": 0},
        {"id": 75, "question": "What is 'Reflection.Emit' used for?", "options": ["Creating code dynamically at runtime", "Printing objects", "Both A and B", "None"], "correct": 0},
        {"id": 76, "question": "What's 'ASP.NET Core Kestrel' server?", "options": ["A browser", "High-performance web server integrated with .NET Core", "A mobile OS", "None"], "correct": 1},
        {"id": 77, "question": "What is 'NuGet Package'?", "options": ["A type of food", "A software package for .NET for managing libraries and dependencies", "None of the above", "None"], "correct": 1},
        {"id": 78, "question": "What is 'WPF' (Windows Presentation Foundation)?", "options": ["UI framework for building desktop apps for Windows", "A web framework", "None of the above", "None"], "correct": 0},
        {"id": 79, "question": "What is 'Silverlight'?", "options": ["A deprecated web framework similar to Flash", "A type of light", "None", "None"], "correct": 0},
        {"id": 80, "question": "What is 'Xamarin' primarily for?", "options": ["Mobile development only", "Cross-platform mobile app development (iOS, Android) using C#/.NET", "None of the above", "None"], "correct": 1},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
