import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_cicd_api(request):
    questions_pool = [
        {"id": 1, "question": "What does CI/CD stand for?", "options": ["Constant Improvement / Cloud Delivery", "Continuous Integration / Continuous Deployment or Delivery", "Neither", "Both"], "correct": 1},
        {"id": 2, "question": "What is 'Continuous Integration' (CI)?", "options": ["Automatically merging code changes from many contributors frequently", "Merging only once a week", "Neither", "Both"], "correct": 0},
        {"id": 3, "question": "What is 'Continuous Delivery' (CD)?", "options": ["Code is always ready for a production release through automation", "Delivering mail continuously", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Continuous Deployment' (CD)?", "options": ["Every validated code change is automatically released to customers", "Manual release only", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What's the difference between Continuous Delivery and Deployment?", "options": ["Delivery requires a manual approval step to push to production; Deployment is fully automatic", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "Which of these is a popular CI/CD tool?", "options": ["Jenkins", "GitLab CI/CD", "CircleCI", "All of the above"], "correct": 3},
        {"id": 7, "question": "What is a 'Pipeline' in CI/CD context?", "options": ["The automated sequence of steps to build, test, and deliver code", "A water pipe", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What's the meaning of 'Build Stage'?", "options": ["Compiling code and resolving dependencies automatically", "Starting a building project", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Test Stage' in a pipeline?", "options": ["Running unit, integration, and other tests to ensure quality", "Reviewing photos", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Deploy Stage'?", "options": ["Actually moving the software code to an environment (staging or production)", "Writing code only", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Automation' importance in CI/CD?", "options": ["Removing manual steps for speed, reliability, and frequency of updates", "Using more humans", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'Artifact' in a pipeline context?", "options": ["Tangible result of a build (e.g. JAR, Docker image) to be deployed", "A historic item", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What's the meaning of 'Rollback' in CI/CD?", "options": ["A hardware reset", "Reverting to a previous stable state after a failed update", "Neither", "Both"], "correct": 1},
        {"id": 14, "question": "What's 'Blue-Green Deployment'?", "options": ["Using two identical environments to reduce downtime for updates", "A UI redesign", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Canary Deployment'?", "options": ["Updating a small percentage of users first to test for errors", "A bird in a cage", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'A/B Testing' through CD?", "options": ["Releasing different versions to groups to measure performance/preference", "A math test", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Infrastructure as Code' (IaC)?", "options": ["Managing IT infrastructure (servers, network) using code files", "Writing code on a server", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "Which of these is an IaC tool?", "options": ["Terraform", "Ansible", "Pulumi", "All of the above"], "correct": 3},
        {"id": 19, "question": "What's the meaning of 'Staging Environment'?", "options": ["A pre-production environment mimicking the real one for final checks", "A theater stage", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Environment Variable' significance?", "options": ["Storing config settings (keys, URLs) separate from the code", "Secret text for humans only", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Jenkins' primarily used for?", "options": ["Open-source automation server for building CI/CD pipelines", "A famous person", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What is 'GitHub Actions' significance?", "options": ["Providing built-in CI/CD platform directly within the GitHub repo", "Buttons on GitHub", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What's a 'Git Hook'?", "options": ["Automated triggers that run scripts at specific Git lifecycle events (like push)", "A physical hook", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What's 'DevOps' cultural impact?", "options": ["Combining dev and ops for faster, more reliable software delivery", "Hiring more people", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'SRE' (Site Reliability Engineering)?", "options": ["Operations approach that uses software engineering for reliability", "A security team", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Unit Test' in CI?", "options": ["Testing small individual components of code automatically during integration", "Testing for units", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Integration Test' in CI?", "options": ["Testing how multiple code modules work together as a system", "A long test", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Regression Test'?", "options": ["Ensuring that new updates didn't break existing working features", "Deleting old code", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'Static Code Analysis' (Linting)?", "options": ["Checking code for errors or style issues without actually running it", "Reading code out loud", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "What's the value of using CI/CD in businesses?", "options": ["Faster time-to-market and lower failure rates in production", "Buying more servers", "Neither", "Both"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Secret Management'?", "options": ["Hiding keys", "Securely storing and distributing API keys and passwords in pipelines", "Neither", "Both"], "correct": 1},
        {"id": 32, "question": "What is 'Build Agent' (Runner)?", "options": ["A separate machine used to execute the pipeline jobs", "A person building something", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What's 'Orchestration' role?", "options": ["Coordinating automated tasks across different systems and environments", "Music directing", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Kubernetes' role in CD?", "options": ["Providing reliable platform for automatically deploying containerized apps", "Drawing charts", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Docker' role in CI/CD?", "options": ["Ensuring consistent environments across development and production", "A types of database", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'GitFlow'?", "options": ["A common branching model for managing releases in a team", "Moving water in Git", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's 'Trunk-based Development'?", "options": ["Developers collaborating on a single main branch (trunk) with frequent integration", "Developing a tree", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What's 'Feature Toggle' (Flags)?", "options": ["Enabling/disabling features in production without redeploying code", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What's 'Hotfix'?", "options": ["A fast fix applied to the production code for critical bugs", "A heated fix", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Immutable Infrastructure'?", "options": ["Never modifying a server; replacing it entirely with new version", "A very strong server", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Serverless' in CI/CD?", "options": ["Automatically scaling and running code without managing VM instances", "No servers at all", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's 'VPC' networking role?", "options": ["Isolating and securing the infrastructure where deployments happen", "A types of video", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Self-Healing' in a pipeline?", "options": ["Automatically detecting and restarting failed services", "Healing a person", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Monitoring' role post-deploy?", "options": ["Observing system health and logs in production for errors", "Watching TV", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'WebHook' use?", "options": ["System-to-system notifications (e.g. Git notifies Jenkins to start build)", "A web-based tool", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Feedback Loop' in DevOps?", "options": ["Getting quick results from tests to developers to fix bugs faster", "A loop of noise", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What's 'Zero Downtime' goal?", "options": ["Users should not experience any interruption during a deployment", "Working extremely fast", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "Which constant is commonly used for CI config file?", "options": ["YAML", "JSON", "Both A and B", "None"], "correct": 0},
        {"id": 49, "question": "What is 'Managed CI/CD' (e.g. Travis CI)?", "options": ["Platform-as-a-Service for CI/CD requiring limited setup", "A manager doing it", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What's 'Code Linting' significance?", "options": ["Fixing style and common bugs upfront during the CI stage", "Fixing fabric", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Release' versus 'Deployment'?", "options": ["Deployment moves bits to a server; Release makes the feature visible to users", "Same things", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'GitLab CI/CD' uniqueness?", "options": ["Integrated directly into GitLab repositories out of box", "A famous person", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Cloud-Native' CI/CD tools?", "options": ["Built specifically for cloud environments like Kubernetes", "Being born in cloud", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Configuration as Code' (CaC)?", "options": ["Managing application settings through version-controlled files", "Writing config on a server", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's 'Scalability' importance for CI servers?", "options": ["Handling many simultaneous builds without slow-downs", "Measuring things", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Downtime' cost (financial/brand)?", "options": ["Lost revenue and trust when customers can't use the app", "Waiting time only", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Manual Intervention' risk?", "options": ["Chance of human error increases when steps aren't automated", "Hiring humans", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Deployment Frequency' metric?", "options": ["The rate at which code is delivered to production (aim for high frequency)", "A radio frequency", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'Lead Time for Changes'?", "options": ["Time from commit to successfully running in production", "How long you wait", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Mean Time to Recovery' (MTTR)?", "options": ["The average time to fix a problem in production after it's detected", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Change Failure Rate'?", "options": ["Percentage of changes that result in failure or need immediate rollback", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What are 'DORA metrics'?", "options": ["Standard metrics for measuring DevOps performance of a team", "Dora the explorer", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'GitOps'?", "options": ["Operations using Git as the source of truth for entire infrastructure", "A type of game", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'ChatOps'?", "options": ["Performing operations tasks through conversation within tools like Slack", "Talking to ops team", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Container Registry' role in CI/CD?", "options": ["Storing and managing container images produced by build stage", "A folder of boxes", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Code Review' role in CI/CD?", "options": ["Human check of quality before code integrated into main branch", "Reading a book", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Automatic Rollback'?", "options": ["Automated revert if system monitors detect errors after deployment", "Rolling a ball back", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Shadowing' in deployment?", "options": ["Sending real traffic to new version but without using its output yet", "Following a person", "Neither", "Both"], "correct": 1},
        {"id": 69, "question": "What is 'Shift-Left' in testing?", "options": ["Testing earlier in the development lifecycle to find bugs sooner", "Moving things to left", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's 'Vulnerability Scanning' component?", "options": ["Checking code for security holes automatically during build stage", "Scanning a face", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Jenkins Pipeline' (Scripts)?", "options": ["Defining the automation steps in groovy scripts in Jenkins", "A pipeline with water", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Travis CI'?", "options": ["A cloud-based CI service that integrates tightly with GitHub repo", "A famous person", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'CircleCI'?", "options": ["A cloud CI/CD platform known for speed and YAML configuration", "A circle tool", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "Which of these is a Cloud-provider native tool?", "options": ["AWS CodePipeline", "Azure Pipelines", "Google Cloud Build", "All of the above"], "correct": 3},
        {"id": 75, "question": "What's 'Microservices' significance to CI/CD pipelines?", "options": ["Often requires many small, independent pipelines per service", "Small computer parts", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Server Hardening' in deployment context?", "options": ["Securing the server automatically during the deployment process", "Making a server physical stronger", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "How can you speed up a pipeline?", "options": ["Running tests in parallel and caching dependencies", "Removing all tests", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Caching' in a build process?", "options": ["Saving downloaded libraries to avoid re-downloading on every run", "Storing money", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which constant is used to denote a successful build?", "options": ["Success / Pass", "Done", "Both", "Neither"], "correct": 0},
        {"id": 80, "question": "What is the primary message of 'Continuous' everything?", "options": ["Improving speed, quality and reliability through constant feedback loops", "Working non-stop", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Blue-Green Deployment'?", "options": ["Zero-downtime deployment strategy", "Deployment with colors", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Canary Deployment'?", "options": ["Gradual rollout to subset of users", "Bird deployment", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Rolling Deployment'?", "options": ["Gradual replacement of instances", "Rolling deployment", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Feature Flag'?", "options": ["Toggle for enabling/disabling features", "Flag for features", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'A/B Testing' in deployment?", "options": ["Comparing two versions", "Testing letters", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Infrastructure as Code' (IaC)?", "options": ["Managing infrastructure through code", "Code for infrastructure", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'GitOps'?", "options": ["Git-based operations", "Operations with Git", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'DevSecOps'?", "options": ["Integrating security into DevOps", "Security in DevOps", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Site Reliability Engineering' (SRE)?", "options": ["Applying engineering to reliability", "Reliability engineering", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Observability'?", "options": ["Ability to understand system from external signals", "Observing systems", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Pipeline as Code'?", "options": ["Defining pipelines in code", "Code for pipelines", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'GitOps'?", "options": ["Git-based operations", "Operations with Git", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'DevSecOps'?", "options": ["Integrating security into DevOps", "Security in DevOps", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Site Reliability Engineering' (SRE)?", "options": ["Applying engineering to reliability", "Reliability engineering", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Observability'?", "options": ["Ability to understand system from external signals", "Observing systems", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Pipeline as Code'?", "options": ["Defining pipelines in code", "Code for pipelines", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Chaos Engineering'?", "options": ["Testing resilience through controlled failures", "Engineering chaos", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Value Stream Mapping'?", "options": ["Visualizing workflow steps", "Mapping value streams", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Continuous Improvement'?", "options": ["Ongoing process optimization", "Improving continuously", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'DevOps Culture'?", "options": ["Collaborative environment for development and operations", "Culture for DevOps", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
