import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_cloudbasics_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Cloud Computing?", "options": ["Computing on a cloud in sky", "Delivering computing services over the internet on demand", "A local server", "None"], "correct": 1},
        {"id": 2, "question": "What are the three main service models of Cloud Computing?", "options": ["SaaS, PaaS, IaaS", "Speed, Storage, Security", "Java, C, Python", "None"], "correct": 0},
        {"id": 3, "question": "What is 'SaaS'?", "options": ["Software as a Service (e.g. Google Drive, Netflix)", "Server as a Software", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'PaaS'?", "options": ["Platform as a Service (e.g. AWS Elastic Beanstalk)", "Program as a Service", "None", "None"], "correct": 0},
        {"id": 5, "question": "What is 'IaaS'?", "options": ["Infrastructure as a Service (e.g. AWS EC2, Azure VMs)", "Internet as a Storage", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'Public Cloud'?", "options": ["Services offered over the public internet to anyone", "A cloud everyone can see", "Both", "None"], "correct": 0},
        {"id": 7, "question": "What is 'Private Cloud'?", "options": ["Cloud infrastructure operated solely for a single organization", "A secret cloud", "Both", "None"], "correct": 0},
        {"id": 8, "question": "What is 'Hybrid Cloud'?", "options": ["A combination of public and private clouds", "A new type of vehicle", "Both", "None"], "correct": 0},
        {"id": 9, "question": "What is 'Scalability' in cloud context?", "options": ["The ability to easily increase or decrease resources to handle load", "Measuring numbers", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Elasticity'?", "options": ["A material property", "The ability to automatically scale resources up or down based on demand", "Both", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Pay-as-you-go' model?", "options": ["Paying only for the resources you actually consume", "A monthly fixed plan", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'High Availability' (HA)?", "options": ["Ensuring a system is always accessible with minimal downtime", "High speed", "Both", "None"], "correct": 0},
        {"id": 13, "question": "What is 'Disaster Recovery'?", "options": ["Helping after a storm", "Plans and processes to restore systems and data after a failure", "Both", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Virtualization'?", "options": ["Creating virtual versions of servers, storage, or networks", "Watching movies", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "Who are the major cloud providers?", "options": ["AWS, Microsoft Azure, Google Cloud", "Oracle, IBM Cloud", "Both A and B", "Neither"], "correct": 2},
        {"id": 16, "question": "What is 'Multi-cloud' strategy?", "options": ["Using services from multiple cloud providers (e.g. AWS and Azure)", "Using many clouds", "Both", "None"], "correct": 0},
        {"id": 17, "question": "What's 'Region' in cloud provider context?", "options": ["A physical location in the world where multiple data centers exist", "A country only", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'Availability Zone' (AZ)?", "options": ["An isolated location within a region with its own power and network", "A safe place", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Edge Computing'?", "options": ["Computing on the edge of a desk", "Processing data closer to where it is generated (the edge) to reduce latency", "Both", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Serverless Computing'?", "options": ["Computing without servers", "Cloud provider manages the infrastructure automatically (e.g. AWS Lambda)", "Both", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Cloud Storage'?", "options": ["Storing data in a cloud", "Online storage of data across multiple distributed servers", "Both", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Object Storage'?", "options": ["Storing items in a house", "Flat storage for unstructured data using keys and metadata (e.g. S3)", "Neither", "Both"], "correct": 1},
        {"id": 23, "question": "What is 'Block Storage'?", "options": ["Storing blocks of wood", "Data storage in chunks (blocks) like a physical hard drive (e.g. EBS)", "Both", "None"], "correct": 1},
        {"id": 24, "question": "What is 'File Storage'?", "options": ["Storing documents", "Storage accessible via a file system interface (e.g. NFS, SMB)", "Both", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Auto Scaling'?", "options": ["Automatically resizing a chart", "Automatically adding or removing server instances based on defined criteria", "Neither", "Both"], "correct": 1},
        {"id": 26, "question": "What is a 'Load Balancer' in cloud?", "options": ["Balancing equipment", "A tool that distributes incoming traffic across multiple servers", "Both", "None"], "correct": 1},
        {"id": 27, "question": "What is 'VPC' (Virtual Private Cloud)?", "options": ["A private network space isolated within a public cloud provider", "A computer name", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'CDN' (Content Delivery Network)?", "options": ["A network of servers used for fast delivery of web content based on location", "A TV channel", "Both", "None"], "correct": 0},
        {"id": 29, "question": "What's the meaning of 'Cloud Native'?", "options": ["Being born in a cloud", "Applications specifically designed and built to run efficiently in the cloud", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "What is 'Cloud Migration'?", "options": ["Moving data and applications from local servers to the cloud", "Bird migration", "Neither", "Both"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Total Cost of Ownership' (TCO) in cloud?", "options": ["The total cost to operate a system locally vs in the cloud", "Buying a server", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'CAPEX' vs 'OPEX' in cloud finance?", "options": ["Capital Expenditure (buying upfront) vs Operating Expenditure (pay as you go)", "Types of accounts", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Latency' in cloud communication?", "options": ["The delay before a transfer of data begins following an instruction", "Slow speed", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Throughput'?", "options": ["Putting something through", "The amount of data successfully transferred from one place to another in a time", "Neither", "Both"], "correct": 1},
        {"id": 35, "question": "What is 'Containers' (e.g. Docker) in cloud?", "options": ["A way to package and isolate apps with their dependencies uniformly", "Shipping containers", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Kubernetes' commonly used for?", "options": ["Orchestrating and managing multiple containers at scale", "Drawing graphs", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What represents the 'Shared Responsibility Model'?", "options": ["Cloud provider secure the cloud; Customer secures data IN the cloud", "Sharing a room", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Identity and Access Management' (IAM)?", "options": ["Managing who has access to which cloud resources", "A secret ID", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Cloud Security Group'?", "options": ["A virtual firewall that controls inbound and outbound traffic for a server", "A club for security people", "Both", "None"], "correct": 0},
        {"id": 40, "question": "What is 'Data Sovereignty'?", "options": ["Countries having their own data", "The idea that data is subject to the laws of the country where it is stored", "Both", "None"], "correct": 1},
        {"id": 41, "question": "What is 'Cloud-First' strategy?", "options": ["Only using clouds", "Prioritizing cloud solutions over on-premises ones for new IT projects", "Both", "None"], "correct": 1},
        {"id": 42, "question": "What is 'API' importance in cloud?", "options": ["APIs allow systems in the cloud to communicate and automate tasks", "Adding people", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's the meaning of 'Provisioning'?", "options": ["The process of setting up and configuring cloud resources (like a VM)", "Feeding people", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Deprovisioning'?", "options": ["Releasing or removing cloud resources when no longer needed", "Cleaning up a mess", "Both", "None"], "correct": 0},
        {"id": 45, "question": "What's 'Microservices' relationship with Cloud?", "options": ["Architectural style that fits perfectly with elastic cloud infrastructure", "Small computer parts", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'DevOps' in cloud terminology?", "options": ["A set of practices that combines development and operations into one flow", "A type of car", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Infrastructure as Code' (IaC)?", "options": ["Managing cloud resources using configuration files/code (e.g. Terraform)", "Writing code for servers", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Cloud-Ready' versus 'Cloud-Native'?", "options": ["Ready is traditional app moved to cloud; Native is built specifically for it", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's the impact of 'Cloud Sprawl'?", "options": ["Excessive cloud resource usage that isn't managed or monitored, wasting money", "Many clouds in sky", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Cloud Bursting'?", "options": ["The cloud bursting into rain", "Temporarily moving local workload to a public cloud when capacity peaks", "Both", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Fault Tolerance' in cloud?", "options": ["The ability of a system to continue operating despite one or more component failures", "Ignoring errors", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Redundancy'?", "options": ["Duplicating critical components to ensure system reliability after a failure", "Repeating files", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Snapshot' in cloud storage?", "options": ["A backup copy of a disk or volume at a specific point in time", "Taking a photo", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Multi-Tenancy'?", "options": ["One company having many clouds", "Sharing a single set of cloud resources among multiple customers securely", "Both", "None"], "correct": 1},
        {"id": 55, "question": "What is 'Single-Tenancy'?", "options": ["A dedicated cloud infrastructure for just one customer", "Only one user", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'VPC Peering'?", "options": ["Connecting two VPCs together so traffic can flow privately between them", "Looking at a VPC", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Gateway' in cloud networking?", "options": ["A network point that acts as an entrance to another network", "A portal", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Subnet'?", "options": ["A range of IP addresses within a VPC", "A net for subnetting", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Routing Table' in VPC context?", "options": ["Set of rules determining where network traffic is directed based on destination IP", "Rules for roads", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's 'Public Subnet'?", "options": ["A subnet that has a route to the internet (via internet gateway)", "A subnet for everyone", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What's 'Private Subnet'?", "options": ["A subnet that has no direct access to the public internet", "A secret subnet", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'VPN' (Virtual Private Network)?", "options": ["An encrypted tunnel over the public internet to connect a local office to cloud", "A fast internet", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Direct Connect' (AWS) / 'ExpressRoute' (Azure)?", "options": ["A private, physical dedicated connection from a facility to cloud provider", "Connecting directly to a person", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'Elastic Load Balancer' (ELB)?", "options": ["A load balancer that scales automatically along with traffic", "A physical scale", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Scaling Up' (Vertical Scaling)?", "options": ["Adding more power (CPU, RAM) to an existing server instance", "Growing taller", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Scaling Out' (Horizontal Scaling)?", "options": ["Adding more individual server instances to a group", "Moving horizontally", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'NoSQL Database' fit for cloud?", "options": ["High scalability and handling massive unstructured data loads", "No database at all", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "Which of these is an AWS database service?", "options": ["RDS (Relational)", "DynamoDB (NoSQL)", "Aurora", "All of the above"], "correct": 3},
        {"id": 69, "question": "What is 'BigQuery' in Google Cloud?", "options": ["A fully managed, serverless data warehouse for big data analytics", "A large question", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'SQL Database' in Azure?", "options": ["Microsoft's managed relational database service in the cloud", "A SQL file", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Provisioning' time?", "options": ["The time it takes to get a new cloud resource up and running", "Reading a provision", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's 'Agility' benefit of the cloud?", "options": ["Being fast in a race", "The ability to experiment and innovate quickly without long hardware lead times", "Neither", "Both"], "correct": 1},
        {"id": 73, "question": "What is 'Vendor Lock-in'?", "options": ["Being stuck with one cloud provider due to high migration difficulty/costs", "Locking out a vendor", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Compliance' in cloud?", "options": ["Adhering to legal and industry-specific regulations for security and data", "Complying with office rules", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Cold Storage'?", "options": ["Storage for data rarely accessed but kept for compliance (e.g. Glacier)", "Storage in a fridge", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Hot Storage'?", "options": ["Fast, expensive storage for data that is accessed frequently", "A heated room", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Ephemeral' storage?", "options": ["Temporary storage that is wiped when the server instance stops or terminates", "Permanent storage", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "Which constant represents 'Infrastructure as Code'?", "options": ["IaC", "SaC", "Both", "None"], "correct": 0},
        {"id": 79, "question": "What is 'Cost Optimization' in cloud?", "options": ["Reducing cloud spend by rightsizing resources and choosing better plans", "Buying more servers", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary driver for many companies moving to the cloud?", "options": ["Cost savings, Agility, and Scalability", "Having more servers", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Infrastructure as Code' (IaC)?", "options": ["Managing infrastructure through code and automation", "Writing code for servers", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'DevOps'?", "options": ["Combining development and operations practices", "Development operations", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'CI/CD'?", "options": ["Continuous Integration and Continuous Deployment", "Code deployment", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Auto Scaling'?", "options": ["Automatically adjusting resources based on demand", "Scaling automatically", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Load Balancing'?", "options": ["Distributing traffic across multiple servers", "Balancing loads", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'CDN' (Content Delivery Network)?", "options": ["Distributed servers for fast content delivery", "Content delivery network", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Edge Computing'?", "options": ["Processing data closer to users", "Computing at the edge", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Cloud Migration'?", "options": ["Moving applications and data to cloud", "Migrating to cloud", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Hybrid Cloud'?", "options": ["Combination of public and private cloud", "Mixed cloud", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Multi-Cloud'?", "options": ["Using multiple cloud providers", "Many clouds", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Cloud Native'?", "options": ["Applications designed for cloud environments", "Native cloud apps", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Serverless Computing'?", "options": ["Running code without managing servers", "Computing without servers", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Function as a Service' (FaaS)?", "options": ["Running functions in response to events", "Functions as service", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'API Gateway'?", "options": ["Managing API requests and routing", "Gateway for APIs", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Container Orchestration'?", "options": ["Managing containerized applications", "Orchestrating containers", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Microservices'?", "options": ["Small, independent services", "Tiny services", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Service Mesh'?", "options": ["Infrastructure for managing service communication", "Mesh for services", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Cloud Security'?", "options": ["Protecting cloud resources and data", "Security in cloud", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Cloud Monitoring'?", "options": ["Observing cloud resource performance", "Monitoring cloud", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Cloud Governance'?", "options": ["Managing cloud policies and compliance", "Governance in cloud", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
