import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_computerfundamentals_api(request):
    questions_pool = [
        {"id": 1, "question": "What is a Computer?", "options": ["An electronic device that processes data into information", "A types of TV", "A list of notes", "None"], "correct": 0},
        {"id": 2, "question": "What is 'Hardware'?", "options": ["Physical components like CPU, RAM, and keyboard", "A soft and weak part", "Neither", "Both"], "correct": 0},
        {"id": 3, "question": "What is 'Software'?", "options": ["A types of clothes", "Set of instructions (programs) that tell hardware what to do", "Neither", "Both"], "correct": 1},
        {"id": 4, "question": "What is 'CPU'?", "options": ["Central Processing Unit (The 'brain' of the computer)", "Central Power Unit", "Both A and B", "Neither"], "correct": 0},
        {"id": 5, "question": "What is 'RAM' (Random Access Memory)?", "options": ["Temporary, fast storage used while a computer is running", "Permanent storage", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'ROM' (Read-Only Memory)?", "options": ["Permanent, non-volatile memory holding startup instructions", "Memory for Read and Write", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is an 'Input Device'?", "options": ["Keyboard, Mouse, Scanner", "Monitor, Printer, Speaker", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is an 'Output Device'?", "options": ["Devices that provide info from a computer (e.g. Monitor, Printer)", "Devices for input", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Storage Device'?", "options": ["Hard Disk (HDD), SSD, USB Drive", "A box for computers", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What's the meaning of 'Motherboard'?", "options": ["The main circuit board connecting all components of a computer", "A board for families", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'OS' (Operating System)?", "options": ["Windows, macOS, Linux (System software managing hardware/apps)", "A search engine", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'Bit' in computer terms?", "options": ["Binary digit (the smallest unit of data, 0 or 1)", "A small piece of hardware", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "How many bits are in one 'Byte'?", "options": ["8", "16", "32", "64"], "correct": 0},
        {"id": 14, "question": "What is 'Kilobyte' (KB) approximately?", "options": ["1024 Bytes", "1000 Bytes", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Megabyte' (MB) approximately?", "options": ["1024 Kilobytes", "1 Million bits", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What's 'Gigabyte' (GB)?", "options": ["1024 Megabytes", "A large computer", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Terabyte' (TB)?", "options": ["1024 Gigabytes", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'ALU'?", "options": ["Arithmetic Logic Unit (performing math and logic in CPU)", "Always Logged Under", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'CU' in CPU context?", "options": ["Control Unit (directing operations and traffic for CPU)", "Copper Unit", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Primary Memory' versus 'Secondary Memory'?", "options": ["Internal (RAM/ROM) vs External (HDD/SSD/USB)", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What's the meaning of 'Booting'?", "options": ["Starting or restarting a computer OS", "Kicking a computer", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What is 'BIOS' (Basic Input/Output System)?", "options": ["Firmware that initializes hardware during the booting process", "A biology term", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'GUI' (Graphical User Interface)?", "options": ["Interface with icons, windows and mice specifically for users", "A black screen with text only (CLI)", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'CLI' (Command Line Interface)?", "options": ["Interacting with a computer using text-based commands only", "Interface with icons only", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What's the role of 'Cache Memory'?", "options": ["High-speed, temporary storage for frequently used CPU instructions", "Saving money", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Application Software'?", "options": ["Programs for specific tasks (e.g. Word, Photoshop, Browser)", "Software for building apps", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'System Software'?", "options": ["Programs managing the computer itself (e.g. OS, Drivers)", "Software for developers only", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Peripheral Device'?", "options": ["Any external device connected to the computer (e.g. Printer, Mouse)", "A computer name", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'Malware'?", "options": ["A types of clothes", "Malicious software intended to harm or steal data (e.g. Viruses, Worms)", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "What is 'Antivirus' software?", "options": ["A types of health drink", "Software specifically for detecting and removing malware", "Neither", "Both"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Database'?", "options": ["An organized collection of data stored and accessed electronically", "A list of notes", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Computer Network'?", "options": ["A group of computers connected to share resources and data", "A list of people in an office", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Internet'?", "options": ["A global net of interconnected computer networks", "A types of TV", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'WWW' (World Wide Web)?", "options": ["System of public web pages accessible via internet", "A car name", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'URL'?", "options": ["Uniform Resource Locator (a web address)", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'HTTP' (Hypertext Transfer Protocol)?", "options": ["Protocol for transferring web pages over internet", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'HTTPS'?", "options": ["Secure version of HTTP (encrypted)", "A types of bank", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Web Browser' (e.g. Chrome, Firefox)?", "options": ["Software specifically for accessing and viewing the WWW", "A types of map", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Email' importance?", "options": ["Electronic mail for sending messages over internet rapidly", "Paper mail", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Search Engine' (e.g. Google)?", "options": ["Tool specifically to find information online", "An engine for a car", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Social Media'?", "options": ["Platforms specifically for social interaction and networking online", "Buying food", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Cloud Storage'?", "options": ["Storing data online on remote servers (e.g. Google Drive)", "Storing in sky only", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Firewall' in security?", "options": ["A wall of fire", "System for network security that controls incoming/outgoing traffic", "Neither", "Both"], "correct": 1},
        {"id": 44, "question": "What is 'Password' significance?", "options": ["A secret word or string for authenticating and securing accounts", "Your name", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Two-Factor Authentication' (2FA)?", "options": ["Adding a second security layer for login (like a phone code)", "Using two hands only", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Backup' significance?", "options": ["Storing a copy of data separately to prevent loss", "Moving a car back", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Digital Literacy'?", "options": ["Ability to find, use, and share info using computers/internet", "Reading a book only", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's 'File extension' (.doc, .jpg)?", "options": ["Tells the computer what kind of file it is and what app to use", "Something added to a file", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Desktop' in OS context?", "options": ["Main screen area with icons and tasks displayed after login", "A physical desk", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Taskbar'?", "options": ["A place where current opened programs are displayed for quick access", "A bar for drinking", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Folder' significance?", "options": ["A virtual container used to organize files", "A physical paper folder", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Shortcut' icon?", "options": ["An icon that opens a specific file or folder from a different location", "A faster road", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Recycle Bin' / 'Trash'?", "options": ["Where deleted files go temporarily before being permanently removed", "A types of book", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Copy-Paste' (Ctrl+C, Ctrl+V)?", "options": ["Method for duplicating and placing text or files quickly", "Drawing by hand", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Cut-Paste' (Ctrl+X, Ctrl+V)?", "options": ["Moving text or files from one location to another", "Cutting by paper", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Formatting' a disk?", "options": ["Erasing all data specifically to prepare it for first-time use", "Designing a cover", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Peripheral' connectivity (USB, HDMI)?", "options": ["Standards for connecting external hardware to computer", "Typing on keyboard", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Driver' in computer context?", "options": ["A person driving a car", "Software that allows OS to communicate with specific hardware (Printer, etc.)", "Neither", "Both"], "correct": 1},
        {"id": 59, "question": "What is 'Resolution' (Display)?", "options": ["Number of pixels on a screen determining image clarity", "Making a promise", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Pixel'?", "options": ["The smallest single point of a digital image on a screen", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'LAN' (Local Area Network)?", "options": ["Connected computers in a small area (like home or office)", "A country in Asia", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'WAN' (Wide Area Network)?", "options": ["Network specifically covering a large city, country, or even globally", "A fan for cooling", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "Who is 'Administrator' on a computer?", "options": ["User with full control and permissions to change settings", "A secretary", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'User Account'?", "options": ["A personal space for a specific person with their own settings/files", "A bank account", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Update' (Software)?", "options": ["New versions of software with improvements or security fixes", "A news story", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Upgrade' (Hardware)?", "options": ["Replacing old physical parts with newer, more powerful ones", "Buying a new car", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Data Encryption'?", "options": ["Scrambling data specifically to keep it secret and unreadable", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Compression' (.zip)?", "options": ["Reducing file size specifically for faster transfer or storage", "Pressing hard on something", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Router' in home networking?", "options": ["Device that directs traffic between your devices and the internet", "A car name", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Modem'?", "options": ["Connecting your home to the internet provider's network", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Wi-Fi'?", "options": ["Wireless networking for devices using radio waves", "A types of TV", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Bluetooth'?", "options": ["Short-range wireless specifically for connecting peripherals (mice, etc.)", "A types of blue tooth", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Phishing'?", "options": ["Catching fish at home", "Fraudulent emails specifically to steal your passwords or data", "Neither", "Both"], "correct": 1},
        {"id": 74, "question": "What is 'Server'?", "options": ["A person who serves food", "A powerful computer specifically for providing services to others", "Neither", "Both"], "correct": 1},
        {"id": 75, "question": "What is 'Client'?", "options": ["A person buying things", "A computer or app that requests services from a server", "Neither", "Both"], "correct": 1},
        {"id": 76, "question": "What's 'Binary' system (0 and 1)?", "options": ["The fundamental language of computers based on two states", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "How many states are in binary?", "options": ["Two (0 and 1)", "Ten", "Sixteen", "None"], "correct": 0},
        {"id": 78, "question": "What's 'Clock Speed' (GHz)?", "options": ["The speed at which a CPU performs operations per second", "Speed of a watch", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What's 'Multi-core' CPU?", "options": ["Having multiple 'brains' on a single chip for multitasking", "A very large ball", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary benefit of computers in modern life?", "options": ["Speed, accuracy, and automation of tasks and information", "Having more TV channels", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
