import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_dashboards_api(request):
    questions_pool = [
        {"id": 1, "question": "What is a Power BI Dashboard?", "options": ["A types of car part", "A single-page canvas summarizing key insights into one place", "A collection of multiple reports", "None"], "correct": 1},
        {"id": 2, "question": "What's the difference between a Dashboard and a Report?", "options": ["Report can have multiple pages; Dashboard is just one page", "Dashboard is created from report visuals; Report is created from data", "Both A and B", "Neither"], "correct": 2},
        {"id": 3, "question": "Where can you create Power BI Dashboards?", "options": ["Power BI Desktop only", "Power BI Service (the web portal) only", "Both", "None"], "correct": 1},
        {"id": 4, "question": "What are 'Tiles' on a dashboard?", "options": ["Physical tiles for floors", "Individual visuals pinned to the dashboard canvas from reports", "A type of chart", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Pinning' in Power BI Service?", "options": ["A physical pin", "Taking a visual from a report and adding it to a dashboard", "Neither", "Both"], "correct": 1},
        {"id": 6, "question": "What is 'Power BI service' (app.powerbi.com)?", "options": ["A website for news", "The online platform for publishing, sharing, and collaborating on reports and dashboards", "Both", "None"], "correct": 1},
        {"id": 7, "question": "What are 'KPIs' (Key Performance Indicators)?", "options": ["Visuals showing progress toward a defined target/goal", "Calculating numbers for people", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Q&A' visual feature?", "options": ["Question and Answer using natural language to query your data and get visuals", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Real-time Streaming' in dashboards?", "options": ["Streaming videos on a chart", "Pushing live data directly to a dashboard for immediate visualization", "Neither", "Both"], "correct": 1},
        {"id": 10, "question": "What is a 'Workspace' in Power BI service?", "options": ["A space for workers", "A shared environment where teams can collaborate on content", "Neither", "Both"], "correct": 1},
        {"id": 11, "question": "What is 'Publishing' in Power BI context?", "options": ["Uploading a report from the Desktop app to the online Service", "A book being printed", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'App' in Power BI service?", "options": ["A way to bundle related dashboards and reports for mass distribution within an organization", "A mobile phone app only", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What's the benefit of 'Mobile View' for dashboards?", "options": ["Optimizing the layout specifically for phone-sized screens", "Making reports faster", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Sharing' versus 'App Publishing'?", "options": ["Sharing for individuals; App for distributing to large groups", "Both the same", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What are 'Alerts' in Power BI Service dashboards?", "options": ["Notifications triggered when data reaches a specific threshold value", "Starting a program", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "Can you pin a whole report page to a dashboard?", "options": ["Yes, as a 'Live Page' tile", "No, only individual visuals", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Power BI Gateway' useful for?", "options": ["Securing an office", "Connecting online Service to local on-premises data sources for refresh", "Both", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Cross-Highlighting' versus 'Cross-Filtering' in reports?", "options": ["Different ways related visuals interact when one is clicked", "Neither", "Both", "None"], "correct": 0},
        {"id": 19, "question": "What's the role of 'Themes' in dashboard design?", "options": ["Changing colors to match company branding and styling across all visuals", "A musical score", "Both", "None"], "correct": 0},
        {"id": 20, "question": "Which visual is best for summarizing massive volumes of data at a glance?", "options": ["Dashboard Card", "Pie Chart", "Matrix", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Interactivity' in a dashboard context?", "options": ["Users clicking on parts of a visual to change others", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What is 'Power BI Pro' license primarily for?", "options": ["Getting faster speed", "Allowing users to publish and share reports with other Pro users", "Both", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Power BI Premium'?", "options": ["A high-capacity tier for large enterprises with dedicated resources", "The most expensive plan", "Both A and B", "Neither"], "correct": 2},
        {"id": 24, "question": "How do you add an image or text directly to a dashboard?", "options": ["Using 'Add Tile' -> 'Image/Text box'", "You cannot", "Drawing it on the screen", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Content Pack' (legacy)?", "options": ["A way to share dashboards across the organization", "A packet of food", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Dataset' in the Service?", "options": ["A collection of data ready to be used by many reports and dashboards", "A single file", "Both", "None"], "correct": 0},
        {"id": 27, "question": "What is 'RLS' (Row-Level Security)?", "options": ["Restricting data access based on who the user is logged in as", "A physical key", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "How can you view a dashboard on a phone?", "options": ["Using the Power BI Mobile App for iOS/Android", "Opening a specific browser on phone", "Both", "None"], "correct": 0},
        {"id": 29, "question": "What is 'Insights' (Quick Insights)?", "options": ["AI-driven feature that searches your data for interesting patterns automatically", "A helpful tip", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Which tool is best for creating the actual reports used for pinning?", "options": ["Power BI Desktop", "Excel", "NotePad", "None"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Tile Refresh'?", "options": ["Updating the dashboard tiles as the underlying report data changes", "Cleaning physical tiles", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Focused Mode' for a tile?", "options": ["Enlarging a single visual to fill the whole screen for detailed viewing", "Focusing a camera", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'See Records' (See Data)?", "options": ["Viewing raw data records used to generate a specific visual element", "Reading a person's records", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "Can you set different data sources for different tiles on the same dashboard?", "options": ["Yes, by pinning from different reports linked to different datasets", "No", "Only for Pro users", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Power BI Desktop' (local tool)?", "options": ["Free application for data modeling and report design", "A high-performance server", "Both A and B", "Neither"], "correct": 0},
        {"id": 36, "question": "What is 'Power BI Report Server'?", "options": ["An on-premises report solution for organizations wanting to host their own reports", "A shared laptop", "Both", "None"], "correct": 0},
        {"id": 37, "question": "How can you refresh data manually in the Service?", "options": ["By clicking 'Refresh Now' on the dataset", "By restarting the computer", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Scheduled Refresh'?", "options": ["Setting specific times for Power BI to automatically update your data", "Cleaning the office", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'External Link' on a tile?", "options": ["Linking to another website when a tile is clicked", "A security risk", "Both", "None"], "correct": 0},
        {"id": 40, "question": "Which of these is a typical dashboard visual?", "options": ["Gauge Chart", "Card", "Multi-row card", "All of the above"], "correct": 3},
        {"id": 41, "question": "What's the purpose of 'Slicers' in report pinned as a Live Page?", "options": ["Allowing the user to filter the dashboard content dynamically", "Cutting a pie", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Data Storytelling'?", "options": ["Narrating a story while showing data to make it more impactful and understandable", "Writing a fictional book", "Both", "None"], "correct": 0},
        {"id": 43, "question": "Which of these is a popular way to export a Power BI dashboard?", "options": ["Export to PDF", "Export to PowerPoint", "Both A and B", "Neither"], "correct": 2},
        {"id": 44, "question": "What is 'Implicit Sharing'?", "options": ["Sharing reports through a group workspace instead of direct individuals", "Accidental sharing", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Custom Visual'?", "options": ["A visual downloaded from the marketplace created by a third-party developer", "A unique drawing", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's the meaning of 'Embed' in Power BI Service?", "options": ["Generating code to insert a dashboard/report into another website or portal", "Embedding a physical chip", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Power BI Embedded' specifically for?", "options": ["Developers wanting to include Power BI visuals into their own custom applications", "A special hardware", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'DirectQuery' for live dashboards?", "options": ["Power BI reaches directly into the data source live whenever a visual is rendered", "Asking users a question", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's a 'Streaming Dataset' primarily for?", "options": ["Sensors or live feeds updating a dashboard in real-time without storage", "Streaming music", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "Can you rename tiles on a dashboard after pinning?", "options": ["Yes, by editing the tile's details", "No", "Only in Desktop", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Dashboard Usage Metrics'?", "options": ["Reports showing how often a dashboard is viewed and by whom", "Managing costs", "Both", "None"], "correct": 0},
        {"id": 52, "question": "What is 'Favorites' in Power BI service?", "options": ["Marking specific reports/dashboards for easy access in the future", "Best friends list", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's a 'Template' in Power BI Service context?", "options": ["A pre-built starting point for common reports like IT or Finance analysis", "A design of a room", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Power Automate' integration useful for?", "options": ["Triggering workflows based on specific data alerts set in Power BI", "Buying new cars", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Pin to live page' different from regular pinning?", "options": ["Pinned page maintains all its interactivity (slicers, filters)", "Regular pinning is faster", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "Which visual is best used for comparing values across geographic locations?", "options": ["Map", "Filled Map", "Shape Map", "All of the above"], "correct": 3},
        {"id": 57, "question": "What is 'Drill through' in context of dashboards and reports?", "options": ["Navigating from a general summary to a detailed page explaining that data", "A type of drill tool", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Tooltips' useful for in dashboard design?", "options": ["Showing extra context or data when a user hovers over a visual", "Deleting charts", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'DAX' primarily used for?", "options": ["Custom calculations, measures, and data aggregation within reports", "Designing the UI color", "Both", "None"], "correct": 0},
        {"id": 60, "question": "What's 'Power Query' used for during report construction?", "options": ["Connecting, cleaning, and transforming data before it's modeled", "Sending emails", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "Which file extension is used for Power BI Desktop files?", "options": [".pbix", ".pbit", ".pdf", ".xlsx"], "correct": 0},
        {"id": 62, "question": "What's '.pbit' file?", "options": ["Power BI Template file (contains structure but no data)", "Personal bit file", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Subscription' for a dashboard?", "options": ["Receiving a periodic email snapshot of the dashboard status", "Paying for access", "Both", "None"], "correct": 0},
        {"id": 64, "question": "What is 'Line of Business' (LOB) data?", "options": ["Internal business data like sales, finance, operations", "Business news", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's 'Data storytelling' core principle?", "options": ["Simplifying complex insights through clear visuals and clear labels", "Drawing cartoons", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Clutter' in dashboard design?", "options": ["Excessive non-data-ink (borders, bold lines) that distracts from insights", "A messy room", "Both", "None"], "correct": 0},
        {"id": 67, "question": "Which visual represents the flow between two stages well?", "options": ["Waterfall Chart", "Funnel Chart", "Sankey Chart", "All (depending on context)"], "correct": 3},
        {"id": 68, "question": "What is 'Visualizing over time' best with?", "options": ["Line Chart", "Area Chart", "Stack Bar chart", "None"], "correct": 0},
        {"id": 69, "question": "What's 'Heatmap' in Power BI context?", "options": ["A visual using colors to show data intensity at various points", "Map of heated buildings", "Both", "None"], "correct": 0},
        {"id": 70, "question": "What's 'Cross-report drillthrough'?", "options": ["Drilling from a visual in one report to a page in a totally different report", "Joining reports", "Both", "None"], "correct": 0},
        {"id": 71, "question": "What is the 'Visualizations' pane for?", "options": ["Selecting and configuring chart types in Desktop", "Deleting charts", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is the 'Fields' pane for?", "options": ["Selecting columns and measures to place into visuals", "A field in a farm", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "Which of these is a Power BI UI theme?", "options": ["Dark Mode", "High Contrast", "Custom", "All of the above"], "correct": 3},
        {"id": 74, "question": "What's 'Data lineage' for dashboards in Service?", "options": ["Tracking the origin of data back to the source", "Family tree", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Governance' in Power BI context?", "options": ["Policies and procedures for managing data and content securely", "The government rules", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What's 'Power BI Dataflow'?", "options": ["Shared data preparation stored in the cloud for reuse across many models", "Data on a river", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'DirectQuery' latency benefit?", "options": ["Zero latency in seeing source data changes on report refresh", "Faster report load", "Both", "None"], "correct": 0},
        {"id": 78, "question": "Which visual is used to represent target versus achievement?", "options": ["Gauge", "KPI", "Thermometer", "All of the above"], "correct": 3},
        {"id": 79, "question": "What's 'Export to PowerPoint' benefit?", "options": ["Quickly creating presentation slides from dashboard snapshots", "Running faster", "Both", "None"], "correct": 0},
        {"id": 80, "question": "What is the primary role of Power BI Dashboards compared to reports?", "options": ["Providing high-level executive summaries of important metrics", "Providing deep technical details", "Both", "None"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
