import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_dbbasics_api(request):
    questions_pool = [
        {"id": 1, "question": "What is a Database?", "options": ["An organized collection of data stored and accessed electronically", "A list of notes", "A type of table", "None"], "correct": 0},
        {"id": 2, "question": "What is 'DBMS' (Database Management System)?", "options": ["Software for managing and interacting with a database (e.g. MySQL, Oracle)", "A hardware for DBMS", "Neither", "Both"], "correct": 0},
        {"id": 3, "question": "What is 'SQL' (Structured Query Language)?", "options": ["A programming language specifically designed for managing databases", "A secure query log", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Relational Database-RDBMS'?", "options": ["A database explicitly using tables and relationships to organize data", "No database at all", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'Table' in database context?", "options": ["A collection of related data presented in rows and columns", "A physical kitchen table", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is a 'Row' (Record)?", "options": ["A single horizontal entry in a table representing one individual item", "A horizontal list", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is a 'Column' (Field)?", "options": ["A vertical segment of a table containing specific attribute for all records", "A vertical line", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Primary Key'?", "options": ["A unique identifier used for every record in a table (like an ID)", "A secret key", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Foreign Key'?", "options": ["A column specifically for linking two related tables together", "An international key", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Data Integrity'?", "options": ["Ensuring that data in a database is accurate, complete and consistent", "Deleting data once", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Normalization'?", "options": ["Making things normal", "Process for reducing data redundancy by splitting tables into related pieces", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'Denormalization'?", "options": ["Combining tables specifically to speed up data retrieval (redundancy is OK)", "A change in weather", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Query' in database terms?", "options": ["Asking a question", "A request specifically for data from a database (e.g. SELECT)", "Neither", "Both"], "correct": 1},
        {"id": 14, "question": "What's 'CRUD' (Create, Read, Update, Delete)?", "options": ["Standard fundamental operations in any database system", "Calculations for math", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Index' for a database?", "options": ["A data structure specifically to speed up data search and retrieval", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Schema' significance?", "options": ["The structural configuration of tables and their relationships in a database", "A design of a room", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'View' in database terms?", "options": ["A virtual table based on the result of a pre-defined SQL query", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'Stored Procedure'?", "options": ["A types of health drink", "A pre-written block of SQL code stored and reusable in DBMS", "Neither", "Both"], "correct": 1},
        {"id": 19, "question": "What is 'Transaction' in database?", "options": ["Buying a house", "A sequence of operations explicitly performed as a single logical unit", "Neither", "Both"], "correct": 1},
        {"id": 20, "question": "What's 'ACID' (Atomicity, Consistency, Isolation, Durability)?", "options": ["Essential properties specifically ensuring reliable database transactions", "A types of chemical name", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'NoSQL' database?", "options": ["Database specifically designed for high-performance without strict tables (document/graph)", "No database at all", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What's 'One-to-Many' relationship flow?", "options": ["One record in table A is linked to many records in table B", "Each user has many accounts", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'Many-to-Many' relationship?", "options": ["Multiple records in A match multiple records in B", "A complex friendship", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'Join' in SQL?", "options": ["Combining rows from two or more tables based on a related column", "Merging strings", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Inner Join'?", "options": ["Returns rows only if there's a match in BOTH tables", "Returns everything", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Left Join'?", "options": ["Returns all rows from the left table and matched from the right", "Returns left part", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Database Administrator' (DBA) role?", "options": ["Person specifically responsible for managing and securing the database", "A person buying items", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Backup and Recovery' in databases?", "options": ["Ensuring data can be restored after a crash or corruption", "Moving a car back", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's 'Scalability' for a database?", "options": ["Handling of increasing data volume and users without failing", "Measuring size", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Which of these is a popular DBMS?", "options": ["MySQL", "PostgreSQL", "Oracle Database", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'DDL' (Data Definition Language)?", "options": ["SQL commands for defining structure (CREATE, ALTER, DROP)", "Deleting a folder", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'DML' (Data Manipulation Language)?", "options": ["SQL commands for managing data (INSERT, UPDATE, DELETE)", "A new computer brand", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'DCL' (Data Control Language)?", "options": ["SQL commands for managing permissions (GRANT, REVOKE)", "A speed test", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Constraint' in a table?", "options": ["Rules specifically defining allowed data for a column (e.g. NOT NULL, UNIQUE)", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What's the meaning of 'NULL' value?", "options": ["A value that is intentionally left blank (representing no data)", "A types of zero", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Unique Constraint'?", "options": ["Ensuring that all values in a column are different for every record", "Designing a logo", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's the effect of 'Auto-Increment' specifically for IDs?", "options": ["Automatically generating a new number for the primary key for each record", "Starting a program", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Aggregate Function' in SQL (e.g. SUM, AVG, COUNT)?", "options": ["Performing calculation specifically on a set of values across many rows", "Adding things together manually", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Group By' clause used for?", "options": ["Grouping records together based on specific column values for analysis", "Grouping people by age", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Order By' used for?", "options": ["Sorting the resulting records in a specific order (ascending/descending)", "Ordering a pizza", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Where' clause for?", "options": ["Filtering specific records based on a defined condition", "Asking for location", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Having' clause significance?", "options": ["Filtering of grouped records (similar to Where but for aggregates)", "Having a party", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Full Outer Join'?", "options": ["Returns all rows if there's a match in EITHER table", "Everything in out", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Self Join'?", "options": ["When a table is joined specifically with itself locally", "Joining a club", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Cross Join' (Cartesian Product)?", "options": ["Returns every possible combination of rows specifically between two tables", "Crossing a road", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's 'Data Redundancy' problem?", "options": ["Storing same information multiple times wasting space and causing sync issues", "Repeating files", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Composite Key'?", "options": ["A physical key made from composite material", "A primary key made explicitly from two or more columns combined", "Neither", "Both"], "correct": 1},
        {"id": 48, "question": "What is 'Normalization's 1NF (First Normal Form)?", "options": ["Ensuring rows are unique and every column contains only one value", "A first step in training", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Normalization's 2NF (Second Normal Form)?", "options": ["Ensuring all non-key columns depend fully on the primary key", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Normalization's 3NF (Third Normal Form)?", "options": ["Eliminating transitive dependencies between non-key columns", "Working on a third part", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What's 'Database Engine' (e.g. InnoDB, MyISAM)?", "options": ["The core software component specifically managing data storage and transactions", "A engine for a car", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's 'Cold Backup' vs 'Hot Backup'?", "options": ["Backing up while DB is offline vs while it is online/running", "Backing up in winter", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Full Backup'?", "options": ["Backing up everything on a disk", "A complete copy of the entire database structure and data", "Neither", "Both"], "correct": 1},
        {"id": 54, "question": "What is 'Incremental Backup'?", "options": ["Backing up only the changes specifically made since the last backup", "A slow backup", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Clustering' for databases?", "options": ["Having multiple database servers work together for high availability/performance", "Grouping people together", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Sharding' (Horizontal Partitioning)?", "options": ["Splitting one huge table into multiple pieces across different servers", "Shaving a face", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's 'Replication' (Master-Slave)?", "options": ["Automatically copying data from one primary database (master) to others (slaves)", "Producing a biological copy", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'NoSQL's Document Store' (e.g. MongoDB)?", "options": ["Storing data in flexible, JSON-like document format", "Storing paper docs", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'NoSQL's Key-Value Store' (e.g. Redis)?", "options": ["Storing data in simple key-to-value pairs specifically for fast access", "A book of values", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's 'NoSQL's Graph Database' (e.g. Neo4j)?", "options": ["Storing data explicitly in nodes and relationships (edges) like a net", "A chart for data", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "Who created the standard SQL language?", "options": ["IBM and Oracle later standardized by ANSI", "Google", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's the meaning of 'Deadlock' in database?", "options": ["When two transactions are stuck because they are each waiting for the other", "A literal lock on a door", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Rollback' in transaction management?", "options": ["Reverting all changes in a transaction specifically because of an error/failure", "Rolling a ball back", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Commit' in a transaction?", "options": ["Permanently saving all changes made during the successful transaction", "A promise only", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Cursor' in database programming?", "options": ["A mouse cursor only", "A mechanism allowing programmers to iterate through each record one at a time", "Neither", "Both"], "correct": 1},
        {"id": 66, "question": "What is 'Trigger' significance?", "options": ["Starting a gun only", "A pre-written block of code that runs automatically when a table event happens", "Neither", "Both"], "correct": 1},
        {"id": 67, "question": "What is 'SQL Injection' (Security)?", "options": ["An attack where a user inserts malicious SQL directly into input fields", "Giving a vaccine", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents the 'Concurrency Control'?", "options": ["Managing multiple simultaneous database users' accesses to prevent conflicts", "Managing costs", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'Data Warehouse' specifically for analytics?", "options": ["A large central repository for integrated data from multiple sources", "A physical warehouse building", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'ETL' (Extract, Transform, Load)?", "options": ["The process specifically of moving data from source to a data warehouse", "Changing power", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Which constant is used for any record ('*') in a SELECT query?", "options": ["*", "all", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "How many tables can you join in a single query?", "options": ["Multiple", "Only two", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Big Data' databases role?", "options": ["Handling of massive, high-velocity datasets that traditional DBs can't manage", "Very large paper docs", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's the meaning of 'Data Center' for cloud databases?", "options": ["The physical facility housing the servers and storage for cloud data", "A types of mall", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Which constant represents 'Not Equal' operator in SQL?", "options": ["<> or !=", "is not", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Case Sensitivity' in SQL context?", "options": ["Determines if table/column names distinguish between upper and lower case", "Sensitive emotions", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Auto-Refresh' for database dashboards?", "options": ["Automatically updating graphs as the underlying database data changes", "Cleaning the computer", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which file extension is commonly used for SQL backup files?", "options": [".sql", ".bak", "Both A and B", "Neither"], "correct": 2},
        {"id": 80, "question": "Why is Database management essential for every modern application?", "options": ["Ensuring secure, accurate and high-performance storage and retrieval of information", "Having more social media followers", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Database Normalization'?", "options": ["Organizing data to reduce redundancy", "Making data normal", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Database Indexing'?", "options": ["Creating data structures for faster queries", "Indexing data", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Database Transaction'?", "options": ["Unit of work performed on database", "Transaction in database", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'ACID Properties'?", "options": ["Atomicity, Consistency, Isolation, Durability", "Database properties", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Database Schema'?", "options": ["Structure of database", "Database structure", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Primary Key'?", "options": ["Unique identifier for records", "Key for primary data", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Foreign Key'?", "options": ["Key linking tables", "External key", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Database View'?", "options": ["Virtual table based on query", "View of database", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Stored Procedure'?", "options": ["Precompiled SQL code stored in database", "Procedure for storing data", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Database Trigger'?", "options": ["Automatic action on data changes", "Trigger for database", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Database Cursor'?", "options": ["Pointer to query results", "Cursor in database", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Database Connection Pool'?", "options": ["Cache of database connections", "Pool of connections", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Database Partitioning'?", "options": ["Dividing data across multiple storage", "Partitioning database", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Database Replication'?", "options": ["Copying data across databases", "Replicating database", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Database Sharding'?", "options": ["Horizontal partitioning of data", "Breaking database into shards", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Database Backup'?", "options": ["Copy of database for recovery", "Backing up database", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Database Recovery'?", "options": ["Restoring database from backup", "Recovering database", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Database Migration'?", "options": ["Moving data between database versions", "Migrating database", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Database Audit'?", "options": ["Reviewing database changes", "Auditing database", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Database Performance Tuning'?", "options": ["Optimizing database for speed", "Tuning database performance", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
