import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_datahandling_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Data Handling'?", "options": ["Moving physical items", "The process specifically of collecting, recording and presenting information", "Neither", "Both"], "correct": 1},
        {"id": 2, "question": "What is 'Data'?", "options": ["Raw facts and figures without specific context", "A types of fruit", "Neither", "Both"], "correct": 0},
        {"id": 3, "question": "What is 'Information'?", "options": ["Data that has been processed and organized specifically for meaning", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Frequency' in data?", "options": ["Number of times a specific value appears in a dataset", "A types of radio", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'Tally Mark'?", "options": ["A mark used specifically for counting data in groups of five", "A mark on a road", "Neither", "Both"], "correct": 1},
        {"id": 6, "question": "What is 'Pictograph'?", "options": ["A types of photo", "Representing data specifically using pictures or icons", "Both", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Bar Graph'?", "options": ["Representing data specifically with rectangular bars of varying heights/lengths", "A types of drinking bar", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Pie Chart'?", "options": ["Organizing data specifically in a circular chart divided into slices", "A types of food", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What represents the 'Mean' (Average)?", "options": ["The sum of values specifically divided by the total number of values", "The middle value", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What represents the 'Median'?", "options": ["The middle value in a set of data sorted in ascending order", "The most frequent value", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What represents the 'Mode'?", "options": ["The value that appears most frequently specifically in a dataset", "The average value", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'Range' in data set?", "options": ["A mountain range", "The difference specifically between the highest and lowest values", "Neither", "Both"], "correct": 1},
        {"id": 13, "question": "What is 'Primary Data'?", "options": ["Data collected specifically by the researcher themselves first-hand", "Data from a book", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Secondary Data'?", "options": ["Data already collected specifically by someone else (e.g. from internet, books)", "Raw data", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Qualitative Data'?", "options": ["Data describing qualities specifically (like color, texture, flavor)", "Data with numbers only", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Quantitative Data'?", "options": ["Data that can be measured specifically and expressed in numbers", "Data with colors only", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Discrete Data'?", "options": ["Data that can only take specific, separate values (e.g. number of kids)", "A secret data", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What's the meaning of 'Continuous Data'?", "options": ["Data that can take any value within a range (e.g. height, weight)", "Data without end", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Observation' in data collection?", "options": ["Watching carefully to record data specifically in a study", "A types of glasses", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Survey'?", "options": ["Asking questions specifically to a group to gather info (e.g. Questionnaires)", "Measuring land only", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Data Visualization'?", "options": ["Representing data specifically using graphs, charts and maps for better insight", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What represents 'Outlier'?", "options": ["A data point specifically that is significantly different from others in the set", "A person outside a group", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What's the meaning of 'Scale' on a graph?", "options": ["The set of numbers specifically on the axis determining the value range", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What's 'X-axis' in a 2D graph?", "options": ["The horizontal line specifically on a graph", "Vertical line", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What's 'Y-axis'?", "options": ["The vertical line specifically on a graph", "Horizontal line", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Line Graph' used for?", "options": ["Representing data specifically that changes over time (trends)", "Drawing straight lines", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Scatter Plot' significane?", "options": ["Showing specifically the relationship between two different variables", "A types of painting", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What's 'Correlation' in Data Handling?", "options": ["The statistical relationship specifically between two sets of data", "Coordinating a meeting", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's 'Data Mining'?", "options": ["Digging for physical coal", "Discovering patterns and knowledge from very large datasets", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "What is 'Histogram' specifically?", "options": ["A graphical representation showing frequency specifically of data in intervals", "A list of stories", "Neither", "Both"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Raw Data'?", "options": ["Original data specifically that has not yet been processed or organized", "Uncooked food", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Database' role in Data Handling?", "options": ["Securely storing and organizing data for easy retrieval and management", "A types of table", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Sorting' data for?", "options": ["Arranging data specifically in a particular order (A-Z, 0-9)", "Cleaning a room", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the meaning of 'Filtering' data set?", "options": ["Hiding unnecessary data based on specific criteria or rules", "Cleaning water", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Data Security'?", "options": ["Protecting digital data specifically from unauthorized access or theft", "Locking a desk only", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents 'Data Privacy'?", "options": ["The right specifically of a person to control how their personal data is used", "Secrecy for one person", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Probability' in data terms?", "options": ["Likelihood specifically of an event occurring based on data", "Guessing completely", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "How many states are in basic probability coin flip?", "options": ["Two (Head or Tail)", "One", "Ten", "None"], "correct": 0},
        {"id": 39, "question": "What is 'Percentage' (%) calculation?", "options": ["Expressing a value as a fraction specifically of 100", "Multiplying by zero", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's 'Data Integrity' significance?", "options": ["Ensuring data remains accurate and consistent specifically throughout its life", "Deleting data once", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What's 'Data Entry' job?", "options": ["The process specifically of inputting data into a computer manually", "Entering a room with data", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Spreadsheet' (e.g. Excel) for?", "options": ["Software specifically for organizing and calculating data in tables", "Writing a letter", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Data Scientist' role?", "options": ["Expert specifically using statistics and programming to find data insights", "Searching for stars", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Big Data'?", "options": ["Massive datasets specifically too large for traditional tools to handle", "A very large ball", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Cloud Computing' role in Data?", "options": ["Storing and processing very large amounts of data specifically online", "Weather forecasting", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What represents the 'Mode' in (2,3,3,4)?", "options": ["3", "4", "2", "None"], "correct": 0},
        {"id": 47, "question": "What represents the 'Mean' in (2,4,6)?", "options": ["4", "12", "6", "None"], "correct": 0},
        {"id": 48, "question": "What represents the 'Median' in (1,5,10)?", "options": ["5", "1", "10", "None"], "correct": 0},
        {"id": 49, "question": "What represents the 'Range' in (2, 20)?", "options": ["18", "22", "20", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Data Compression' significance?", "options": ["Reducing the size of data files specifically for fast storage/transfer", "Pressing something hard", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Data Backup' significance?", "options": ["Storing a copy of data separately specifically to prevent loss", "Moving a car back", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Encryption' for data?", "options": ["Converting data into code specifically to keep it secret and secure", "A types of lock", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Database Schema'?", "options": ["The formal structure specifically of a database tables and relationships", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'SQL' (Basic)?", "options": ["Language explicitly used for managing data in a relational database", "A secure query log", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Table' in relational DB?", "options": ["Collection of data logically presented in rows and columns", "A kitchen table", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What represents a 'Primary Key'?", "options": ["A unique identifier used for every record in a database table", "A secret key", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What represents a 'Foreign Key'?", "options": ["A field specifically for linking two related tables together", "An international key", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Data Normalization'?", "options": ["Reducing redundancy specifically by splitting huge tables into smaller ones", "Making things normal", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'Data Extraction'?", "options": ["Pulling specific data specifically from a source for analysis", "Removing a tooth", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's 'Data Transformation'?", "options": ["Changing raw data specifically into a format better for analysis", "Changing power", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Infographic'?", "options": ["A visual representation specifically of complex data/info for easy reading", "A styles of photo", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What represents 'Frequency Distribution Table'?", "options": ["A table showing specifically how often each data value appears", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'Bias' in data context?", "options": ["Errors specifically in data collection/analysis that lead to wrong results", "Being nice to people", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Sample' specifically for a population?", "options": ["A small subgroup chosen specifically to represent a larger population", "A types of gift", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's the meaning of 'Random Sampling'?", "options": ["Choosing items by chance specifically to ensure fairness in representativeness", "Guessing a name", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Trend analysis'?", "options": ["Looking at data overtime specifically to find patterns or shifts", "Searching for clothes", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Dashboard' for data?", "options": ["A visual display specifically of the most important metrics and charts", "A car dashboard", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "How to calculate 'Mean' for (10, 20)?", "options": ["15", "30", "10", "None"], "correct": 0},
        {"id": 69, "question": "How to find 'Range' for (1, 100)?", "options": ["99", "101", "100", "None"], "correct": 0},
        {"id": 70, "question": "What represents the 'X' in (X, Y) coordinate?", "options": ["The horizontal position specifically on a graph", "Vertical position", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What represents the 'Y' in (X, Y) coordinate?", "options": ["The vertical position specifically on a graph", "Horizontal position", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's 'Data Cleaning' importance?", "options": ["Removing errors, duplicates and fixing inconsistencies in a dataset", "Cleaning a desk", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'Data Accuracy'?", "options": ["How well the data correctly reflects the true real-world value", "Speed of typing", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'JSON' typically used for?", "options": ["A human-readable format specifically for transmitting and storing data objects", "A new computer game", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'CSV' (.csv) file?", "options": ["Comma Separated Values file specifically for sharing data tables simply", "A types of shoes", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents 'Data-driven decision making'?", "options": ["Using hard facts and analysis specifically rather than intuition for choices", "Guessing from a dream", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Business Intelligence' (BI) in data context?", "options": ["Using software tools explicitly to turn raw data into actionable insights", "Hiring people for biz", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "How can you present data visually online?", "options": ["Using web graphs, charts, and interactive dashboards", "Writing notes for friends", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which of these is used for presenting data?", "options": ["Power BI", "Tableau", "Excel Charts", "All of the above"], "correct": 3},
        {"id": 80, "question": "What is the primary benefit of good Data Handling?", "options": ["Providing clear, accurate information specifically for better understanding and decisions", "Having more TV channels", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
