import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_data_visualization_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Data Visualization?", "options": ["Drawing as art", "The graphical representation of information and data", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "Which of these is a Python library for data visualization?", "options": ["Matplotlib", "Seaborn", "Plotly", "All of the above"], "correct": 3},
        {"id": 3, "question": "What is the primary function of Matplotlib?", "options": ["Database management", "Creating static, animated, and interactive visualizations in Python", "A security log", "None"], "correct": 1},
        {"id": 4, "question": "What is Seaborn?", "options": ["A type of fish", "A library based on Matplotlib for high-level statistical graphics", "A design tool", "None"], "correct": 1},
        {"id": 5, "question": "What is a 'Bar Chart' primarily used for?", "options": ["Comparing different categories", "Showing a single trend over time", "A type of table", "None"], "correct": 0},
        {"id": 6, "question": "What is a 'Line Chart' primarily used for?", "options": ["Comparing two groups", "Displaying trends and changes over a continuous interval (like time)", "Neither", "Both"], "correct": 1},
        {"id": 7, "question": "What is a 'Scatter Plot' primarily used for?", "options": ["Visualizing relationship between two numerical variables", "A decorative text", "A type of chart", "None"], "correct": 0},
        {"id": 8, "question": "What is a 'Histogram'?", "options": ["A map of history", "A plot that shows the frequency distribution of continuous data", "A security log", "None"], "correct": 1},
        {"id": 9, "question": "What is a 'Pie Chart'?", "options": ["A circular graph divided into slices to represent proportion/percentage", "A square graph", "Both", "None"], "correct": 0},
        {"id": 10, "question": "What is 'Plotly'?", "options": ["A search for plots", "A library for building interactive, web-based graphs and charts", "Both A and B", "Neither"], "correct": 1},
        {"id": 11, "question": "What is 'Bokeh'?", "options": ["A blurry background", "A library for creating interactive, large-scale visualizations for modern web browsers", "None", "None"], "correct": 1},
        {"id": 12, "question": "Which of these is used for multi-variate visualization?", "options": ["Heatmap", "Pair Plot", "Parallel Coordinates", "All of the above"], "correct": 3},
        {"id": 13, "question": "What is a 'Heatmap'?", "options": ["A map of hot cities", "A graphical representation where values are represented by colors", "Neither", "Both"], "correct": 1},
        {"id": 14, "question": "What is a 'Box Plot' (Box-and-Whisker)?", "options": ["A box containing physical items", "A plot showing distribution of data based on quartiles and highlighting outliers", "A tech spec", "None"], "correct": 1},
        {"id": 15, "question": "What are 'Outliers' in a visualization?", "options": ["Data points that differ significantly from other observations", "Labels on the graph", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "Which constant is used for the X-axis label in Matplotlib?", "options": ["plt.xlabel()", "plt.ylabel()", "plt.title()", "None"], "correct": 0},
        {"id": 17, "question": "Which constant is used for the Y-axis label in Matplotlib?", "options": ["plt.xlabel()", "plt.ylabel()", "plt.set()", "None"], "correct": 1},
        {"id": 18, "question": "How do you show a plot in Matplotlib?", "options": ["plt.display()", "plt.show()", "plt.render()", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Folium' used for?", "options": ["Visualizing geographically mapped data (interactive maps)", "Drawing a circle", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What's the meaning of 'Color Palette' (sns.set_palette)?", "options": ["A set of colors to make plots more visually appealing and informative", "Cleaning the graph", "None", "None"], "correct": 0},
        {"id": 21, "question": "Which library is known for the phrase 'Grammar of Graphics'?", "options": ["Matplotlib", "Seaborn", "Plotnine (based on ggplot2)", "All of the above"], "correct": 2},
        {"id": 22, "question": "What is a 'Joint Plot' in Seaborn?", "options": ["Plotting two separate variables", "Combining two different plots (univariate and bivariate) in one visualization", "Neither", "Both"], "correct": 1},
        {"id": 23, "question": "What's a 'Violin Plot'?", "options": ["Playing a violin with code", "A combination of box plot and kernel density plot showing distribution shape", "A search tool", "None"], "correct": 1},
        {"id": 24, "question": "How do you save a figure in Matplotlib?", "options": ["plt.save()", "plt.savefig('filename')", "Both", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Aspect Ratio' in visualization context?", "options": ["Shape of a person", "The proportional relationship between the width and height of a plot", "A technical specification", "None"], "correct": 1},
        {"id": 26, "question": "Which of these is a popular BI tool for non-programmers?", "options": ["Tableau", "Power BI", "Google Data Studio", "All of the above"], "correct": 3},
        {"id": 27, "question": "What is a 'Treemap'?", "options": ["A map of trees", "Representing hierarchical data using nested rectangles of different sizes and colors", "Both", "None"], "correct": 1},
        {"id": 28, "question": "What is a 'Word Cloud'?", "options": ["A cloud shaped like a word", "A visual representation where words are sized by their frequency/importance", "Neither", "Both"], "correct": 1},
        {"id": 29, "question": "What is 'Dashboard'?", "options": ["A physical car part", "A collection of multiple visualizations on one screen to provide an overview", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "Which library is best for very high-performance plotting of large datasets?", "options": ["Datashader", "Matplotlib", "Plotly", "None"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Hue' parameter in Seaborn?", "options": ["The size of a plot", "A semantic mapping that allows color differentiation of data based on a category", "Both", "None"], "correct": 1},
        {"id": 32, "question": "What is 'Alpha' parameter in Matplotlib?", "options": ["The transparency level of a plot (ranging from 0 to 1)", "A high-priority setting", "Both", "None"], "correct": 0},
        {"id": 33, "question": "What is 'FacetGrid' in Seaborn?", "options": ["A grid for faces", "A tool for creating a grid of subplots based on categorical variables", "Neither", "Both"], "correct": 1},
        {"id": 34, "question": "What is 'Regplot' in Seaborn used for?", "options": ["Showing a linear regression fit between two variables", "Deleting a database", "Both", "None"], "correct": 0},
        {"id": 35, "question": "What is 'KDE' (Kernel Density Estimation) plot?", "options": ["A plot for density of kernels", "A way to estimate and plot the continuous probability density function of a variable", "Both", "None"], "correct": 1},
        {"id": 36, "question": "What is a 'Subplot' in Matplotlib?", "options": ["A separate chart file", "A specific individual chart within a larger grid of Multiple charts", "Both", "None"], "correct": 1},
        {"id": 37, "question": "How can you change the overall style of plots in Matplotlib?", "options": ["plt.style.use('style_name')", "plt.set_style()", "plt.change()", "None"], "correct": 0},
        {"id": 38, "question": "Which of these is a common color map name in Matplotlib?", "options": ["viridis", "plasma", "magma", "All of the above"], "correct": 3},
        {"id": 39, "question": "What is 'Plotnine'? ", "options": ["A library achieving a ggplot2-like grammar of graphics in Python", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Altair'?", "options": ["A declarative statistical visualization library for Python based on Vega-Lite", "A search tool", "None", "None"], "correct": 0},
        {"id": 41, "question": "What is 'Canvas' in data vis context?", "options": ["The physical background where the visualization is drawn", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What are 'Ticks' in a plot axis?", "options": ["Small marks on the axis to indicate intervals/categories", "Bugs on the chart", "Both", "None"], "correct": 0},
        {"id": 43, "question": "What is 'Legend' on a chart?", "options": ["A famous story", "A key explaining the colors/symbols used in the plot", "Neither", "Both"], "correct": 1},
        {"id": 44, "question": "What is a 'Stacked Bar Chart'?", "options": ["Grouping bars side-by-side", "Bars for each category are stacked on top of each other to show a total", "Neither", "Both"], "correct": 1},
        {"id": 45, "question": "Which of these is a disadvantage of a Pie Chart?", "options": ["Hard to compare small differences between segments", "Too many colors", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's the meaning of 'Context' in Seaborn (sns.set_context)?", "options": ["Setting the theme for specific environments like 'paper', 'talk', 'poster'", "Designing icons", "Both", "None"], "correct": 0},
        {"id": 47, "question": "What is 'Plotly Express'?", "options": ["Fast delivery", "A high-level interface for creating variety of charts with very little code", "Neither", "Both"], "correct": 1},
        {"id": 48, "question": "What is 'Dash' by Plotly?", "options": ["A run to the finish line", "A framework for building analytical web applications in Python (no JS needed)", "Neither", "Both"], "correct": 1},
        {"id": 49, "question": "Which visualization is best for correlating multiple numeric variables at once?", "options": ["Heatmap", "Pair Plot", "Both", "None"], "correct": 2},
        {"id": 50, "question": "What is 'Streamplot' in Matplotlib?", "options": ["A plot for streaming videos", "Used for displaying 2D vector fields containing flow information", "Neither", "Both"], "correct": 1},
        {"id": 51, "question": "What is 'Error Bar' in a plot?", "options": ["An error in code", "A graphical representation of the variability of data on a chart", "Both", "None"], "correct": 1},
        {"id": 52, "question": "What is a 'Candlestick Chart' primarily used for?", "options": ["Visualizing candles", "Showing price movements of an asset (financial visualization)", "Both", "None"], "correct": 1},
        {"id": 53, "question": "What's 'Streamlit' in data vis context?", "options": ["A framework for easily creating and sharing custom web apps for data science", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "Which function allows creating multiple plots in one line using Seaborn?", "options": ["sns.pairplot()", "sns.grid()", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Data Ink Ratio'?", "options": ["The ratio of physical ink to paper", "The proportion of ink used for data vs non-data (labels, borders) elements", "Neither", "Both"], "correct": 1},
        {"id": 56, "question": "What is an 'Infographic'?", "options": ["A graphic with info", "A visual representation combining data vis with graphic design to tell a story", "Neither", "Both"], "correct": 1},
        {"id": 57, "question": "Which plot type is used for displaying parts of a whole?", "options": ["Pie Chart", "Treemap", "Donut Chart", "All of the above"], "correct": 3},
        {"id": 58, "question": "What is a 'Radar Chart' (Spider chart)?", "options": ["Plotting 2D data that looks like a web, often for performance metrics", "A search tool", "Both", "None"], "correct": 0},
        {"id": 59, "question": "Which visualization shows both distribution and correlation of two numerical variables?", "options": ["Joint Plot", "Line Chart", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Interactive Visualization'?", "options": ["Allowing the user to hover, zoom, or filter the chart to explore data dynamically", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "How do you set a plot title in Matplotlib?", "options": ["plt.title('Name')", "plt.name()", "Both", "None"], "correct": 0},
        {"id": 62, "question": "How do you set axis limits in Matplotlib?", "options": ["plt.axis_limit()", "plt.xlim() and plt.ylim()", "Neither", "Both"], "correct": 1},
        {"id": 63, "question": "Which function adds a grid to a Matplotlib plot?", "options": ["plt.grid(True)", "plt.show_grid()", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'D3.js' in the broader context?", "options": ["Javascript library for creating highly custom and detailed web visualizations", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'SVG' for web visualization?", "options": ["Scalable Vector Graphics (retains resolution at any size)", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's the meaning of 'Small Multiples'?", "options": ["Series of similar graphs with same scale for comparison across categories", "Small numbers on a chart", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is a 'Bubble Chart'?", "options": ["Visualizing bubbles in water", "A scatter plot where a third variable determines the size of the bubbles", "Both", "None"], "correct": 1},
        {"id": 68, "question": "What's the role of 'Annotations' on a chart?", "options": ["Deleting data", "Text labels or highlights used to point out specific insights in the visual", "Neither", "Both"], "correct": 1},
        {"id": 69, "question": "Which plot is used to identify the spread of the middle 50% of data?", "options": ["Box Plot", "Histogram", "Both", "None"], "correct": 0},
        {"id": 70, "question": "What is 'Geoplot'?", "options": ["General plot for data", "Visualizing geospatial/geographic data", "Neither", "Both"], "correct": 1},
        {"id": 71, "question": "What is a 'Sankey Diagram'?", "options": ["A diagram showing physical pipes", "A visualization for showing flow amounts between various categories", "Neither", "Both"], "correct": 1},
        {"id": 72, "question": "What is a 'Funnel Chart' commonly used for?", "options": ["A literal funnel", "Visualizing values as they decrease through stages of a process (e.g. sales)", "Neither", "Both"], "correct": 1},
        {"id": 73, "question": "What is status of 'Matplotlib' in Python community?", "options": ["The foundational library for almost all other visualization tools in Python", "A security log", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "How do you increase plot resolution in Matplotlib?", "options": ["Using the 'dpi' parameter when saving or creating", "Adding more data", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's the effect of 'plt.tight_layout()'?", "options": ["Deletes plot margins", "Adjusts subplots to fit neatly inside the figure area and prevents overlaps", "Neither", "Both"], "correct": 1},
        {"id": 76, "question": "What's 'Matplotlib Animation' module for?", "options": ["Making a cartoon", "Generating movie or GIF files of changing visualizations", "Neither", "Both"], "correct": 1},
        {"id": 77, "question": "What is 'HoloViews'?", "options": ["A library that simplifies visual data exploration by separating data and analysis", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "Which chart type is best for showing parts of a whole?", "options": ["Pie Chart", "Stacked Bar Chart", "Both", "None"], "correct": 2},
        {"id": 79, "question": "What is 'Correlation matrix' visualization?", "options": ["Typically shown as a colored Heatmap showing relationship between multiple variables", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What's 'Mapbox' used for in custom visualizations?", "options": ["Building detailed and interactive web maps", "Drawing a circle", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Bokeh'?", "options": ["Interactive visualization library for web applications", "A type of plant", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Plotly'?", "options": ["Web-based visualization library", "Online plotting", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Dash'?", "options": ["Python framework for analytical web apps", "Dashboard framework", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Streamlit'?", "options": ["Python library for data apps", "Streaming data", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Altair'?", "options": ["Declarative statistical visualization library", "A star constellation", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'D3.js'?", "options": ["JavaScript library for data-driven documents", "Data documents", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Tableau'?", "options": ["Business intelligence and visualization platform", "A type of board", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Power BI'?", "options": ["Microsoft business analytics tool", "Powerful BI", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Grafana'?", "options": ["Open-source monitoring and visualization platform", "Graphing tool", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Kibana'?", "options": ["Visualization tool for Elasticsearch", "Data analysis tool", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Superset'?", "options": ["Open-source business intelligence platform", "Super set", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Looker'?", "options": ["Data platform for business intelligence", "Looking tool", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Data Storytelling'?", "options": ["Presenting data as narrative", "Telling data stories", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Heatmap'?", "options": ["Color-coded matrix visualization", "Hot map visualization", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Choropleth Map'?", "options": ["Thematic map with shaded regions", "Map with colors", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Sankey Diagram'?", "options": ["Flow diagram showing proportional relationships", "Diagram of flows", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Tree Map'?", "options": ["Hierarchical data visualization", "Map of trees", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Network Graph'?", "options": ["Visualization of relationships and connections", "Graph of networks", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Geospatial Visualization'?", "options": ["Mapping and analyzing location-based data", "Visualizing geography", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Interactive Dashboard'?", "options": ["Dynamic visualization with user controls", "Interactive dashboard", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
