import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_datamodeling_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Data Modeling?", "options": ["Drawing pictures", "Creating a conceptual or physical representation of data and its relationships", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "What is the primary goal of Data Modeling in Power BI?", "options": ["Making charts bigger", "Defining table relationships to enable efficient data analysis and insight", "None", "None"], "correct": 1},
        {"id": 3, "question": "What is a 'Relationship' in Data Modeling?", "options": ["A friendship between tables", "A connection that defines how two tables are linked together via common columns", "Both A and B", "Neither"], "correct": 1},
        {"id": 4, "question": "What is 'Cardinality'?", "options": ["A type of bird", "The nature of the relationship (One-to-One, One-to-Many, Many-to-Many)", "A bank account", "None"], "correct": 1},
        {"id": 5, "question": "What is 'One-to-Many' relationship?", "options": ["One record in table A matches many in table B", "Each user has many passwords", "Both", "None"], "correct": 0},
        {"id": 6, "question": "What is 'Many-to-Many' relationship?", "options": ["Multiple records in A match multiple in B", "Complex relationship often requiring a bridge (join) table", "Both A and B", "Neither"], "correct": 2},
        {"id": 7, "question": "What is a 'Fact Table'?", "options": ["A table containing background facts", "A table containing measurable, quantitative data (e.g. sales, orders)", "A type of chart", "None"], "correct": 1},
        {"id": 8, "question": "What is a 'Dimension Table'?", "options": ["A table for sizes", "A table containing descriptive attributes (e.g. product name, customer details)", "Both", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Star Schema'?", "options": ["A group of stars in sky", "Modeling where one fact table is surrounded by multiple simplified dimension tables", "Neither", "Both"], "correct": 1},
        {"id": 10, "question": "What is 'Snowflake Schema'?", "options": ["A schema for people in winter", "Similar to Star Schema, but dimension tables are normalized into further tables", "Both", "None"], "correct": 1},
        {"id": 11, "question": "What is 'DAX' (Data Analysis Expressions)?", "options": ["A formula language used in Power BI for custom calculations and aggregations", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is a 'Calculated Column'?", "options": ["A column for math only", "A new column added to a table using a DAX formula that's stored in the model", "Neither", "Both"], "correct": 1},
        {"id": 13, "question": "What is a 'Measure' in Power BI?", "options": ["A ruler tool", "A dynamic calculation performed on the fly in reports based on chosen filters", "Neither", "Both"], "correct": 1},
        {"id": 14, "question": "What's the difference between Calculated Column and Measure?", "options": ["Column is pre-calculated; Measure is calculated at report runtime", "Column uses more data", "Both", "None"], "correct": 0},
        {"id": 15, "question": "What is 'Relationship Direction' (Cross Filtering)?", "options": ["Determines which way a filter flows between tables (Single or Both)", "A road sign", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Bidirectional' filtering?", "options": ["A filter that flows both ways between two connected tables", "Sharing data in two files", "Both", "None"], "correct": 0},
        {"id": 17, "question": "What is 'Active' vs 'Inactive' relationship?", "options": ["Active is used by default; Inactive needs a specific DAX function (USERELATIONSHIP)", "Manual vs auto", "Both", "None"], "correct": 0},
        {"id": 18, "question": "What is 'Data Normalization'?", "options": ["Making things normal", "Reducing data redundancy by splitting tables into smaller, related ones", "Both", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Data Denormalization'?", "options": ["Opposite of normalization", "Combining tables to reduce joins for better query performance in analytics", "Both", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Schema' primarily for?", "options": ["A design for UI", "The structural configuration of tables and their relationships in a database", "Both", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Granularity'?", "options": ["Types of grain", "The level of detail represented in a single row of a table (e.g. daily vs monthly)", "Neither", "Both"], "correct": 1},
        {"id": 22, "question": "What is 'Filter Context' in DAX?", "options": ["Context for filters", "The specific filters applied to a dynamic calculation based on report selections", "Both", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Row Context' in DAX?", "options": ["Calculating for a row", "When a formula iterates through a table row by row (like in a calculated column)", "Both", "None"], "correct": 1},
        {"id": 24, "question": "What's the role of 'Relationship Key'?", "options": ["The column used to link tables (Primary Key in one, Foreign Key in other)", "A physical key", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "Which of these is a DAX aggregation function?", "options": ["SUM", "AVERAGE", "COUNT", "All of the above"], "correct": 3},
        {"id": 26, "question": "What is 'Data Type' consistency in a relationship?", "options": ["Both sides of a relationship must use the same data type for keys", "Formatting text", "None", "None"], "correct": 0},
        {"id": 27, "question": "Can you have multiple active relationships between the same two tables?", "options": ["No, only one can be active at a time in Power BI", "Yes", "Both", "None"], "correct": 0},
        {"id": 28, "question": "What is 'Calculated Table' in Power BI modeling?", "options": ["A table derived from other tables using a DAX formula", "A table with manual entries", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's the meaning of 'Hide from Report View'?", "options": ["Keeping technical columns/tables hidden from the end user to simplify the UI", "Deleting the file", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Which view in Power BI Desktop is used for modeling?", "options": ["Report View", "Model View", "Data View", "Neither"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'User-Defined Hierarchy'?", "options": ["A custom ranking for data levels (e.g. Country -> City -> Street)", "A security log", "Both", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Data Category' primarily used for?", "options": ["Identifying columns as special types like Location (Latitude, Longitude)", "Grouping files", "Both", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Sort by Column' useful for?", "options": ["Sorting months alphabetically correctly (Jan, Feb...)", "Ordering people by name", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'RELATED' function in DAX?", "options": ["Returning related data from another table through an existing relationship", "Matching people", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'RELATEDTABLE' function for?", "options": ["Calculates an entire table based on current context relationships", "Drawing tables", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What are 'Implicit Measures'?", "options": ["Measures created automatically when you drag a column to a visual (like Sum of Age)", "Secret calculations", "Both", "None"], "correct": 0},
        {"id": 37, "question": "What are 'Explicit Measures'?", "options": ["Measures clearly written using DAX formulas by the developer", "Both", "Neither", "None"], "correct": 0},
        {"id": 38, "question": "What's the meaning of 'Ambiguous Relationship'?", "options": ["When multiple paths exist between two tables causing calculation confusion", "A confusing friendship", "Both", "None"], "correct": 0},
        {"id": 39, "question": "What is 'Power Query' (M Language) versus DAX?", "options": ["Power Query handles data prep; DAX handles calculations in the model", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Self-Service BI'?", "options": ["User serves themselves a drink", "Allowing business users to build their own models and reports easily", "Neither", "Both"], "correct": 1},
        {"id": 41, "question": "What is 'Bridge Table'?", "options": ["A table on a physical bridge", "A table used to resolve many-to-many relationships between two others", "Neither", "Both"], "correct": 1},
        {"id": 42, "question": "What is 'Linkage' in Data Modeling context?", "options": ["Connecting data", "The process of joining data sources together into a single model", "Neither", "Both"], "correct": 1},
        {"id": 43, "question": "What is 'Data Source' in Power BI?", "options": ["Source of truth", "Any place where data originates (e.g. SQL, Excel, Web)", "Both", "None"], "correct": 1},
        {"id": 44, "question": "What is 'One-to-One' cardinality usage case?", "options": ["Extending a table with more properties", "Separating sensitive info to another table", "Both A and B", "Neither"], "correct": 2},
        {"id": 45, "question": "Which DAX function is used to calculate percentages easily?", "options": ["DIVIDE", "PERC", "Both", "None"], "correct": 0},
        {"id": 46, "question": "What's the 'Relationships' tab in Power BI Desktop for?", "options": ["A visual map of all table connections in the current model", "Adding contacts", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What are 'Calculated Columns' impact on memory?", "options": ["Increase model size as they are stored with the data", "No impact", "Decreases size", "None"], "correct": 0},
        {"id": 48, "question": "What are 'Measures' impact on memory?", "options": ["Very low impact because they are computed on-the-fly and not stored", "Increases significantly", "None", "None"], "correct": 0},
        {"id": 49, "question": "What is 'Data Refresh'?", "options": ["Cleaning a physical screen", "Updating the data in the model from the original source", "Both", "None"], "correct": 1},
        {"id": 50, "question": "What is 'Incremental Refresh'?", "options": ["Only updating new or changed data records to save time and resources", "A slow refresh", "None", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Data Warehouse'?", "options": ["A large building for storage", "A central repository of integrated data from different sources for analysis", "Both", "None"], "correct": 1},
        {"id": 52, "question": "What is 'Schema Drift'?", "options": ["Schema moving in water", "Changes in the structure of source data that might break the model", "Neither", "Both"], "correct": 1},
        {"id": 53, "question": "What is 'Data Transformation' part of Modeling?", "options": ["Changing raw data into a clean, structured form (ETL process)", "Transforming people", "None", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Data Dictionary'?", "options": ["A list of tables and columns with their descriptions and meta-data", "A book of values", "Both", "None"], "correct": 0},
        {"id": 55, "question": "Which of these is used for complex logic in DAX?", "options": ["SWITCH", "IF", "Both", "Neither"], "correct": 2},
        {"id": 56, "question": "What is 'CALCULATE' function in DAX?", "options": ["The most powerful DAX function for modifying filter context", "A simple calculator", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's the difference between SUM and SUMX?", "options": ["SUM iterates through current context; SUMX can iterate over any table row-by-row", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Time Intelligence' in DAX?", "options": ["Calculating based on dates (Year-To-Date, Previous Year, etc.)", "Clever time management", "Both", "None"], "correct": 0},
        {"id": 59, "question": "What is 'TOTALYTD' function?", "options": ["Calculates the Year-To-Date total for a given expression", "Total of a year", "Both", "None"], "correct": 0},
        {"id": 60, "question": "What is 'DATEADD' used for?", "options": ["Adding days to a calendar", "Moving a date forward or backward by a specific interval (days, months, years)", "Both", "None"], "correct": 1},
        {"id": 61, "question": "What is 'Data Lineage'?", "options": ["Visualizing the path data takes from source to report", "Data family history", "Both", "None"], "correct": 0},
        {"id": 62, "question": "What's 'DirectQuery' mode vs 'Import'?", "options": ["DirectQuery hits DB live; Import pulls data snapshot into memory", "Same", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Composite Model'?", "options": ["A model combining both Import and DirectQuery sources", "A small model", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's the meaning of 'Normalization'?", "options": ["Dividing one large table into multiple related smaller ones for efficiency", "Making values normal", "Both", "None"], "correct": 0},
        {"id": 65, "question": "What is 'De-normalization' primarily for?", "options": ["Reduces number of joins to speed up big data reporting", "Deleting columns", "Both", "None"], "correct": 0},
        {"id": 66, "question": "What is 'ER Diagram' (Entity Relationship)?", "options": ["A formal graphical map of data model structure and paths", "An image of users", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Column Profiling'?", "options": ["Checking min, max, mean and distribution of data in a column", "A security check", "Both", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Data Scrubbing'?", "options": ["Removing Errors", "Cleaning physical hardware", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's the value of using a 'Date Table' in Power BI Modeling?", "options": ["Enables advanced time intelligence calculations reliably", "Drawing a calendar", "Both", "None"], "correct": 0},
        {"id": 70, "question": "What is 'Bridge Relationship'?", "options": ["Handling many-to-many through a common middle table", "A literal bridge", "None", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Circular Dependency' in modeling?", "options": ["When two calculations depend on each other, causing an error", "A loop in relationships", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'USERELATIONSHIP' function used for in DAX?", "options": ["To activate a specific inactive relationship for a single calculation", "Connecting to a user", "Both", "None"], "correct": 0},
        {"id": 73, "question": "What's 'CrossFilter' function for?", "options": ["Modifying the filter direction of a relationship within a DAX measure", "A physical filter", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "Which of these is a DAX logical function?", "options": ["AND", "OR", "NOT", "All of the above"], "correct": 3},
        {"id": 75, "question": "What is 'DAX Formatter' used for?", "options": ["Beautifying DAX code according to industry standards for readability", "A code compiler", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Can you define relationships based on multiple columns in Power BI natively?", "options": ["No, it typically requires a single key column (or a concatenated composite key)", "Yes", "None", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Many-to-One' relationship flow?", "options": ["Filtering from the one side to the many side by default", "Reverse only", "Both", "None"], "correct": 0},
        {"id": 78, "question": "What's 'Blank' in DAX context?", "options": ["Equivalent to Null in SQL representing no value", "A zero", "A space", "None"], "correct": 0},
        {"id": 79, "question": "What's 'Data Redundancy' problem?", "options": ["Storing same information multiple times wasting space and causing sync issues", "Repeating files", "Both", "None"], "correct": 0},
        {"id": 80, "question": "What is the primary tool for Data Modeling in Microsoft ecosystem?", "options": ["Power BI", "Excel Power Pivot", "Analysis Services", "All of the above"], "correct": 3},
        {"id": 81, "question": "What is 'Star Schema'?", "options": ["Schema design for data warehousing", "Star schema", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Snowflake Schema'?", "options": ["Schema design for cloud data warehouse", "Snowflake schema", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Fact Table'?", "options": ["Table containing business metrics", "Table of facts", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Dimension Table'?", "options": ["Table containing descriptive attributes", "Table of dimensions", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Bridge Table'?", "options": ["Table linking fact and dimension tables", "Bridge between tables", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Data Mart'?", "options": ["Subset of data warehouse for specific department", "Market for data", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'OLAP' vs 'OLTP'?", "options": ["Online analytical processing vs online transaction processing", "Analysis vs transactions", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'ETL' process?", "options": ["Extract, Transform, Load", "Electronic transfer load", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'ELT' process?", "options": ["Extract, Load, Transform", "Electronic load transform", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Data Lake'?", "options": ["Centralized repository for raw data", "Lake of data", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Data Warehouse'?", "options": ["Central repository for integrated data", "Warehouse for data", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Master Data Management' (MDM)?", "options": ["Managing reference data across systems", "Mastering data", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Data Governance'?", "options": ["Managing data quality and policies", "Governing data", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Data Lineage'?", "options": ["Tracking data origin and transformations", "Lineage of data", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Data Quality'?", "options": ["Assessing data accuracy and completeness", "Quality of data", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Entity Relationship' (ER) modeling?", "options": ["Designing relationships between data entities", "Modeling relationships", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Normalization'?", "options": ["Organizing data to reduce redundancy", "Making data normal", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Denormalization'?", "options": ["Adding redundancy for query performance", "Making data denormal", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Aggregation'?", "options": ["Summarizing data for analysis", "Aggregating data", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Data Virtualization'?", "options": ["Creating unified view of distributed data", "Virtualizing data", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
