import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_deeplearning_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Deep Learning?", "options": ["A type of memory", "A subset of Machine Learning using multi-layered neural networks", "Deep ocean research", "None"], "correct": 1},
        {"id": 2, "question": "What is an 'Artificial Neural Network' (ANN)?", "options": ["A computer network", "A computing system inspired by the biological brain structure", "A type of database", "None"], "correct": 1},
        {"id": 3, "question": "What is an 'Input Layer'?", "options": ["The final result of the model", "The first layer of a neural network that receives raw data", "A type of table", "None"], "correct": 1},
        {"id": 4, "question": "What is a 'Hidden Layer'?", "options": ["A secret layer of data", "Layers between input and output that perform feature extraction", "A technical specification", "None"], "correct": 1},
        {"id": 5, "question": "What is an 'Output Layer'?", "options": ["The final layer that produces the prediction or classification", "The layer where data is entered", "A type of chart", "None"], "correct": 0},
        {"id": 6, "question": "What is 'Backpropagation'?", "options": ["Sorting a simple list", "An algorithm for training neural networks by calculating gradients backwards", "Connecting to a database", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Activation Function'?", "options": ["A function that starts the computer", "A function that determines the output of a neuron", "A type of graph", "None"], "correct": 1},
        {"id": 8, "question": "Which of these is a popular activation function in deep learning?", "options": ["ReLU", "Sigmoid", "Tanh", "All of the above"], "correct": 3},
        {"id": 9, "question": "What is 'CNN' (Convolutional Neural Network) primarily used for?", "options": ["NLP", "Image and video recognition", "Sound processing", "None"], "correct": 1},
        {"id": 10, "question": "What is 'RNN' (Recurrent Neural Network) primarily used for?", "options": ["Image classification", "Sequential data processing (like text, time-series)", "A type of sorting", "None"], "correct": 1},
        {"id": 11, "question": "What is 'LSTM'?", "options": ["Long Short-Term Memory (a type of RNN)", "Large Storage Tool Module", "Low Stability Task Machine", "None"], "correct": 0},
        {"id": 12, "question": "What is 'Gradient Descent'?", "options": ["A downhill race", "An optimization algorithm to minimize the loss function", "A type of sorting", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Loss Function' (Cost Function)?", "options": ["Measuring performance of code", "A function that measures how far off a model's predictions are from targets", "Deleting errors", "None"], "correct": 1},
        {"id": 14, "question": "Which of these is a popular deep learning library?", "options": ["TensorFlow", "PyTorch", "Keras", "All of the above"], "correct": 3},
        {"id": 15, "question": "What is 'Overfitting' in deep learning?", "options": ["The model is performing well on all datasets", "The model learns the training data too well, failing to generalize", "A code error", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Dropout'?", "options": ["Stopping a course", "A regularization technique that randomly removes neurons during training", "A type of backup", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Transfer Learning'?", "options": ["Learning in a new school", "Using a pre-trained model for a new, similar task", "Combining two datasets", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Batch Normalization'?", "options": ["Sorting a simple list", "A technique to normalize inputs to a layer to speed up training", "A security feature", "None"], "correct": 1},
        {"id": 19, "question": "What is an 'Optimizer' (e.g. Adam, SGD)?", "options": ["A person in charge of code", "An algorithm that updates neural network weights based on gradients", "A type of server", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Hyperparameter Tuning'?", "options": ["Increasing the volume", "Providing the best values for settings like learning rate, batch size", "A technical specification", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Data Augmentation'?", "options": ["Deleting bad data", "Providing variety to a dataset by transforming existing data (e.g. rotating images)", "Adding more servers", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Embedding' in NLP?", "options": ["A hidden file", "A dense vector representation of words or tokens", "A type of browser", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Softmax' activation function used for?", "options": ["Hidden layers", "Output layer for multi-class classification to produce probabilities", "A type of sorting", "None"], "correct": 1},
        {"id": 24, "question": "What is 'GAN' (Generative Adversarial Network)?", "options": ["A type of network speed", "Two neural networks (generator and discriminator) competing to create realistic data", "A security company", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Transformer' architecture?", "options": ["A toy that turns into a robot", "A neural network architecture using self-attention (e.g., BERT, GPT)", "A type of database", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Fine-tuning'?", "options": ["Adjusting the volume", "Slightly training a pre-trained model on a new, specific dataset", "A type of cleanup", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Weights' and 'Biases'?", "options": ["Parameters learned by a neural network during training", "The length of code", "A type of server name", "None"], "correct": 0},
        {"id": 28, "question": "What is 'Epoch'?", "options": ["A period of time", "One complete pass of the training dataset through the network", "A type of file", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Learning Rate'?", "options": ["How fast a person learns", "A parameter that determines the step size during gradient descent", "A technical specification", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Vanishing Gradient' problem?", "options": ["When the gradients become zero or very small, stopping training", "When the code disappears", "A type of server error", "None"], "correct": 0},
        {"id": 31, "question": "What is 'Exploding Gradient' problem?", "options": ["When gradients specifically become excessively large during training, causing instability", "When the CPU melts", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What represents the 'Neuron' in ANN?", "options": ["A basic computing unit specifically that processes inputs and produces an output", "A types of computer part", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What's the purpose of 'Stochastic Gradient Descent' (SGD)?", "options": ["Updating specifically model weights using a single sample or subset at a time", "A slow way to learn", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Adam' optimizer?", "options": ["An adaptive learning specifically rate optimization algorithm", "A person's name", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents specific 'Cross-Entropy' loss?", "options": ["A loss function specifically used for classification tasks producing probabilities", "Losing your keys", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents 'Mean Squared Error' (MSE)?", "options": ["A loss function specifically used for regression tasks (e.g., predicting house prices)", "A types of graph", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Convolution' in CNN?", "options": ["Mathematical operation specifically that extracts features from an image using filters", "Merging two files", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Pooling' (e.g. Max Pooling) in CNN?", "options": ["Reducing specifically the spatial dimensions of a feature map for efficiency", "Swimming in data", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What represents the 'Stride' in CNN?", "options": ["The number specifically of pixels the filter moves across the input image", "Walking fast", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What represents the 'Padding' (Zero Padding)?", "options": ["Adding zeros specifically to the border of an image to preserve spatial size", "Soft items around a PC", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What represents specific 'Fully Connected Layer'?", "options": ["A layer specifically where every neuron is connected to every neuron in next layer", "A types of cable", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Autoencoder' used for?", "options": ["Unsupervised discovery specifically of efficient data representations (bottleneck)", "Writing code automatically", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What represents the 'Bottleneck' in autoencoders?", "options": ["The layer specifically with the fewest neurons that forces data compression", "A physical bottle", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Generative Model'?", "options": ["A model specifically capable of generating new data samples similar to training set", "A fashion model", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What represents the 'Discriminator' in a GAN?", "options": ["A network specifically that tries to distinguish between real and fake data", "A person who is mean", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What represents the 'Generator' in a GAN?", "options": ["A network specifically that tries to create realistic fake data to fool discriminator", "A power machine", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Self-Attention' mechanism?", "options": ["Relating different specifically parts of a sequence to compute a representation", "Paying attention to oneself", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's the meaning of 'BERT' in NLP?", "options": ["Bidirectional Encoder specifically Representations from Transformers", "A types of character", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's the meaning of 'Attention is All You Need'?", "options": ["The seminal paper specifically that introduced the Transformer architecture", "A motivational quote", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What represents specific 'Embedding Layer'?", "options": ["A layer specifically mapping categorical data (like words) to numerical vectors", "Hiding something", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Word2Vec'?", "options": ["A technique specifically for learning word embeddings from large text corpora", "Two words together", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What represents specific 'Tokenizer'?", "options": ["Dividing specifically text into smaller units (tokens) for model processing", "Buying things", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What represents the 'One-Hot Encoding'?", "options": ["A representation specifically where only one bit is '1' (hot) to identify a category", "A hot day", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'GRU' (Gated Recurrent Unit)?", "options": ["A simplified specifically version of LSTM for sequence modeling", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's 'Fine-tuning' usefulness?", "options": ["Adapting specifically a pre-trained model to a much smaller task-specific dataset", "Cleaning a disk", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Regularization' purpose?", "options": ["Techniques specifically used to prevent overfitting in models (L1, L2, Dropout)", "A government rule", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'L1 Regularization' (Lasso)?", "options": ["Adding the sum specifically of absolute values of weights to the loss", "A types of soup", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'L2 Regularization' (Ridge)?", "options": ["Adding the sum specifically of squared values of weights to the loss", "A bridge in a city", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What represents specific 'Confusion Matrix'?", "options": ["A table specifically used to evaluate the performance of a classification model", "A confused person", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Precision' in model metrics?", "options": ["The ratio specifically of correctly predicted positive results to total predicted positive", "Being exact", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Recall' (Sensitivity)?", "options": ["The ratio specifically of correctly predicted positive results to all actual positive results", "Remembering a name", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What represents the 'F1 Score'?", "options": ["The harmonic specifically mean of precision and recall", "A types of racing", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Validation Set'?", "options": ["Data specifically used to tune hyperparameters and choose between models", "A set of laws", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What represents 'Test Set'?", "options": ["Data specifically used to evaluate the final model's performance realistically", "A set of exams", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Data Preprocessing'?", "options": ["Cleaning and specifically preparing data before it is fed into an AI model", "Doing it later", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents specific 'Feature' in AI?", "options": ["An individual specifically measurable property used as an input to a model", "A types of show", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents the 'Labels' in supervised learning?", "options": ["The actual target values or classes specifically for each data sample", "A name tag", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "Can Deep Learning happen without a GPU?", "options": ["Yes, but it is specifically much slower (CPU is used)", "No", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents 'CUDA' in Nvidia GPUs?", "options": ["A parallel specifically computing platform and API for utilizing GPUs", "A types of fish", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's 'TPU' (Tensor Processing Unit)?", "options": ["AI-specific specifically processor developed by Google for high-speed AI tasks", "A computer box", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's the meaning of 'End-to-End' learning?", "options": ["A method specifically of training a whole model from raw input directly to output", "Learning from start", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents 'Supervised Learning'?", "options": ["Training models specifically on labeled datasets", "Watching a model", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents 'Unsupervised Learning'?", "options": ["Finding hidden specifically patterns or groupings in unlabeled datasets", "Learning alone", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents 'Reinforcement Learning'?", "options": ["Agents specifically learning to make decisions by receiving rewards or penalties", "Strict learning", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What represents specific 'Batch' in training?", "options": ["A small subset specifically of data samples used for one weight update", "A group of food", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents specific 'Iteration'?", "options": ["One weight update specifically using a single batch of data", "Doing things once", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Normalization' specifically for data?", "options": ["Scaling data specifically to a range (like 0 to 1) for better training", "Being normal", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Standardization'?", "options": ["Transforming data specifically to have zero mean and unit variance", "Setting a rule", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents 'Colab' by Google?", "options": ["A free specifically online platform using Jupyter notebooks with GPU support", "A types of drink", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Deep Learning so effective for complex tasks?", "options": ["Ability to handle huge data and automatically learn hierarchical features", "Because of many files", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Neural Network'?", "options": ["Computing system inspired by biological brains", "Network of neurons", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Backpropagation'?", "options": ["Algorithm for training neural networks", "Propagating backwards", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Gradient Descent'?", "options": ["Optimization algorithm for finding minimum", "Descending gradients", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Activation Function'?", "options": ["Function introducing non-linearity", "Activating functions", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Convolutional Neural Network' (CNN)?", "options": ["Network for image processing", "Convolution network", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Recurrent Neural Network' (RNN)?", "options": ["Network for sequential data", "Recurrent network", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Transformer' architecture?", "options": ["Neural network using attention mechanism", "Transformer model", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Transfer Learning'?", "options": ["Using pre-trained models for new tasks", "Learning transfers", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Fine-tuning'?", "options": ["Adapting pre-trained models to specific tasks", "Fine adjustments", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Data Augmentation'?", "options": ["Creating training data variations", "Augmenting data", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Batch Normalization'?", "options": ["Normalizing within each batch", "Normalizing batches", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Dropout'?", "options": ["Regularization technique to prevent overfitting", "Dropping out", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Early Stopping'?", "options": ["Stopping training when validation stops improving", "Stopping early", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Learning Rate'?", "options": ["Step size for gradient updates", "Rate of learning", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Momentum' in optimization?", "options": ["Accelerating gradient descent", "Speed of learning", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Adam Optimizer'?", "options": ["Adaptive learning rate optimization", "Adam optimization", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Loss Function'?", "options": ["Measures model prediction error", "Function for loss", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Cross-Entropy Loss'?", "options": ["Loss function for classification", "Entropy loss", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Mean Squared Error'?", "options": ["Average of squared prediction errors", "Error measurement", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Model Evaluation'?", "options": ["Assessing model performance", "Evaluating models", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
