import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_deployment_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Deployment' in software development?", "options": ["Writing code", "The process of moving software from development to a production environment", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "What is 'CI/CD'?", "options": ["Constant Improvement", "Continuous Integration and Continuous Deployment/Delivery", "Neither", "Both"], "correct": 1},
        {"id": 3, "question": "What is 'Continuous Integration' (CI)?", "options": ["Automatically merging code changes into a central repository frequently", "Building a computer", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Continuous Delivery' (CD)?", "options": ["Code is always in a state where it could be deployed to production", "Always delivering mail", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'Continuous Deployment'?", "options": ["Every code change that passes tests is automatically deployed to production", "Deploying once a year", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "Which of these is a popular deployment tool?", "options": ["Jenkins", "GitHub Actions", "AWS CodeDeploy", "All of the above"], "correct": 3},
        {"id": 7, "question": "What is a 'Deployment Pipeline'?", "options": ["A pipe for water", "Automated sequence of steps (build, test, deploy) and checks", "Both", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Blue-Green Deployment'?", "options": ["Using two identical environments to reduce downtime during updates", "Painting a UI blue and green", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Canary Deployment'?", "options": ["Releasing to a small subset of users first to test stability", "A bird in a cage", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Rolling Deployment'?", "options": ["Gradually updating instances in a group one by one until all are new", "Rolling a ball", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'A/B Testing' through deployment?", "options": ["Comparing two versions of an app to see which performs better", "A math test", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is a 'Staging Environment'?", "options": ["A physical stage", "A pre-production environment that mimics production for final testing", "Both", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Production Environment'?", "options": ["Where the live version of the software is used by real customers", "A place for building servers", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Environment Variables' used for in deployment?", "options": ["Storing configuration like API keys or database URLs for specific environments", "A secret text", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Docker' and its role in deployment?", "options": ["Containerization for consistent app behavior across different environments", "A type of database", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Orchestration' (e.g. Kubernetes)?", "options": ["Managing multiple containers and their deployments automatically at scale", "Music directing", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Rollback'?", "options": ["A complete hardware reset", "Reverting to a previous stable version after a failed deployment", "Neither", "Both"], "correct": 1},
        {"id": 18, "question": "What is 'Infrastructure as Code' (IaC)?", "options": ["Managing and provisioning infrastructure through machine-readable files", "Writing code on a server", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "Which of these is an IaC tool?", "options": ["Terraform", "AWS CloudFormation", "Ansible", "All of the above"], "correct": 3},
        {"id": 20, "question": "What is 'Artifact' in deployment context?", "options": ["A tangible result of the build process (e.g. JAR file, Docker image)", "A historical item", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Build Server' (e.g. Jenkins)?", "options": ["A machine specifically for compiling and testing code automatically", "A server for construction workers", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What's 'Zero Downtime Deployment'?", "options": ["Deploying without any service interruption for the user", "Running fast", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'Docker Compose' used for?", "options": ["Managing multi-container applications (e.g. App + DB) on a single host", "Drawing a map", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'AWS Elastic Beanstalk'?", "options": ["A PaaS for deploying and scaling web applications automatically", "A physical beanstalk", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Heroku'?", "options": ["A cloud platform (PaaS) that simplifies app deployment and management", "A social media brand", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Vercel' / 'Netlify' primarily for?", "options": ["Deploying static and frontend web applications (like React, Next.js)", "A search tool", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Ansible' used for in deployment?", "options": ["Configuration management and automation for software provisioning", "A new computer brand", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What's 'Secret Management'?", "options": ["Hiding keys", "Securely storing and distributing sensitive info like passwords in deployments", "Neither", "Both"], "correct": 1},
        {"id": 29, "question": "What is 'Immutable Infrastructure'?", "options": ["Infrastructure that is never modified after deployment (replaced for updates)", "Very hard infrastructure", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Which of these is a typical business use case for CI/CD?", "options": ["Faster release cycles", "Lower risk and better code quality", "Automatic bug detection", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Unit Testing' in a pipeline?", "options": ["Testing individual pieces of code for correctness during the build", "A test for units", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Integration Testing'?", "options": ["Testing how different modules of an application work together", "A long test", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Smoke Test'?", "options": ["A test with fire", "Quick tests performed right after deployment to check for major issues", "Neither", "Both"], "correct": 1},
        {"id": 34, "question": "What is 'Regression Testing'?", "options": ["Ensuring that new changes haven't broken existing functionality", "Deleting old code", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What's the role of 'Version Control' (e.g. Git) in deployment?", "options": ["Tracking code changes and being the source for the CI/CD pipeline", "Saving files", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What's a 'Git Hook'?", "options": ["A physical hook", "Scripts that trigger automatically before or after Git events (like push/commit)", "Neither", "Both"], "correct": 1},
        {"id": 37, "question": "What is 'WebHook' in deployment automations?", "options": ["A way for one system to notify another (e.g. Git notifies Jenkins) of an event", "A web-based tool", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Branching Strategy' (e.g. GitFlow)?", "options": ["Agreement on how developers use branches to organize code for deployment", "A strategy for trees", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What's the 'Main' (or Master) branch for?", "options": ["Containing the stable, production-ready code", "Writing new features", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Hotfix' branch?", "options": ["A branch for quickly fixing critical issues in the production version", "A heated branch", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Feature' branch in dev workflow?", "options": ["Developing and testing a new feature in isolation before merging", "A branch for UI only", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Pull Request' (PR) or Merge Request?", "options": ["A formal request to merge changes from one branch into another with review", "Asking for money", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Code Review'?", "options": ["Reviewing books", "Developers examining each other's code for quality before integration", "Neither", "Both"], "correct": 1},
        {"id": 44, "question": "What is 'DevHub' or developer portal?", "options": ["Central place for resources and tools needed for app deployment/dev", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's 'DevOps' cultural impact?", "options": ["Breaking the silos between development and operations teams", "Hiring more people", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'SRE' (Site Reliability Engineering)?", "options": ["Applying software engineering to operations tasks for better reliability/scale", "A security team", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Self-Healing' in infrastructure?", "options": ["Infrastructure that automatically detects and fixes its own failures", "Healing a person", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'K8s' common shorthand for?", "options": ["Kubernetes", "8 computers", "A type of key", "None"], "correct": 0},
        {"id": 49, "question": "What's a 'Pod' in Kubernetes?", "options": ["Smallest deployable unit in Kubernetes representing one or more containers", "A small group of people", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Deployment' object in Kubernetes?", "options": ["Defines the desired state for a group of identical Pods (replicas)", "Deploying a physical server", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Ingress' in Kubernetes networking?", "options": ["Managing external access to the services in a cluster (like HTTP/HTTPS)", "Ingressing a folder", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'ConfigMap' used for in containers?", "options": ["Sharing configuration data separately from the application image", "A map of configs", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Stateless' vs 'Stateful' deployment?", "options": ["Stateless apps don't store local data; Stateful ones require persistent storage", "One is for math", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Health Check' in a load balancer/orchestrator?", "options": ["Determining if an instance is healthy and capable of receiving traffic", "A doctor's visit", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Rolling Update' strategy in Kubernetes?", "options": ["Gradual replacement of old Pods with new ones without downtime", "Rolling a ball", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Helm' for Kubernetes?", "options": ["A package manager for Kubernetes (using Charts)", "Steering a ship", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's the role of 'Jenkinsfile'?", "options": ["A script that defines the entire CI/CD pipeline in Jenkins as code", "A personal file", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Gitea' or 'GitLab'?", "options": ["Platforms for hosting Git repositories with built-in CI/CD features", "A social media app", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'Monolithic' versus 'Microservices' deployment?", "options": ["Deploying as one huge unit versus many small independent units", "A style of architecture", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Dark Launching'?", "options": ["Launching at night", "Deploying changes to production without making them visible to users for testing", "Neither", "Both"], "correct": 1},
        {"id": 61, "question": "What is 'Feature Toggle' (Flags)?", "options": ["Turning features on/off dynamically in production using a dashboard/config", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'Monitoring' in deployment post-release?", "options": ["Observing the live performance, errors, and usage of the deployed software", "Watching TV", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's the value of 'Logging' (e.g. ELK stack)?", "options": ["Recording data for troubleshooting bugs after deployment", "Keeping a diary", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "Which of these is a typical server for deployment?", "options": ["Nginx", "Apache", "Tomcat", "All of the above"], "correct": 3},
        {"id": 65, "question": "What is 'Reverse Proxy' primarily used for?", "options": ["Forwarding client requests from internet to the correct backend server", "A security log", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'SSL/TLS' for deployment?", "options": ["Ensuring secure, encrypted communication between client and server (HTTPS)", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's the meaning of 'Uptime' (e.g. 99.9%)?", "options": ["The percentage of time the system is operational and available to users", "Staying up late", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Latency' in web apps?", "options": ["The time it takes for a user request to get a response from the server", "Slow speed", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Throughput' measure?", "options": ["Total number of requests a system can handle in a given timeframe", "A hole in a wall", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "How can you check if your server is running well?", "options": ["Using monitoring tools or checking logs", "Restarting frequently", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's 'Shadow Deployment'?", "options": ["Deploying in shadows", "Routing production traffic to a new version to test performance without user impact", "Neither", "Both"], "correct": 1},
        {"id": 72, "question": "What is 'Server Hardening' for deployment?", "options": ["Making a server physically stronger", "Applying security patches and reducing vulnerabilities before production", "Neither", "Both"], "correct": 1},
        {"id": 73, "question": "What are 'Post-deployment Scripts'?", "options": ["Automated tasks run immediately after a successful deployment (e.g. migrations)", "A note for code", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Database Migration' in a pipeline?", "options": ["Automatically updating DB schema to match the new code version", "Moving a database", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Jenkins' specifically?", "options": ["An open-source automation server primarily used for CI/CD pipelines", "A famous person", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What's 'GitHub Actions' importance?", "options": ["Built-in CI/CD platform directly within GitHub for easier automation", "A set of buttons", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What's 'YAML' importance in deployment?", "options": ["A common configuration format used for pipelines and Kubernetes manifests", "A new computer game", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'DotEnv' file (.env) used for?", "options": ["Managing environment-specific configurations locally and in deployment", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'App Service' (Azure) / 'App Engine' (GCP)?", "options": ["Fully managed platforms for deploying web apps without server trouble", "A speed test", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What's the overall goal of modern deployment strategies?", "options": ["Ensuring fast, reliable, and frequent software releases with minimal risk", "Buying more servers", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Blue-Green Deployment'?", "options": ["Zero-downtime deployment strategy", "Deployment with colors", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Canary Deployment'?", "options": ["Gradual rollout to subset of users", "Bird deployment", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Rolling Deployment'?", "options": ["Gradual replacement of instances", "Rolling deployment", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Feature Flag'?", "options": ["Toggle for enabling/disabling features", "Flag for features", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Infrastructure as Code' (IaC)?", "options": ["Managing infrastructure through code", "Code for infrastructure", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'GitOps'?", "options": ["Git-based operations", "Operations with Git", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'DevSecOps'?", "options": ["Integrating security into DevOps", "Security in DevOps", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Site Reliability Engineering' (SRE)?", "options": ["Applying engineering to reliability", "Reliability engineering", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Observability'?", "options": ["Ability to understand system from external signals", "Observing systems", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Pipeline as Code'?", "options": ["Defining pipelines in code", "Code for pipelines", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Chaos Engineering'?", "options": ["Testing resilience through controlled failures", "Engineering chaos", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Value Stream Mapping'?", "options": ["Visualizing workflow steps", "Mapping value streams", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Continuous Improvement'?", "options": ["Ongoing process optimization", "Improving continuously", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'DevOps Culture'?", "options": ["Collaborative environment for development and operations", "Culture for DevOps", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'A/B Testing' in deployment?", "options": ["Comparing two versions", "Testing letters", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Load Balancing'?", "options": ["Distributing traffic across servers", "Balancing loads", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Auto Scaling'?", "options": ["Automatically adjusting resources based on demand", "Scaling automatically", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Health Check'?", "options": ["Monitoring application health status", "Checking health", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Configuration Management'?", "options": ["Managing application configurations", "Managing configs", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Deployment Pipeline'?", "options": ["Automated process for software delivery", "Pipeline for deployment", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
