import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_docker_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Docker?", "options": ["A tool for shipping physical containers", "A platform for developers to develop, ship, and run applications in containers", "A web browser", "None"], "correct": 1},
        {"id": 2, "question": "What is a 'Container'?", "options": ["A types of box", "A lightweight, standalone, executable package including everything to run software", "A server instance", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Docker Image'?", "options": ["A physical photo", "A read-only template with instructions for creating a Docker container", "Neither", "Both"], "correct": 1},
        {"id": 4, "question": "What's the relationship between Image and Container?", "options": ["Image is the plan/blueprint; Container is the running instance", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'Dockerfile'?", "options": ["A computer file", "A text document containing all instructions to build a Docker image", "Neither", "Both"], "correct": 1},
        {"id": 6, "question": "What is 'Docker Hub'?", "options": ["A physical port", "A cloud-based registry for sharing and finding Docker images", "Neither", "Both"], "correct": 1},
        {"id": 7, "question": "What is 'Docker Desktop'?", "options": ["An app for Windows/Mac to locally build and share containerized apps", "A types of computer", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Docker Engine'?", "options": ["A car engine", "The core underlying client-server technology that creates and runs containers", "Neither", "Both"], "correct": 1},
        {"id": 9, "question": "What is 'Containerization' benefit?", "options": ["Isolation, portability, and consistency across different environments", "Fast internet", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "How is a Container different from a VM?", "options": ["Containers share the host OS kernel; VMs include a full guest OS", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Docker Compose'?", "options": ["Composing music using Docker", "A tool for defining and running multi-container applications (using YAML)", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'Docker Swarm'?", "options": ["A group of bees", "A native clustering and orchestration tool for Docker containers", "Neither", "Both"], "correct": 1},
        {"id": 13, "question": "What is 'Docker Registry'?", "options": ["A place to store and distribute Docker images", "A list of people", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Layer' in Docker image?", "options": ["A physical layer in earth", "A set of intermediate images that build up to the final image", "Neither", "Both"], "correct": 1},
        {"id": 15, "question": "What is 'Caching' in Docker build?", "options": ["Reusing layers that haven't changed to speed up the image building process", "Saving money", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "Which command builds a Docker image from a Dockerfile?", "options": ["docker build", "docker start", "docker new", "None"], "correct": 0},
        {"id": 17, "question": "Which command runs a Docker container from an image?", "options": ["docker run", "docker execute", "docker open", "None"], "correct": 0},
        {"id": 18, "question": "What's the command to list all running containers?", "options": ["docker ps", "docker ls", "docker list", "None"], "correct": 0},
        {"id": 19, "question": "How do you stop a running Docker container?", "options": ["docker stop container_id", "docker end", "neither", "both"], "correct": 0},
        {"id": 20, "question": "How do you remove a Docker container?", "options": ["docker delete", "docker rm container_id", "neither", "both"], "correct": 1},
        {"id": 21, "question": "How do you remove a Docker image?", "options": ["docker rmi image_id", "docker delete-img", "neither", "both"], "correct": 0},
        {"id": 22, "question": "What is 'Volume' in Docker?", "options": ["Sound level", "A mechanism for persisting data outside the container's lifecycle", "Neither", "Both"], "correct": 1},
        {"id": 23, "question": "What is 'Bind Mount'?", "options": ["Binding a book", "Mapping a folder/file from the host machine directly into a container", "Neither", "Both"], "correct": 1},
        {"id": 24, "question": "What is 'Port Mapping' (-p)?", "options": ["Connecting a port in host to a port in container for external access", "Drawing a map", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What's the meaning of 'Base Image'?", "options": ["The starting image (like Ubuntu or Python) used in a Dockerfile", "A simple image", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Tagging' image for?", "options": ["Labelling image versions (e.g. myapp:v1.0 or myapp:latest)", "Designing a logo", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What's 'EntryPoint' versus 'Cmd' in Dockerfile?", "options": ["Specifying the main command to run; Cmd provides default arguments", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Env' instruction for?", "options": ["Setting environment variables inside the container for config", "An error code", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's '.dockerignore' for?", "options": ["Ignoring specific files/folders from being sent to the Docker daemon", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Which of these is a popular alternative to Docker?", "options": ["Podman", "Containerd", "LXC", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Multi-stage Build' in Docker?", "options": ["Building in different locations", "Using multiple 'FROM' statements to minimize the final image size", "Neither", "Both"], "correct": 1},
        {"id": 32, "question": "What's the benefit of choosing small base images like Alpine?", "options": ["Security, faster downloads, and smaller storage footprint", "More features", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Docker Network'?", "options": ["A way for multiple containers to communicate with each other securely", "Internet speed check", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the default Docker network type?", "options": ["Bridge", "Host", "Overlay", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Bridge Network'?", "options": ["The default private network within a single host for multiple containers", "A literal bridge", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Host Network'?", "options": ["Container uses the host's actual networking stack directly", "A network for home", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'None Network'?", "options": ["Disables all networking for a container (isolated)", "No internet only", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Overlay Network'?", "options": ["Connecting containers across multiple Docker hosts (for Swarm)", "A network over another", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "How can you view logs of a running container?", "options": ["docker logs container_id", "docker see", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "How can you execute a command inside a running container?", "options": ["docker exec -it container_id command", "docker open", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is '-it' flag for?", "options": ["Interactive terminal mode for user input", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's 'Docker Volume' versus 'Bind Mount'?", "options": ["Volume is managed by Docker; Bind mount is a direct host path mapping", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Docker Inspect'?", "options": ["Viewing detailed low-level JSON information about a container/image", "Repairing a container", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Docker Stats'?", "options": ["Viewing live resource usage (CPU/Memory) for running containers", "A performance chart", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Orchestration' (K8s) vs Docker?", "options": ["Docker focuses on individual containers; K8s manages clusters of them", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "How do you push an image to Docker Hub?", "options": ["docker push username/image:tag", "docker upload", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "How do you log in to Docker via CLI?", "options": ["docker login", "docker connect", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Build Context' in Docker build?", "options": ["The set of files available to the build command to put into the image", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's the effect of 'Expose' in Dockerfile?", "options": ["Documenting which port the container is intended to listen on", "Opening a window", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'WorkDir' in Dockerfile?", "options": ["Setting the working directory for subsequent instructions (like CD)", "A file name", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Copy' vs 'Add' in Dockerfile?", "options": ["Copy moves local files; Add can extract tar files and download from URLs", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Docker Prune' (-a)?", "options": ["Cleaning up all unused containers, images, and networks at once", "A type of fruit", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Container Orchestration'?", "options": ["Automating deployment, scaling, and management of hundreds of containers", "Directing a music show", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Docker-Compose.yml'?", "options": ["The configuration file for defining multi-container services", "A text file of names", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "How do you start services defined in a compose file?", "options": ["docker-compose up", "docker-compose start", "Both A and B", "Neither"], "correct": 0},
        {"id": 56, "question": "How do you stop and remove services in compose?", "options": ["docker-compose down", "docker-compose stop", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Docker Machine' (Legacy)?", "options": ["A tool for installing Docker on virtual hosts", "Machine for physical containers", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Container Lifecycle'?", "options": ["The stages a container goes through: Created -> Running -> Stopped -> Removed", "Age of a machine", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Docker Events'?", "options": ["A list of party events", "A real-time stream of server-side events in Docker daemon", "Neither", "Both"], "correct": 1},
        {"id": 60, "question": "What is 'Docker Version' command?", "options": ["Showing installed Docker version and client/server info", "A version for math", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Registry Mirror'?", "options": ["A local copy of a registry to speed up image downloads", "A literal mirror", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What signifies the 'Success' of a Docker build?", "options": ["Seeing 'Successfully built [ImageId]' in terminal", "A green screen", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Docker API' (Rest API)?", "options": ["Allows other programs to control the Docker daemon over a network", "A programming language", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Named Volume' vs 'Anonymous Volume'?", "options": ["Named has a specific identifier; Anonymous is given a random ID by Docker", "One has a person's name", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Entrypoint' with shell vs exec form?", "options": ["Exec form is preferred as it correctly handles signals like stop/kill", "Shell form is faster", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "How do you view which containers are consuming most memory?", "options": ["docker stats", "docker check", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Docker CP' command for?", "options": ["Copying files/folders between local machine and a running container", "A short file", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Container Port' vs 'Host Port'?", "options": ["Internal port of app vs public port of the machine", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "Which constant is used for root in Dockerfile?", "options": ["USER root", "PRINCIPAL", "Both", "None"], "correct": 0},
        {"id": 70, "question": "Can you run Docker on a computer without a GUI?", "options": ["Yes, using the Docker CLI (Standard for servers)", "No", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Docker Context'?", "options": ["Managing multiple Docker environment connections (local, remote, cloud)", "A help guide", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Docker Buildx'?", "options": ["Extending build capabilities with multiple builders and platforms (multi-arch)", "Better build", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's the meaning of 'Container Orchestrator'?", "options": ["System to manage many containers (like K8s, Docker Swarm)", "Musical direction", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'HealthCheck' in Dockerfile?", "options": ["Instruction to check if the app inside container is actually working", "A doctor's visit", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "Which of these is a typical image name format?", "options": ["repository:tag", "name:extension", "Both A and B", "Neither"], "correct": 0},
        {"id": 76, "question": "What is 'Daemon' in Docker?", "options": ["The background process that manages all Docker objects and requests", "A historical figure", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Client' in Docker architecture?", "options": ["The CLI tool (docker command) that users interact with", "A person buying items", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "How can you debug a failing Docker build?", "options": ["By checking the output logs of each layer", "Guessing", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which symbol is used for Docker logo?", "options": ["A whale carrying containers", "A ship with boxes", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Docker essential for modern Microservices?", "options": ["Simplifies environment management and ensures consistent software behavior", "Faster internet speed", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Docker Swarm'?", "options": ["Native clustering and orchestration solution for Docker", "A group of Docker containers", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Docker Compose'?", "options": ["Tool for defining and running multi-container applications", "Writing Docker files", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Dockerfile'?", "options": ["Text file with instructions to build Docker image", "File for Docker", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Docker Hub'?", "options": ["Cloud service for sharing and storing Docker images", "A hub for Docker", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Docker Registry'?", "options": ["Storage and distribution system for Docker images", "Registry for Docker", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Docker Volume'?", "options": ["Persistent storage for Docker containers", "Volume for Docker", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Docker Network'?", "options": ["Communication system between containers", "Network for Docker", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Docker Multi-stage Build'?", "options": ["Building images in stages to reduce size", "Building Docker in stages", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Docker Health Check'?", "options": ["Monitoring container health status", "Checking Docker health", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Docker Restart Policy'?", "options": ["Behavior when container exits", "Restarting Docker containers", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Docker Resource Limits'?", "options": ["Restricting container resource usage", "Limiting Docker resources", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Docker Environment Variables'?", "options": ["Configuration values passed to containers", "Environment in Docker", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Docker Entrypoint'?", "options": ["Command executed when container starts", "Entry point for Docker", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Docker CMD'?", "options": ["Default command for container", "Command for Docker", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Docker USER'?", "options": ["User that runs commands in container", "User for Docker", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Docker WORKDIR'?", "options": ["Working directory for commands", "Working directory in Docker", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Docker COPY' vs 'ADD'?", "options": ["COPY copies files; ADD can copy and extract archives", "Both copy files", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Docker EXPOSE'?", "options": ["Informing about network ports", "Exposing Docker ports", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Docker ARG'?", "options": ["Build-time variables", "Arguments for Docker", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Docker ONBUILD'?", "options": ["Trigger for downstream builds", "Building on Docker", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
