import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_ec2s3_api(request):
    questions_pool = [
        {"id": 1, "question": "What is AWS EC2?", "options": ["Elastic Cloud Compute (virtualized, resizable servers)", "Electronic Computer 2", "Elastic Compute 2", "None"], "correct": 0},
        {"id": 2, "question": "What is a 'VM' in cloud context?", "options": ["Virtual Machine (an OS environment behaves like a separate computer)", "Virtual Money", "Video Machine", "None"], "correct": 0},
        {"id": 3, "question": "What is an 'AMI' (Amazon Machine Image)?", "options": ["A types of car", "A template containing an OS, server, and applications to launch EC2", "Neither", "Both"], "correct": 1},
        {"id": 4, "question": "What is 'Instance Type' in EC2?", "options": ["Determines the CPU, memory, storage, and networking capacity for an EC2", "A specific server brand", "A security log", "None"], "correct": 0},
        {"id": 5, "question": "What is 'On-Demand' instance in EC2?", "options": ["Payment only for seconds you use without long-term commitment", "Pay once for life", "A pre-paid account", "None"], "correct": 0},
        {"id": 6, "question": "What is 'Reserved Instance'?", "options": ["Providing significant discount by committing to use instance for 1-3 years", "Instances for VIPs", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'Spot Instance' in EC2?", "options": ["Buying spare compute capacity for deep discounts (up to 90%) but can be terminated", "A random instance", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Auto Scaling Group' (ASG)?", "options": ["Automatically adding or removing EC2 instances to maintain performance", "A group for scales", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'EBS' (Elastic Block Store)?", "options": ["A durable, high-performance block storage volume for use with a single EC2", "A book store", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Key Pair' used for in EC2?", "options": ["A physical key", "A set of security credentials used to securely log in to an EC2 instance", "Neither", "Both"], "correct": 1},
        {"id": 11, "question": "What is 'Security Group' in AWS?", "options": ["A groups for guards", "A virtual firewall that controls inbound and outbound traffic for EC2 instances", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'User Data' script in EC2?", "options": ["Script executed once at the same time an instance is launched for configuration", "A person's data", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Placement Group'?", "options": ["A strategy for placing EC2 instances physically together for better networking", "A grouping of items", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is AWS S3 (Simple Storage Service)?", "options": ["High-speed object storage service for data (Internet-scale storage)", "Simple Storage 3", "Super Security Service", "None"], "correct": 0},
        {"id": 15, "question": "What is a 'Bucket' in AWS S3?", "options": ["A physical container", "A logical container for storing objects (files) in S3", "Both", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Object' in S3?", "options": ["A file being stored (e.g. image, video, document) with metadata", "A physical item", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "Which of these is a valid S3 storage class?", "options": ["S3 Standard", "S3 Intelligent-Tiering", "S3 Glacier", "All of the above"], "correct": 3},
        {"id": 18, "question": "What's the meaning of 'S3 Standard'?", "options": ["For frequently accessed data with high availability", "For any data", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'S3 Glacier'?", "options": ["Storage for ice in cloud", "Low-cost storage for long-term data archiving with various retrieval times", "Neither", "Both"], "correct": 1},
        {"id": 20, "question": "What is 'S3 Object Versioning'?", "options": ["Keeping multiple versions of an object in the same bucket to prevent loss", "One version only", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What's 'Bucket Policy' for?", "options": ["Managing who has access to an entire S3 bucket via JSON-based rules", "Managing the bucket itself", "Both", "None"], "correct": 0},
        {"id": 22, "question": "What is 'Endpoint' for S3?", "options": ["A URL used to access or download objects from a bucket", "The end of a file", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'Static Website Hosting' in S3?", "options": ["Using S3 to host a simple HTML website without any servers", "Hosting a database", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'Cross-Region Replication'?", "options": ["Automatically copying objects across S3 buckets in different regions for HA", "Copying in city", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Lifecycle Policy' used for?", "options": ["Managing data by automatically moving it to cheaper storage after some time", "A policy for life", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'EFS' (Elastic File System)?", "options": ["A shared file system that can be accessed by multiple EC2 instances simultaneously", "A fast folder", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Instance Store'?", "options": ["A place where you buy instances", "Temporary, high-speed storage physically attached to the EC2 host machine", "Neither", "Both"], "correct": 1},
        {"id": 28, "question": "What's the meaning of 'Elastic' in both services?", "options": ["The ability to scale resources automatically as demand changes", "Being flexible like a rubber band", "Both A and B", "Neither"], "correct": 2},
        {"id": 29, "question": "Which constant is used for AWS regional endpoint?", "options": ["region_name.amazonaws.com", "aws.region", "Both", "None"], "correct": 0},
        {"id": 30, "question": "Which of these is a typical business use case for EC2?", "options": ["Hosting a web server", "Building a custom application", "Data processing", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Elastic IP Address'?", "options": ["A static IPv4 address for an EC2 instance that won't change when stopped", "A fast internet", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What's the meaning of 'Provisioned IOPS' for EBS?", "options": ["Selecting specific high-speed storage performance for intense database usage", "Sharing many IOPS", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'S3 Select'?", "options": ["Selecting only part of an object's data to retrieve (e.g. a specific CSV row)", "A search for objects", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'VPC' (Virtual Private Cloud)?", "options": ["A virtual private network in AWS for isolated resource launching", "A video PC", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Internet Gateway'?", "options": ["A tool allowing EC2 instances in a VPC to communicate with the internet", "A portal for web", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Subnet' in VPC?", "options": ["A net for sub netting", "A segment of an IP address range in a VPC for organization", "Neither", "Both"], "correct": 1},
        {"id": 37, "question": "What is 'Public Subnet'?", "options": ["A subnet for everyone", "A subnet with an internet gateway route for public internet access", "Neither", "Both"], "correct": 1},
        {"id": 38, "question": "What's 'Private Subnet'?", "options": ["A secret subnet", "A subnet with no direct route to the internet for security", "Neither", "Both"], "correct": 1},
        {"id": 39, "question": "What is 'ELB' (Elastic Load Balancer)?", "options": ["Distributing incoming traffic across multiple EC2 targets", "A physical scale", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Route 53'?", "options": ["A road in AWS", "Amazon's DNS service for domain registration and traffic routing", "Neither", "Both"], "correct": 1},
        {"id": 41, "question": "What is 'S3 Transfer Acceleration'?", "options": ["Enabling fast data transfer to/from an S3 bucket across long distances using CDN", "A fast car", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'S3 Presigned URL' for?", "options": ["Giving a URL a special name", "Temporarily sharing access to a private object in S3 for a specific time", "Both", "None"], "correct": 1},
        {"id": 43, "question": "What's the benefit of using 'S3 Event Notifications'?", "options": ["Receiving alerts when objects are added/deleted to trigger actions", "Reading books with code", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Dedicated Host' in EC2?", "options": ["A server specifically for a guest", "A physical server exclusively for a single customer use", "Neither", "Both"], "correct": 1},
        {"id": 45, "question": "What is 'Standard Reserved Instance' vs 'Convertible'?", "options": ["Standard offers more discount; Convertible allows changing instance types", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Savings Plans' in AWS?", "options": ["A flexible way to save on EC2/Fargate/Lambda usage costs", "Saving money in a bank", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'T-series' EC2 instances known for?", "options": ["Bursting performance when needed (burstable CPU)", "A music series", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Cluster Placement Group'?", "options": ["Grouping instances closely on a physical rack for low latency", "Grouping items together", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Partition Placement Group'?", "options": ["Ensuring instances in a group are physically isolated across different racks", "Dividing a room", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Spread Placement Group'?", "options": ["Placing instances far away from each other individually for reliability", "Spreading a blanket", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "which protocol is usually used to SSH into an EC2 linux instance?", "options": ["HTTP", "SSH (Port 22)", "FTP", "RDP"], "correct": 1},
        {"id": 52, "question": "which protocol is usually used to log in to an EC2 Windows instance?", "options": ["HTTP", "RDP (Port 3389)", "SSH", "None"], "correct": 1},
        {"id": 53, "question": "What is 'S3 Intelligent-Tiering'?", "options": ["Moving data automatically between tiers based on changing access patterns", "A smart person", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'EBS Snapshot'?", "options": ["A point-in-time backup of an EBS volume stored in S3", "A photo on a disk", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'EBS Throughput Optimized HDD' (st1)?", "options": ["Low-cost magnetic storage for frequently accessed, throughput-heavy workloads", "A fast hard drive", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Cold HDD' (sc1)?", "options": ["Lowest-cost magnetic storage for data accessed less frequently", "A cold hard drive", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'S3 Cross-Account Replication'?", "options": ["Replicating objects between buckets in two totally different AWS accounts", "Sharing with friends", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's the meaning of 'S3 Object Lock'?", "options": ["Preventing objects from being deleted or overwritten for a fixed time", "Locking a house", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'AWS Snowball'?", "options": ["A physical device to move massive amounts of data in and out of S3", "A ball made from snow", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'AWS Outposts'?", "options": ["A way to run AWS services in an on-premises facility using AWS hardware", "A physical sign in AWS", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Lambda' in AWS?", "options": ["A mathematics term", "Serverless compute service that runs code in response to triggers", "Neither", "Both"], "correct": 1},
        {"id": 62, "question": "Can you trigger a Lambda function when an object is uploaded to S3?", "options": ["Yes, using S3 event notifications", "No", "Only for Pro accounts", "None"], "correct": 0},
        {"id": 63, "question": "What is 'CloudWatch'?", "options": ["Watching clouds on TV", "Monitoring and observability service for AWS resources and applications", "Neither", "Both"], "correct": 1},
        {"id": 64, "question": "What is 'CloudTrail'?", "options": ["Logging service that records AWS API calls for auditing and security", "A trail on a mountain", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'CloudFormation'?", "options": ["A tool to model and set up your AWS resources using code (infrastructure as code)", "Formation of clouds in the sky", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Amazon Route 53' health check?", "options": ["Monitoring your end points and rerouting traffic if an endpoint is unhealthy", "Checking health of developers", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Amazon S3 Inventory'?", "options": ["Providing a list of objects and their metadata for analysis regularly", "A list of things you buy", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'S3 Access Points'?", "options": ["A way to simplify data access for shared datasets at scale", "A point to access the internet", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "Which constant is used for public access setting in S3?", "options": ["block_public_access", "open_all", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Amazon VPC Endpoint'?", "options": ["Allowing private connection between VPC and AWS services (like S3) without using internet", "The end of a network", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's the benefit of 'S3 Multi-part Upload'?", "options": ["Uploading large files in parallel chunks for better speed and reliability", "Uploading many files at once", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'EBS Multi-attach'?", "options": ["Allowing an EBS volume to be attached to multiple nitro-based EC2 instances simultaneously", "Attaching many things", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'IOPS'?", "options": ["Input/Output Operations Per Second (a measure of disk speed)", "A type of chart", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Hibernate' for EC2?", "options": ["Sleeping in winter", "Saving the contents of the instance memory (RAM) to EBS when stopping", "Neither", "Both"], "correct": 1},
        {"id": 75, "question": "What is 'CloudFront'?", "options": ["Content Delivery Network (CDN) to deliver data, videos, and APIs globally with low latency", "The front of a cloud", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'ACM' (AWS Certificate Manager)?", "options": ["Managing SSL/TLS certificates for websites", "Designing certificates", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'ALB' (Application Load Balancer)?", "options": ["A load balancer optimized for HTTP/HTTPS traffic (Layer 7)", "A physical weight", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'NLB' (Network Load Balancer)?", "options": ["A high-performance load balancer for TCP/UDP traffic (Layer 4)", "Neither", "Both", "None"], "correct": 0},
        {"id": 79, "question": "Which of these is a typical EC2 status check?", "options": ["System Status Check", "Instance Status Check", "Both A and B", "Neither"], "correct": 2},
        {"id": 80, "question": "What is the primary benefit of pay-as-you-go model for EC2?", "options": ["No upfront cost and ability to scale down anytime", "Having many servers for free", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
