import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_ethereum_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Ethereum'?", "options": ["A cryptocurrency only", "An open-source blockchain platform with smart contract functionality", "A browser", "None"], "correct": 1},
        {"id": 2, "question": "Who is the primary co-founder of Ethereum?", "options": ["Satoshi Nakamoto", "Vitalik Buterin", "Bill Gates", "Mark Zuckerberg"], "correct": 1},
        {"id": 3, "question": "What is 'Ether' (ETH)?", "options": ["A type of gas", "The native cryptocurrency of the Ethereum network", "A programming language", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Smart Contract' in Ethereum?", "options": ["A physical contract", "Self-executing contracts with the terms directly written into code", "A type of table", "None"], "correct": 1},
        {"id": 5, "question": "What is the 'Ethereum Virtual Machine' (EVM)?", "options": ["A physical computer", "The runtime environment for smart contracts in Ethereum", "A type of chart", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Gas' in Ethereum?", "options": ["A type of fuel", "The unit measuring the computational effort required for transactions/contracts", "An internet speed", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Solidity'?", "options": ["A physical property", "The primary programming language for writing Ethereum smart contracts", "A technical specification", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Decentralized Application' (dApp)?", "options": ["A mobile app", "An application that runs on a peer-to-peer network of computers", "Both A and B", "Neither"], "correct": 1},
        {"id": 9, "question": "What is 'PoS' (Proof of Stake) in Ethereum context?", "options": ["The current consensus mechanism for Ethereum after the Merge", "The old mining system", "A type of database", "None"], "correct": 0},
        {"id": 10, "question": "What is 'Metamask'?", "options": ["A superhero name", "A browser extension and crypto wallet for Ethereum interaction", "A type of robot", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Blockchain'?", "options": ["A block of wood", "A distributed ledger that records all transactions across a network", "A search engine", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Miner' / 'Validator'?", "options": ["A person in a cave", "An entity that verifies and adds new blocks to the blockchain", "A security log", "None"], "correct": 1},
        {"id": 13, "question": "What is an 'Address' in Ethereum?", "options": ["A physical home address", "A unique alphanumeric identifier for a user or smart contract", "A type of table", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Genesis Block'?", "options": ["The latest block", "The very first block ever created on a blockchain", "A piece of data", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Immutable' in blockchain?", "options": ["Data that can be easily changed", "Data that cannot be modified once it is recorded", "A type of error", "None"], "correct": 1},
        {"id": 16, "question": "What is 'DAO'?", "options": ["Decentralized Autonomous Organization", "Digital Access Organization", "Design of data objects", "None"], "correct": 0},
        {"id": 17, "question": "What is 'The Merge' in Ethereum history?", "options": ["Merging two databases", "Ethereum's transition from Proof of Work to Proof of Stake", "Connecting two blocks", "None"], "correct": 1},
        {"id": 18, "question": "What is 'ERC-20'?", "options": ["A technical standard for token creation on Ethereum", "A type of computer", "A financial report", "None"], "correct": 0},
        {"id": 19, "question": "What is 'ERC-721'?", "options": ["A standard for fungible tokens", "A standard for Non-Fungible Tokens (NFTs) on Ethereum", "A type of chart", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Truffle' / 'Hardhat'?", "options": ["A type of chocolate", "Popular development frameworks for Ethereum smart contracts", "A design tool", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Infura' in blockchain dev?", "options": ["A type of computer brand", "A suite of tools providing infrastructure to access Ethereum/IPFS", "None", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Private Key'?", "options": ["A key to unlock a home", "A secret alphanumeric code that allows access and spending of funds", "A type of password", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Public Key'?", "options": ["A key for everyone", "An address derived from a private key for receiving funds", "None of the above", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Mining' in PoW?", "options": ["Creating a new coin manually", "The process of using computational power to solve complex puzzles and add blocks", "None of the above", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Wallet' context?", "options": ["A physical leather wallet", "Software or hardware that stores a user's digital keys and interacts with blockchain", "A tech spec", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Scalability' problem in Ethereum?", "options": ["Internet speed", "The difficulty of handling high transaction volume at low cost", "Deleting old data", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Layer 2' solution?", "options": ["A second server", "Secondary protocols built on top of the main blockchain to improve speed/cost", "A security feature", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Testnet' (e.g. Goerli, Sepolia)?", "options": ["A private network", "Blockchains used by developers for testing without real ETH", "None of the above", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Mainnet'?", "options": ["The primary public production blockchain network", "A type of internet connection", "None", "None"], "correct": 0},
        {"id": 30, "question": "What is 'Gas Limit'?", "options": ["The maximum amount of gas a user is willing to spend for a transaction", "A speed limit", "A physical tank", "None"], "correct": 0},
        {"id": 31, "question": "What standard specifically is ERC-1155?", "options": ["Multi-token standard specifically allowing both fungible and non-fungible tokens", "Standard for only NFTs", "A types of car", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Go-Ethereum' (Geth)?", "options": ["One specifically of the most popular implementations of the Ethereum protocol in Go language", "A city in Germany", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What's the meaning of 'State' in Ethereum blockchain?", "options": ["The current status specifically of all accounts and contracts on the network at any block", "A country name", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Web3.js' or 'Ethers.js'?", "options": ["JavaScript libraries specifically for interacting with the Ethereum blockchain", "A types of browser", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents the 'Private Blockchain'?", "options": ["Blockchain specifically where access and participation are restricted to a specific group", "A blockchain for files", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents the 'Public Blockchain'?", "options": ["Blockchain specifically open to anyone to join and participate (like Ethereum)", "A types of park", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Gas Fee' dynamic pricing (EIP-1559)?", "options": ["Mechanism specifically that divides gas fees into base fee (burnt) and priority fee", "A speed test", "A types of math", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Uncle Block' (Ommer block)?", "options": ["A valid block specifically not included in the main chain (mostly in old PoW)", "A blocks from a relative", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "Which constant is used for 'Selfdestruct' in Solidity?", "options": ["Function specifically to delete a smart contract and send remaining funds to an address", "Exploding the PC", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What represents the 'Oracle' in blockchain?", "options": ["Service providing specifically external data to smart contracts (e.g. Chainlink)", "A types of database", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What's 'DeFi' (Decentralized Finance)?", "options": ["Financial services specifically built on public blockchains avoiding traditional intermediaries", "A bank name", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What represents the 'Stablecoin'?", "options": ["Cryptocurrency specifically designed to maintain a stable value relative to an asset (e.g. USD)", "A types of horse coin", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'AMM' (Automated Market Maker)?", "options": ["Protocol specifically allowing users to trade assets automatically using liquidity pools", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Yield Farming'?", "options": ["Earning specifically additional rewards by providing liquidity to DeFi protocols", "Farming in a field", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's 'Staking' usefulness in PoS?", "options": ["Pledging your ETH specifically to help secure the network and earn rewards", "Hitting a stake", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What represents specific 'Slashing' in PoS?", "options": ["惩罚 (Punishment) specifically where a validator loses ETH for malicious behavior", "Cutting wood", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What represents 'Rollup' in Layer 2?", "options": ["Process specifically of bundling transactions off-chain and posting them to Ethereum", "A types of dessert", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's 'Optimistic Rollup'?", "options": ["Layer 2 specifically assuming transactions are valid unless proven otherwise", "A happy cake", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What represents 'ZK-Rollup'?", "options": ["Layer 2 specifically using Zero-Knowledge proofs for transaction verification", "A secret box", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What represents 'Zero-Knowledge Proof'?", "options": ["Method specifically to prove something is true without revealing the info itself", "Knowing nothing", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'MetaMask' primarily used for?", "options": ["Crypto wallet specifically providing access to decentralized applications", "Playing a game", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What represents the 'Hardware Wallet' (e.g. Ledger)?", "options": ["Physical device specifically designed to store private keys offline securely", "A types of computer", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What represents 'Cold Storage'?", "options": ["Storing specifically private keys offline to prevent hacking", "Storing food in a fridge", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the meaning of 'Fork' in blockchain?", "options": ["A split specifically in the blockchain's transaction history or protocol", "A types of cutlery", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's 'Hard Fork'?", "options": ["A protocol update specifically that is not backward compatible", "A metal fork", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Soft Fork'?", "options": ["A protocol update specifically that is backward compatible", "A plastic fork", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What represents the 'Ethereum Classic' (ETC)?", "options": ["The original blockchain specifically that remained after the DAO fork", "A types of music", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What represents specific 'Beacon Chain'?", "options": ["The foundational chain specifically for Ethereum's Proof of Stake system", "A light in a sea", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Shanghai Upgrade' significance?", "options": ["Enabling specifically the withdrawal of staked ETH for validators", "A building in China", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's 'Account Abstraction' (ERC-4337)?", "options": ["Improving specifically user experience by allowing complex logic for accounts", "Deleting an account", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "How many decimals in one ETH?", "options": ["18 (lowest unit is wei)", "Only two", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Wei' specifically?", "options": ["The smallest unit specifically of ETH (1 ETH = 10^18 wei)", "A types of food", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Gwei' common use?", "options": ["Measuring specifically gas prices conveniently (10^9 wei)", "A types of weight", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What represents specific 'Remix' IDE?", "options": ["An online tool specifically used for writing, testing and deploying smart contracts", "A types of music app", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's 'Swarm' or 'IPFS' relation to Ethereum?", "options": ["Decentralized specifically storage solutions often used for dApp files", "A crowd of people", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents 'ENS' (Ethereum Name Service)?", "options": ["Service specifically for mapping long addresses to human-readable names (.eth)", "A list of names", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Danksharding' for?", "options": ["Scalability specifically aimed at making transactions much cheaper on Layer 2", "A types of food", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's 'Double Spending' problem?", "options": ["The risk specifically of a digital currency being spent twice", "Spending too much money", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents specific 'Nonce'?", "options": ["A number specifically unique to each transaction to prevent replay attacks", "A types of error", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents the 'ABI' (Application Binary Interface)?", "options": ["Standard specifically for interacting with contracts in the EVM", "A types of music", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Can you run a full node at home?", "options": ["Yes, with specifically suitable hardware and internet connection", "No", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents the 'Light Client'?", "options": ["Node specifically that only downloads block headers for faster verification", "A thin person", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents the 'Goerli' or 'Sepolia'?", "options": ["Primary testnets specifically for Ethereum developers", "Types of names", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "How to verify a contract on Etherscan?", "options": ["Uploading specifically the source code to match the bytecode on-chain", "Just clicking a button", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Etherscan' role?", "options": ["The most popular specifically block explorer for the Ethereum network", "Scanning for code", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents specific 'Token' in blockchain?", "options": ["A digital asset specifically created on top of an existing blockchain platform", "A coin for a ride", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents the 'Wallet Connect' protocol?", "options": ["Connecting specifically mobile wallets to dApps securely", "Linking two phones", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents 'Uniswap'?", "options": ["A leading specifically decentralized exchange (DEX) on Ethereum", "A types of school", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents specific 'Slippage'?", "options": ["The difference specifically between expected and actual execution price of a trade", "Slipping on ice", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Ethereum called the 'World Computer'?", "options": ["Because it provides specifically a global, decentralized platform for computation", "Because it is huge", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
