import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_ethicalhacking_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Ethical Hacking'?", "options": ["Breaking into computers for fun", "Authorized, structured attempt to identify security weaknesses", "Stealing sensitive data", "None"], "correct": 1},
        {"id": 2, "question": "What is the primary motive of an 'Ethical Hacker'?", "options": ["To gain money", "To check security for improvement", "To cause chaos", "To show off skills only"], "correct": 1},
        {"id": 3, "question": "What is an 'Ethical Hacker' called?", "options": ["Black Hat", "White Hat", "Grey Hat", "Red Hat"], "correct": 1},
        {"id": 4, "question": "What is 'Reconnaissance' in Ethical Hacking?", "options": ["Gaining information about your target", "Identifying vulnerabilities", "Breaking a firewall", "None"], "correct": 0},
        {"id": 5, "question": "What is 'Scanning' in Ethical Hacking?", "options": ["Entering a data center", "The technical enumeration of target information like open ports and services", "A design tool", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Exploitation' in hacking context?", "options": ["Taking advantage of a security hole to gain or expand access", "A business strategy", "None of the above", "None"], "correct": 0},
        {"id": 7, "question": "What is 'Post-Exploitation'?", "options": ["Finding another vulnerability", "Maintaining access and collecting intelligence from the compromised system", "A type of speed test", "None"], "correct": 1},
        {"id": 8, "question": "What is a 'Trojan Horse'?", "options": ["A Greek legend only", "Malicious software that disguises itself as a useful program", "A security software", "None"], "correct": 1},
        {"id": 9, "question": "What is an 'SQL Injection'?", "options": ["Injecting a liquid", "A type of attack where malicious SQL is injected into input data", "A type of table", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Cross-Site Request Forgery' (CSRF)?", "options": ["Signing a document", "An attack that tricks a victim into executing actions on a web application where they are authenticated", "A type of chart", "None"], "correct": 1},
        {"id": 11, "question": "What is the result of 'Brute Force' attack?", "options": ["Attempting to gain access by trying all possible passwords/keys", "A physical attack", "A type of speed test", "None"], "correct": 0},
        {"id": 12, "question": "What is 'DDoS'?", "options": ["Distributed Denial of Service", "Dynamic Data system", "Design of servers", "None"], "correct": 0},
        {"id": 13, "question": "Which tool is commonly used to find open ports and running services?", "options": ["Nmap", "Wireshark", "Metasploit", "All of the above"], "correct": 3},
        {"id": 14, "question": "What is a 'Zero-Day' vulnerability?", "options": ["A vulnerability with zero users", "A security weakness that is unknown to the vendor and has no patch", "A type of server error", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Phishing'?", "options": ["Catching real fish", "An attempt to steal sensitive info by pretending to be a trustworthy source (e.g. email)", "A type of network error", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Social Engineering' in hacking?", "options": ["Designing a new server", "Manipulating people to give up their login credentials or secrets", "A type of database", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Vulnerability'?", "options": ["A type of software", "A weakness in a system that can be exploited by an attacker", "A type of data table", "None"], "correct": 1},
        {"id": 18, "question": "What is an 'Exploit'?", "options": ["Identifying a vulnerability", "Code or a technique used to take advantage of a vulnerability", "A technical specification", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Rooting' or 'Jailbreaking'?", "options": ["Removing the server's battery", "Gaining root access to a device from which a user is restricted", "A type of backup", "None"], "correct": 1},
        {"id": 20, "question": "What is the 'Metasploit Framework'?", "options": ["A framework for graphics", "A popular tool for developing and executing exploit code", "A design tool", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Steganography'?", "options": ["Measuring stars", "Hiding information within another file like an image or audio", "A type of browser", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Keystroke Logging' (Keylogging)?", "options": ["Recording all keys pressed on a keyboard without user knowledge", "Writing a fast code", "A security feature", "None"], "correct": 0},
        {"id": 23, "question": "What is 'Cryptography'?", "options": ["Deleting data", "The science of securing communication by converting data into unreadable format", "None of the above", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Digital Signature'?", "options": ["A name written on paper", "A mathematical technique used to validate the authenticity and integrity of a digital message", "A type of font", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Honey Pot'?", "options": ["A type of delicious food", "A decoy system designed to lure and detect cyber attackers", "A security log", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Malware'?", "options": ["A brand of hardware", "Malicious software (viruses, ransomware, etc.) designed to cause harm", "None of the above", "None"], "correct": 1},
        {"id": 27, "question": "What is an 'IDS'?", "options": ["Intrusion Detection System", "Integrated Data System", "Internal Design Setup", "None"], "correct": 0},
        {"id": 28, "question": "What is an 'Identity Theft'?", "options": ["Assuming another person's name for fun", "Gaining and using another person's personal info for fraud/theft", "A security log", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Bug Bounty'?", "options": ["A program that rewards ethical hackers for finding and reporting vulnerabilities", "A type of computer bug", "Buying bugs for a collection", "None"], "correct": 0},
        {"id": 30, "question": "What is 'CISSP'?", "options": ["A type of internet speed", "A highly respected professional certification for cybersecurity", "A technical specification", "None"], "correct": 1},
        {"id": 31, "question": "What is 'Black Hat' hacker motive?", "options": ["Acting specifically with malicious intent to steal or damage systems", "Fixing code bugs", "Improving security", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Grey Hat' hacker?", "options": ["Hackers specifically who may violate laws but often lack malicious intent", "A designer of hats", "Both", "None"], "correct": 0},
        {"id": 33, "question": "What's 'Banner Grabbing' used for?", "options": ["Identifying service names specifically and versions running on open ports", "Taking a poster from a wall", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Footprinting' in Ethical Hacking?", "options": ["Gaining as much info specifically about a target's network or infrastructure", "Measuring foot size", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents specific 'Passive Reconnaissance'?", "options": ["Information gathering specifically without direct interaction with the target", "Watching a person", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents specific 'Active Reconnaissance'?", "options": ["Information gathering specifically through direct interaction with target (e.g. scanning)", "Direct talk", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'OS Fingerprinting'?", "options": ["Determining the operating system specifically of a target by analyzing responses", "Taking fingerprints from a PC", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What's 'Burp Suite' primarily for?", "options": ["Web application security testing specifically to find vulnerabilities", "Cleaning a database", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What's 'Wireshark' role in hacking?", "options": ["Capturing and specifically analyzing network traffic at a low level", "Identifying sharks", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What represents 'Packet Sniffing'?", "options": ["Monitoring data packets specifically passing over a network to capture info", "Smelling a package", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What represents specific 'Privilege Escalation'?", "options": ["Gaining higher level of access specifically than originally intended on a system", "Getting a job promotion", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Credential Stuffing' attack?", "options": ["Using stolen usernames specifically and passwords on multiple sites automatically", "Putting paper in a box", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Session Hijacking'?", "options": ["Stealing a user's session token specifically to impersonate them", "Closing a laptop", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's the meaning of 'Payload'?", "options": ["The part of an exploit specifically that performs the actual malicious action", "The price for a job", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Shell' in hacking context?", "options": ["A command-line interface specifically gained on a target for remote control", "A sea shell", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Backdoor' significance?", "options": ["A hidden method specifically to bypass normal authentication in a system", "The rear exit of a house", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What represents 'Ransomware'?", "options": ["Malware that encrypts specifically files and demands payment for the key", "A types of news", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Spyware' specifically?", "options": ["Software designed specifically to secretly monitor user actions and data", "A secret agent", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What represents specific 'Adware'?", "options": ["Software that displays specifically unwanted advertisements to the user", "Drawing tool", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Rootkit' specifically?", "options": ["Malware hidden specifically in the core of an OS to gain full control", "A set of plants", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Botnet' significance?", "options": ["A networkspecifically of infected computers controlled for coordinated attacks", "A group of robots", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's the meaning of 'Man-in-the-Middle' (MITM)?", "options": ["An attacker who interceps specifically and alters communication between parties", "A social talk", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Vishing' attack?", "options": ["Phishing attack specifically carried out over voice calls or VoIP", "A types of vision", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's 'Smishing' significance?", "options": ["Phishing attack specifically carried out via SMS text messages", "A small bug", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Whaling' in fishing context?", "options": ["Phishing attack specifically targeting powerful executives in an organization", "Catching big fish", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What represents 'Spear Phishing'?", "options": ["Highly targeted phishing specifically aimed at a specific person or company", "Fishing with a spear", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Eavesdropping' on a network?", "options": ["Illegally listening in specifically on private communication channels", "Listening to a door", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What represents 'WPA2' vs 'WPA3' for Wi-Fi?", "options": ["WPA3 is the latest specifically and more secure standard for wireless", "WPA2 is faster", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Bluejacking' incident?", "options": ["Sending unsolicited specifically messages to a device via Bluetooth", "Stealing a blue car", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What represents 'Bluesnarfing'?", "options": ["Unauthorized access to info specifically on a device via Bluetooth", "A blue character", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What's the effect of 'Worm' malware?", "options": ["Self-replicating malware specifically that spreads across networks without help", "A types of insect", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Payload' for an exploit?", "options": ["The actual code or script specifically executed on target after successful exploit", "The money for a shipment", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'Penetration Testing' (Pen-test)?", "options": ["Controlled simulation specifically of a cyberattack to find security gaps", "A types of desk test", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Vulnerability Assessment'?", "options": ["Scanning and identifying specifically security weaknesses without exploiting them", "Judging a person", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's 'Social Engineering Toolkit' (SET)?", "options": ["A framework specifically designed to perform advanced social engineering attacks", "A types of dictionary", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'John the Ripper' tool?", "options": ["A fast and powerful specifically password auditing and password cracking tool", "A types of historical person", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents 'Hydra' tool in hacking?", "options": ["A fast network specifically logon cracker for many protocols like SSH, HTTP", "A types of monster", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Rainbow Table' in password cracking?", "options": ["A precomputed table specifically for reversing cryptographic hash functions", "A colorful art table", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's the meaning of 'Salting' in hashing?", "options": ["Adding random data specifically to hashing process to prevent rainbow attacks", "Putting salt in food", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents 'Hashing' in security?", "options": ["Converting data specifically into a fixed-length string for integrity checks", "Chopping vegetables", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Encryption' vs 'Decryption'?", "options": ["Converting plaintext specifically to ciphertext and back for confidentiality", "Formatting a disk", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents 'HTTPS' certificate?", "options": ["Standard technology specifically for securing an internet connection (SSL/TLS)", "A types of bill", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Compliance' in cybersecurity?", "options": ["Meeting specifically the official security standards and legal requirements", "Following a book", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents 'GDPR' for data privacy?", "options": ["European Union specifically regulation on data protection and privacy", "Giving digital paper", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What represents specific 'IAM'?", "options": ["Identity and Access Management specifically for controlling user permissions", "A name for a person", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Least Privilege' concept?", "options": ["Giving users specifically only the minimum level of access they need", "Giving full power", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What's the purpose of 'Security Policy'?", "options": ["Set of rules specifically that define organizational security strategy", "A types of insurance", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Incident Response' plan?", "options": ["Detailed instructions specifically on how to react to security breaches/attacks", "Answering a phone", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents 'Certified Ethical Hacker' (CEH)?", "options": ["A professional specifically qualification for demonstrating hacking skills", "A types of driver license", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Ethical Hacking essential for security?", "options": ["Proactively finding specifically and fixing security gaps before attackers do", "Because it is cheaper", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
