import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_etlpipes_api(request):
    questions_pool = [
        {"id": 1, "question": "What does 'ETL' stand for in data engineering?", "options": ["Extract, Transform, Load", "Extra Task Logic", "Every Task Lead", "None"], "correct": 0},
        {"id": 2, "question": "What is 'Extract' in ETL context?", "options": ["Removing bad data", "Fetching data from various source systems across the organization", "A type of database", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Transform' in ETL context?", "options": ["Changing the data format", "Cleaning and structuring data into a suitable format for analysis", "Both A and B", "Neither"], "correct": 2},
        {"id": 4, "question": "What is 'Load' in ETL context?", "options": ["Running a computer program", "Storing the transformed data into a final target like a data warehouse", "A design tool", "None"], "correct": 1},
        {"id": 5, "question": "What is a 'Data Warehouse'?", "options": ["A physical warehouse for disks", "A central repository for integrated data from multiple sources", "A type of table", "None"], "correct": 1},
        {"id": 6, "question": "What is a 'Data Lake'?", "options": ["A lake with data centers", "A large repository of raw data in its native format until needed", "A security log", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Data Pipeline'?", "options": ["A physical pipe in a data center", "The sequence of processes that moves data from source to target", "A tech spec", "None"], "correct": 1},
        {"id": 8, "question": "What is 'ELT' (Extract, Load, Transform)?", "options": ["The same as ETL", "A process where data is loaded into the target first and then transformed", "A decorative part of code", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Snowflake' in data context?", "options": ["A piece of ice", "A popular cloud-based data platform and warehouse service", "A design tool", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Apache Airflow' used for?", "options": ["Monitoring air quality", "Workflow automation and scheduling for data engineering pipelines", "A technical specification", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Data Cleaning'?", "options": ["Wiping physical servers", "The process of identifying and correcting errors/inconsistencies in data", "Both A and B", "Neither"], "correct": 1},
        {"id": 12, "question": "What is 'Data Integrity' in ETL context?", "options": ["Accurate, complete, and reliable data throughout the process", "Changing data and file types", "None", "None"], "correct": 0},
        {"id": 13, "question": "What is 'Delta Loading'?", "options": ["Loading only the newly added or updated data from a source", "Loading all data every time", "A type of table", "None"], "correct": 0},
        {"id": 14, "question": "What is 'Full Load' in ETL?", "options": ["Loading the entire dataset from source to target every time", "Loading only changed data", "A tech spec", "None"], "correct": 0},
        {"id": 15, "question": "What is 'Schema Drift'?", "options": ["A type of design concept", "When the source system's schema changes unexpectedly, potentially breaking the pipeline", "None of the above", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Data Validation'?", "options": ["Confirming user identity", "Verifying the accuracy and quality of data after transform/load", "A security log", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Staging Area' for ETL?", "options": ["A place for actors", "A temporary storage area used between source systems and data warehouse", "A design tool", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Apache Spark' commonly used for in ETL?", "options": ["Processing large-scale datasets in parallel", "Designing icons", "None", "None"], "correct": 0},
        {"id": 19, "question": "What is 'dbt' (data build tool)?", "options": ["A design tool", "A development framework that simplifies transforming data in a warehouse using SQL", "A tech spec", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Metadata' in data engineering?", "options": ["A type of data about data (e.g. source system, load time)", "Information on users", "None of the above", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Data Orchestration'?", "options": ["Directing a musical event", "Coordinating and managing end-to-end data pipelines with dependencies", "None of the above", "None"], "correct": 1},
        {"id": 22, "question": "What's the meaning of 'Data Governance'?", "options": ["Principles used to manage and ensure high quality and security of data", "Deleting all data", "Starting a database", "None"], "correct": 0},
        {"id": 23, "question": "What is 'Real-time ETL' (Streaming ETL)?", "options": ["Fetching and processing data continuously as it is generated", "Doing it all once a month", "Both A and B", "Neither"], "correct": 0},
        {"id": 24, "question": "What is 'Batch ETL'?", "options": ["Loading data at scheduled intervals (e.g. daily, weekly)", "Doing it in real-time", "None", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Change Data Capture' (CDC)?", "options": ["Catching a virus", "A technique used to monitor and capture changed data from source systems", "A security log", "None"], "correct": 1},
        {"id": 26, "question": "Which of these is a popular cloud-based ETL service?", "options": ["AWS Glue", "Azure Data Factory", "Google Cloud Dataflow", "All of the above"], "correct": 3},
        {"id": 27, "question": "What is 'Normalization' primarily used for?", "options": ["Increasing data duplication", "Reducing redundancy and improving database design", "Sorting a list", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Denormalization' for data warehouses?", "options": ["Decreasing data speed", "Adding redundancy back for faster read performance during analysis", "A technical specification", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Data Catalog'?", "options": ["A shopping list", "A searchable directory that helps users find and understand datasets", "A decorative part of code", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Data Engineering' primarily?", "options": ["Analyzing data and making predictions", "Building and maintaining the systems that collect and process data", "Designing UI only", "None"], "correct": 1},
        {"id": 31, "question": "What is 'Schema' specifically?", "options": ["The structure specifically that defines how data is organized in a database", "A list of strings", "A types of math", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Star Schema' in data warehousing?", "options": ["A types of drawing", "A data model specifically where a central fact table is surrounded by dimension tables", "Neither", "Both"], "correct": 1},
        {"id": 33, "question": "What is 'Snowflake Schema'?", "options": ["An extension specifically of a star schema with more normalized dimension tables", "A types of ice", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the meaning of 'Fact Table'?", "options": ["Table containing specifically quantitative information for analysis (e.g. sales)", "A table of truths", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What's the meaning of 'Dimension Table'?", "options": ["Table containing specifically descriptive attributes (e.g. products, customers)", "A types of graph", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Granularity' of data?", "options": ["The level specifically of detail or summarization of the data", "Mixing sugar", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'SCD' (Slowly Changing Dimensions)?", "options": ["Dimensions specifically that change slowly over time (e.g. customer address)", "A fast car", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'SCD Type 1'?", "options": ["Overwriting specifically old data with new data (no history kept)", "Keeping all history", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'SCD Type 2'?", "options": ["Adding a new row specifically for every change to maintain full history", "Deleting all rows", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's the meaning of 'Surrogate Key'?", "options": ["A substitution specifically for a natural key used for identification", "A fake key for a door", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Primary Key' in ETL context?", "options": ["A unique identifier specifically for each record in a table", "The most important key", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Foreign Key'?", "options": ["A field that uniquely identifies specifically a row in another table", "A key from another country", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What represents the 'Mapping' in ETL?", "options": ["A set of logical rules specifically that define how data is transformed", "A types of drawing", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Data Lineage' specifically?", "options": ["The origin specifically and history of data as it moves through pipelines", "Looking at family tree", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Data Quality' specifically?", "options": ["A measure specifically of data accuracy, completeness, and reliability", "Buying good data", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's the effect of 'Data Deduplication'?", "options": ["Removing specifically identical copies of data to save space and improve quality", "Adding more data", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Data Masking'?", "options": ["Hiding sensitive data specifically with proxy data for security", "Wearing a mask", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What represents specific 'Partitioning'?", "options": ["Dividing specifically large tables into smaller parts for performance", "Separating a room", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Big Data' in ETL context?", "options": ["Extremely large specifically and complex data sets (e.g. Petabytes)", "A large font size", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Hadoop' primarily used for?", "options": ["Distributed specifically storage and processing of large data sets", "A digital game", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'HDFS'?", "options": ["Hadoop Distributed File System specifically for storing large files", "High data file system", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's the meaning of 'MapReduce' specifically?", "options": ["Programming model specifically for processing large data in parallel", "Mapping a city", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Apache Kafka' used for?", "options": ["Distributed specifically event streaming platform for real-time pipelines", "Writing books", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What represents the 'NoSQL' database?", "options": ["Non-relational database specifically for flexible data models", "A database without SQL", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents 'Columnar Storage'?", "options": ["Storing data specifically by columns instead of rows to improve read speed", "A types of columns", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'In-memory Processing'?", "options": ["Processing data specifically in RAM for much faster execution", "Using mental math", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's the meaning of 'Data Silo'?", "options": ["Isolated data specifically that is not easily accessible by other parts of org", "A storage for corn", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Data Mesh' architecture?", "options": ["A decentralized specifically data management approach based on domains", "A types of network", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What represents 'Data Fabric'?", "options": ["An architecture specifically aiming to integrate data across diverse platforms", "A types of cloth", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How do you handle Errors in ETL?", "options": ["Logging failures specifically and setting up re-try mechanisms or alerts", "Ignoring them", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What represents 'Backfilling' in pipelines?", "options": ["Running a pipeline specifically for historical dates after a fix or update", "Filling a bag", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Idempotency' in data pipelines?", "options": ["Ensuring specifically that running a pipeline multiple times gives the same result", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What represents the 'DAG' in Airflow?", "options": ["Directed Acyclic Graph specifically to represent task dependencies", "A sharp tool", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Kubernetes' role for ETL?", "options": ["Container orchestration specifically for scaling data processing tasks", "A security tool", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's the meaning of 'Parquet' or 'ORC'?", "options": ["Optimized columnar file formats specifically for big data storage", "Types of wooden floors", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents 'Avro' format?", "options": ["A row-based specifically data serialization system for Hadoop", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents 'CSV' in ETL context?", "options": ["Comma-separated values specifically used as a simple data transfer format", "Computer system version", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents 'JSON' data?", "options": ["JavaScript Object Notation specifically used for semi-structured data", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'XML' role?", "options": ["Extensible Markup Language specifically used for data representation", "A types of music", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents 'SQL' in data engineering?", "options": ["Standard language specifically for managing and querying databases", "A routing name", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What represents 'Pandas' in Python?", "options": ["A library for specifically data manipulation and analysis", "A types of animal", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents 'NumPy'?", "options": ["A library for specifically numerical computing in Python", "A types of numbers", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Dask' useful for?", "options": ["Parallel computing specifically with Python for large datasets", "A types of desk", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents the 'Redshift' in AWS?", "options": ["A fully managed cloud specifically data warehouse service", "A types of light", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What represents 'BigQuery' in Google Cloud?", "options": ["Serverless data warehouse specifically for large-scale analysis", "A big question", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents specific 'Synapse' in Azure?", "options": ["Analytics service specifically bringing together data warehousing and big data", "Part of a brain", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What's 'Data Observability'?", "options": ["Monitoring specifically data health and pipeline performance in real-time", "Watching a screen", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents 'DevOps' for Data (DataOps)?", "options": ["Automating and specifically improving quality of data analytics development", "Being a developer", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What's the meaning of 'Cloud-Native' ETL?", "options": ["Building pipelines specifically designed for cloud environments", "Using a physical cloud", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is ETL important for business decision making?", "options": ["Providing specifically high-quality and integrated data for accurate analysis", "Because it uses more RAM", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
