import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_excel_api(request):
    questions_pool = [
        {"id": 1, "question": "What is MS Excel?", "options": ["A word processor", "A spreadsheet application specifically for calculations, analysis and visualization", "A types of TV", "None"], "correct": 1},
        {"id": 2, "question": "What is the file extension for MS Excel?", "options": [".xlsx", ".xls", ".csv", "All of the above"], "correct": 3},
        {"id": 3, "question": "What is a 'Worksheet'?", "options": ["A single page/tab in an Excel file", "The whole physical file", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is a 'Workbook'?", "options": ["The entire Excel file specifically containing one or more worksheets", "A single page of Excel only", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is a 'Cell'?", "options": ["A room for prisoners", "The intersection specifically of a row and a column for data entry", "Neither", "Both"], "correct": 1},
        {"id": 6, "question": "What is 'Row' in Excel?", "options": ["The horizontal part of a worksheet (identified by numbers)", "Vertical part of a worksheet", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'Column' in Excel?", "options": ["The vertical part specifically of a worksheet (identified by letters)", "Horizontal part of a worksheet", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Cell Address' (e.g. A1)?", "options": ["Combination of column letter and row number for a specific cell", "A physical home address", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is a 'Range'?", "options": ["A group specifically of two or more selected cells (e.g. A1:B10)", "A mountain range", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is a 'Formula'?", "options": ["A types of equation", "A mathematical expression starting with '=' specifically for calculating values", "Both", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Function' (e.g. SUM, AVG)?", "options": ["A types of math equation only", "A pre-defined shortcut specifically to perform common calculations", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'AutoSum'?", "options": ["Automatically adding up numbers specifically in a selected range of cells", "Calculating math with a pen", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Sort and Filter' for?", "options": ["Organizing data specifically by criteria or hiding specific parts", "Cleaning food", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Pivot Table' significance?", "options": ["Summarizing and analyzing very large amounts of data dynamically", "A table in an office", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Chart' / 'Graph' in Excel?", "options": ["Visual representation specifically of data for easier analysis", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What's 'VLOOKUP' significance?", "options": ["Searching for a specific value in a table and returning data from same row", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What's 'Absolute Reference' ($A$1)?", "options": ["Fixing a cell reference that doesn't change when copied to others", "A reference for a person", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What's 'Relative Reference' (A1)?", "options": ["A cell reference that changes automatically when copied to others", "A primary reference", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Active Cell'?", "options": ["The cell you are currently specifically typing in (with green border)", "A types of battery", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Formula Bar' significance?", "options": ["The area specifically at the top to enter and edit formulas and data", "A bar for drinking", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Fill Handle'?", "options": ["The small green square specifically used to copy/extend data or patterns", "Drawing a box", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What's the 'Error' starting with # in Excel?", "options": ["Indicates something is wrong with a formula or data (e.g. #VALUE!)", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "How to save a file quickly?", "options": ["Ctrl + S", "Ctrl + X", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'Conditional Formatting'?", "options": ["Changing cell appearance specifically based on conditions (e.g. color if < 0)", "A styles of text", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Merge and Center'?", "options": ["Combining two or more cells and centering the text horizontally", "Deleting everything", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What's 'Wrap Text' significance?", "options": ["Fitting long text into a single cell specifically by increasing row height", "Covering food", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Freeze Panes' function?", "options": ["Keeping specific rows/columns visible specifically while scrolling through sheet", "Freezing food in office", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Template' in Excel context?", "options": ["Pre-designed worksheets specifically for common tasks (Budget, Inventory)", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's 'Export as PDF' used for?", "options": ["Saving a static copy of a worksheet specifically for easy sharing", "Making it faster", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Who created MS Excel?", "options": ["Microsoft", "Google", "Apple", "Oracle"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'IF' function in Excel?", "options": ["Returns different values specifically based on a condition being true or false", "Starting a program", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'AVERAGE' function?", "options": ["Calculating the mean value specifically for a set of numbers", "Finding a center", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'COUNT' function?", "options": ["Counting how many cells in a range specifically contain numbers", "Starting points", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'COUNTA' function?", "options": ["Counting how many cells in a range are NOT empty (text/numbers/etc.)", "Counting a game score", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'MAX' and 'MIN' functions?", "options": ["Finding the highest and lowest values in a selected range", "Searching for a name", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What's 'HLOOKUP' vs 'VLOOKUP'?", "options": ["Horizontal vs Vertical searching for values in tables", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Concatenate' (or textjoin)?", "options": ["Joining two or more pieces of text together specifically into one cell", "Sharing files", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Flash Fill' tool?", "options": ["Automatically filling data specifically by detecting patterns after a few examples", "Filling a car", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What's 'Data Validation' feature?", "options": ["Restricting what type of data can be entered into a specific cell", "Validating math", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's 'Data Table' used for?", "options": ["Creating a table and observing results of changing variables (Scenario)", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Goal Seek' in Excel?", "options": ["Finding the starting input value specifically to reach a desired end goal result", "A types of game", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's 'Solver' tool significance?", "options": ["Advanced tool specifically for finding optimal solutions for complex problems", "A person who solves", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Named Range'?", "options": ["Giving a custom name specifically for a group of cells for easier formula writing", "A name for a person", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Macro' significance in Excel?", "options": ["Automating repetitive tasks explicitly through recorded scripts (VBA)", "Small computer parts", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'VBA' (Visual Basic for Applications)?", "options": ["The programming language used to write macros and automation in Excel", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Add-In' used for in Excel?", "options": ["Extending Excel's built-in features by installing third-party tools", "A styles of text", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "How to select all cells in a sheet?", "options": ["Ctrl + A", "Ctrl + S", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "How to insert a new row?", "options": ["Right-click on row number -> Insert", "Triple-click on cell", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "How to delete a column?", "options": ["Right-click on column letter -> Delete", "Pressing backspace only", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Hide/Unhide' rows or columns?", "options": ["Temporarily removing them from view specifically without deleting data", "Moving things back", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What's the meaning of 'Gridlines'?", "options": ["The gray horizontal and vertical lines defining cell boundaries", "A types of bridge", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's the effect of 'Ruler' view in Excel?", "options": ["Measuring and aligning worksheet objects on the screen", "Measuring roads", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "How do you view two parts of a large sheet at once?", "options": ["Using the 'Split' feature or 'New Window'", "Using two monitors", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'Cell Style' (e.g. Heading, Normal)?", "options": ["Applying consistent fonts and colors to cells for professional look", "A types of clothes", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Cell border' vs 'Gridlines'?", "options": ["Custom black frames around cells specifically vs global gray boundaries", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "How to clear contents of a cell quickly?", "options": ["Pressing 'Delete' key on keyboard", "Deleting the whole row", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "How to clear all formatting of a cell?", "options": ["Home -> Clear (Eraser icon) -> Clear Formats", "Deleting the cell", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Find' shortcut?", "options": ["Ctrl + F", "Ctrl + S", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Replace' shortcut?", "options": ["Ctrl + H", "Ctrl + J", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's 'Auto-Refresh' specifically for Pivot Tables?", "options": ["Updating the summary specifically after data in the source table has changed", "Cleaning the computer", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Slicer' in Pivot Tables?", "options": ["A types of knife", "An easy-to-use visual tool specifically for filtering pivot table data", "Neither", "Both"], "correct": 1},
        {"id": 62, "question": "What is 'Timeline' specifically for data?", "options": ["A visual filter specifically for sorting data based on dates/times", "A history book", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Data Series' in a chart?", "options": ["A related set of data points specifically used to build a chart", "A video series", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Legend' in a chart context?", "options": ["The key explaining what different colors/shapes represent on the graph", "A famous story", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What represents the 'X-axis' and 'Y-axis'?", "options": ["Horizontal and Vertical dimensions specifically of a 2D chart", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "How to add a secondary axis in a chart?", "options": ["Right-click data series -> Format -> Secondary Axis", "Drawing it manually", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Trendline' used for?", "options": ["A line specifically to visually show the overall direction of data overtime", "A types of clothes", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's the meaning of 'Format Cells' (Ctrl+1)?", "options": ["Deep settings for font, border, alignment and number formats of a cell", "Deleting a cell", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'Number Format' (Currency, Date, Percentage)?", "options": ["Tells Excel how to display and treat raw numerical data", "Styles of writing", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "How to enter a new line inside a single cell?", "options": ["Alt + Enter", "Ctrl + Enter", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "How to hide a worksheet tab?", "options": ["Right-click worksheet name -> Hide", "Deleting the worksheet", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's the meaning of 'Sheet Protection'?", "options": ["Locking some or all cells so users can't accidentally change data", "A roof for a sheet", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "Can you share an Excel file through Cloud (OneDrive)?", "options": ["Yes, multiple people can edit the same sheet in real-time online", "No", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Auto-Save' specifically for Office 365?", "options": ["Automatically saving every few seconds to prevent work loss online", "Saving once a day", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "Which constant is used for 'Undo' in Excel?", "options": ["Ctrl + Z", "Ctrl + Y", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Which constant is used for 'Redo'?", "options": ["Ctrl + Y", "Ctrl + R", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Zoom control' for?", "options": ["Adjusting the worksheet view size quickly while editing", "Fast speed in car", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Print Area' feature?", "options": ["Choosing only a specific part of the worksheet to be printed", "A types of paper", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "How can you view formulas instead of values in every cell?", "options": ["Ctrl + ` (Backtick)", "Ctrl + F", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary benefit of MS Excel?", "options": ["Providing powerful tools for advanced data analysis and organization effortlessly", "Having more TV channels", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
