import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_flutterreactnative_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Flutter'?", "options": ["A JavaScript library", "Google's UI toolkit for building natively compiled mobile/web/desktop apps", "A mobile OS", "None"], "correct": 1},
        {"id": 2, "question": "What is 'React Native'?", "options": ["A framework for web only", "Meta's framework to build mobile apps using React and JavaScript", "A type of table", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Cross-platform' development?", "options": ["Building apps for one platform only", "Building apps using a single codebase that runs on multiple platforms (iOS, Android)", "Developing for different regions", "None"], "correct": 1},
        {"id": 4, "question": "What is the primary language used in Flutter?", "options": ["Java", "Kotlin", "Dart", "Swift"], "correct": 2},
        {"id": 5, "question": "What is 'Hot Reload'?", "options": ["A computer heating problem", "A feature that allows developers to see code changes instantly without restarting the app", "A design tool", "None"], "correct": 1},
        {"id": 6, "question": "In React Native, what is 'JSX'?", "options": ["A type of video file", "A syntax extension for JavaScript that looks like HTML", "A database engine", "None"], "correct": 1},
        {"id": 7, "question": "What is a 'Widget' in Flutter?", "options": ["A physical component", "The basic building block for every part of the Flutter UI", "A type of chart", "None"], "correct": 1},
        {"id": 8, "question": "In React Native, what is 'Props' (Properties)?", "options": ["Background colors", "Arguments passed into components for customization", "A list of strings", "None"], "correct": 1},
        {"id": 9, "question": "What is 'State' in mobile app context?", "options": ["A country or region", "An object that stores data that can change over time in a component", "A technical specification", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Redux' commonly used for in React Native?", "options": ["A styling tool", "A state management library", "A type of database", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Material Design' in Flutter?", "options": ["Designing the phone Case", "A design language developed by Google specifically for UI", "A type of screen", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Cupertino' in Flutter?", "options": ["A city in California only", "A set of widgets that follow the iOS design guidelines", "A design tool", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Expo' in React Native development?", "options": ["A software exhibition", "A framework and a platform for universal React applications", "A database connector", "None"], "correct": 1},
        {"id": 14, "question": "What does a '.apk' file represent for Android?", "options": ["A document", "Android Package Kit (the installer for Android apps)", "A type of image", "None"], "correct": 1},
        {"id": 15, "question": "What does an '.ipa' file represent for iOS?", "options": ["iOS App Store Package (installer for iOS apps)", "A type of video", "A technical manual", "None"], "correct": 0},
        {"id": 16, "question": "What is 'Native Module' in cross-platform development?", "options": ["Writing raw assembly", "Writing platform-specific code (Java/Swift) to extend framework functionality", "A built-in component", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Virtual DOM' in React context?", "options": ["A fake website", "A lightweight copy of the actual DOM for efficient UI updates", "A type of backup", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Flexbox' in React Native?", "options": ["A flexible box for data", "A layout engine used to design flexible UI structures", "A design tool", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Pub.dev' in Flutter ecosystem?", "options": ["A social network for developers", "The official package repository for Dart and Flutter packages", "A news site", "None"], "correct": 1},
        {"id": 20, "question": "What is 'NPM' in React Native ecosystem?", "options": ["Node Package Manager (for managing dependencies)", "New Phone Media", "None of the above", "None"], "correct": 0},
        {"id": 21, "question": "How do you style components in React Native?", "options": ["Using CSS", "Using StyleSheet.create() (resembles CSS properties)", "Adding raw HTML tags", "None"], "correct": 1},
        {"id": 22, "question": "What is 'StatefulWidget' in Flutter?", "options": ["A widget that never changes", "A widget that has mutable state", "A type of screen", "None"], "correct": 1},
        {"id": 23, "question": "What is 'StatelessWidget' in Flutter?", "options": ["A widget that can change", "A widget that does not require mutable state", "None of the above", "None"], "correct": 1},
        {"id": 24, "question": "Which command-line tool is used for building and testing Flutter apps?", "options": ["flutter cli", "flutter doctor / flutter run", "flutter go", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Bridge' in React Native architecture?", "options": ["Building a physical connection", "A communication layer between JavaScript and Native modules", "A security feature", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Firebase' commonly used for in mobile apps?", "options": ["A real-time database, authentication, and hosting by Google", "Designing UI only", "None of the above", "None"], "correct": 0},
        {"id": 27, "question": "What is 'App Store Connect' for iOS?", "options": ["Connecting to the internet on iPhone", "A suite of web-based tools to manage apps sold on the App Store", "None", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Google Play Console' for Android?", "options": ["A game console by Google", "A platform for releasing and managing Android apps on the Google Play Store", "A type of browser", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Responsive Design'?", "options": ["Fast design", "Building apps that automatically adapt UI for different screen sizes", "A design color", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Debugging' in mobile development?", "options": ["Eliminating bugs in software using tools like Flutter DevTools or Chrome Debugger", "Starting an app", "A technical specification", "None"], "correct": 0},
        {"id": 31, "question": "Which constant is used for 'Main()' in Flutter?", "options": ["The entry point specifically for every Flutter application", "Starting a car", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'RunApp()' function in Flutter?", "options": ["Starting specifically the root widget of the application", "Running a script", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Scaffold' widget in Flutter?", "options": ["A layout structure specifically for basic visual app elements like appBar and body", "A construction tool", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'AppBar' in Flutter?", "options": ["A toolbar specifically at the top of the screen", "A drink bar", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents the 'FloatingActionButton'?", "options": ["A circular button specifically that hovers over content to promote primary action", "A floating boat", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Navigator' in Flutter?", "options": ["A widget specifically managing a stack of app screens (routes)", "A GPS tool", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "In React Native, what is 'View' component?", "options": ["The most fundamental component specifically for building UI, like a div in web", "A scenic view", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "In React Native, what is 'Text' component?", "options": ["Component specifically for displaying text on the screen", "Writing a letter", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "In React Native, what is 'Image' component?", "options": ["Component specifically to display different types of images", "A photo album", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'ScrollView' in React Native?", "options": ["A component specifically as a scrolling container for multiple components", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'FlatList' in React Native?", "options": ["Efficient way specifically to render large lists of data dynamically", "A physical list of items", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "In Flutter, what is 'setState()'?", "options": ["Method specifically used to notify the framework that internal state has changed", "Changing countries", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "In Flutter, what is 'Provider' pattern?", "options": ["A wrapper specifically around InheritedWidget to manage state efficiently", "Providing a service", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Riverpod' in Flutter context?", "options": ["A modern state management library specifically for Flutter and Dart", "A types of fruit", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'BLoC' (Business Logic Component)?", "options": ["A design pattern specifically used to separate business logic from UI in Flutter", "A types of toy block", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'MobX' in mobile state management?", "options": ["A library specifically making state management simple using observable data", "A mobile phone company", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'AsyncStorage' in React Native?", "options": ["A simple, unencrypted, asynchronous, persistent, key-value storage system", "Storing files online", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Shared Preferences' in Flutter (via plugin)?", "options": ["Persistent storage specifically for simple data across app restarts", "Sharing a room", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's the meaning of 'NavigationContainer' in React Native?", "options": ["The root component specifically for managing navigation state and history", "A container on a ship", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Stack Navigator' in React Navigation?", "options": ["Provides specifically a way for your app to transition between screens", "A stack of books", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Tab Navigator'?", "options": ["Navigation specifically via icons/text at the bottom or top of the screen", "A tab in a browser", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Drawer Navigator'?", "options": ["Navigation specifically via a side menu that slides in and out", "A kitchen drawer", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "How can you debug Flutter app UI?", "options": ["Using the Widget Inspector in Flutter DevTools", "Looking at a screen", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'LogBox' in React Native?", "options": ["An on-screen display specifically for errors and warnings in the app", "A wooden box for logs", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents specific 'Asset' in app code?", "options": ["Bundled files specifically like images, fonts, and icons inside the app package", "A house or car", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Pubspec.yaml' significance?", "options": ["The metadata file specifically for Flutter projects including dependencies and assets", "A regular text file", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What represents the 'Package.json'?", "options": ["The metadata file specifically for React Native projects including dependencies", "A types of box", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'AOT' (Ahead-of-Time) compilation in Flutter?", "options": ["Compiling code specifically to native machine code before execution for performance", "Compiling after run", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'JIT' (Just-in-Time) compilation for dev?", "options": ["Compiling code specifically on the fly during development (allows hot reload)", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How can you create a custom widget in Flutter?", "options": ["By creating a new class specifically that extends StatelessWidget or StatefulWidget", "Drawing on paper", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What's the effect of 'Key' in Flutter widgets?", "options": ["Identifying widgets specifically uniquely across rebuilds to maintain state", "A key for a lock", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'Safe Area' significance in mobile UI?", "options": ["Ensuring UI specifically doesn't overlap with system notches, status bars", "A safe room", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'SafeArea' widget in Flutter?", "options": ["A widget that automatically adds padding specifically to avoid system UI overlays", "A security feature", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'StyleSheet' in React Native?", "options": ["An abstraction specifically similar to CSS Style Sheets for component design", "A sheet of paper", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "How to handle user clicks in React Native?", "options": ["Using TouchableOpacity specifically or Pressable components", "Using a mouse", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "How to handle user taps in Flutter?", "options": ["GestureDetector specifically or InkWell widgets", "Touching a wall", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents 'Native Modules'?", "options": ["Platform-specific code (Java/Swift) specifically connected to the framework", "A built-in tool", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents 'Platform.OS' in React Native?", "options": ["Detecting specifically whether the app is running on iOS or Android", "The operating system only", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "Which of these is a major advantage of Flutter?", "options": ["Single codebase, high performance, and beautiful rich UI", "It has more colors", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's the meaning of 'Code Push' in mobile apps?", "options": ["Pushing code updates specifically directly to users without App Store review", "Pushing a button", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Which constant is used for 'Build()' method in Flutter?", "options": ["The method specifically where you define your widget's UI structure", "Building a house", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents the 'Context' in Flutter?", "options": ["A handle specifically to the location of a widget in the widget tree", "A book's content", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents specific 'Module' in React Native?", "options": ["A self-contained piece specifically of functionality (like a screen or component)", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents 'Metro' in React Native?", "options": ["The JavaScript bundler specifically for React Native apps", "A fast train", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Debugger' usefulness for mobile apps?", "options": ["Inspecting variables specifically and execution flow to fix bugs", "A pest control", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What's 'Unit Testing' in mobile context?", "options": ["Testing individual functions specifically or logic components", "Testing a single room", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents 'Widget Testing' in Flutter?", "options": ["Testing specifically UI components in isolation", "Testing a small tool", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents the 'Integration Testing'?", "options": ["Testing how specifically different parts of the app work together as a whole", "Testing the internet", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "How many apps can you build with one Flutter codebase?", "options": ["Many (iOS, Android, Web, Desktop)", "Only one", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why use cross-platform frameworks for business?", "options": ["Reduces development time and cost specifically by sharing a single codebase", "It's a newer trend", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
