import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_generativeai_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Generative AI?", "options": ["AI that generates power", "AI capable of creating new content like text, images, or music", "A very old version of AI", "None"], "correct": 1},
        {"id": 2, "question": "What is an 'LLM' (Large Language Model)?", "options": ["A huge text file", "AI trained on vast amounts of text to understand and generate human-like language", "A long math problem", "None"], "correct": 1},
        {"id": 3, "question": "What is 'ChatGPT'?", "options": ["A person who likes to chat", "A popular AI chatbot developed by OpenAI in late 2022", "A hardware component", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Prompt Engineering'?", "options": ["Building a physical bridge", "The process of designing and refining input prompts to get better results from AI", "A design tool", "None"], "correct": 1},
        {"id": 5, "question": "What does GPT stand for?", "options": ["Generative Pre-trained Transformer", "General Purpose Tool", "Global Positioning Tool", "None"], "correct": 0},
        {"id": 6, "question": "What is 'Hallucination' in the context of LLMs?", "options": ["A health problem", "When an AI model generates factually incorrect or nonsensical information convincingly", "A type of screen glitch", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Fine-tuning' for LLMs?", "options": ["Moving a computer", "Slightly training a pre-trained model on a smaller, specific dataset to improve its performance", "A security feature", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Attention Mechanism' (Self-attention)?", "options": ["A help guide", "A technique that allows a model to weigh the importance of different parts of input data", "A type of chart", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Zero-shot Learning'?", "options": ["A model with zero data", "A model making a prediction on a task it was not specifically trained for", "A type of sorting", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Few-shot Learning'?", "options": ["A model with all the data", "A model making a prediction with only a few examples in the prompt", "A type of backup", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Diffusion Model' primarily used for?", "options": ["Image generation (like Stable Diffusion)", "NLP", "Sound processing", "None"], "correct": 0},
        {"id": 12, "question": "What is 'OpenAI'?", "options": ["A person who likes code", "A leading AI research and deployment company behind GPT", "A type of hardware", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Parameters' in an LLM context?", "options": ["The length of code", "The internal variables a model learns (e.g. GPT-3 has 175 billion)", "A type of server name", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Context Window'?", "options": ["A window in a computer app", "The maximum amount of text an LLM can 'look at' during a single prompt", "A security log", "None"], "correct": 1},
        {"id": 15, "question": "Which of these is a popular generative AI tool for images?", "options": ["DALL-E", "Midjourney", "Stable Diffusion", "All of the above"], "correct": 3},
        {"id": 16, "question": "What is 'Multimodal AI'?", "options": ["AI with only one mode", "AI capable of processing and generating data from different sources (text, image, audio)", "A type of server", "None"], "correct": 1},
        {"id": 17, "question": "What is 'API' (Application Programming Interface) for LLMs?", "options": ["A list of users", "A way for developers to integrate LLM features into their own apps", "A technical manual", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Token' in an LLM?", "options": ["A physical coin", "Small chunks of text that a model processes instead of individual words", "A security password", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Auto-regressive' generation?", "options": ["Generating the next word based on all previous words", "A type of sorting", "A mathematical regression", "None"], "correct": 0},
        {"id": 20, "question": "What is 'Reinforcement Learning from Human Feedback' (RLHF)?", "options": ["A way to train AI by manually correcting code", "Fine-tuning models based on human preferences for safety and quality", "None of the above", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Transformer' architecture derived from?", "options": ["Attention Is All You Need (paper)", "Attention only needs a few things", "AI Is All You Need", "None"], "correct": 0},
        {"id": 22, "question": "What is 'DALL-E' known for?", "options": ["Text to video", "Text to image generation", "Coding help", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Claude'?", "options": ["A person's name", "An AI model developed by Anthropic", "A database engine", "None"], "correct": 1},
        {"id": 24, "question": "What is 'LLama'?", "options": ["An animal only", "An open-source LLM developed by Meta (Facebook)", "A type of game", "None"], "correct": 1},
        {"id": 25, "question": "What is 'In-context Learning'?", "options": ["Learning in a new school", "The ability of an LLM to learn a task from instructions and examples provided in its prompt", "A type of backup", "None"], "correct": 1},
        {"id": 26, "question": "What does a 'Temperature' setting in LLMs do?", "options": ["Measures server heat", "Controls the randomness/creativity of generated output", "A type of formatting", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Ethical AI' for generative models?", "options": ["Correcting syntax errors", "Principles to reduce bias, prevent harmful content, and respect copyright", "Increased internet speed", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Code Generation'?", "options": ["Writing raw C code", "Automatically creating or suggesting code based on natural language prompts", "Starting a database", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Chain-of-thought' prompting?", "options": ["A series of thoughts", "Encouraging a model to break down its reasoning into logical steps", "A security feature", "None"], "correct": 1},
        {"id": 30, "question": "What is 'General AI' (AGI) hypothetical goal?", "options": ["AI that can only play chess", "AI that can perform any intellectual task a human can", "A type of computer screen", "None"], "correct": 1},
        {"id": 31, "question": "What is 'Generative Adversarial Network' (GAN)?", "options": ["Two neural networks specifically competing to create realistic data (like fake faces)", "A network for games", "A types of internet speed", "None"], "correct": 0},
        {"id": 32, "question": "What is 'GPT-4' significance?", "options": ["Successor to GPT-3.5 with greatly improved reasoning and multimodal input", "A text file version 4", "A new type of computer", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Gemini' AI?", "options": ["Google's most capable and general AI model with native multimodality", "A star sign only", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Co-pilot' in programming?", "options": ["An AI assistant specifically that helps users write and optimize code in an IDE", "A person who flies a plane", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Vector Database' (e.g. Pinecone)?", "options": ["Database specifically designed to store and query high-dimensional embeddings", "A database for images only", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What's 'Knowledge Retrieval' (RAG)?", "options": ["Retrieval-Augmented Generation (giving LLMs access to specific external data)", "Filling a quiz", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Stable Diffusion'?", "options": ["Open-source latent text-to-image diffusion model", "A types of chemical lab", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Runway Gen-2' used for?", "options": ["AI-driven text-to-video specifically or video-to-video generation", "A types of sport", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Voice Cloning'?", "options": ["Using AI specifically to reproduce an individual's unique voice from a sample", "Buying a new phone", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Deepfake' significance?", "options": ["Media specifically where a person's likeness is replaced with someone else's using AI", "A deep lake", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What's the meaning of 'Bias' in Generative AI?", "options": ["When an AI model reflects and amplifies existing human prejudices from data", "A diagonal line", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Explainable AI' (XAI)?", "options": ["AI specifically designed to explain its reasoning and outcomes clearly", "AI that talks more", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What represents the 'Prompt'?", "options": ["The text or input specifically given to an AI model to guide its response", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Negative Prompt'?", "options": ["Telling the AI specifically what NOT to include in the generated output", "A rude message", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Latent Space'?", "options": ["A mathematical representation specifically of compressed data features", "Space in an attic", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What represents specific 'Embedding'?", "options": ["Numerical vector representation specifically of content (text/image) in space", "Fixing an image", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Semantic Search'?", "options": ["Searching by meaning specifically rather than just keyword matching", "Searching for a name", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Fine-tuning' vs 'Prompting'?", "options": ["Updating model weights vs giving a specific instruction", "Same thing", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Hyperparameters' in AI?", "options": ["Settings specifically used to control the training process (like learning rate)", "Fast parameters", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Loss Function'?", "options": ["A measure of how well specifically an AI model's predictions match actual data", "Losing a game", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What's 'Backpropagation'?", "options": ["Algorithm specifically for updating weights in a neural network during training", "Propagating plants", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Overfitting'?", "options": ["When a model learns specifically too much detail from training data and fails on new data", "Fitting a dress", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Underfitting'?", "options": ["When a model is specifically too simple to capture patterns in the data", "A small shirt", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What represents 'Foundation Model'?", "options": ["A broad AI model trained on huge data specifically that can be adapted to tasks", "A types of makeup", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Open-source' in AI (e.g. Llama)?", "options": ["Publicly sharing the model's weights specifically for others to use and modify", "Selling code", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What represents the 'Inference'?", "options": ["The process specifically of an AI model making a prediction based on new input", "A suggestion", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Edge AI'?", "options": ["AI models specifically designed to run on-device (like a phone) rather than cloud", "Sharp AI", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's the meaning of 'Context' in LLMs?", "options": ["The information specifically provided to the model in the conversation history", "A textbook", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Top-P' (Nucleus sampling)?", "options": ["A decoding strategy specifically for sampling words based on cumulative prob", "Working at top", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Top-K' sampling?", "options": ["Limiting word choices specifically to the K most probable next words", "Going to top", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What represents 'Synthetic Data'?", "options": ["Data generated specifically by AI to train other AI models", "Plastic data", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'AI Alignment'?", "options": ["Ensuring specifically that AI systems behave in a way that helps humans", "Lining up robots", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'Turing Test'?", "options": ["A test specifically of a machine's ability to exhibit human-like intelligence", "A types of car test", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'PaLM' (Pathways Language Model)?", "options": ["Google's earlier large-scale LLM specifically with high capability", "A palm tree", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'LaMDA'?", "options": ["Google's language model specifically specialized for conversation", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Perplexity' in LLM evaluation?", "options": ["A metric specifically measuring how well a model predicts a sample of text", "Being confused", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What represents 'Constitutional AI'?", "options": ["AI trained specifically with formal rules to ensure safety and alignment", "Government AI", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents 'InstructGPT'?", "options": ["Models specifically fine-tuned to follow specific instructions better", "AI for teaching", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'LoRA' (Low-Rank Adaptation)?", "options": ["Efficient way specifically to fine-tune large models using very few parameters", "A types of flower", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents 'Quantization' in LLM?", "options": ["Reducing specific model size by using lower precision numbers for weights", "Counting things", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Whisper' by OpenAI?", "options": ["High-accuracy automatic speech recognition (ASR) system", "A quiet talk", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents 'Midjourney'?", "options": ["A popular AI service specifically for generating artistic images from text", "A journey on a road", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'Firefly' in Adobe apps?", "options": ["Adobe's generative AI models integrated into design tools like Photoshop", "A types of bug", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents 'Auto-GPT'?", "options": ["An experimental open-source project specifically that makes GPT-4 autonomous", "A self-driving car", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What represents 'BabyAGI'?", "options": ["A types of Python script specifically aimed at building autonomous agents", "A small baby", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "How to reduce hallucinations in LLMs?", "options": ["Using RAG, ground-truth data, and clear prompting specifically", "Buying a new CPU", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Inpainting'?", "options": ["Repairing specifically or filling in parts of an image using AI", "Painting inside a room", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents 'Outpainting'?", "options": ["Expanding specifically an image beyond its original boundaries using AI", "Painting outside", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What represents 'Style Transfer'?", "options": ["Applying the artistic style specifically of one image to another using AI", "A fashion brand", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Generative AI transforming industries?", "options": ["By automating content creation specifically and enhancing human creativity", "Because it is expensive", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
