import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_gitgithub_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Git?", "options": ["A types of table", "A distributed version control system for tracking code changes", "A cloud storage", "None"], "correct": 1},
        {"id": 2, "question": "What is GitHub?", "options": ["A cloud platform for hosting Git repositories and collaborating", "A programming language", "Both", "None"], "correct": 0},
        {"id": 3, "question": "What is a 'Repository' (Repo)?", "options": ["A folder containing your project files and their history in Git", "A group of people", "Both", "None"], "correct": 0},
        {"id": 4, "question": "What is 'Commit' in Git?", "options": ["A promise", "A snapshot of your changes saved to the local repository", "Both", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Push' in Git?", "options": ["Pushing a physical button", "Uploading your local commits to a remote repository (like GitHub)", "Neither", "Both"], "correct": 1},
        {"id": 6, "question": "What is 'Pull' in Git?", "options": ["Downloading changes from a remote repository and merging them locally", "Pulling a lever", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'Branch'? ", "options": ["A physical tree branch", "A parallel version of a repository allowed for isolated development", "Neither", "Both"], "correct": 1},
        {"id": 8, "question": "What is 'Merge'?", "options": ["Combining changes from one branch into another (e.g. feature to main)", "Deleting a folder", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Clone'?", "options": ["Making a copy of a remote repository on your local machine", "A biological copy", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Fork' in GitHub?", "options": ["A kitchen utensil", "Creating your own personal copy of someone else's repository", "Both", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Pull Request' (PR)?", "options": ["A request to merge your changes into a different repository/branch with review", "Asking for money", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is '.gitignore' file for?", "options": ["Specifying which files or folders Git should NOT track/upload", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Staging Area' (Index)?", "options": ["A middle ground where you prepare changes before committing them", "A stage in theater", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Fetch' in Git?", "options": ["Downloading changes from remote without merging them into your local work", "Fetching a ball", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'diff' command useful for?", "options": ["Showing the exact differences between two versions of a file", "A mathematical term", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Conflict' in Git?", "options": ["Fighting with friends", "When Git can't automatically merge changes because of overlapping edits", "Neither", "Both"], "correct": 1},
        {"id": 17, "question": "What's the meaning of 'Main' (or Master) branch?", "options": ["The primary branch containing stable, production-ready code", "Writing new features", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'Origin' in Git context?", "options": ["The source of a project", "The default name given to the primary remote repository", "Neither", "Both"], "correct": 1},
        {"id": 19, "question": "What is 'HEAD'? ", "options": ["The physical head", "A pointer to the current branch/commit you are working on", "Both", "None"], "correct": 1},
        {"id": 20, "question": "What is a 'Tag' for in Git?", "options": ["A price tag", "A marker used to capture a specific point in a repository's history (e.g. v1.0)", "Both", "None"], "correct": 1},
        {"id": 21, "question": "What is the command to initialize a new Git repository?", "options": ["git start", "git init", "git new", "None"], "correct": 1},
        {"id": 22, "question": "How do you add all changed files to the staging area?", "options": ["git add .", "git add --all", "Both A and B", "Neither"], "correct": 2},
        {"id": 23, "question": "How do you check the current status of your files in Git?", "options": ["git search", "git status", "git list", "None"], "correct": 1},
        {"id": 24, "question": "Command to commit your changes with a message?", "options": ["git commit 'msg'", "git commit -m 'msg'", "git save 'msg'", "None"], "correct": 1},
        {"id": 25, "question": "How do you view the history of commits?", "options": ["git log", "git history", "Both", "None"], "correct": 0},
        {"id": 26, "question": "What is 'GitHub Pages'?", "options": ["Hosting static websites directly from a GitHub repository", "A news page", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'GitHub Actions'?", "options": ["Built-in CI/CD for automating your project's workflow on GitHub events", "Buttons on GitHub", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What's the difference between Git and GitHub?", "options": ["Git is the tool (VCS); GitHub is the online hosting platform for Git", "Same thing", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'README.md' importance?", "options": ["Providing description, instructions, and info about your project to others", "A secret text", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Who created Git?", "options": ["Linus Torvalds", "Bill Gates", "Mark Zuckerberg", "None"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Stash' useful for?", "options": ["Temporarily saving your uncommitted changes to work on something else", "Saving money", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "How do you clear a stash?", "options": ["git stash clear", "git stash pop (to apply and remove)", "Both A and B", "Neither"], "correct": 2},
        {"id": 33, "question": "What's the meaning of 'Checkout'?", "options": ["Switching between different branches or restoring a file version", "Leaving a hotel", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Rebase'?", "options": ["Combining or moving a sequence of commits to a new base commit", "Starting over from zero", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Cherry-pick'?", "options": ["Picking a single commit from one branch and applying it to another", "Buying fruit", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What's the value of using 'Remote' repositories?", "options": ["Ensuring collaboration and backup of your code off-machine", "Starting a business", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Upstream' branch?", "options": ["Establishing a link between your local branch and a remote branch", "Moving up a river", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What's the benefit of Small frequent commits?", "options": ["Easier troubleshooting and clearer project history", "Saving database space", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'GitKraken' or 'Sourcetree'?", "options": ["GUI (Graphical User Interface) tools for managing Git repositories", "A sea creature", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "How do you permanently delete a local branch?", "options": ["git branch -d branch_name", "git branch -delete", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Pull' = 'Fetch' + 'Merge'?", "options": ["Yes, git pull does both automatically", "No, they are separate totally", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's the meaning of '.git' folder?", "options": ["The hidden folder that stores all the metadata and history of the repo", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'SSH' key used for with GitHub?", "options": ["Securely connecting and pushing to GitHub without typing password every time", "A car key brand", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'SSH-keygen'?", "options": ["The command used to generate a new pair of SSH keys", "Generating secrets", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'README.md' extension mean?", "options": ["Markdown (a simple lightweight formatting language)", "More data", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Markdown' for in repositories?", "options": ["Creating beautiful documents with formatting like bold, links, and lists", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Contributor' in GitHub?", "options": ["Someone who has successfully proposed changes and merged them to a repo", "Someone who only watches", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's the benefit of 'Open Source' on GitHub?", "options": ["Letting anyone see, learn from, and contribute to improvements in code", "Buying servers", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's 'Stars' on GitHub repo for?", "options": ["Bookmarking a repository you find interesting or useful", "Ranking by money", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Watch' on GitHub repo for?", "options": ["Receiving notifications for all activity in that repository", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What's 'Issue' feature on GitHub?", "options": ["A built-in system to track bugs, enhancements, and tasks for a project", "A magazine name", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's 'Milestone' on GitHub?", "options": ["Grouping related issues and PRs together to track progress for a release", "A physical rock", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Project' (Kanban) board on GitHub?", "options": ["A visual board to manage tasks and workflow for your repository", "A drawing board", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Gist' on GitHub?", "options": ["A simple way to share single code snippets or notes with others", "A person's name", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's 'Squash' merge?", "options": ["Combining all commits of a branch into a single commit upon merging", "Squeezing fruit", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Fast-forward' merge?", "options": ["A simple merge where Git moves the branch head forward if no conflicts", "Fast speed", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Remote Add' command?", "options": ["git remote add name url", "git add remote", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "How do you rename a local branch?", "options": ["git branch -m new_name", "git rename", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "How can you view only the last 3 commits?", "options": ["git log -n 3", "git list 3", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's the meaning of 'Tracked' vs 'Untracked' files?", "options": ["Tracked are files that Git already has in its database", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "How to 'Amending' a commit?", "options": ["git commit --amend (allows changing the last commit's message or files)", "git fix last", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'Revert' versus 'Reset'?", "options": ["Revert creates a new commit that undoes old; Reset moves existing branch head", "Same things", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'Hard Reset' risk?", "options": ["It can permanently delete your uncommitted work and local history", "No risk", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "How many remotes can one repository have?", "options": ["Multiple", "Only one", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's 'Force Push' (git push -f)?", "options": ["Potentially dangerous operation that overwrites remote history", "Pushing very hard", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Blame' in Git context?", "options": ["Showing who changed each line of a file last and why (metadata)", "Fighting at work", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Reflog' for?", "options": ["A complete log of all changes to the tips of branches for recovery", "Logging a program", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "How do you check modified but unstaged files?", "options": ["git diff", "git check", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "How do you check staged files compared to last commit?", "options": ["git diff --staged", "git diff last", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'SVN' in relation to Git?", "options": ["Older centralized version control system", "A fast computer", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Can Git work completely offline?", "options": ["Yes, it is distributed and everything is stored locally", "No", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Merge Conflict' resolution process?", "options": ["Identifying overlapped changes, picking the correct version, and committing", "Deleting the code", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'Pull' impact on local work?", "options": ["It can lead to conflicts if your and remote changes overlap", "It cleans your work", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's the meaning of 'Private' repo on GitHub?", "options": ["Only you and authorized people can see or access the code", "Secret code for only one person", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's the meaning of 'Public' repo on GitHub?", "options": ["Anyone on the internet can view the code", "Everyone can edit it", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Which constant is used for default branch name in many new repos?", "options": ["main", "master", "primary", "None"], "correct": 0},
        {"id": 77, "question": "How can you view commit details?", "options": ["git show commit_id", "git detail", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Git Bash'?", "options": ["Git command line for Windows with Unix-like features", "A party for Git lovers", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which file extension is commonly used for Markdown?", "options": [".md", ".markdown", "Both A and B", "Neither"], "correct": 2},
        {"id": 80, "question": "Why is Git essential for modern software development?", "options": ["Allows safe collaboration, tracking progress and easy version management", "Faster internet speed", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
