import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_gcp_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Google Cloud Platform (GCP)?", "options": ["A types of search engine", "A suite of cloud computing services by Google on the same infrastructure as search", "A web browser", "None"], "correct": 1},
        {"id": 2, "question": "What are the three main service models in GCP?", "options": ["SaaS, PaaS, IaaS", "Speed, Storage, Security", "Java, C, Python", "None"], "correct": 0},
        {"id": 3, "question": "What is 'Google Cloud Console'?", "options": ["A website for news", "A web-based interface used to manage all your GCP resources manually", "Both", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Compute Engine' (GCE)?", "options": ["Google's IaaS offering (virtualized virtual machines)", "A new engine for a car", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'App Engine' (GAE)?", "options": ["A PaaS for building and deploying web applications easily without server management", "A phone app", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'Google Kubernetes Engine' (GKE)?", "options": ["Management for physical containers", "Managed Kubernetes service for scaling containerized apps automatically", "Neither", "Both"], "correct": 1},
        {"id": 7, "question": "What is 'Cloud Storage' in GCP?", "options": ["Storing physical data on a phone", "Object storage for unstructured data (similar to S3)", "A type of table", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Cloud Bigtable'?", "options": ["High-performance, NoSQL wide-column database for sparse data", "A very large table in an office", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'BigQuery'?", "options": ["A serverless, petabyte-scale data warehouse for big data analytics", "A large question", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What's the role of 'IAM' in GCP?", "options": ["Securely controlling access to GCP resources based on roles and permissions", "A personal ID", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Cloud SQL'?", "options": ["A managed relational database service (MySQL, PostgreSQL, SQL Server)", "A local SQL file", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'Cloud Spanner'?", "options": ["A tool for spanning a bridge", "Globally distributed, strongly consistent relational database for large scale", "Both", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Cloud Pub/Sub'?", "options": ["A messaging service for asynchronous communication between services", "A pub in a city", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Cloud Functions'?", "options": ["Math in GCP only", "A lightweight, serverless compute service that runs code in response to events", "Both", "None"], "correct": 1},
        {"id": 15, "question": "What is 'VPC' (Virtual Private Cloud) in GCP?", "options": ["A virtual private network space isolated within GCP", "A video PC", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Cloud DNS'?", "options": ["Amazon's DNS service", "Microsoft's DNS", "Managed domain name system for name translation in GCP", "None"], "correct": 2},
        {"id": 17, "question": "What's 'Load Balancing' in Google Cloud?", "options": ["Distributing incoming traffic across multiple GCP resources to ensure HA", "A physical weight", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'Cloud Deployment Manager'?", "options": ["Modeling and deploying GCP infrastructure using configuration files (IaC)", "A person from Google", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Firebase'?", "options": ["Google's mobile and web application development platform", "A video game", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Cloud Vision AI'?", "options": ["Better glasses for AI", "Pre-trained models for image analysis and recognition", "Neither", "Both"], "correct": 1},
        {"id": 21, "question": "What is 'Cloud Natural Language AI'?", "options": ["Machines understanding text and speech in GCP", "Learning languages for people", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What's the meaning of 'Identity-Aware Proxy' (IAP)?", "options": ["Guarding a building", "Controlling access to cloud apps by verifying user identity without VPN", "Neither", "Both"], "correct": 1},
        {"id": 23, "question": "What is 'Cloud Run'?", "options": ["Running on a cloud", "A severless platform that automatically scales containerized applications", "Both", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Google Cloud Free Tier'?", "options": ["Includes specific amount of free services for new users within limits", "Sharing a room", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Cloud Billing'?", "options": ["Tracking and paying for GCP resources used in an account", "A bill for an office", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Cloud Marketplace'?", "options": ["Buying physical items", "Online store for thousands of certified third-party apps for GCP", "Both", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Google Cloud Search'?", "options": ["GCP's enterprise search service for indexing internal company information", "A web search", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Cloud Operations' (formerly Stackdriver)?", "options": ["Watching TV in GCP", "A central place to monitor, log, and diagnose cloud apps and infrastructure", "Both", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Error Reporting' in GCP?", "options": ["Reporting a mistake", "Identifying and grouping errors generated by your applications in cloud", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "What is 'GCP Project'?", "options": ["A logical container specifically for managing resources, billing, and access in GCP", "A plan for work", "Neither", "Both"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Cloud Interconnect'?", "options": ["Connecting companies with clouds", "Provides a private, high-speed physical connection from your facility to Google", "Both", "None"], "correct": 1},
        {"id": 32, "question": "What is 'Cloud VPN'?", "options": ["Connecting local network to GCP VPC privately over the public internet", "A fast internet", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Cloud Router'?", "options": ["Automatically managing VPC routes using BGP for BGP-based VPNs", "A router for office", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Cloud Armor'?", "options": ["Google's managed DDoS protection and WAF for apps", "A types of suit", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What's 'Global Load Balancer' in GCP?", "options": ["Global proxy for directing users to nearest region and maintaining HA", "A very large scale", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Cloud Identity'?", "options": ["Identity platform for managing users, apps, and devices centrally", "A secret ID", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Cloud Dataflow'?", "options": ["A managed service for building and running parallel data processing pipelines", "Data on a river", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Cloud Dataproc'?", "options": ["Managed Spark and Hadoop for big data clusters in GCP", "A building material", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Cloud Composer'?", "options": ["Managed Airflow service for orchestrating workflows and pipelines", "Music player for GCP", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Vertex AI'?", "options": ["Unified AI platform for building, deploying and managing ML models", "A new computer game", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'AutoML' in Google Cloud?", "options": ["Building ML models automatically using Google's expertise without code", "Automatic cars", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Dialogflow'?", "options": ["Tool for building conversational interfaces like chatbots and voice apps", "A flow of charts", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Apigee'?", "options": ["A platform for managing, securing, and analyzing APIs in the cloud", "A news app", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Cloud Key Management Service' (KMS)?", "options": ["Managing encryption keys in cloud securely", "Managing car keys", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's 'Cloud Monitoring' (Stackdriver)?", "options": ["Unified monitoring service for logs, metrics and alerts from your GCP environment", "Watching clouds", "Both", "None"], "correct": 0},
        {"id": 46, "question": "What's 'Cloud Logging'?", "options": ["Storing and searching log files from all your Google Cloud resources", "Writing in a diary", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Cloud Trace'?", "options": ["Distribution tracing system specifically for analyzing app latency and bottleneck", "Tracing a drawing", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Cloud Profiler'?", "options": ["Continuous profiling for resource-intensive apps to help optimize performance", "A person who likes profiles", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's 'Google Cloud Anthos'?", "options": ["Hybrid and multi-cloud platform specifically to manage GKE clusters anywhere", "A flower", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Bare Metal Solution' in GCP?", "options": ["Metals for servers", "Running specialized workloads like Oracle on dedicated hardware near GCP", "Both", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Direct Peering'?", "options": ["Lining up servers in city", "Establishing a direct, physical connection between Google and your network", "Both", "None"], "correct": 1},
        {"id": 52, "question": "What's the role of 'Edge PoPs' (Point of Presence)?", "options": ["Google facilities where you can connect directly to their network for speed", "Blowing a bubble", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Local SSD' in GCE?", "options": ["Temporary, high-performance physical disk specifically for virtual machines", "A local drive", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'Persistent Disk' in GCE?", "options": ["Flexible, durable block storage (like HDD/SSD) that can survive VM restarts", "Permanent hard drive", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "Which of these allows hosting a database in Google Cloud?", "options": ["Cloud SQL", "Bigtable", "Cloud Spanner", "All of the above"], "correct": 3},
        {"id": 56, "question": "What is 'Organization' node in GCP resource hierarchy?", "options": ["The root node for an entire company's GCP presence", "A room in a building", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "How can you run code on Google Cloud without managing a server?", "options": ["Using Cloud Functions", "Using App Engine", "Neither", "Both A and B"], "correct": 3},
        {"id": 58, "question": "What is Google Cloud's 'Preemptible VM'?", "options": ["Extra-cheap VMs for short tasks that can be stopped by Google at any time", "A fast VM", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What happens if a preemptible VM is stopped?", "options": ["You are only charged for the time used (even if stopped)", "Nothing happens", "The whole project stops", "None"], "correct": 0},
        {"id": 60, "question": "What is 'Cloud Firestore'?", "options": ["NoSQL document database for building web and mobile apps globally", "A store for fire", "Both", "None"], "correct": 0},
        {"id": 61, "question": "What is 'Cloud SDK' (gcloud)?", "options": ["Command-line tool explicitly used to manage GCP resources", "A new computer game", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Cloud Shell'?", "options": ["Shells on a beach", "Authenticated, browser-based command line to manage your cloud resources", "Both", "None"], "correct": 1},
        {"id": 63, "question": "What's 'GCP Region'?", "options": ["A physical location with multiple data centers in Google Cloud infrastructure", "A country in a map", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'Availability Zone' in GCP context?", "options": ["An isolated location within a region (Zone) for fault tolerance", "A safe place", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "Which of these is used for content delivery in GCP?", "options": ["Cloud CDN", "Cloud Storage", "Cloud DNS", "None"], "correct": 0},
        {"id": 66, "question": "What's 'Cloud Identity for customers' (CIAM)?", "options": ["Allowing your own app's users to log in through multiple third parties", "Identity for secret agents", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'BeyondCorp' model in GCP?", "options": ["Google's security framework providing access without traditional VPNs", "Something beyond a company", "Both", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Cloud Data Fusion'?", "options": ["Fully managed, cloud-native data integration service for building ETL pipelines", "Mixing data animals", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "Which constant is used for Google Cloud project id?", "options": ["project_id", "id_project", "Both", "None"], "correct": 0},
        {"id": 70, "question": "What's 'BigQuery Omni'?", "options": ["Using BigQuery to analyze data across other clouds (AWS, Azure) without export", "A type of car", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Artifact Registry'?", "options": ["A place to store historical items", "Secure, central place to manage packages and container images in Google Cloud", "Both", "None"], "correct": 1},
        {"id": 72, "question": "What's 'Binary Authorization'?", "options": ["Checking binary code", "Deploying only trusted container images that meet specific security criteria", "Neither", "Both"], "correct": 1},
        {"id": 73, "question": "What is 'Shielded VMs' in GCE?", "options": ["VM with an armor", "VMs designed carefully to prevent rootkits and kernel-level malware", "Neither", "Both"], "correct": 1},
        {"id": 74, "question": "What is 'Secret Manager' specifically for?", "options": ["Hiding keys", "Storing and managing sensitive data like passwords, API keys, and certs", "Neither", "Both"], "correct": 1},
        {"id": 75, "question": "How can you estimate your GCP costs?", "options": ["Google Cloud Pricing Calculator", "Manual calculation", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What's the meaning of 'Live Migration' in Compute Engine?", "options": ["Migrating instances after they died", "Keeping VMs running even during host maintenance without downtime", "Neither", "Both"], "correct": 1},
        {"id": 77, "question": "What is 'Cloud Memorystore'?", "options": ["A memory store for brains", "Fully managed, high-performance in-memory service for Redis and Memcached", "Neither", "Both"], "correct": 1},
        {"id": 78, "question": "What is 'Looker' in GCP?", "options": ["A types of clothes", "A modern data platform for business intelligence and data analytics", "Neither", "Both"], "correct": 1},
        {"id": 79, "question": "What's 'Google Cloud Premium Tier' network?", "options": ["Highest performance network for low latency and high quality", "A high speed car", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What's the primary benefit of Google Cloud for companies already using many Google tools?", "options": ["Unified interface, consistent billing, and high-performance infrastructure", "Having more servers", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Google Cloud Storage'?", "options": ["Object storage service for any amount of data", "Storage for Google files", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Google Cloud SQL'?", "options": ["Managed relational database service", "SQL for Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Google Cloud Firestore'?", "options": ["NoSQL document database", "A database for Google", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Google Cloud BigQuery'?", "options": ["Serverless data warehouse", "Big data queries", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Google Cloud Functions'?", "options": ["Serverless compute platform", "Functions for Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Google Cloud Run'?", "options": ["Serverless container platform", "Running containers on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Google Kubernetes Engine' (GKE)?", "options": ["Managed Kubernetes service", "Kubernetes on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Google Cloud IAM'?", "options": ["Identity and access management", "Managing access to Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Google Cloud VPC'?", "options": ["Virtual private cloud network", "Private network on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Google Cloud Load Balancing'?", "options": ["Distributing traffic across instances", "Balancing Google Cloud traffic", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Google Cloud CDN'?", "options": ["Content delivery network", "Fast content delivery on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Google Cloud Armor'?", "options": ["Web application firewall", "Security for Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Google Cloud Monitoring'?", "options": ["Observability and monitoring service", "Monitoring Google Cloud resources", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Google Cloud Logging'?", "options": ["Log management and analysis", "Managing logs on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Google Cloud Trace'?", "options": ["Application performance monitoring", "Tracing applications on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Google Cloud Profiler'?", "options": ["Application performance profiling", "Profiling apps on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Google Cloud Debugger'?", "options": ["Application debugging service", "Debugging apps on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Google Cloud Error Reporting'?", "options": ["Error tracking and alerting", "Managing errors on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Google Cloud Deployment Manager'?", "options": ["Infrastructure deployment service", "Deploying infrastructure on Google Cloud", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Google Cloud Resource Manager'?", "options": ["Resource organization and management", "Managing Google Cloud resources", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
