import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_hibernate_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Hibernate?", "options": ["A type of animal", "An open-source ORM framework for Java", "A programming language", "None"], "correct": 1},
        {"id": 2, "question": "What does ORM stand for?", "options": ["Object-Relational Mapping", "Online Resource Management", "Order-Record Management", "None"], "correct": 0},
        {"id": 3, "question": "What is the primary function of Hibernate?", "options": ["Creating UI", "Mapping Java objects to relational database tables", "Managing internet speed", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Session' in Hibernate?", "options": ["A user login session", "A short-lived object used for performing CRUD on instances", "A type of chart", "None"], "correct": 1},
        {"id": 5, "question": "What is 'SessionFactory'?", "options": ["A place for session workers", "A thread-safe, heavy object used to create specific sessions", "A type of bank", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Transaction' in Hibernate?", "options": ["A financial report", "Ensuring database consistency by grouping multiple operations into one logical unit", "A security log", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Query' in Hibernate (HQL)?", "options": ["Hibernate Quality List", "Hibernate Query Language (Object-oriented query language)", "None", "None"], "correct": 1},
        {"id": 8, "question": "What is the result of 'save()' in Hibernate?", "options": ["Deleting an object", "Inserting a record and getting a primary key", "A type of table", "None"], "correct": 1},
        {"id": 9, "question": "What is the result of 'update()'?", "options": ["Modifying an existing database record based on object state", "Moving an object", "None", "None"], "correct": 0},
        {"id": 10, "question": "What is the result of 'delete()'?", "options": ["Removing a record from the database", "Deleting a file", "A type of error", "None"], "correct": 0},
        {"id": 11, "question": "What is 'Caching' in Hibernate?", "options": ["Storing media files", "A feature to store frequently used data in memory to reduce database hits", "A design tool", "None"], "correct": 1},
        {"id": 12, "question": "What is 'First-level Cache'?", "options": ["The Session cache (default, mandatory)", "The SessionFactory cache", "A type of disk", "None"], "correct": 0},
        {"id": 13, "question": "What is 'Second-level Cache'?", "options": ["The Session cache", "A cache that is shared across all Sessions in a SessionFactory", "A type of chart", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Entity' in Hibernate?", "options": ["A person in history", "A Java class that is mapped to a database table", "A technical manual", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Mapping File' (e.g. .hbm.xml)?", "options": ["A file with instructions on how to map a class to a table", "A list of users", "None", "None"], "correct": 0},
        {"id": 16, "question": "Which annotation is used to mark a class as a Hibernate entity?", "options": ["@Table", "@Entity", "@Model", "@Map"], "correct": 1},
        {"id": 17, "question": "Which annotation defines the primary key of an entity?", "options": ["@Key", "@Id", "@Primary", "@Code"], "correct": 1},
        {"id": 18, "question": "Which annotation defines a table name in Hibernate?", "options": ["@Table", "@Entity", "@SetTable", "None"], "correct": 0},
        {"id": 19, "question": "What is 'Criteria Query'?", "options": ["A simple filter", "An object-oriented way to define complex queries programmatically", "A security log", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Lazy Loading' in Hibernate?", "options": ["Delaying the loading of related associations until specifically needed", "Slowing down the server", "None of the above", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Eager Loading'?", "options": ["Loading everything immediately including associations in one query", "Fast internet speed", "Both A and B", "Neither"], "correct": 0},
        {"id": 22, "question": "What is 'Dirty Checking'?", "options": ["Checking for syntax errors", "A mechanism to automatically detect changes in persistent objects and update the DB", "None of the above", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Transient' state of an object?", "options": ["Object has been deleted", "New object not yet associated with any Hibernate session", "None of the above", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Persistent' state?", "options": ["Object associated with a specific session and represented in the DB", "A secret object", "None of the above", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Detached' state?", "options": ["Object was persistent but its session has been closed", "A decorative text", "None and None", "None"], "correct": 0},
        {"id": 26, "question": "What's the meaning of 'HQL'?", "options": ["Hibernate Query Language", "Java SQL Language", "Standard SQL", "None"], "correct": 0},
        {"id": 27, "question": "Can Hibernate work with any relational database?", "options": ["Yes, by using specific Dialects", "No", "Only Oracle and MySQL", "None"], "correct": 0},
        {"id": 28, "question": "What is 'Dialect' in Hibernate context?", "options": ["A language for people", "A class that informs Hibernate about the specific SQL version and features of a database", "A type of table", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Auto-commit' in Hibernate transactions?", "options": ["Committing transactions automatically after each statement", "Manual commits", "None", "None"], "correct": 0},
        {"id": 30, "question": "Which of these is a popular alternative ORM for Java?", "options": ["MyBatis", "Spring Data JPA", "EclipseLink", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Cascade' attribute for in Hibernate?", "options": ["A design color", "A property that propagates operations (like save/delete) from parent to child entities", "A security log", "None"], "correct": 1},
        {"id": 32, "question": "What is 'One-to-One' mapping?", "options": ["Each row in table A matches one row in table B and vice-versa", "Merging two tables", "A type of chart", "None"], "correct": 0},
        {"id": 33, "question": "What is 'One-to-Many' mapping?", "options": ["A single entity in A associated with multiple in B", "One user with many passwords", "None", "None"], "correct": 0},
        {"id": 34, "question": "What is 'Many-to-One' mapping?", "options": ["Opposite of One-to-Many", "Multiple rows in A mapped to a single row in B", "Both A and B", "Neither"], "correct": 2},
        {"id": 35, "question": "What is 'Many-to-Many' mapping?", "options": ["Rows in A match multiple in B and vice-versa (usually via a join table)", "A list of strings", "None", "None"], "correct": 0},
        {"id": 36, "question": "What is 'Joined Strategy' for inheritance?", "options": ["Merging all data in one table", "A strategy where subclasses each have their own separate table joined to a parent table", "A tech spec", "None"], "correct": 1},
        {"id": 37, "question": "What is 'Single Table Strategy'?", "options": ["A table for one person", "The default strategy where all classes in an inheritance hierarchy use one table", "A security token", "None"], "correct": 1},
        {"id": 38, "question": "What is 'Discriminator Column'?", "options": ["A column for sensitive info", "A column in a single-table inheritance setup to identify the entity type", "A type of table", "None"], "correct": 1},
        {"id": 39, "question": "What is 'Proxy Object' in lazy loading?", "options": ["Hiding your identity", "A placeholder object for a lazily loaded associated entity", "Both", "None"], "correct": 1},
        {"id": 40, "question": "Which interface is used to configure Hibernate applications?", "options": ["Configuration", "Setup", "Boot", "Design"], "correct": 0},
        {"id": 41, "question": "What's the meaning of 'Hibernate.cfg.xml'?", "options": ["A list of files", "The main configuration file containing database connection details", "A decorative text", "None"], "correct": 1},
        {"id": 42, "question": "How do you start a transaction in Hibernate Session?", "options": ["session.start()", "session.beginTransaction()", "session.go()", "None"], "correct": 1},
        {"id": 43, "question": "How do you commit a transaction?", "options": ["transaction.save()", "transaction.commit()", "transaction.end()", "None"], "correct": 1},
        {"id": 44, "question": "How do you rollback a transaction in case of error?", "options": ["transaction.undo()", "transaction.rollback()", "transaction.stop()", "None"], "correct": 1},
        {"id": 45, "question": "What is 'Optimistic Locking'?", "options": ["Locks everything by default", "Assuming no conflicts and checking version number before updating", "A type of error", "None"], "correct": 1},
        {"id": 46, "question": "What is 'Pessimistic Locking'?", "options": ["Always assuming the best", "Locking the database record at the start to prevent any concurrent modification", "Both", "None"], "correct": 1},
        {"id": 47, "question": "What is 'Natural Id'?", "options": ["An id from nature", "A property that is a business key (like email) as opposed to a surrogate surrogate key", "Both", "None"], "correct": 1},
        {"id": 48, "question": "What is 'Named Query'?", "options": ["A query with a name", "Predefined HQL or SQL queries that are stored in metadata for reuse", "Both", "None"], "correct": 1},
        {"id": 49, "question": "What is 'Native SQL Query' in Hibernate?", "options": ["Using raw SQL instead of HQL", "A language for people", "A technical specification", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Flush()' in Hibernate?", "options": ["Wiping the database", "Synchronizing the state of the session with the database", "Both", "None"], "correct": 1},
        {"id": 51, "question": "What is the difference between 'get()' and 'load()'?", "options": ["get() returns null if not found; load() throws ObjectNotFoundException", "get() hits DB immediately; load() returns a proxy (lazy)", "Both A and B", "Neither"], "correct": 2},
        {"id": 52, "question": "What is '@GeneratedValue' for?", "options": ["Sets a value and generates code", "Assists in automatically generating identifiers (primary keys)", "None of the above", "None"], "correct": 1},
        {"id": 53, "question": "What is 'JPA' (Java Persistence API)?", "options": ["A type of table", "The standard specification for persistence management in Java", "A programming language", "None"], "correct": 1},
        {"id": 54, "question": "What does a 'Dialect' do for SQL portability?", "options": ["Helps translate HQL into specific SQL of the underlying DB", "Translates to binary", "Both A and B", "Neither"], "correct": 0},
        {"id": 55, "question": "What is 'Connection Pooling' in Hibernate?", "options": ["Managing hundreds of databases", "Reusing a set of available database connections for performance", "None of the above", "None"], "correct": 1},
        {"id": 56, "question": "Which annotation creates a custom primary key generation strategy?", "options": ["@SequenceGenerator", "@TableGenerator", "Both", "None"], "correct": 2},
        {"id": 57, "question": "What is 'Component' (Embeddable) mapping?", "options": ["A reusable object that is part of an entity and stored in the same table", "A secretive part of code", "None of the above", "None"], "correct": 0},
        {"id": 58, "question": "What is 'InheritanceMapping' used for?", "options": ["Designing icons", "Defining how inheritance relationships are stored in relational tables", "A routing name", "None"], "correct": 1},
        {"id": 59, "question": "What is '@JoinColumn' annotation for?", "options": ["Joining two files", "Specifying the column used to join entities in relationships", "Both", "None"], "correct": 1},
        {"id": 60, "question": "What is 'MappedBy' attribute used for?", "options": ["Identifies the owning side of a bidirectional relationship", "Deleting a record", "Formatting text", "None"], "correct": 0},
        {"id": 61, "question": "What is 'Query Cache' in Hibernate?", "options": ["Storing results of a specific query in cache", "Caching the query text only", "None of the above", "None"], "correct": 0},
        {"id": 62, "question": "What is 'Evict()' technique?", "options": ["Moving out of a house", "Removing a specific persistent object from the Hibernate First-level Cache (Session)", "Both", "None"], "correct": 1},
        {"id": 63, "question": "What is 'Clear()' technique?", "options": ["Deleting the database", "Removing all objects from the current Session cache", "None of the above", "None"], "correct": 1},
        {"id": 64, "question": "What is 'Dirty Checking' interval?", "options": ["Checking once a month", "Hibernate checks for changes during the flush process", "Both", "None"], "correct": 1},
        {"id": 65, "question": "What is 'StatelessSession'?", "options": ["A session with no state", "A lightweight session that doesn't provide first-level cache or dirty checking", "Neither", "Both"], "correct": 1},
        {"id": 66, "question": "What is 'Interceptor' in Hibernate?", "options": ["A security officer", "A feature that allows users to react to framework events (like save/load)", "None of the above", "None"], "correct": 1},
        {"id": 67, "question": "What is 'CriteriaBuilder' for?", "options": ["Building icons", "Creating strongly-typed, object-oriented criteria queries", "A decorative text", "None"], "correct": 1},
        {"id": 68, "question": "Which annotation defines a view model?", "options": ["Not a standard Hibernate annotation", "A decorative attribute", "None", "None"], "correct": 0},
        {"id": 69, "question": "Can Hibernate be used with NoSQL databases?", "options": ["Only certain ones through Hibernate OGM", "No", "Yes, any NoSQL", "None"], "correct": 0},
        {"id": 70, "question": "What is the result of '@OrderBy' annotation?", "options": ["Specifies how associated collections should be sorted when loaded", "Deleting a record", "None", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Version' field in Optimistic locking?", "options": ["A field for sensitive info", "A special field (integer or timestamp) used by Hibernate for version tracking", "None", "None"], "correct": 1},
        {"id": 72, "question": "What is 'Batch processing' in Hibernate?", "options": ["Deleting all data", "Performing bulk updates/inserts in batches for efficiency", "None", "None"], "correct": 1},
        {"id": 73, "question": "Which method is used for updating multiple objects at once in HQL?", "options": ["executeUpdate()", "modifyAll()", "BatchSave()", "None"], "correct": 0},
        {"id": 74, "question": "What is 'JNDI' (Java Naming and Directory Interface) used for?", "options": ["Linking database names", "A Java API used by applications to find names and directory services", "Both", "None"], "correct": 1},
        {"id": 75, "question": "What is 'Ehcache'?", "options": ["A popular third-party provider for Hibernate Second-level cache", "A type of memory", "A decorative part of code", "None"], "correct": 0},
        {"id": 76, "question": "What's the meaning of 'Impedance Mismatch'?", "options": ["A technical term for the difficulty of mapping objects to relational database tables", "Merging two files", "None of the above", "None"], "correct": 0},
        {"id": 77, "question": "Can Hibernate generate database schemas?", "options": ["Yes, using hbm2ddl.auto property", "No", "Only for tiny databases", "None"], "correct": 0},
        {"id": 78, "question": "Which value of hbm2ddl.auto should you use in production?", "options": ["create", "update", "validate or none", "drop"], "correct": 2},
        {"id": 79, "question": "What is 'Hibernate Statistics'?", "options": ["A security log", "A tool providing internal metrics like session hits, query times to analyze perf", "None", "None"], "correct": 1},
        {"id": 80, "question": "Which annotation connects a persistent property to its table column?", "options": ["@Target", "@Column", "@Header", "@Label"], "correct": 1},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
