import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_html_api(request):
    questions_pool = [
        {"id": 1, "question": "What does HTML stand for?", "options": ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyper Tool Markup Language"], "correct": 0},
        {"id": 2, "question": "Who is making the Web standards?", "options": ["Mozilla", "Microsoft", "The World Wide Web Consortium", "Google"], "correct": 2},
        {"id": 3, "question": "Choose the correct HTML element for the largest heading:", "options": ["<heading>", "<h1>", "<h6>", "<head>"], "correct": 1},
        {"id": 4, "question": "What is the correct HTML element for inserting a line break?", "options": ["<break>", "<lb>", "<br>", "<newline>"], "correct": 2},
        {"id": 5, "question": "What is the correct HTML for adding a background color?", "options": ["<body bg=\"yellow\">", "<background>yellow</background>", "<body style=\"background-color:yellow;\">", "<body bgcolor=\"yellow\">"], "correct": 2},
        {"id": 6, "question": "Choose the correct HTML element to define important text", "options": ["<strong>", "<b>", "<important>", "<i>"], "correct": 0},
        {"id": 7, "question": "Choose the correct HTML element to define emphasized text", "options": ["<italic>", "<i>", "<em>", "<strong>"], "correct": 2},
        {"id": 8, "question": "What is the correct HTML for creating a hyperlink?", "options": ["<a>http://www.w3schools.com</a>", "<a url=\"http://www.w3schools.com\">W3Schools.com</a>", "<a name=\"http://www.w3schools.com\">W3Schools.com</a>", "<a href=\"http://www.w3schools.com\">W3Schools</a>"], "correct": 3},
        {"id": 9, "question": "Which character is used to indicate an end tag?", "options": ["*", "^", "<", "/"], "correct": 3},
        {"id": 10, "question": "How can you open a link in a new tab/browser window?", "options": ["<a href=\"url\" target=\"new\">", "<a href=\"url\" target=\"_blank\">", "<a href=\"url\" new>", "<a href=\"url\" target=\"_window\">"], "correct": 1},
        {"id": 11, "question": "Which of these elements are all <table> elements?", "options": ["<table><tr><td>", "<table><head><tfoot>", "<thead><body><tr>", "<table><tr><tt>"], "correct": 0},
        {"id": 12, "question": "Inline elements are normally displayed without starting a new line.", "options": ["True", "False", "None", "Both"], "correct": 0},
        {"id": 13, "question": "How can you make a numbered list?", "options": ["<ul>", "<dl>", "<ol>", "<list>"], "correct": 2},
        {"id": 14, "question": "How can you make a bulleted list?", "options": ["<ol>", "<dl>", "<ul>", "<list>"], "correct": 2},
        {"id": 15, "question": "What is the correct HTML for making a checkbox?", "options": ["<checkbox>", "<input type=\"check\">", "<check>", "<input type=\"checkbox\">"], "correct": 3},
        {"id": 16, "question": "What is the correct HTML for making a text input field?", "options": ["<input type=\"textfield\">", "<textfield>", "<input type=\"text\">", "<textinput>"], "correct": 2},
        {"id": 17, "question": "What is the correct HTML for making a drop-down list?", "options": ["<input type=\"dropdown\">", "<select>", "<list>", "<input type=\"list\">"], "correct": 1},
        {"id": 18, "question": "What is the correct HTML for making a text area?", "options": ["<input type=\"textbox\">", "<textarea>", "<input type=\"textarea\">", "<text>"], "correct": 1},
        {"id": 19, "question": "What is the correct HTML for inserting an image?", "options": ["<img href=\"image.gif\" alt=\"MyImage\">", "<img src=\"image.gif\" alt=\"MyImage\">", "<image src=\"image.gif\" alt=\"MyImage\">", "<img alt=\"MyImage\">image.gif</img>"], "correct": 1},
        {"id": 20, "question": "What is the correct HTML for inserting a background image?", "options": ["<body background=\"bgimage.gif\">", "<background img=\"bgimage.gif\">", "<body style=\"background-image:url(bgimage.gif)\">", "<img src=\"bgimage.gif\" background>"], "correct": 2},
        {"id": 21, "question": "An <iframe> is used to display a web page within a web page.", "options": ["True", "False", "Sometimes", "With plugins"], "correct": 0},
        {"id": 22, "question": "HTML comments start with <!-- and end with -->", "options": ["True", "False", "Sometimes", "None"], "correct": 0},
        {"id": 23, "question": "Block elements are normally displayed without starting a new line.", "options": ["True", "False", "Sometimes", "Never"], "correct": 1},
        {"id": 24, "question": "Which HTML element defines the title of a document?", "options": ["<meta>", "<head>", "<title>", "<header>"], "correct": 2},
        {"id": 25, "question": "Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?", "options": ["alt", "title", "src", "longdesc"], "correct": 0},
        {"id": 26, "question": "Which doctype is correct for HTML5?", "options": ["<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 5.0//EN\" \"http://www.w3.org/TR/html5/strict.dtd\">", "<!DOCTYPE html>", "<!DOCTYPE HTML5>", "<!DOCTYPE>"], "correct": 1},
        {"id": 27, "question": "Which HTML element is used to specify a footer for a document or section?", "options": ["<bottom>", "<footer>", "<section>", "<nav>"], "correct": 1},
        {"id": 28, "question": "In HTML, you can embed SVG elements directly into an HTML page.", "options": ["True", "False", "Only with plugins", "None"], "correct": 0},
        {"id": 29, "question": "What is the correct HTML element for playing video files?", "options": ["<media>", "<movie>", "<video>", "<play>"], "correct": 2},
        {"id": 30, "question": "What is the correct HTML element for playing audio files?", "options": ["<sound>", "<mp3>", "<audio>", "<voice>"], "correct": 2},
        {"id": 31, "question": "The HTML global attribute, \"contenteditable\" is used to:", "options": ["Update content from the server", "Specify whether the content of an element should be editable or not", "Return the spelling of text", "Format content"], "correct": 1},
        {"id": 32, "question": "In HTML, onblur and onfocus are:", "options": ["Style attributes", "HTML elements", "Event attributes", "None of the above"], "correct": 2},
        {"id": 33, "question": "Graphics defined by SVG is in which format?", "options": ["HTML", "XML", "CSS", "JSON"], "correct": 1},
        {"id": 34, "question": "The HTML <canvas> element is used to:", "options": ["Draw graphics", "Manipulate data in MySQL", "Format text", "Create tables"], "correct": 0},
        {"id": 35, "question": "In HTML, which attribute is used to specify that an input field must be filled out?", "options": ["required", "placeholder", "validate", "formvalidate"], "correct": 0},
        {"id": 36, "question": "Which input type defines a slider control?", "options": ["slider", "range", "controls", "search"], "correct": 1},
        {"id": 37, "question": "Which HTML element is used to display a scalar measurement within a range?", "options": ["<gauge>", "<meter>", "<measure>", "<range>"], "correct": 1},
        {"id": 38, "question": "Which HTML element defines navigation links?", "options": ["<navigate>", "<nav>", "<navigation>", "<ul>"], "correct": 1},
        {"id": 39, "question": "In HTML, what does the <aside> element define?", "options": ["Content aside from the page content", "A navigation list to be shown at the left side of the page", "The ASCII character-set", "A background element"], "correct": 0},
        {"id": 40, "question": "Which HTML element is used to specify a header for a document or section?", "options": ["<top>", "<header>", "<head>", "<section>"], "correct": 1},
        {"id": 41, "question": "The <fieldset> element is used to group related elements in a form.", "options": ["True", "False", "Sometimes", "Never"], "correct": 0},
        {"id": 42, "question": "Which of these is not an HTML5 input type?", "options": ["color", "email", "datetime", "paragraph"], "correct": 3},
        {"id": 43, "question": "Which attribute specifies a hint that describes the expected value of an input field?", "options": ["value", "placeholder", "title", "hint"], "correct": 1},
        {"id": 44, "question": "The <datalist> element specifies a list of pre-defined options for an input element.", "options": ["True", "False", "For forms only", "None"], "correct": 0},
        {"id": 45, "question": "In HTML5, which tag is used to specify a grouping of introductory or navigational aids?", "options": ["<nav>", "<header>", "<footer>", "<group>"], "correct": 1},
        {"id": 46, "question": "What does the <caption> tag define in an HTML table?", "options": ["Table title", "Table body", "Table footer", "Table heading"], "correct": 0},
        {"id": 47, "question": "What is the correct syntax for a mailto link?", "options": ["<a href=\"email:me@example.com\">", "<mail>me@example.com</mail>", "<a href=\"mailto:me@example.com\">", "<a mail=\"me@example.com\">"], "correct": 2},
        {"id": 48, "question": "Which element defines an image map?", "options": ["<map>", "<imagemap>", "<areamap>", "<canvas>"], "correct": 0},
        {"id": 49, "question": "Which attribute provides additional information about an element?", "options": ["class", "id", "title", "style"], "correct": 2},
        {"id": 50, "question": "HTML files must be saved with what extension?", "options": [".ht", ".html", ".web", ".page"], "correct": 1},
        {"id": 51, "question": "What is 'ARIA' in HTML?", "options": ["Accessible Rich Internet Applications", "Advanced Routing Integration App", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'alt' attribute primarily for?", "options": ["Image description for screen readers", "Image color", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Role' attribute?", "options": ["Defines the purpose of an element for assistive tech", "Defines the CSS class", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is '<main>' tag?", "options": ["Container for the primary content of the document", "A greeting", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is '<section>' tag?", "options": ["Defines generic section of a document", "A part of a fruit", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is '<article>' tag?", "options": ["Independent, self-contained content", "A newspaper", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is '<nav>' tag?", "options": ["Section with navigation links", "A boat", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is '<aside>' tag?", "options": ["Content indirectly related to main content", "Moving something to side", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is '<figure>' tag?", "options": ["Self-contained content, like photos/diagrams", "A number", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is '<figcaption>' tag?", "options": ["Caption for a <figure> element", "A picture", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Doctype' declaration?", "options": ["Instruction to the browser about HTML version", "A medical doctor", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'UTF-8' encoding?", "options": ["Standard character encoding for web", "A types of file", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Meta Viewport' tag?", "options": ["Controls layout on mobile browsers", "A types of glass", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Base' tag?", "options": ["Specifies base URL/target for all relative URLs", "A foundation", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Pre' tag?", "options": ["Preformatted text (preserves whitespace)", "Preparation", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Code' tag?", "options": ["Defines a fragment of computer code", "Secret writing", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Blockquote' tag?", "options": ["Section quoted from another source", "A block of text", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Cite' tag?", "options": ["Defines the title of a work (e.g. book, film)", "Seeing something", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Abbr' tag?", "options": ["Defines an abbreviation or acronym", "Short for 'average'", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Dfn' tag?", "options": ["Represents the defining instance of a term", "A types of drive", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Kbd' tag?", "options": ["Defines keyboard input", "A types of board", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Samp' tag?", "options": ["Defines sample output from a computer program", "A sample", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Var' tag?", "options": ["Defines a variable in programming or math", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Small' tag?", "options": ["Defines smaller text (like side comments)", "Little", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Sub' tag?", "options": ["Defines subscripted text", "Below", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Sup' tag?", "options": ["Defines superscripted text", "Above", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Mark' tag?", "options": ["Defines text that should be highlighted", "A person's name", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Ruby' tag?", "options": ["Defines ruby annotations (for East Asian typography)", "A red gem", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Time' tag?", "options": ["Defines a specific period in time", "A watch", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is 'Wbr' tag?", "options": ["Word Break Opportunity", "A types of bridge", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Address' tag?", "options": ["Defines contact information for author/owner", "Literal address", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Details' and 'Summary' tags?", "options": ["Created interactive disclosure widgets", "A short story", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Dialog' tag?", "options": ["Defines a dialog box or other interactive component", "Talking", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Template' tag?", "options": ["Holding HTML that is not rendered on page load", "A guide", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Slot' tag?", "options": ["Placeholder inside a web component", "A gap", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Svg' tag?", "options": ["Scalable Vector Graphics", "Save Video Game", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Mathml'?", "options": ["Mathematical Markup Language", "Math ML", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Embed' tag?", "options": ["Container for external resource (like plugins)", "Putting inside", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Object' tag?", "options": ["Defines an external resource (image, nested doc, plugin)", "A thing", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Param' tag?", "options": ["Defines parameters for <object> element", "A types of ram", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Source' tag?", "options": ["Specifies multiple media resources for <picture>, <video>, <audio>", "Original file", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Track' tag?", "options": ["Defines text tracks for <video> and <audio>", "A circular path", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Canvas' tag?", "options": ["Used to draw graphics via scripting (JS)", "A types of cloth", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Map' and 'Area' tags?", "options": ["Defining image maps with clickable areas", "Location finding", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Data' tag?", "options": ["Links given content with machine-readable translation", "Information", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Meter' tag?", "options": ["Defines scalar measurement within known range", "A unit of length", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Progress' tag?", "options": ["Displays the completion progress of a task", "Moving forward", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Output' tag?", "options": ["Represents result of a calculation", "Printing something", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Rel=Stylesheet'?", "options": ["Describes the relationship between current doc and linked resource", "Relative", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Href' attribute?", "options": ["Specifies the URL of the page the link goes to", "Home reference", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, 20)})
