import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_iam_api(request):
    questions_pool = [
        {"id": 1, "question": "What does IAM stand for in AWS?", "options": ["Identity and Access Management", "Internal Account Management", "International Access Mode", "None"], "correct": 0},
        {"id": 2, "question": "What is the primary purpose of IAM?", "options": ["Managing storage", "Securely controlling access to AWS resources for users and roles", "Both A and B", "Neither"], "correct": 1},
        {"id": 3, "question": "What is 'IAM User'?", "options": ["An entity that represents a specific person or application within AWS", "A generic user name", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'IAM Group'?", "options": ["A group of users with identical permissions for easier management", "A collection of servers", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'IAM Role'?", "options": ["A set of permissions for a specific task that can be assumed by anyone", "A permanent identity", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is a 'Policy' in IAM?", "options": ["A legal document", "A JSON document defining permissions and access for users/roles", "Neither", "Both"], "correct": 1},
        {"id": 7, "question": "What is 'MFA' (Multi-Factor Authentication)?", "options": ["Using multiple passwords", "A security layer requiring at least two pieces of proof to log in", "Both A and B", "Neither"], "correct": 1},
        {"id": 8, "question": "What is 'Root User'?", "options": ["A person who likes nature", "The primary account identity with full, unrestricted access to all resources", "Neither", "Both"], "correct": 1},
        {"id": 9, "question": "Which of these is a valid IAM policy type?", "options": ["AWS Managed", "Customer Managed", "Inline", "All of the above"], "correct": 3},
        {"id": 10, "question": "What is 'Principle of Least Privilege'?", "options": ["Giving only the minimum access needed to perform a specific job", "Giving all access at once", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Permission Boundary' in IAM?", "options": ["A wall in the office", "A feature to limit the maximum permissions a delegated user can grant", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What's the meaning of 'Access Key' and 'Secret Key'?", "options": ["Credentials used for programmatic access to AWS via CLI or API", "Password for login", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'IAM Identity Center' (formerly SSO)?", "options": ["A central place to manage single sign-on access to multiple AWS accounts", "A login page for people", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Role Assumption' (AssumeRole)?", "options": ["A mechanism that allows a user to temporarily take on an IAM role's permissions", "Becoming a different person", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Resource-based Policy' (e.g. S3 Bucket Policy)?", "options": ["A policy attached to the resource itself, not the user", "A policy specifically for resources", "Both A and B", "Neither"], "correct": 2},
        {"id": 16, "question": "What is 'Identity-based Policy'?", "options": ["A policy attached directly to an IAM user, group, or role", "A secret policy", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Arn' (Amazon Resource Name)?", "options": ["A unique identifier for every AWS resource (e.g. arn:aws:iam...)", "An error code", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What's the meaning of 'Effect' in a policy statement?", "options": ["Determines if access is 'Allow' or 'Deny'", "Adding special effects", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What's the meaning of 'Action' in a policy?", "options": ["Specifies the specific API operation (e.g. s3:ListBucket)", "A physical action", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What's the meaning of 'Resource' in a policy?", "options": ["The specific AWS resource the policy applies to", "A physical item", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Condition' in a policy statement?", "options": ["A logic for math", "Optional criteria that must be met for the policy to take effect", "Neither", "Both"], "correct": 1},
        {"id": 22, "question": "What is 'CloudTrail' integration with IAM?", "options": ["Recording all IAM actions for audit and tracking", "A trail on a mountain", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What's 'Service-Linked Role'?", "options": ["Predefined role for an AWS service (like EC2) to perform tasks on your behalf", "Linking servers together", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "Can IAM be used globally across all regions?", "options": ["Yes, it is a global service", "No", "Only through a special setup", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Access Analyzer' in IAM?", "options": ["Reviewing which resources are accessible to external identities", "A search tool", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Visual Editor' in IAM policy creation?", "options": ["A GUI tool to help build JSON policies without writing code", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Federated Identity'?", "options": ["Allowing users from external systems (like okta, google) to access AWS", "A group of countries", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'SAML' (Security Assertion Markup Language)?", "options": ["An open standard for exchanging authentication and authorization data", "A programming language", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'Trust Relationship' of an IAM role?", "options": ["Defines who or what is allowed to assume that role", "A friendship note", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "What should you never do with Root user credentials?", "options": ["Use them for everyday administrative tasks", "Share them with anyone", "Both A and B", "Neither"], "correct": 2},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'IAM Credentials Report'?", "options": ["A downloadable file with status of all user credentials in account", "A report for cards", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "How often should you rotate access keys for better security?", "options": ["Regularly (e.g. every 90 days)", "Never", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What's the benefit of removing unused IAM users?", "options": ["Reducing potential attack surface and security risks", "Faster login", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Tagging' in IAM used for?", "options": ["Adding metadata to users/roles for better organization and automation", "Designing logos", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'ABAC' (Attribute-Based Access Control)?", "options": ["Granting permissions based on user and resource attributes (tags)", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'RBAC' (Role-Based Access Control)?", "options": ["Granting permissions based on defined job roles (standard IAM approach)", "A type of ball", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's the meaning of 'Deny' priority in policies?", "options": ["An explicit Deny always overrides any Allow in IAM", "Denying a person entry", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'IAM Simulator' (Policy Simulator)?", "options": ["A tool to test if your IAM policies allow or deny specific actions", "A flight simulator", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Service Control Policy' (SCP)?", "options": ["Upper-level policy in Organizations to restrict maximum permissions globally", "A service for control", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's 'AWS Organizations' relationship with IAM?", "options": ["Central management for multiple AWS accounts with centralized billing and policies", "A group of people", "Both", "None"], "correct": 0},
        {"id": 41, "question": "What is 'Cross-account access'?", "options": ["One account accessing resources in another account through roles", "Accessing a bank", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Inline Policy' impact?", "options": ["Embedded directly in a user/role; becomes harder to reuse across multiple entities", "Making things faster", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'AWS Managed Policy' benefit?", "options": ["Created and maintained by AWS for common roles (e.g. AdministratorAccess)", "Free account", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "Which of these is a typical business scenario for using IAM Roles?", "options": ["Granting EC2 instances permissions to access S3 buckets", "Giving mobile apps temporary access to AWS resources", "Both A and B", "Neither"], "correct": 2},
        {"id": 45, "question": "What is 'Web Identity Federation'?", "options": ["Logging in to AWS using social logins like Google or Facebook", "A web design", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'OpenID Connect' (OIDC)?", "options": ["An identity layer on top of OAuth 2.0 to verify end-user identity", "A connection to web", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What's the role of 'Principal' in an IAM policy?", "options": ["The user, role, service, or account that is being allowed/denied access", "Principal of a school", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Resource-based Policy' target?", "options": ["Attached to a specific resource (e.g. S3 Bucket, KMS Key, SQS Queue)", "A person", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Trust Policy' for an IAM Role?", "options": ["Defines what external principals can assume the role", "A friendship note", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What's the meaning of 'STS' (Security Token Service)?", "options": ["Generates temporary security credentials for users and roles", "Security token script", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "Which constant represents any resource in a policy ('*')?", "options": ["'*'", "all", "all_resources", "None"], "correct": 0},
        {"id": 52, "question": "Can you use wildcards in IAM actions (e.g. s3:*)?", "options": ["Yes, to include all actions for a specific service", "No", "Only for Root", "None"], "correct": 0},
        {"id": 53, "question": "Which of these is a best practice for Root account?", "options": ["Enable MFA", "Do not use for tasks", "Secure the credentials", "All of the above"], "correct": 3},
        {"id": 54, "question": "What is 'Credential Rotation'?", "options": ["Regularly changing passwords and keys to reduce risk if they're leaked", "Rotating a file", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'AWS Account ID'?", "options": ["A 12-digit number that uniquely identifies an account", "A personal ID", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'AWS CLI' (Command Line Interface)?", "options": ["Tool to manage AWS services through terminal using IAM credentials", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Access Key ID' versus 'Secret Access Key'?", "options": ["Public vs Private credentials for programmatic access", "Username vs Password", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'NotAction' in IAM policy?", "options": ["Grants access to everything EXCEPT the specified actions", "Starting an action", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'NotResource' in a policy?", "options": ["Means the policy applies to everything EXCEPT the specified resource", "Deleting items", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What's the benefit of 'IAM Groups' for onboarding new employees?", "options": ["Quickly granting all necessary permissions to new users by adding them to groups", "Fast hiring", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is '@' in IAM user context?", "options": ["Separates account name from user (e.g. user@account)", "Adding people", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'IAM Access Analyzer' for S3?", "options": ["Scanning buckets to find those with public or shared access", "A type of chart", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'KMS' (Key Management Service)?", "options": ["Managing encryption keys in AWS which often integrates with IAM", "A car key brand", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's the meaning of 'CloudTrail' logs for investigations?", "options": ["Seeing exactly WHO performed what action and WHEN they did it", "A trail on a mountain", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Identity-based policy' ownership?", "options": ["Owned by the identity (user/group/role) they are attached to", "A secret owner", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Resource-based policy' ownership?", "options": ["Owned by the resource itself (like an S3 bucket or KMS key)", "A person", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "Can you have multiple statements in one JSON policy?", "options": ["Yes, they are within a 'Statement' array in the JSON document", "No", "Only for special accounts", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Sid' (Statement ID) in a policy?", "options": ["An optional unique identifier for each statement in a JSON policy", "A name", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'Version' date at the top of a policy?", "options": ["Refers to the specific IAM policy language version (e.g. 2012-10-17)", "Today's date", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "How can you view IAM actions in the AWS console?", "options": ["Under IAM service dashboard", "In a new browser window", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Service Control Policy' (SCP) usage?", "options": ["Restricting the maximum possible permissions for accounts within an organization", "A policy for service", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "Can you share an AWS account with someone else safely?", "options": ["By creating specific IAM users for them (never share root password)", "Yes, share root", "No", "None"], "correct": 0},
        {"id": 73, "question": "What is 'Cross-account IAM Role' benefit?", "options": ["Securely allowing users from one account to perform tasks in another", "Sharing costs", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'AWS Security Token Service' (AWS STS)?", "options": ["The service behind short-term credential generation", "A security guard", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's 'PassRole' permission?", "options": ["Allowing an AWS service (like EC2) to assume a particular role on your behalf", "Passing a role to a person", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Which of these is used for multi-factor authentication?", "options": ["Google Authenticator", "Hardware tokens", "Both", "None"], "correct": 2},
        {"id": 77, "question": "What's 'Virtual MFA Device'?", "options": ["An app on a phone that provides a 6-digit code for login", "A fake device", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's the meaning of 'IAM Inline Policy'?", "options": ["Embedded inside an entity (not reusable)", "Faster policy", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What's the meaning of 'IAM Managed Policy'?", "options": ["Reusable standalone policy (either by AWS or customer)", "Managed by a person", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary way to manage fine-grained access in AWS?", "options": ["Using IAM roles and policies based on users' specific responsibilities", "Sharing root account", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
