import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_iosswift_api(request):
    questions_pool = [
        {"id": 1, "question": "What is the primary OS for iOS development?", "options": ["macOS", "Linux", "Windows", "Both A and B"], "correct": 0},
        {"id": 2, "question": "What is the official IDE for iOS development?", "options": ["Visual Studio", "Xcode", "Android Studio", "IntelliJ IDEA"], "correct": 1},
        {"id": 3, "question": "Which language is currently preferred for modern iOS apps?", "options": ["Objective-C", "Swift", "C#", "Dart"], "correct": 1},
        {"id": 4, "question": "What is 'SwiftUI'?", "options": ["A framework for web only", "Apple's modern, declarative framework for building user interfaces", "A type of table", "None"], "correct": 1},
        {"id": 5, "question": "What is 'UIKit'?", "options": ["The traditional framework for building iOS interfaces using imperative code", "A design tool for icons", "None of the above", "None"], "correct": 0},
        {"id": 6, "question": "What is 'ViewController' in iOS development context?", "options": ["The main person in charge", "A component that manages a single view (screen) and its logic", "A type of chart", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Storyboard' in Xcode?", "options": ["A map for stories", "A visual layout editor to design UI and navigate between views", "A text file of code", "None"], "correct": 1},
        {"id": 8, "question": "What is 'CocoaPods' or 'Swift Package Manager' (SPM)?", "options": ["A type of design flow", "Dependency management tools for iOS and macOS app development", "A list of strings", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Auto Layout' in iOS?", "options": ["Automatically starting an app", "A system that allows you to create responsive UI based on constraints", "A type of screen", "None"], "correct": 1},
        {"id": 10, "question": "What is 'AppDelegate' / 'SceneDelegate' for?", "options": ["To manage the app's overall lifecycle and scene configurations", "To design UI icons", "A security feature", "None"], "correct": 0},
        {"id": 11, "question": "What is 'Optionals' in Swift programming?", "options": ["Things you can skip in code", "A type that can represent either a value or 'nil' (no value)", "A type of table", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Grand Central Dispatch' (GCD)?", "options": ["A central train station", "A low-level library for managing concurrent code and background tasks", "A design language", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Alamofire' commonly used for?", "options": ["A fire alarm system", "A popular third-party library for networking in Swift", "A database engine", "None"], "correct": 1},
        {"id": 14, "question": "What does '.ipa' file represent?", "options": ["iOS App Store Package (installer for iOS devices)", "A design specification", "A type of video", "None"], "correct": 0},
        {"id": 15, "question": "What is 'TestFlight' used for?", "options": ["Developing test cases", "Beta testing iOS applications with selected external/internal users", "A technical specification", "None"], "correct": 1},
        {"id": 16, "question": "What's the meaning of 'Delegation' pattern in iOS?", "options": ["Delegating work to another country", "A design pattern allowing one object to act on behalf of another", "A type of backup", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Core Data'?", "options": ["A primary data structure", "Apple's local data storage framework (replaces SQLite for many users)", "A network protocol", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Singleton' in iOS development context?", "options": ["A single user", "A design pattern where only one instance of a class exists", "A type of error", "None"], "correct": 1},
        {"id": 19, "question": "Which of these is a popular layout system in SwiftUI?", "options": ["VStack (Vertical stack)", "HStack (Horizontal stack)", "ZStack (Depth stack)", "All of the above"], "correct": 3},
        {"id": 20, "question": "What is 'Protocols' in Swift programming?", "options": ["Rules for users", "A blueprint of methods and properties a class/struct must follow", "A technical manual", "None"], "correct": 1},
        {"id": 21, "question": "What's the meaning of 'Closure' in Swift?", "options": ["Closing an app session", "A self-contained block of functionality that can be passed around in code", "A security log", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Swift Playgrounds' used for?", "options": ["A playground for children", "An interactive app to learn Swift and experiment with code", "A design tool", "None"], "correct": 1},
        {"id": 23, "question": "What is 'User Defaults' used for in iOS?", "options": ["Storing large video files", "Storing simple user preferences and settings in key-value pairs", "A security feature", "None"], "correct": 1},
        {"id": 24, "question": "What is 'CloudKit'?", "options": ["A cloud for weather", "Apple's service providing secure cloud storage and data synchronization", "None of the above", "None"], "correct": 1},
        {"id": 25, "question": "Which command-line tool is used for building and managing iOS projects?", "options": ["xcodebuild", "swift cli", "ios-build", "None"], "correct": 0},
        {"id": 26, "question": "What is 'Instruments' tool in Xcode used for?", "options": ["Playing music", "Monitoring and analyzing app performance (memory, CPU, leaked data)", "A tech spec", "None"], "correct": 1},
        {"id": 27, "question": "What is 'San Francisco' in Apple context?", "options": ["A city in California", "The system font for iOS and macOS devices", "Both A and B", "Neither"], "correct": 2},
        {"id": 28, "question": "Which framework is used for developing user interfaces in Swift for older iOS versions?", "options": ["UIKit", "SwiftUI", "WatchKit", "None"], "correct": 0},
        {"id": 29, "question": "What is 'Combine' framework used for?", "options": ["Merging two apps", "Enabling reactive programming by handling asynchronous events and data", "None", "None"], "correct": 1},
        {"id": 30, "question": "What is 'FaceID / TouchID' API used for?", "options": ["Biometric authentication for secure access to app features", "Identifying faces in photos", "None", "None"], "correct": 0},
        {"id": 31, "question": "What is 'XIB' file specifically?", "options": ["XML Interface Builder specifically for designing single UI views visually", "A file for icons", "A types of code", "None"], "correct": 0},
        {"id": 32, "question": "What is 'ARC' (Automatic Reference Counting)?", "options": ["System that automatically manages memory by keeping track of object references", "A math counting tool", "A types of internet speed", "None"], "correct": 0},
        {"id": 33, "question": "What's the meaning of 'Strong' reference?", "options": ["Keeping an object alive specifically as long as the reference exists", "A heavy object", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's the meaning of 'Weak' reference?", "options": ["Reference that doesn't keep the object alive specifically to prevent cycles", "A broken link", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Retain Cycle' in memory management?", "options": ["When two objects have strong references specifically to each other", "A cycle in a game", "A database name", "None"], "correct": 0},
        {"id": 36, "question": "What is 'Unowned' reference?", "options": ["Similar to weak but specifically assumes the object will never be nil", "A stolen object", "A types of math", "None"], "correct": 0},
        {"id": 37, "question": "What is 'Extension' in Swift?", "options": ["Adding new functionality specifically to an existing class or struct", "Downloading a file", "A types of browser tool", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Generic' in Swift programming?", "options": ["Writing flexible, reusable functions specifically that work with any type", "A common object", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Enum' (Enumeration)?", "options": ["Defining a common type specifically for a group of related values", "A types of math equation", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Struct' vs 'Class' in Swift?", "options": ["Value type specifically vs Reference type", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "Which constant is used for 'Self' in Swift?", "options": ["Referring specifically to the current instance of a type", "Referring to everyone", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Property Wrapper' (@State, @Binding)?", "options": ["A types of UI design", "Special syntax specifically to manage how a property is stored and accessed", "Neither", "Both"], "correct": 1},
        {"id": 43, "question": "What represents top-level view in SwiftUI?", "options": ["ContentView", "MainView", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'NavigationStack' in SwiftUI?", "options": ["Managing views specifically for hierarchical navigation", "A list of titles", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Asset Catalog' (Assets.xcassets)?", "options": ["Where icons, images, and colors specifically are stored in Xcode", "A list of files", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Cocoa Touch'?", "options": ["The UI framework specifically for iOS applications development", "Touching a screen", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "How to handle tap gestures in SwiftUI?", "options": ["onTapGesture modifier", "onPress method", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "How to create an alert in SwiftUI?", "options": ["Using the .alert() modifier", "Using print()", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'SF Symbols'?", "options": ["Apple's library specifically of thousands of consistent system icons", "A types of font", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Core Graphics'?", "options": ["Low-level drawing specifically for custom paths and shapes", "Graphic design tool", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What's 'Core Animation'?", "options": ["Framework specifically for managing visual transitions and animations", "A types of film", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'ARKit'?", "options": ["Framework specifically for creating Augmented Reality experiences on iOS", "A kit for cars", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'SceneKit'?", "options": ["High-level 3D graphics framework specifically for games and apps", "A types of stage", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'SpriteKit'?", "options": ["Framework specifically for 2D games development", "A types of drink", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Metal' in iOS?", "options": ["High-performance, low-overhead graphics specifically for GPU tasks", "A physical material", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Provisioning Profile'?", "options": ["Digital certificate specifically used for installing apps on devices", "A settings list", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'App Store Connect'?", "options": ["Web portal specifically used to manage apps for the App Store", "Connecting two apps", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Bundle ID'?", "options": ["Unique identifier specifically for your app on the system", "A types of package", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "How can you check for safe area in iOS?", "options": ["Ensuring UI specifically doesn't overlap with notches or home indicators", "Using a physical ruler", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Dark Mode' specifically for iOS?", "options": ["System-wide color scheme specifically using dark backgrounds", "Turning off screen", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What represents the 'plist' (Property List)?", "options": ["XML file specifically used for storing configuration data like Info.plist", "A list of properties", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What represents the 'Swift Package Manager' (SPM)?", "options": ["Integrated tool specifically for managing code dependencies", "A package for delivery", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Dependency' in iOS projects?", "options": ["External libraries specifically that your app relies on to function", "A person in need", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "How to perform a clean build in Xcode?", "options": ["Shift + Cmd + K", "Cmd + B", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "How to run the app in simulator?", "options": ["Cmd + R", "Cmd + S", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Simulators' in Xcode?", "options": ["Simulating specifically an iPhone or iPad on your Mac screen", "A types of game", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "Can you develop iOS apps on Windows natively?", "options": ["No, it specifically requires macOS and Xcode", "Yes", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's the meaning of 'Sandbox' in iOS security?", "options": ["Restricting app's access specifically to files and hardware for safety", "Playing with sand", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'IDFA'?", "options": ["Identifier for Advertisers specifically used for tracking", "An ID for a fan", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Keychain'?", "options": ["Secure storage specifically for sensitive data like passwords and keys", "A physical chain", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Which constant is used for '@State'?", "options": ["Managing simple local state within a SwiftUI view", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "Which constant is used for '@Binding'?", "options": ["Passing state specifically from one view to another for modification", "Binding a book", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What represents the '@ObservedObject'?", "options": ["An external object specifically that a view monitors for changes", "A physical object", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What represents the '@EnvironmentObject'?", "options": ["An object specifically shared across many views in the app hierarchy", "A types of nature", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'App Group' used for?", "options": ["Sharing data specifically between different apps from the same developer", "A group of friends", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents the 'WidgetKit'?", "options": ["Framework specifically for creating home screen and lock screen widgets", "A types of small tool", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents the 'Live Activity'?", "options": ["Displaying real-time info specifically on the lock screen (e.g. food delivery)", "Being alive", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "How to localise an iOS app?", "options": ["Using .strings files specifically for translated text", "Moving the office", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Universal Link'?", "options": ["Links that open your app specifically instead of a browser when tapped", "A link for everyone", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Swift preferred over Objective-C?", "options": ["Safety, readability, and modern syntax specifically to increase performance", "It has more colors", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
