import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_jdbc_api(request):
    questions_pool = [
        {"id": 1, "question": "What does JDBC stand for?", "options": ["Java Database Connectivity", "Java Digital Business Center", "Joint Data Build Center", "None"], "correct": 0},
        {"id": 2, "question": "What is the primary function of JDBC?", "options": ["Creating UI", "Allowing Java applications to interact with relational databases", "Managing internet speed", "None"], "correct": 1},
        {"id": 3, "question": "What is 'JDBC Driver'?", "options": ["A physical driver", "A software component that enables communication with a specific database", "A type of table", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Connection' in JDBC?", "options": ["A user login session", "A session between a Java application and a database", "A type of chart", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Statement' in JDBC?", "options": ["A legal document", "An interface used to execute static SQL statements", "A type of bank", "None"], "correct": 1},
        {"id": 6, "question": "What is 'PreparedStatement'?", "options": ["A fast SQL", "A pre-compiled SQL statement used for execution efficiency and security", "A security log", "None"], "correct": 1},
        {"id": 7, "question": "What is 'ResultSet' in JDBC?", "options": ["The final result count", "A table representing the results of a database query", "A type of chart", "None"], "correct": 1},
        {"id": 8, "question": "Which method is used to get a database connection?", "options": ["DriverManager.getConnection()", "Connection.start()", "Both A and B", "Neither"], "correct": 0},
        {"id": 9, "question": "Which method executes a query returning a ResultSet?", "options": ["executeUpdate()", "executeQuery()", "fetchResult()", "None"], "correct": 1},
        {"id": 10, "question": "Which method executes a non-query SQL (like INSERT/UPDATE/DELETE)?", "options": ["executeUpdate()", "executeQuery()", "None of the above", "None"], "correct": 0},
        {"id": 11, "question": "What is 'ExecuteBatch()' useful for?", "options": ["Deleting all data", "Performing multiple SQL updates in a single network round-trip", "A design tool", "None"], "correct": 1},
        {"id": 12, "question": "What is a 'JDBC-ODBC Bridge' driver?", "options": ["A type of driver that connects Java applications via ODBC", "A literal physical bridge", "A security token", "None"], "correct": 0},
        {"id": 13, "question": "What is 'Type 4' JDBC driver?", "options": ["A native-protocol all-Java driver", "A server-based driver", "A type of chart", "None"], "correct": 0},
        {"id": 14, "question": "What is 'Batch Update' in JDBC?", "options": ["Updating once a year", "Grouping multiple SQL updates/inserts into one block for performance", "A technical manual", "None"], "correct": 1},
        {"id": 15, "question": "What is 'SQLException'?", "options": ["A successful connection", "An exception thrown by JDBC when errors occur in database access", "None", "None"], "correct": 1},
        {"id": 16, "question": "Which method is used to close a ResultSet?", "options": ["end()", "close()", "stop()", "Done"], "correct": 1},
        {"id": 17, "question": "What is a 'DatabaseMetadata' in JDBC?", "options": ["Data about the database (e.g. name, version, supported features)", "A list of users", "None", "None"], "correct": 0},
        {"id": 18, "question": "What is a 'ResultSetMetadata'?", "options": ["Metadata about the columns and types in a specific ResultSet", "A decorative text", "None", "None"], "correct": 0},
        {"id": 19, "question": "What is 'DriverManager' for JDBC?", "options": ["Managing driver files", "Selecting a driver and facilitating a database connection", "A security log", "None"], "correct": 1},
        {"id": 20, "question": "What is 'CallableStatement'?", "options": ["Calling a person", "Executing stored procedures and functions from a database", "None of the above", "None"], "correct": 1},
        {"id": 21, "question": "What's the meaning of 'Connection Pooling' in JDBC?", "options": ["A set of reusable database connections maintained for efficiency", "Hundreds of databases", "Both", "None"], "correct": 0},
        {"id": 22, "question": "Can JDBC be used with NoSQL databases?", "options": ["No, it is for RDBMS", "Yes, any NoSQL", "Both A and B", "Neither"], "correct": 0},
        {"id": 23, "question": "What is 'JDBC API'?", "options": ["A framework", "A set of classes and interfaces in java.sql for database access", "Both", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Transaction Isolation' in JDBC?", "options": ["Protecting data transactions", "A mechanism to control how changes in one transaction are visible in another", "None", "None"], "correct": 1},
        {"id": 25, "question": "Which method sets the transaction isolation level?", "options": ["setTransactionIsolation()", "modifyIsolation()", "None", "None"], "correct": 0},
        {"id": 26, "question": "Which isolation level is used for preventing dirty reads?", "options": ["READ_COMMITTED", "READ_UNCOMMITTED", "SERIALIZABLE", "None"], "correct": 0},
        {"id": 27, "question": "What is 'AutoCommit' mode set to by default in JDBC?", "options": ["True", "False", "None", "None"], "correct": 0},
        {"id": 28, "question": "How do you disable AutoCommit in JDBC?", "options": ["connection.setAutoCommit(false)", "connection.manualCommit()", "None", "None"], "correct": 0},
        {"id": 29, "question": "Which method commits a manually-managed transaction?", "options": ["connection.commit()", "connection.save()", "None", "None"], "correct": 0},
        {"id": 30, "question": "Which of these is a major component of JDBC framework?", "options": ["DriverManager", "Connection", "Statement", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is the primary benefit of PreparedStatement over Statement?", "options": ["Execution speed and protection from SQL Injection", "Ease of writing code", "Both A and B", "Neither"], "correct": 0},
        {"id": 32, "question": "Which method is used for closing a connection in JDBC?", "options": ["connection.close()", "connection.end()", "connection.stop()", "None"], "correct": 0},
        {"id": 33, "question": "What is the result of 'ResultSet.next()'?", "options": ["Moves the cursor to the next row and returns true if it exists", "Jumps to the end", "None", "None"], "correct": 0},
        {"id": 34, "question": "How can you get column data from a ResultSet?", "options": ["rs.get(columnName)", "rs.getxxx(columnIndex/columnName)", "Both A and B", "Neither"], "correct": 1},
        {"id": 35, "question": "What is 'DataSource' in JDBC context?", "options": ["A source of files", "A standard interface to obtain a connection from a source", "None", "None"], "correct": 1},
        {"id": 36, "question": "Which interface provides better performance using connection pooling?", "options": ["DriverManager", "DataSource", "Statement", "None"], "correct": 1},
        {"id": 37, "question": "What is 'Commit' in JDBC transactions?", "options": ["Saving all changes permanently", "Starting over", "A routing name", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Rollback'?", "options": ["A complete hardware reset", "Canceling all changes in the current transaction branch", "A security log", "None"], "correct": 1},
        {"id": 39, "question": "What is 'Savepoint' in JDBC?", "options": ["A point in a game", "Markers within a transaction to allow partial rollback", "Neither", "Both"], "correct": 1},
        {"id": 40, "question": "How do you set a savepoint in a transaction?", "options": ["connection.setSavepoint()", "connection.mark()", "None", "None"], "correct": 0},
        {"id": 41, "question": "How do you rollback to a specific savepoint?", "options": ["connection.rollback(savepoint)", "connection.undoTo(savepoint)", "None", "None"], "correct": 0},
        {"id": 42, "question": "What is 'RowSet' interface in JDBC package?", "options": ["A set of rows in memory", "A disconnected ResultSet that doesn't keep an open connection", "A type of table", "None"], "correct": 1},
        {"id": 43, "question": "What's the meaning of 'Dirty Read' in database transactions?", "options": ["Reading with errors", "Reading data that was changed by another transaction but not yet committed", "Both", "None"], "correct": 1},
        {"id": 44, "question": "What is 'Non-repeatable Read'?", "options": ["Reading data twice and seeing different results because it changed", "A security bug", "None of the above", "None"], "correct": 0},
        {"id": 45, "question": "What is 'Phantom Read' in database management?", "options": ["Reading data that disappeared", "Reading new rows added by another transaction between two identical reads", "A search tool", "None"], "correct": 1},
        {"id": 46, "question": "Which of these is the most restricted isolation level?", "options": ["TRANSACTION_SERIALIZABLE", "TRANSACTION_READ_COMMITTED", "None", "None"], "correct": 0},
        {"id": 47, "question": "What is 'JdbcTemplate' in Spring framework?", "options": ["A design tool", "A central class that simplifies JDBC operations and handles resources", "A tech spec", "None"], "correct": 1},
        {"id": 48, "question": "What is 'Cursor' in JDBC context?", "options": ["A pointer on a screen only", "A pointer that tracks current location in a ResultSet", "None", "None"], "correct": 1},
        {"id": 49, "question": "Can a ResultSet contain multiple tables?", "options": ["No, it corresponds to one query's result", "Yes", "Only if it is in memory", "None"], "correct": 0},
        {"id": 50, "question": "What is '@Query' annotation used for in modern frameworks building on JDBC?", "options": ["Linking data", "Specifying custom SQL to run for a method", "Both", "None"], "correct": 1},
        {"id": 51, "question": "What is 'JDBC JAR' file for?", "options": ["A library containing the driver implementation for a specific database", "A list of strings", "None", "None"], "correct": 0},
        {"id": 52, "question": "Which of these allows calling a MySQL stored procedure?", "options": ["CallableStatement", "PreparedStatement", "None", "None"], "correct": 0},
        {"id": 53, "question": "What is 'Fetch Size' in Statement interface?", "options": ["Determines the number of rows fetched per trip to the database for performance", "Size of files", "None of the above", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Max Rows' property?", "options": ["Sets the maximum number of rows that can be returned in a ResultSet", "Deletes all rows", "A routing rule", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Query Timeout' property?", "options": ["Sets the maximum time to wait for a database query to complete", "Stops the program", "None of the above", "None"], "correct": 0},
        {"id": 56, "question": "How can you identify the columns in a ResultSet?", "options": ["By Index (starting from 1)", "By Column Name", "Both A and B", "Neither"], "correct": 2},
        {"id": 57, "question": "Which JDBC driver type does not require any local installation of client drivers?", "options": ["Type 3", "Type 4", "None", "None"], "correct": 1},
        {"id": 58, "question": "What is 'JDBC 4.0' feature?", "options": ["Automatic driver loading via Service Provider mechanism", "Faster database connectivity", "None", "None"], "correct": 0},
        {"id": 59, "question": "What is the result of 'DriverManager.getDrivers()'?", "options": ["A list of all currently loaded JDBC drivers", "Formatting text", "None of the above", "None"], "correct": 0},
        {"id": 60, "question": "How do you set a NULL value in a PreparedStatement?", "options": ["stmt.setNull(index, Types.INTEGER)", "stmt.set(null)", "None of the above", "None"], "correct": 0},
        {"id": 61, "question": "What is 'SQL Injection' vulnerability?", "options": ["Injecting malicious SQL through application inputs to manipulate queries", "Deleting files", "Both", "None"], "correct": 0},
        {"id": 62, "question": "Which JDBC component is used to prevent SQL Injection primarily?", "options": ["PreparedStatement", "Statement", "ResultSet", "None"], "correct": 0},
        {"id": 63, "question": "What is 'Database URL'?", "options": ["The help site for the database", "A connection string used to identify a specific database for a driver", "A search tool", "None"], "correct": 1},
        {"id": 64, "question": "What is the common prefix for MySQL JDBC URL?", "options": ["jdbc:mysql://", "java:mysql://", "db:mysql://", "None"], "correct": 0},
        {"id": 65, "question": "What is 'Auto Closeable' for JDBC resources in Java 7+?", "options": ["Manually closing files", "Using 'try-with-resources' to automatically close connections/statements", "None of the above", "None"], "correct": 1},
        {"id": 66, "question": "Which method provides the auto-generated key after an insertion?", "options": ["getGeneratedKeys()", "fetchId()", "None of the above", "None"], "correct": 0},
        {"id": 67, "question": "What is the result of 'stmt.setFetchDirection()'? ", "options": ["Determines forward/backward iteration through ResultSet", "A speed test", "None of the above", "None"], "correct": 0},
        {"id": 68, "question": "How can you get the number of rows changed in an executeUpdate()?", "options": ["The method returns an 'int' with the count", "Using a new query", "None", "None"], "correct": 0},
        {"id": 69, "question": "What is 'BLOB' in JDBC?", "options": ["A large piece of text", "Binary Large OBject (used for storing images, files, etc.)", "None of the above", "None"], "correct": 1},
        {"id": 70, "question": "What is 'CLOB' in JDBC?", "options": ["Character Large OBject (storing massive text data)", "A type of table", "None of the above", "None"], "correct": 0},
        {"id": 71, "question": "How do you store a BLOB in a Prepared Statement?", "options": ["setBlob() or setBinaryStream()", "setFile()", "None", "None"], "correct": 0},
        {"id": 72, "question": "Can you scroll backwards in a default ResultSet?", "options": ["No (only forward unless TYPE_SCROLL_SENSITIVE or INSENSITIVE)", "Yes", "Both", "None"], "correct": 0},
        {"id": 73, "question": "What is 'Updatable ResultSet'?", "options": ["Updating and viewing files", "A ResultSet that allows modifying data directly and projecting those changes back to DB", "None", "None"], "correct": 1},
        {"id": 74, "question": "What is the result of 'stmt.addBatch()'?", "options": ["Adding a single SQL to a local list for later bulk execution", "Adding people to a group", "Both A and B", "None"], "correct": 0},
        {"id": 75, "question": "What is 'SQLWarning'?", "options": ["A fatal error", "A subclass of Exception for information about database access warnings", "None", "None"], "correct": 1},
        {"id": 76, "question": "What is 'DriverManager.setLoginTimeout()' for?", "options": ["Sets the maximum log in time for a user", "Sets the maximum time to wait for a database connection to open", "Both", "None"], "correct": 1},
        {"id": 77, "question": "Which command is used to load a driver manually in older JDBC versions?", "options": ["Class.forName('com.mysql.cj.jdbc.Driver')", "Driver.load()", "Both", "None"], "correct": 0},
        {"id": 78, "question": "What is 'JdbcRowSet' vs 'CachedRowSet'?", "options": ["JdbcRowSet keeps connection; CachedRowSet is disconnected", "They are identical", "None", "None"], "correct": 0},
        {"id": 79, "question": "Which API should you generally use in modern Java applications instead of raw JDBC for big projects?", "options": ["Spring Data JPA / Hibernate", "Raw SQL only", "None", "None"], "correct": 0},
        {"id": 80, "question": "What is 'Database Connection URI'?", "options": ["Another name for the JDBC URL", "A server address", "None of the above", "None"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
