import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_k8sbasics_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Kubernetes (K8s)?", "options": ["8 computers in a row", "An open-source system for automating deployment and management of containers", "A web browser", "None"], "correct": 1},
        {"id": 2, "question": "What is 'Container Orchestration'?", "options": ["Managing hundreds of containers with automation for scaling and availability", "A music concert", "Neither", "Both"], "correct": 0},
        {"id": 3, "question": "What is a 'Cluster' in K8s?", "options": ["A set of machines (nodes) that run containerized applications in K8s", "A group of stars", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is a 'Node'?", "options": ["A point in a network", "A physical or virtual machine in a cluster that runs Pods", "Neither", "Both"], "correct": 1},
        {"id": 5, "question": "What is a 'Pod'?", "options": ["Smallest deployable unit in K8s (containing one or more containers)", "A group of whales", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'Control Plane'?", "options": ["Managing the K8s cluster's overall state and coordinating nodes", "An airplane cockpit", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'kubectl'?", "options": ["A command line tool to control and manage K8s clusters", "A key to a lock", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is a 'Deployment'?", "options": ["Managing desired state for a group of identical Pods automatically", "Deploying a physical server", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'ReplicaSet'?", "options": ["A set of replica watches", "Used to maintain a stable set of replica Pods running at any time", "Neither", "Both"], "correct": 1},
        {"id": 10, "question": "What is 'Service' in K8s?", "options": ["Assisting people", "An abstraction to expose an application running on a set of Pods as a network service", "Both", "None"], "correct": 1},
        {"id": 11, "question": "What is 'ClusterIP' Service?", "options": ["The default internal service type for communication ONLY inside cluster", "A public IP", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'NodePort' Service?", "options": ["Exposing a service on a static port on each node's physical IP address", "A port in a harbor", "Neither", "Both"], "correct": 1},
        {"id": 13, "question": "What is 'LoadBalancer' Service?", "options": ["Automatically creating an external cloud load balancer for a service", "A scale for weighing", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Ingress' in K8s?", "options": ["Managing external access (like HTTP) to the services inside a cluster", "Looking inside", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Namespace'?", "options": ["A name for a space", "A virtual partition for isolating resources within a single K8s cluster", "Neither", "Both"], "correct": 1},
        {"id": 16, "question": "What is 'ConfigMap' for?", "options": ["A map of configs", "A way to inject configuration data separately into Pods as files or env vars", "Both", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Secret' in K8s?", "options": ["A secret for a person", "A mechanism specifically to store and manage sensitive info (like password, tokens)", "Both", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Volume' in K8s?", "options": ["Sound level", "A mechanism to provide persistent or temporary storage to one or more Pods", "Neither", "Both"], "correct": 1},
        {"id": 19, "question": "What is 'PersistentVolume' (PV)?", "options": ["The cluster's actual piece of storage provisioned by an administrator", "Storage specifically for books", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'PersistentVolumeClaim' (PVC)?", "options": ["A user's request specifically for a piece of storage in the K8s cluster", "Writing a claim for money", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Scheduler's role?", "options": ["Deciding which node a new Pod should run on based on resource availability", "Scheduling meetings", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What's 'kube-apiserver'?", "options": ["The central hub of the K8s control plane that exposes the K8s API", "A types of computer", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'etcd'?", "options": ["A high-performance cluster backend database that stores all K8s state data", "A text file of names", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'Kubelet'?", "options": ["The agent that runs on each node to ensure containers are running in Pods", "A small key", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'kube-proxy'?", "options": ["Directing incoming network traffic to the correct Pods via load balancing", "A person who votes for you", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What's the meaning of 'Desired State'?", "options": ["The configuration of resources you want the cluster to maintain automatically", "A state in USA", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Self-Healing' in K8s?", "options": ["Automatically restarting or replacing failed Pods and nodes", "Healing a person", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Horizontal Pod Autoscaler' (HPA)?", "options": ["Automatically scaling the number of Pods up or down based on CPU/RAM usage", "A types of chart", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'YAML' in K8s significance?", "options": ["The common language used to define and configure K8s manifests", "A new computer game", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Who created Kubernetes?", "options": ["Google", "Microsoft", "Amazon", "IBM"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'KEDA'?", "options": ["Kubernetes-based Event Driven Autoscaling", "A types of fruit", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Helm'?", "options": ["A package manager for K8s facilitating easier installation with Charts", "Steering a ship", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Helm Chart'?", "options": ["A collection of YAML manifests for deploying an entire K8s application", "A music ranking", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'KIND'? ", "options": ["Being nice to others", "Kubernetes IN Docker (running clusters inside Docker containers for local testing)", "Both", "None"], "correct": 1},
        {"id": 35, "question": "What's 'Minikube'?", "options": ["A small computer", "A tool that makes it easy to run a single-node K8s cluster locally", "Both", "None"], "correct": 1},
        {"id": 36, "question": "What is 'StatefulSet' used for?", "options": ["Managing stateful apps (like databases) that need unique identities and storage", "Grouping people by state", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's 'DaemonSet' signature?", "options": ["Ensuring a specific Pod runs on EVERY node in the cluster automatically", "A signature from a ghost", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Job' object in K8s?", "options": ["Searching for work", "A controller that runs a Pod to completion (success) then stops", "Neither", "Both"], "correct": 1},
        {"id": 39, "question": "What is 'CronJob'?", "options": ["A job for time", "A Job specifically planned to run on a set schedule (periodic)", "Neither", "Both"], "correct": 1},
        {"id": 40, "question": "What's the meaning of 'Labels' and 'Selectors'?", "options": ["Key-value pairs to organize and select specific sets of K8s resources", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Annotation' in K8s manifest?", "options": ["Adding extra non-identifying metadata to a resource (e.g. info, documentation)", "Writing notes on a book", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's 'RollingUpdate' strategy?", "options": ["The default update strategy: gradually replacing old Pods without downtime", "Rolling a ball", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'Recreate' strategy?", "options": ["Terminating all old Pods before starting new ones (causes downtime)", "Starting over at zero", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Liveness Probe'?", "options": ["Determining if a container is alive (restarts it if not)", "Checking if a person is breathing", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's 'Readiness Probe'?", "options": ["Checking if a container is ready to accept actual network traffic", "A test for readiness", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's 'Startup Probe'?", "options": ["Checking if an app has properly initialized (especially for slow-starting apps)", "Starting a company", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Sidecar' pattern?", "options": ["Adding a helper container alongside a main one in the same Pod", "A motorcycle part only", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Resource Limits'?", "options": ["Max amount of CPU/Memory a container is allowed to use", "Limit for people", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Resource Requests'?", "options": ["Minimum amount of CPU/Memory a container guaranteed to get", "Asking for money", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'OOMKilled' mean in Pod logs?", "options": ["Out of Memory: K8s killed the container for exceeding its allocated limit", "An error with computer", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Controller Manager'?", "options": ["A system that runs different controller loops for node and job management", "Managing a controller", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's 'Cloud Controller Manager'?", "options": ["Managing interaction specifically with the underlying cloud provider (e.g. AWS)", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Taints' and 'Tolerations' for?", "options": ["Node can repel Pods (Taints) and Pods can admit them (Tolerations)", "Matching colors", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Affinity' and 'Anti-affinity'?", "options": ["Controlling which nodes a Pod should (Affinity) or shouldn't (Anti-affinity) run on", "Liking and disliking nodes", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "How can you view Pods using kubectl?", "options": ["kubectl get pods", "kubectl list", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "How can you view details of a specific Pod?", "options": ["kubectl describe pod pod_name", "kubectl see pod", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "How can you view logs of a running Pod?", "options": ["kubectl logs pod_name", "kubectl check", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "How do you apply a YAML manifest to a cluster?", "options": ["kubectl apply -f filename.yaml", "kubectl start", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How do you delete a resource using kubectl?", "options": ["kubectl delete -f filename.yaml", "kubectl remove", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'RBAC' in K8s?", "options": ["Restricting access based on user roles and permissions in the cluster", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'ServiceAccount'?", "options": ["An identity specifically for processes running in Pods to access the K8s API", "A bank account for servers", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'ClusterRole' versus 'Role'?", "options": ["Cluster-wide perms vs specific namespace perms", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'Horizontal Autoscaling' versus 'Vertical Autoscaling' (VPA)?", "options": ["Adding more Pods vs making the existing ones bigger (more CPU/RAM)", "One is horizontal", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's 'Managed Kubernetes' (e.g. EKS, GKE, AKS)?", "options": ["Cloud providers managing the complex Control Plane on your behalf", "Managing it ourselves", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Kubernetes Dashboard'?", "options": ["A web-based GUI for visual monitoring and cluster management", "A physical sign in K8s", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Lens' or 'K9s' in K8s tools?", "options": ["Popular third-party GUI/CLI tools for easier cluster management", "A spectacles brand", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'ArgoCD' or 'Flux' used for?", "options": ["Implementing GitOps for automated, version-controlled K8s deployments", "Starting a business", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's the meaning of 'Stateless' apps in K8s?", "options": ["Applications that don't need to store any data locally (e.g. web servers)", "Apps from one state only", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's the meaning of 'Stateful' apps (e.g. Databases)?", "options": ["Applications that need persistent, stable storage across restarts", "Apps for many states", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Which constant represents the API version at the top of a manifest?", "options": ["apiVersion", "version", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's the meaning of 'Metadata' section in YAML?", "options": ["Adding names, namespaces, and labels to the resource", "A technical spec", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'Spec' section for?", "options": ["Defining the desired state/configuration (e.g. 5 replicas, image name)", "Technical drawings", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Status' section for (automatically created)?", "options": ["Showing the current, actual state of the resource in the cluster", "Manually adding notes", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "How do you check for K8s cluster errors?", "options": ["kubectl get events", "Guessing", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What signifies a 'Running' Pod?", "options": ["Its status column shows 'Running' and all containers are ready", "A green screen", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What's 'Ready' column for (e.g. 1/1)?", "options": ["Indicates how many containers in the Pod have successfully passed readiness checks", "Counting books", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "Can one Pod contain more than one container?", "options": ["Yes, if they share common resources like local network/storage", "No", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Container Port' importance in Pod manifest?", "options": ["Specifying which port the container should listen on within its sandbox", "A port for harbor", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is K8s essential for modern cloud-native apps?", "options": ["Automates scaling, reliability, and deployment at massive scales with ease", "Faster internet speed", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Kubernetes Dashboard'?", "options": ["Web UI for managing Kubernetes clusters", "Dashboard for K8s", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'kubectl'?", "options": ["Command-line tool for Kubernetes", "Kubernetes control", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Helm'?", "options": ["Package manager for Kubernetes applications", "Tool for K8s", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Kustomize'?", "options": ["Template configuration for Kubernetes", "Customizing K8s", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Operator' in Kubernetes?", "options": ["Custom controller for managing applications", "Kubernetes operator", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'CRD' (Custom Resource Definition)?", "options": ["Extension of Kubernetes API", "Custom resource definition", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Service Mesh'?", "options": ["Infrastructure for service-to-service communication", "Mesh for services", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Ingress' in Kubernetes?", "options": ["Managing external access to services", "Entry point for traffic", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Network Policy'?", "options": ["Controlling traffic flow between pods", "Policy for networking", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Persistent Volume'?", "options": ["Storage that persists beyond pod lifetime", "Volume that persists", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'ConfigMap'?", "options": ["Configuration data for applications", "Map of configuration", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Secret'?", "options": ["Sensitive configuration data", "Hidden configuration", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Horizontal Pod Autoscaler'?", "options": ["Automatically adjusting pod count", "Scaling pods horizontally", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Vertical Pod Autoscaler'?", "options": ["Automatically adjusting pod resources", "Scaling pods vertically", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'StatefulSet'?", "options": ["Controller for stateful applications", "Set with state", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'DaemonSet'?", "options": ["Controller for background tasks", "Set of daemons", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Job' in Kubernetes?", "options": ["Controller for batch processing", "Task controller", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'CronJob'?", "options": ["Scheduled job controller", "Time-based job", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Pod Disruption Budget'?", "options": ["Policy for voluntary disruptions", "Budget for disruptions", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Resource Quota'?", "options": ["Limiting resource usage per namespace", "Quota for resources", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
