import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_ml_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Machine Learning?", "options": ["Learning through books", "A branch of AI that focus on data and algorithms to imitate how humans learn", "A programming language", "None"], "correct": 1},
        {"id": 2, "question": "What are the three main types of Machine Learning?", "options": ["Fast, Slow, Medium", "Supervised, Unsupervised, Reinforcement Learning", "Java, C, Python", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Supervised Learning'?", "options": ["Watching humans learn", "Learning on a labeled dataset where each training example has an output", "Both A and B", "Neither"], "correct": 1},
        {"id": 4, "question": "What is 'Unsupervised Learning'?", "options": ["Finding hidden patterns in unlabeled data", "Learning with a teacher", "Predicting a final score", "None"], "correct": 0},
        {"id": 5, "question": "What is 'Reinforcement Learning'?", "options": ["Reinforcing old code", "Learning by trial and error through an agent interacting with an environment", "A security log", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Classification' used for?", "options": ["Predicting continuous values", "Predicting a discrete label or class (e.g. Cat vs Dog, Spam vs Inbox)", "Neither", "Both"], "correct": 1},
        {"id": 7, "question": "What is 'Regression' used for?", "options": ["Predicting continuous outcomes (like house price, temperature)", "Selecting rows in a database", "Both A and B", "Neither"], "correct": 0},
        {"id": 8, "question": "What is a 'Feature' in Machine Learning?", "options": ["A special part of a car", "An individual measurable property or characteristic used in a model", "Neither", "Both"], "correct": 1},
        {"id": 9, "question": "What is a 'Label' or 'Target'?", "options": ["The output we want the model to predict", "A bookmark", "A type of chart", "None"], "correct": 0},
        {"id": 10, "question": "What is 'Training Set'?", "options": ["A group of people", "The subset of data used to train the machine learning algorithm", "Neither", "Both"], "correct": 1},
        {"id": 11, "question": "What is 'Test Set'?", "options": ["Independent data subset used to evaluate the model's accuracy on new data", "A set of physical tests", "Both", "None"], "correct": 0},
        {"id": 12, "question": "What is 'Underfitting'?", "options": ["Model is too simple and fails to capture patterns in training data", "A small model", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Overfitting'?", "options": ["Model learns the training data too well (including noise), failing on new data", "Too many features", "Both", "None"], "correct": 0},
        {"id": 14, "question": "What is 'Cross-Validation'?", "options": ["Validating math", "A technique to evaluate model performance by splitting data multiple times", "A design tool", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Linear Regression'?", "options": ["A math line only", "An algorithm that models relationship between variables with a straight line", "A security log", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Logistic Regression'?", "options": ["Regression for logs", "A classification algorithm used to predict probability of a binary output", "Both", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Decision Tree'?", "options": ["A physical tree", "A model that makes decisions using a tree-like structure of choices", "Both", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Random Forest'?", "options": ["A group of physical trees", "An ensemble model that uses multiple decision trees for better accuracy", "Neither", "Both"], "correct": 1},
        {"id": 19, "question": "What is 'K-Nearest Neighbors' (KNN)?", "options": ["Finding friends", "A classification algorithm based on similarity and proximity of neighbors", "Both", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Support Vector Machine' (SVM)?", "options": ["A support server", "An algorithm that finds a hyperplane to best separate classes in data", "Both", "None"], "correct": 1},
        {"id": 21, "question": "What's the meaning of 'Hyperparameters'?", "options": ["Parameters set before training the model that control the learning process", "Fast parameters", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What is 'Grid Search' used for?", "options": ["Searching for items in a grid", "Systematically working through multiple combinations of hyperparameters to find best", "A security log", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Clustering' in ML?", "options": ["Grouping people together", "Groupings of similar data points (unsupervised) like customers or patterns", "Neither", "Both"], "correct": 1},
        {"id": 24, "question": "What is 'K-Means'?", "options": ["A math average", "A popular clustering algorithm that groups data points around K centers", "Both", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Dimensionality Reduction' for?", "options": ["Making a screen smaller", "Reducing the number of input variables in a dataset (e.g. using PCA)", "Neither", "Both"], "correct": 1},
        {"id": 26, "question": "What is 'Neural Network'?", "options": ["Model inspired by human brain node connections, used in deep learning", "A computer chip", "Both A and B", "Neither"], "correct": 0},
        {"id": 27, "question": "What is 'Deep Learning'?", "options": ["Deep thinking", "Subfield of ML based on artificial neural networks with many layers", "Both", "Both of these"], "correct": 1},
        {"id": 28, "question": "What is 'Gradient Descent'?", "options": ["Descending a mountain", "An optimization algorithm used to minimize the cost (error) of a model", "A design tool", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Regularization' (L1, L2)?", "options": ["Making code regular", "Techniques used to prevent overfitting by penalizing complex models", "Both", "None"], "correct": 1},
        {"id": 30, "question": "Which Python library is the industry standard for traditional ML algorithms?", "options": ["Scikit-learn", "Requests", "Bottle", "Flask"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is the 'Cost Function'?", "options": ["Calculating price", "A mathematical formula measuring the model's error (difference from actual values)", "Both", "None"], "correct": 1},
        {"id": 32, "question": "What is a 'Neural network layer'?", "options": ["Input, Hidden, and Output layers made of interconnected nodes", "A physical sheet", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Loss' in training context?", "options": ["Losing money", "Total error of the model across the entire dataset", "Both", "None"], "correct": 1},
        {"id": 34, "question": "What is the result of 'Bias' in ML?", "options": ["The error from overly simple assumptions in the learning algorithm", "A specific group", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Variance' in ML?", "options": ["Small differences in code", "How much the model changes in response to small variations in training data", "Neither", "Both"], "correct": 1},
        {"id": 36, "question": "What's 'Bias-Variance Tradeoff'?", "options": ["The balance between model complexity and error to minimize total error", "A financial term", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Precision'?", "options": ["Correctness of positive predictions out of all predicted positives", "The accuracy", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Recall'?", "options": ["Proportion of actual positives that were correctly identified", "Thinking back", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'F1-Score' primarily used for?", "options": ["Single metric for accuracy/precision/recall tradeoff using harmonic mean", "A racing score", "Both", "None"], "correct": 0},
        {"id": 40, "question": "What is 'Confusion Matrix'?", "options": ["A table used to evaluate classification performance showing TP, FP, TN, FN", "An error code", "Both", "None"], "correct": 0},
        {"id": 41, "question": "What is 'Standardization'?", "options": ["Formatting data to have mean=0 and std=1", "Deleting records", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's the meaning of 'One-Hot Encoding'?", "options": ["Turning categorical features into a binary vector specifically for models", "Cooking data", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Feature Scaling'?", "options": ["Using a ruler on a chart", "Preparing numerical data for training to prevent large numbers dominating the result", "Neither", "Both"], "correct": 1},
        {"id": 44, "question": "What is 'Imputation'?", "options": ["Method for handling missing data by filling with median/mean/mode", "None of the above", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'PCA' (Principal Component Analysis)?", "options": ["An unsupervised technique to reduce dimensions by finding new, orthogonal axes", "A security log", "Both", "None"], "correct": 0},
        {"id": 46, "question": "What is 'Ensemble Learning'?", "options": ["Using multiple models and combining their results for better predictive power", "Learning in a group", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Bagging'?", "options": ["Ensemble technique using parallel models like Random Forest", "Packing bags", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Boosting'?", "options": ["Increasing speed", "Ensemble technique where models are built sequentially with each fixing its predecessor's errors", "Neither", "Both"], "correct": 1},
        {"id": 49, "question": "Which of these is a popular boosting algorithm?", "options": ["XGBoost", "AdaBoost", "LightGBM", "All of the above"], "correct": 3},
        {"id": 50, "question": "What is 'Naive Bayes' algorithm?", "options": ["A probabilistic classifier based on Bayes' Theorem with independence assumption", "A search tool", "Both", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Natural Language Processing' (NLP)?", "options": ["Machines understanding and interacting with human speech and text", "Learning languages for people", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Computer Vision'?", "options": ["Ability of machines to see and interpret visual information like images/video", "Better glasses", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'CNN' (Convolutional Neural Network)?", "options": ["A news channel only", "A type of deep neural network specifically designed for processing structured grids like images", "Neither", "Both"], "correct": 1},
        {"id": 54, "question": "What is 'RNN' (Recurrent Neural Network)?", "options": ["A type of neural network designed specifically for sequence data (like text or speech)", "Repeating code", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'LSTM' (Long Short-Term Memory)?", "options": ["A special kind of RNN capable of learning long-term dependencies", "A memory card", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Transfer Learning'?", "options": ["Transferring money", "Reusing a pre-trained model on a new, related task to save training time/resources", "Neither", "Both"], "correct": 1},
        {"id": 57, "question": "What is 'Backpropagation'?", "options": ["Propagating back to home", "The primary algorithm used to update weights in neural network during training", "Neither", "Both"], "correct": 1},
        {"id": 58, "question": "What is 'Epoch' versus 'Iteration'?", "options": ["Epoch is full pass over data; Iteration is one batch pass", "One is for math", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Stochastic Gradient Descent' (SGD)?", "options": ["Using only one random data point at a time for updates to speed up training", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Dropout' in deep learning?", "options": ["Dropping out of school", "Randomly ignoring nodes during training to prevent overfitting", "None", "None"], "correct": 1},
        {"id": 61, "question": "What's the meaning of 'Early Stopping'?", "options": ["Stopping the program accidentally", "A regularization technique where training stops early when performance stops improving", "Neither", "Both"], "correct": 1},
        {"id": 62, "question": "What is 'Hyperparameter Tuning'?", "options": ["Systematically finding the optimal configuration for a model", "A performance report", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'MLOps'?", "options": ["Managing both Machine Learning and IT Operations (deployment, monitoring, versioning)", "A mobile phone model", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Data Leakage' in ML?", "options": ["When test information accidentally leaks into the training process", "Deleting records", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'ROC Curve'?", "options": ["A curve for rocks", "A graph showing performance of classification model at different thresholds", "Both", "None"], "correct": 1},
        {"id": 66, "question": "What is 'AUC'?", "options": ["Area Under the (ROC) Curve as a single value for performance", "A security log", "Both", "None"], "correct": 0},
        {"id": 67, "question": "Which of these libraries is used for deep learning?", "options": ["TensorFlow", "PyTorch", "Keras", "All of the above"], "correct": 3},
        {"id": 68, "question": "What is 'AutoML'?", "options": ["Automatically driving cars", "Tools that automate the process of choosing models and hyperparameters", "Both", "None"], "correct": 1},
        {"id": 69, "question": "What's 'Anomaly Detection'?", "options": ["Detecting unusual pattern or outliers in data (e.g. fraud, error)", "Deleting code", "Both", "None"], "correct": 0},
        {"id": 70, "question": "What's the meaning of 'Cold Start' in recommendation systems?", "options": ["Starting a computer in winter", "The difficulty of recommending to new users with zero history", "Neither", "Both"], "correct": 1},
        {"id": 71, "question": "What is 'Collaborative Filtering'?", "options": ["Recommendation system technique based on user similarities and shared behavior", "Filtering data", "Both", "None"], "correct": 0},
        {"id": 72, "question": "What is 'Content-Based Filtering'?", "options": ["Recommending items similar to those a user has liked based on item features", "Reading content", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Feature Importance'?", "options": ["How much each input variable contribute to the model's predictions", "Deleting data", "Both", "None"], "correct": 0},
        {"id": 74, "question": "What is 'Model Persistence'?", "options": ["Continuously training a model", "Saving and loading a trained model (using e.g. pickle, joblib)", "Both", "None"], "correct": 1},
        {"id": 75, "question": "What's 'Word Embedding' (e.g. Word2Vec)?", "options": ["Representing words as dense vectors of numbers reflecting their meaning", "A dictionary", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Active Learning'?", "options": ["Learning while exercising", "A framework where the model can query a user to label specific difficult points", "Neither", "Both"], "correct": 1},
        {"id": 77, "question": "What is 'Semi-supervised Learning'?", "options": ["Learning half the time", "Combining a small amount of labeled data with a large amount of unlabeled data", "Both", "None"], "correct": 1},
        {"id": 78, "question": "Which of these is a typical business use case for ML?", "options": ["Fraud Detection", "Customer Churn Prediction", "Personalized Recommendation", "All of the above"], "correct": 3},
        {"id": 79, "question": "What's 'Explainable AI' (XAI)?", "options": ["AI that can explain its decisions and output", "A simple model", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What's the primary benefit of ML?", "options": ["Automating complex decisions and recognizing invisible patterns at scale", "Starting a business", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Supervised Learning'?", "options": ["Training models on labeled data", "Learning with supervision", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Unsupervised Learning'?", "options": ["Finding patterns in unlabeled data", "Learning without supervision", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Reinforcement Learning'?", "options": ["Learning through rewards and punishments", "Learning with reinforcement", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Feature Engineering'?", "options": ["Creating new features from existing data", "Engineering features", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Model Selection'?", "options": ["Choosing best algorithm for task", "Selecting models", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Cross-Validation'?", "options": ["Evaluating model performance on multiple data splits", "Validating across folds", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Hyperparameter Tuning'?", "options": ["Optimizing model parameters", "Tuning hyperparameters", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Ensemble Learning'?", "options": ["Combining multiple models", "Learning with ensembles", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Bagging'?", "options": ["Bootstrap aggregating with replacement", "Putting models in bags", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Boosting'?", "options": ["Sequential ensemble learning", "Boosting model performance", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Random Forest'?", "options": ["Ensemble of decision trees", "Forest of random trees", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Support Vector Machine' (SVM)?", "options": ["Classification with maximum margin", "Machine for support", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'K-Means Clustering'?", "options": ["Unsupervised clustering algorithm", "Clustering with K means", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Hierarchical Clustering'?", "options": ["Building cluster hierarchy", "Clustering with hierarchy", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Principal Component Analysis' (PCA)?", "options": ["Dimensionality reduction technique", "Analyzing principal components", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Linear Regression'?", "options": ["Predicting continuous values", "Regression with lines", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Logistic Regression'?", "options": ["Classification with sigmoid output", "Regression for logistics", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Decision Tree'?", "options": ["Tree-based decision model", "Tree for decisions", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Neural Network'?", "options": ["Computing system inspired by brain", "Network of neurons", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Model Deployment'?", "options": ["Putting models into production", "Deploying models", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
