import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_azure_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Microsoft Azure?", "options": ["A types of sky", "A cloud computing platform by Microsoft for building and managing apps", "A web browser", "None"], "correct": 1},
        {"id": 2, "question": "What are the three main service models in Azure?", "options": ["SaaS, PaaS, IaaS", "Speed, Storage, Security", "Java, C, Python", "None"], "correct": 0},
        {"id": 3, "question": "What is 'Azure Portal'?", "options": ["A website for news", "A web-based interface used to manage all your Azure resources manually", "Both", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Resource Group' in Azure?", "options": ["A group of people", "A container that holds related resources for an Azure solution", "Neither", "Both"], "correct": 1},
        {"id": 5, "question": "What is 'Virtual Machine' (Azure VM)?", "options": ["A cloud server (IaaS) that runs Windows or Linux", "A physical machine", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'Azure App Service'?", "options": ["A PaaS for building, deploying, and scaling web applications quickly", "A phone app", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'Azure SQL Database'?", "options": ["A fully managed relational database service based on SQL Server", "A local SQL file", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Azure Storage Account'?", "options": ["Storing physical money", "A secure account for storing various data like blobs, files, queues, and tables", "A bank account", "Neither"], "correct": 1},
        {"id": 9, "question": "What is 'Blob Storage' for?", "options": ["Storing blobs of paint", "Storing massive amounts of unstructured data (e.g. images, videos, logs)", "Neither", "Both"], "correct": 1},
        {"id": 10, "question": "What's the meaning of 'LRS' (Locally Redundant Storage)?", "options": ["Storing data thrice within a single data center for low cost", "Local server storage", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'GRS' (Geo-Redundant Storage)?", "options": ["Replicating data across two distant regions for maximum durability", "A high speed storage", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'Azure Active Directory' (Azure AD / Entra ID)?", "options": ["Managing identities and access to cloud apps and resources", "A phone directory", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Azure Virtual Network' (VNet)?", "options": ["Allows various Azure resources to securely communicate with each other privately", "A home WiFi network", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Network Security Group' (NSG)?", "options": ["A virtual firewall that controls inbound and outbound traffic for Azure VNets", "A group for guard", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Azure Load Balancer'?", "options": ["Distributing incoming traffic across multiple VMs to ensure HA", "A physical scale", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Azure Functions'?", "options": ["Math functions in Azure", "A serverless, event-driven compute service to run small pieces of code", "Both", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Azure Cosmos DB'?", "options": ["A globally distributed, multi-model NoSQL database service", "A planet in space", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What's the role of 'Azure DevOps'?", "options": ["A suite of tools for planning, building, testing, and deploying software", "Managing cloud resources only", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Azure ARM Template' (Azure Resource Manager)?", "options": ["Modeling and deploying Azure infrastructure using JSON files (IaC)", "A design tool", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Azure Kubernetes Service' (AKS)?", "options": ["Managing and orchestrating containerized apps automatically", "A news station", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Availability Set'?", "options": ["Grouping VMs to ensure at least one is available during maintenance/failures", "A set of clothes", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What is 'Availability Zone' in Azure?", "options": ["Physically unique locations within a region with independent power/network", "A safe house", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'Azure Advisor'?", "options": ["A person from Microsoft", "A tool providing recommendations to optimize costs, security, and performance", "Both", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Azure Free Account'?", "options": ["Includes specific amount of free services for 12 months for new users", "A social media account", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Azure Cost Management'?", "options": ["Tracking and controlling your cloud spending across the Azure environment", "Managing an office budget", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Azure Marketplace'?", "options": ["A place to buy physical food", "Online store for thousands of certified third-party apps and services for Azure", "Both", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Azure Key Vault'?", "options": ["Safe storage for secrets like passwords, keys, and certificates", "A physical locker", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Azure Monitor'?", "options": ["Watching TV in Azure", "A central place to collect, analyze, and act on telemetry from your cloud", "Both", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Log Analytics' in Azure?", "options": ["Searching logs using a query language to gain insights into system behavior", "Reading books", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "What is 'Azure Subscription'?", "options": ["Paying for a gym", "A logical unit for billing and resource management linked to an Azure account", "Neither", "Both"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Azure ExpressRoute'?", "options": ["A fast train in Azure", "Provides a private, dedicated physical connection from your facility to Azure", "Neither", "Both"], "correct": 1},
        {"id": 32, "question": "What is 'Azure Traffic Manager'?", "options": ["DNS-based load balancer for directing traffic globally based on various rules", "A person for traffic", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Azure Application Gateway'?", "options": ["Web traffic load balancer (Layer 7) allowing you to manage web traffic", "A gateway for people", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'WAF' in Azure?", "options": ["Web Application Firewall to protect web apps from common exploits like SQLi", "A design of text", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Azure Front Door'?", "options": ["Entrance of a building", "Global, scalable entry point for web apps using CDN for better speed", "Neither", "Both"], "correct": 1},
        {"id": 36, "question": "What is 'Azure Container Registry' (ACR)?", "options": ["Private registry for storing and managing Docker container images", "A folder of containers", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Azure Container Instances' (ACI)?", "options": ["Running containers easily without needing to manage full VMs or AKS", "A container in a port", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Azure Logic Apps'?", "options": ["A cloud service that helps schedule, automate, and orchestrate various tasks", "Math logic in Azure", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Azure Data Factory'?", "options": ["Building physical machines", "A managed cloud data integration service for automating data movement (ETL)", "Neither", "Both"], "correct": 1},
        {"id": 41, "question": "What is 'Azure Synapse Analytics'?", "options": ["A combination of data warehousing and big data analytics for fast insights", "A news app", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Azure Databricks'?", "options": ["Apache Spark-based analytics platform optimized specifically for Azure", "A building material", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Azure Cognitive Services'?", "options": ["Pre-built AI APIs (Vision, Speech, Language) for developers", "People thinking in Azure", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Azure Machine Learning'?", "options": ["Building and deploying custom machine learning models at scale", "Learning about clouds", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Azure IoT Hub'?", "options": ["Central message hub for bi-directional communication with IoT devices", "A physical hub for wires", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Azure Site Recovery'?", "options": ["Helping recover a building", "A cloud disaster recovery service ensuring business continuity during outages", "Neither", "Both"], "correct": 1},
        {"id": 47, "question": "What is 'Azure Backup'?", "options": ["Backing up a car", "Simple, reliable cloud-based backup for on-premises and Azure data", "Neither", "Both"], "correct": 1},
        {"id": 48, "question": "What's the role of 'Azure Policy'?", "options": ["Managing corporate standards and compliance by enforcing rules on resources", "A document for users", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'RBAC' in Azure?", "options": ["Managing permissions based on user roles and job functions securely", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Azure Region Pair'?", "options": ["Pairing two regions together for automated replication and disaster recovery", "Couples in Azure", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "Which of these is an Azure compute service?", "options": ["VM", "App Service", "Functions", "All of the above"], "correct": 3},
        {"id": 52, "question": "What is 'Azure B2C'?", "options": ["Business-to-Consumer identity management for web and mobile apps", "A model of bus", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Azure Sentinel' (Microsoft Sentinel)?", "options": ["A cloud-native SIEM/SOAR solution for advanced security across the enterprise", "A security guard", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Azure CLI' vs 'PowerShell'?", "options": ["Cross-platform command line vs Windows shell for managing Azure", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Azure Blueprints'?", "options": ["Drawing a floor plan", "A way to repeatable deploy and update environments with compliant resources", "Neither", "Both"], "correct": 1},
        {"id": 56, "question": "What's 'Azure Graph' (Microsoft Graph)?", "options": ["Gateway to data and intelligence in Microsoft 365 services via API", "Drawing a chart", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Azure Virtual Desktop'?", "options": ["Desktop and application virtualization service entirely in the cloud", "A fake computer screen", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Azure CDN'?", "options": ["Fast, global delivery of content with high bandwidth", "A news network", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Azure Lighthouse'?", "options": ["A physical lighthouse", "Managing multiple Azure customers' environments from a single interface", "Neither", "Both"], "correct": 1},
        {"id": 60, "question": "What's 'Azure ARC'?", "options": ["Project for bridge building", "Managing resources across multi-cloud and on-premises from Azure portal", "Neither", "Both"], "correct": 1},
        {"id": 61, "question": "How can you run code on Azure without any servers to manage?", "options": ["Using Azure Functions", "Using App Service", "Using VMs", "None"], "correct": 0},
        {"id": 62, "question": "What is 'ZRS' (Zone-Redundant Storage)?", "options": ["Replicating data synchronously across three different availability zones", "Storage for zones", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Azure Files'?", "options": ["Fully managed file shares in the cloud accessible via SMB or NFS", "Documents in Azure", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Azure Import/Export Service'?", "options": ["Importing products", "Moving large amounts of data to Azure storage by shipping physical disks", "Neither", "Both"], "correct": 1},
        {"id": 65, "question": "Which of these allows hosting a database in Azure?", "options": ["Azure SQL DB", "Cosmos DB", "PostgreSQL in Azure", "All of the above"], "correct": 3},
        {"id": 66, "question": "What is 'Azure Subscription' hierarchy?", "options": ["Management Group -> Subscription -> Resource Group -> Resource", "A plan for a gym", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'SLA' (Service Level Agreement)?", "options": ["A legal document for user conduct", "Microsoft's commitment for uptime and connectivity of Azure services", "Neither", "Both"], "correct": 1},
        {"id": 68, "question": "What happens if an Azure service doesn't meet its SLA?", "options": ["You might get a service credit based on downtime", "Nothing", "The service stops completely", "None"], "correct": 0},
        {"id": 69, "question": "What is 'Shared Access Signature' (SAS) in Azure Storage?", "options": ["Giving someone a key to a cabinet", "Providing delegated, limited access to resources in your storage account", "Neither", "Both"], "correct": 1},
        {"id": 70, "question": "What is 'Azure Firewall'?", "options": ["Managed cloud-based network security specifically for your VNet resources", "Physical fire protection", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Public IP' vs 'Private IP' in Azure?", "options": ["IP for internet access vs IP for internal communication in VNet", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "How can you automate Azure tasks on a schedule?", "options": ["Azure Automation (using runbooks)", "Manual clicking", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Azure Cloud Shell'?", "options": ["Shells on a beach", "A browser-based, authenticated shell to manage Azure using bash or PowerShell", "Neither", "Both"], "correct": 1},
        {"id": 74, "question": "What's the meaning of 'Scale Set' (VMSS)?", "options": ["A group of identical load-balanced VMs that scale together automatically", "A set of scales for weighing", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Azure HDInsight'?", "options": ["Big data analytics for enterprises using Hadoop, Spark", "Better vision", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Azure Media Services'?", "options": ["Cloud-based video and content encoding, storage, and streaming workflows", "A news station", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Azure Information Protection' (AIP)?", "options": ["Discovering, classifying, and protecting sensitive documents via labeling", "A types of lock", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "Which constant is used for Azure regions (e.g. 'East US')?", "options": ["Location", "Region", "Both", "None"], "correct": 0},
        {"id": 79, "question": "What's 'Azure Service Health' for?", "options": ["Providing localized dashboard updates on the status and issues with your services", "A medical report", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What's the primary benefit of choosing Azure for companies already using Microsoft tools?", "options": ["Seamless integration with Windows, Office 365, and Active Directory", "Having more servers", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
