import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_mongodb_api(request):
    questions_pool = [
        {"id": 1, "question": "What is MongoDB?", "options": ["A relational database", "A NoSQL, document-oriented database", "A type of memory", "None"], "correct": 1},
        {"id": 2, "question": "What format does MongoDB use to store data?", "options": ["JSON", "BSON (Binary JSON)", "XML", "CSV"], "correct": 1},
        {"id": 3, "question": "What is a 'Collection' in MongoDB?", "options": ["A database", "A grouping of MongoDB documents (like a table)", "A list of strings", "None"], "correct": 1},
        {"id": 4, "question": "What is a 'Document' in MongoDB?", "options": ["A printed file", "A single record in a collection in BSON format", "A technical specification", "None"], "correct": 1},
        {"id": 5, "question": "Which of these is used to uniquely identify a document in MongoDB?", "options": ["primaryKey", "_id", "ID", "mongo_id"], "correct": 1},
        {"id": 6, "question": "How do you insert a document in MongoDB using the shell?", "options": ["db.coll.add()", "db.coll.insert() or insertOne()", "db.coll.put()", "None"], "correct": 1},
        {"id": 7, "question": "Which command is used to fetch all documents from a collection?", "options": ["db.coll.get()", "db.coll.find()", "db.coll.select()", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Mongoose' in the context of MongoDB?", "options": ["A type of animal", "An Object Data Modeling (ODM) library for MongoDB and Node.js", "A security tool", "None"], "correct": 1},
        {"id": 9, "question": "Which MongoDB command is used to update a document?", "options": ["db.coll.change()", "db.coll.update() or updateOne()", "db.coll.modify()", "None"], "correct": 1},
        {"id": 10, "question": "Which MongoDB command is used to remove a document?", "options": ["db.coll.delete() or deleteOne()", "db.coll.remove()", "Both A and B", "Neither"], "correct": 2},
        {"id": 11, "question": "What is 'Aggregation' in MongoDB?", "options": ["Connecting to a database", "Processing data records and returning computed results (like group by)", "Sorting a simple list", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Indexing' in MongoDB?", "options": ["A list of all users", "Creating a data structure to improve query performance", "A type of table", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Replication' in MongoDB?", "options": ["Copying a database file", "Synchronizing data across multiple servers for high availability", "A type of backup", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Sharding' in MongoDB?", "options": ["Deleting data segments", "Distributing data across multiple machines for horizontal scaling", "A type of database indexing", "None"], "correct": 1},
        {"id": 15, "question": "Does MongoDB have a fixed schema?", "options": ["Yes", "No (schema-less or dynamic schema)", "Only if defined manually", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Atlas' in MongoDB context?", "options": ["A map", "A fully managed multi-cloud database service by MongoDB", "A type of server", "None"], "correct": 1},
        {"id": 17, "question": "Which operator is used for 'greater than' in MongoDB queries?", "options": ["$gt", "$greater", ">", "$more"], "correct": 0},
        {"id": 18, "question": "Which operator is used to match values in an array?", "options": ["$in", "$array", "$match", "None"], "correct": 0},
        {"id": 19, "question": "What is 'GridFS' used for?", "options": ["A type of file system for small files", "Storing and retrieving large files that exceed the BSON limit (16MB)", "A security feature", "None"], "correct": 1},
        {"id": 20, "question": "Which function provides a count of documents in a collection?", "options": ["db.coll.count()", "db.coll.size()", "db.coll.length()", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Embedded Document'?", "options": ["A document with no name", "A document stored inside another document as a sub-document", "A hidden file", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Reference' in MongoDB?", "options": ["A citation in a book", "Storing related data by including the _id of another document", "A link to a website", "None"], "correct": 1},
        {"id": 23, "question": "Which command-line tool is used for exporting MongoDB data to JSON/CSV?", "options": ["mongoexport", "mongosend", "mongoput", "None"], "correct": 0},
        {"id": 24, "question": "Which command-line tool is used for importing MongoDB data?", "options": ["mongoimport", "mongoget", "mongolink", "None"], "correct": 0},
        {"id": 25, "question": "What is 'DBRef'?", "options": ["A database reference type that includes collection name and _id", "A type of index", "A security token", "None"], "correct": 0},
        {"id": 26, "question": "What is 'Capped Collection'?", "options": ["A collection for users", "Fixed-size collection that automatically overwrites oldest entries when full", "A type of table", "None"], "correct": 1},
        {"id": 27, "question": "Which method sorts the result set in MongoDB?", "options": ["sort()", "order()", "arrange()", "None"], "correct": 0},
        {"id": 28, "question": "What is 'Explain()' used for in MongoDB?", "options": ["Explaining code with comments", "Providing information on how a query was executed for performance analysis", "A security log", "None"], "correct": 1},
        {"id": 29, "question": "What is the default port for MongoDB?", "options": ["27017", "3306", "5432", "8080"], "correct": 0},
        {"id": 30, "question": "Which operator is used to increment a value in MongoDB?", "options": ["$inc", "$add", "$up", "None"], "correct": 0},
        {"id": 31, "question": "What is 'BSON' specifically?", "options": ["Binary representation specifically of JSON-like documents", "A brand of soap", "A types of car", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Projection' in MongoDB find() queries?", "options": ["Limiting the fields specifically that are returned from a document", "Projecting code onto a screen", "A types of math", "None"], "correct": 0},
        {"id": 33, "question": "How do you rename a field specifically in MongoDB documents?", "options": ["$rename operator", "$change operator", "None", "None"], "correct": 0},
        {"id": 34, "question": "What is 'upsert' in an update operation?", "options": ["Updating the document if found, otherwise creating a new one", "Upgrading a server", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What represents the 'Compound Index'?", "options": ["An index specifically on multiple fields of a document", "A very complex index", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What represents the 'Unique Index'?", "options": ["Ensures specifically that no two documents have the same value for the indexed field", "A one-of-a-kind index", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'TTL Index' (Time-To-Live)?", "options": ["Index that automatically deletes documents specifically after a set time", "A fast index", "A types of storage", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Secondary Index'?", "options": ["Any index that is not the default _id index", "A second story index", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "Which method skips the first N documents specifically in a result set?", "options": ["skip()", "jump()", "pass()", "None"], "correct": 0},
        {"id": 40, "question": "Which method limits the number specifically of documents returned?", "options": ["limit()", "cap()", "stop()", "None"], "correct": 0},
        {"id": 41, "question": "What is 'Replica Set'?", "options": ["A group specifically of MongoDB instances that maintain the same data set", "A copies of files", "None", "None"], "correct": 0},
        {"id": 42, "question": "What is 'Primary Node' in a replica set?", "options": ["The node specifically that receives all write operations", "A node with prime numbers", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Secondary Node' in a replica set?", "options": ["Nodes that replicate specifically from the primary for high availability", "Secondary schools", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What represents the 'Arbiter' node?", "options": ["A node specifically that only votes in elections and does not hold data", "A node used for math", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Write Concern' in MongoDB?", "options": ["Describes specifically the level of acknowledgment requested from MongoDB for write ops", "Being worried about code", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Read Preference'?", "options": ["Determines specifically how MongoDB clients route read operations to replica set members", "Choosing a book", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Shard Key'?", "options": ["An indexed field specifically used to distribute documents across shards", "A physical key", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Config Server' in a sharded cluster?", "options": ["Stores specifically the metadata for a sharded cluster", "A router setting", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Mongos' in sharding?", "options": ["A routing service specifically for sharded clusters", "A types of fruit", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What represents the '$match' stage in aggregation?", "options": ["Filters the documents specifically like a find() query", "Matching a ball", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What represents the '$group' stage in aggregation?", "options": ["Groups documents specifically by a specified identifier for calculations", "Grouping students", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What represents the '$project' stage in aggregation?", "options": ["Reshapes the documents specifically by adding/removing fields", "Projecting a movie", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What represents the '$sort' stage in aggregation?", "options": ["Sorts the documents specifically in the pipeline", "Ordering books", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What represents the '$limit' stage in aggregation?", "options": ["Limits the number specifically of documents passing through", "Setting a cap", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What represents the '$unwind' stage in aggregation?", "options": ["Deconstructs specifically an array field into multiple documents", "Taking off a wire", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What represents the '$lookup' stage in aggregation?", "options": ["Performs specifically a left outer join to another collection", "Searching for a word", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Transaction' in MongoDB (v4.0+)?", "options": ["Allowing multiple operations specifically across multiple documents/collections atomically", "Buying a coffee", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's the meaning of 'Atomicity' in MongoDB?", "options": ["Operations are specifically all-or-nothing at the document level", "Atomic bombs", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Map-Reduce' in MongoDB?", "options": ["Data processing paradigm specifically for large-scale data aggregation (older method)", "A types of map", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How can you drop a collection in MongoDB?", "options": ["db.coll.drop()", "db.coll.delete()", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "How can you drop a whole database?", "options": ["db.dropDatabase()", "db.delete()", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'ObjectId' component specifically?", "options": ["A 12-byte identifier specifically with timestamp, machine ID, process ID and counter", "A random string", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "How do you start the MongoDB server (on-prem)?", "options": ["mongod command", "mongo start", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "How do you start the MongoDB shell?", "options": ["mongosh (or mongo) command", "shell start", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What represents the 'mongodump'?", "options": ["Tool specifically for creating a binary export of a database", "Dumping trash", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What represents the 'mongorestore'?", "options": ["Tool specifically for loading a binary export into a database", "Restoring a house", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "Can MongoDB handle time series data?", "options": ["Yes, specifically since version 5.0 with optimized time series collections", "No", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's 'Full-Text Search' in MongoDB Atlas?", "options": ["Built-in search engine specifically based on Apache Lucene", "Searching text in a book", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents the 'Causal Consistency'?", "options": ["Ensuring specifically related operations are finished in correct order across nodes", "A logical talk", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Change Streams'?", "options": ["Feature allowing apps specifically to access real-time data changes in the DB", "A flowing river", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Which operator is used for 'less than'?", "options": ["$lt", "$less", "<", "None"], "correct": 0},
        {"id": 72, "question": "Which operator is used for 'not equal'?", "options": ["$ne", "$not", "!=", "None"], "correct": 0},
        {"id": 73, "question": "Which operator is used for 'or' conditions?", "options": ["$or", "$parallel", "||", "None"], "correct": 0},
        {"id": 74, "question": "Which operator is used for 'and' conditions?", "options": ["$and", "$also", "&&", "None"], "correct": 0},
        {"id": 75, "question": "What's the meaning of 'Multikey Index'?", "options": ["An index specifically on an array field", "Multiple keys for a door", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Geospatial Index'?", "options": ["Index specifically optimized for querying 2D/3D coordinate data", "A map of stars", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents the 'Wildcard Index'?", "options": ["Allows indexing specifically all fields of a document dynamically", "A random card", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "How to check indexes for a collection?", "options": ["db.coll.getIndexes()", "db.coll.list()", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Compass' in MongoDB context?", "options": ["Official GUI specifically for exploring and managing MongoDB data visually", "A tool for directions", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is MongoDB popular for modern app development?", "options": ["Flexibility of schema-less documents specifically and easy horizontal scaling", "It uses more electricity", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
