import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_msoffice_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Microsoft Office?", "options": ["A suite of productivity applications like Word, Excel, PowerPoint", "A types of furniture", "A list of strings", "None"], "correct": 0},
        {"id": 2, "question": "Which application is used for 'Word Processing'?", "options": ["MS Word", "MS Excel", "MS PowerPoint", "None"], "correct": 0},
        {"id": 3, "question": "Which application is used for 'Spreadsheets' (Data/Calc)?", "options": ["MS Word", "MS Excel", "MS Outlook", "None"], "correct": 1},
        {"id": 4, "question": "Which application is used for 'Presentations'?", "options": ["MS Word", "MS Publisher", "MS PowerPoint", "None"], "correct": 2},
        {"id": 5, "question": "What is 'MS Outlook' primarily for?", "options": ["Email and Calendar management", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'MS Access' used for?", "options": ["Managing databases in a simplified way", "A list of notes", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'MS OneNote'?", "options": ["A digital notebook for capturing and organizing notes", "A music player", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'MS Teams' specifically for?", "options": ["Collaboration, chat, and video meetings within a group/company", "Building a computer", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'OneDrive' in MS Office suite?", "options": ["Cloud storage for saving and sharing your files online", "A local server", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "Which constant is used for 'Bold' text in Office?", "options": ["Ctrl + B", "Ctrl + I", "Ctrl + U", "None"], "correct": 0},
        {"id": 11, "question": "Which constant is used for 'Italic' text?", "options": ["Ctrl + B", "Ctrl + I", "Ctrl + J", "None"], "correct": 1},
        {"id": 12, "question": "Which constant is used for 'Underline' text?", "options": ["Ctrl + U", "Ctrl + V", "Ctrl + S", "None"], "correct": 0},
        {"id": 13, "question": "What is 'Copy' shortcut in Windows Office?", "options": ["Ctrl + C", "Ctrl + X", "Ctrl + V", "None"], "correct": 0},
        {"id": 14, "question": "What is 'Cut' shortcut?", "options": ["Ctrl + C", "Ctrl + X", "Ctrl + P", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Paste' shortcut?", "options": ["Ctrl + V", "Ctrl + P", "Ctrl + Z", "None"], "correct": 0},
        {"id": 16, "question": "What is 'Undo' shortcut?", "options": ["Ctrl + Z", "Ctrl + Y", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'Redo' shortcut?", "options": ["Ctrl + Y (or Ctrl+Shift+Z)", "Ctrl + R", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'Ribbon' in Office apps?", "options": ["The toolbar at the top containing all the groups and commands", "A physical ribbon", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What's the meaning of 'Formatting' in Word?", "options": ["Changing the visual appearance of text (font, size, color)", "Erasing everything", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is a 'Cell' in MS Excel?", "options": ["A room for prisoners", "The intersection of a row and a column for data entry", "Neither", "Both"], "correct": 1},
        {"id": 21, "question": "What is a 'Formula' in Excel?", "options": ["A types of equation", "A mathematical expression used to calculate values in a cell", "Both", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Slide' in PowerPoint?", "options": ["A physical playground slide", "A single page in a presentation presentation", "Both", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Animation' in PowerPoint context?", "options": ["A movie in a presentation", "Visual effects applied to individual items on a slide", "Neither", "Both"], "correct": 1},
        {"id": 24, "question": "What is 'Transition' in PowerPoint?", "options": ["The visual effect specifically when moving from one slide to another", "A change in weather", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Spell Check' (F7) primarily for?", "options": ["Finding typos and grammatical errors automatically", "Reviewing a book only", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Cloud Collaboration' in Office 365?", "options": ["Allowing multiple people to edit the same document in real-time online", "Talking on a phone", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What's the difference between Office 2021 and Office 365?", "options": ["365 is subscription-based with cloud features; 2021 is a one-time purchase", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Mail Merge' in MS Word?", "options": ["Sending mail automatically", "Combining a template with a database (like contacts) to create many personalized docs", "Neither", "Both"], "correct": 1},
        {"id": 29, "question": "What is 'Pivot Table' in MS Excel?", "options": ["A table on a physical pivot", "A powerful tool to summarize, analyze and explore large amounts of data", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "Who created Microsoft Office?", "options": ["Microsoft", "Google", "Apple", "Oracle"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Header' in Word?", "options": ["The section at the very top of each page for titles/page numbers", "A heading for a text", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Footer' in Word?", "options": ["The section at the bottom of each page specifically for additional info", "A sports term", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Margin' in a document?", "options": ["The blank space between the text and the edge of the physical page", "A technical drawing", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What's 'Landscape' versus 'Portrait' orientation?", "options": ["Horizontal versus Vertical page layout", "Painting styles only", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Alignment' (Left, Right, Center, Justify)?", "options": ["Positioning text relative to the margins", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Indentation' in Paragraph?", "options": ["Adjusting the distance of the text from the left or right margin", "Writing notes", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'Hyperlink' (Ctrl+K)?", "options": ["A clickable link specifically to another file, email, or a website", "A very fast link", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What's 'Track Changes' feature useful for?", "options": ["Recording all edits made to a document for others to review and accept/reject", "Tracking someone's location", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What's 'Comments' feature in Office Apps?", "options": ["Adding digital sticky notes to specific parts of a document for feedback", "Starting a chat", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What's 'Workbook' vs 'Worksheet' in Excel?", "options": ["Workbook is the whole file; Worksheet is a single tab/page inside the file", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What's 'Range' in Excel?", "options": ["A mountain range", "A group or block of selected cells in a worksheet", "Neither", "Both"], "correct": 1},
        {"id": 42, "question": "What is 'AutoSum' in Excel?", "options": ["Automatically adding up numbers in a selected range of cells", "Calculating math with a pen", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Sort and Filter' in Excel?", "options": ["Organizing data numerically/alphabetically or hiding specific data by criteria", "Cleaning food", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Conditional Formatting' significance?", "options": ["Changing cell appearance based on specific conditions (e.g. highlight if > 100)", "A styles of text", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Freeze Panes' used for?", "options": ["Freezing food in office", "Keeping specific rows or columns visible while scrolling through a sheet", "Neither", "Both"], "correct": 1},
        {"id": 46, "question": "What is 'Chart' / 'Graph' in Excel?", "options": ["Visual representation specifically of numerical data for easier analysis", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'VLOOKUP' significance?", "options": ["Searching for a specific value in a table and returning data from same row", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Template' in Office?", "options": ["A pre-designed starting point specifically for a common document (Resume, Invoice, etc.)", "A design of a room", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "How can you protect an Office file with a password?", "options": ["File -> Info -> Protect Document -> Encrypt with Password", "Locking in a desk drawer", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Export as PDF' used for?", "options": ["Saving a static copy of a document specifically for easy viewing and sharing", "Making it faster", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Slide Master' in PowerPoint?", "options": ["The hidden slide that controls the layout and theme for the whole presentation", "A master of slides", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's 'Presenter View' used for?", "options": ["Seeing your notes and next slide while audience sees the main presentation", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'SmartArt'?", "options": ["AI-driven graphics specifically to visually represent information and ideas", "An intelligent person", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'WordArt'?", "options": ["Adding decorative text effects specifically to titles and headings", "A types of painting", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's the meaning of 'Find and Replace' (Ctrl+H)?", "options": ["Finding specific text and swapping it with others automatically", "Looking for misplaced items", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "How to select all text in a document?", "options": ["Ctrl + A", "Ctrl + S", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "How to save a file quickly?", "options": ["Ctrl + S", "Ctrl + X", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "How to print a document?", "options": ["Ctrl + P", "Ctrl + Q", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Page Break'?", "options": ["Interrupting a book session", "Forcing the text to start on the next physical page in a document", "Neither", "Both"], "correct": 1},
        {"id": 60, "question": "What is 'Section Break' used for?", "options": ["Dividing a document into parts with different layouts or formatting", "A break from work", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Table of Contents' automation?", "options": ["Automatically generating a list of headings and page numbers in Word", "Writing notes on a book", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Font Size' unit?", "options": ["Points (e.g. 12 pt)", "Pixels", "Both", "None"], "correct": 0},
        {"id": 63, "question": "Which constant is used for 'Line Spacing'?", "options": ["Changing vertical space between lines of text in a paragraph", "Measuring roads", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Thesaurus' for?", "options": ["Finding synonyms and antonyms for words in a document", "A book name", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Zoom' control for?", "options": ["Changing how much of the document you see on your screen", "Fast speed", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's the effect of 'Ruler' in Word?", "options": ["Help to align and measure text and set margins professionally", "A person who rules", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Watermark' used for?", "options": ["Adding a faint background text/image to indicate status (e.g. DRAFT)", "Water for an office", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's 'Macros' significance in Excel?", "options": ["Automating repetitive tasks explicitly through recorded scripts or VBA", "Small computer parts", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'Data Validation' in Excel?", "options": ["Restricting what type of data can be entered into a specific cell", "Validating math", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's 'Absolute Reference' ($A$1) in Excel?", "options": ["Fixing a cell reference so it doesn't change when copied to other cells", "A reference for a person", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's 'Relative Reference' (A1) in Excel?", "options": ["A cell reference that changes automatically when copied to other cells", "A family member's reference", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'CONCATENATE' used for?", "options": ["Joining two or more text strings together into one cell", "Sharing files", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'AutoFill' in Excel context?", "options": ["Automatically extending a series of data or formulas based on a pattern", "Filling a car", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Page Layout' view used for?", "options": ["Seeing exactly how the document will look when printed", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "How to add a new slide in PowerPoint?", "options": ["Ctrl + M", "Ctrl + N", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Slide Show' (F5)?", "options": ["Starting the presentation of the slide deck from the very beginning", "A movie in a presentation", "Neither", "Both"], "correct": 1},
        {"id": 77, "question": "What's 'Broadcasting' a presentation?", "options": ["Sharing your slides live over the internet with remote audiences", "A TV station only", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Microsoft 365' (Office 365)?", "options": ["A subscription service that includes Office apps and cloud storage", "A news app", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which of these is a typical Office file extension?", "options": [".docx", ".xlsx", ".pptx", "All of the above"], "correct": 3},
        {"id": 80, "question": "What is the primary benefit of the MS Office suite?", "options": ["Integrated tools for almost all business and personal productivity tasks", "Having more social media followers", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
