import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_msword_api(request):
    questions_pool = [
        {"id": 1, "question": "What is MS Word?", "options": ["A types of table", "A word processing software specifically for documents", "A search for files", "None"], "correct": 1},
        {"id": 2, "question": "What is the file extension for MS Word?", "options": [".docx", ".xlsx", ".pptx", ".txt"], "correct": 0},
        {"id": 3, "question": "What is 'Ribbon' in MS Word?", "options": ["The toolbar at the top that contains all the commands", "A physical ribbon", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Header'?", "options": ["The section at the very top of each page for titles/page numbers", "A heading for a text", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'Footer'?", "options": ["The section at the very bottom of each page specifically for additional info", "A foot for a person", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'Margin'?", "options": ["The blank space between the text and the edge of the physical page", "A technical drawing", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "Which constant is used for 'Bold' text?", "options": ["Ctrl + B", "Ctrl + I", "Ctrl + U", "None"], "correct": 0},
        {"id": 8, "question": "Which constant is used for 'Italic' text?", "options": ["Ctrl + B", "Ctrl + I", "Ctrl + J", "None"], "correct": 1},
        {"id": 9, "question": "Which constant is used for 'Underline' text?", "options": ["Ctrl + U", "Ctrl + V", "Ctrl + S", "None"], "correct": 0},
        {"id": 10, "question": "What is 'Alignment' (Left, Right, Center, Justify)?", "options": ["Positioning text relative to the margins", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Mail Merge'?", "options": ["Sending mail automatically", "Combining a template with a database to create many personalized docs", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'Track Changes' feature useful for?", "options": ["Recording all edits made to a document for others to review", "Tracking location", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Hyperlink'?", "options": ["A clickable link specifically to another file or website", "A very fast link", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'WordArt'?", "options": ["Decorative text effects specifically for titles and headings", "A types of painting", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'SmartArt'?", "options": ["Visual graphics specifically to represent info and ideas", "An intelligent person", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Find and Replace'?", "options": ["Finding specific text and swapping it with others automatically", "Looking for items", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "Which constant is used to select all text?", "options": ["Ctrl + A", "Ctrl + S", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'Undo' shortcut?", "options": ["Ctrl + Z", "Ctrl + Y", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Redo' shortcut?", "options": ["Ctrl + Y", "Ctrl + R", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What is 'Save' shortcut?", "options": ["Ctrl + S", "Ctrl + X", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'Print' shortcut?", "options": ["Ctrl + P", "Ctrl + Q", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What's 'Landscape' versus 'Portrait'?", "options": ["Horizontal versus Vertical page layout", "Painting styles only", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'Page Break'?", "options": ["Forcing the text specifically to start on the next physical page", "Stopping a book session", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'Spelling and Grammar' check (F7)?", "options": ["Automatically finding typos and errors during writing", "Reviewing a book only", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Table' in MS Word context?", "options": ["An organized grid specifically of rows and columns for data", "A kitchen table", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Bulleted/Numbered List' for?", "options": ["Organizing points clearly in a document", "A list of strings only", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Shading' text for?", "options": ["Changing the background color specifically of specific text/paragraph", "Shadow of a building", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Border' for text/page?", "options": ["Adding a frame around specific text, paragraph, or the whole page", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's the meaning of 'Columns' in page layout?", "options": ["Splitting the text into multiple vertical columns specifically like a newspaper", "Vertical list", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Who created MS Word?", "options": ["Microsoft", "Google", "Apple", "Oracle"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Page Border'?", "options": ["A frame around the entire physical page in a document", "A border for a house", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Watermark' used for?", "options": ["Adding faint background text to indicate document status (e.g. DRAFT)", "Water for an office", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Indentation' in Paragraph?", "options": ["Adjusting the distance of the text from the left or right margin", "Writing notes on a book", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Line Spacing' signal?", "options": ["The vertical space specifically between lines of text in a paragraph", "Measuring a road", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Thesaurus' feature?", "options": ["Finding synonyms and antonyms for words in Word", "A book name", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What's 'Page Background' color?", "options": ["Changing the overall color of the document page background", "Painting a wall", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "How can you select a single word quickly?", "options": ["Double-click on the word", "Triple-click on the word", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "How can you select a whole paragraph?", "options": ["Triple-click specifically anywhere in the paragraph", "Double-click", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Format Painter'?", "options": ["Copying the formatting of selected text and applying it to another", "A person who paints", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Clear All Formatting'?", "options": ["Removing all fonts/colors/sizes specifically returning text to its raw form", "Deleting everything", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Show/Hide' paragraph markers (¶)?", "options": ["Viewing hidden symbols specifically for empty spaces and paragraph ends", "A symbols on a map", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What's 'Superscript' vs 'Subscript'?", "options": ["Text above the line (x²) vs text below the line (H₂O)", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's the meaning of 'Drop Cap'?", "options": ["A large initial capital letter used decoratively at start of a paragraph", "Dropping a hat", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "How to add a 'Comment' in Word?", "options": ["Review -> New Comment", "Insert -> Comment", "Both A and B", "Neither"], "correct": 2},
        {"id": 45, "question": "What is 'Compare Documents' feature?", "options": ["Viewing two versions of a doc side-by-side to find differences", "Comparing people", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's 'Navigation Pane' significance?", "options": ["Quickly finding and navigating to headings and pages in large docs", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Table of Contents' automation?", "options": ["Automatically generating a list of headings and page numbers in Word", "Writing on a book", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Footnote' vs 'Endnote'?", "options": ["Bottom of SAME page vs very end of WHOLE document", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Styles' (Heading 1, 2) for?", "options": ["Applying consistent formatting across the whole document for organization", "A types of clothes", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Document Theme'?", "options": ["A collection of coordinated fonts and colors for a professional look", "A musical score", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "Which constant is used for 'Paste'?", "options": ["Ctrl + V", "Ctrl + P", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "Which constant is used for 'Format Painter'?", "options": ["Ctrl + Shift + C (Copy) / Ctrl + Shift + V (Paste)", "Ctrl + P", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "How to add a table image?", "options": ["Insert -> Table", "Draw it by hand", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's 'Shapes' feature for?", "options": ["Adding lines, arrows, basic geometric shapes to a doc", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's 'Icons' inside Word?", "options": ["Searching and inserting professionally designed vector graphics/symbols", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Screenshot' tool in Word?", "options": ["Quickly capturing and inserting a window from your screen into Word", "Taking a phone photo", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Text Box' used for?", "options": ["Adding text anywhere specifically on the page (even over images)", "A box for books", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Equation Editor'?", "options": ["Tool specifically to write complex mathematical and scientific formulas", "A calculator in Word", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'Symbol' insertion for?", "options": ["Adding special characters specifically not on the keyboard (e.g. ©, €)", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "Can you protect a Word doc with password?", "options": ["Yes, using File -> Info -> Protect Document", "No", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "How to export as PDF?", "options": ["File -> Export -> Create PDF/XPS", "Saving as image", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Zoom slider'?", "options": ["Adjusting the view size of the document window quickly", "Fast speed", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'View Ruler' toggle for?", "options": ["Showing/hiding the measurement bar at the top/left of the canvas", "Measuring roads", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's the meaning of 'Layout' tab?", "options": ["Setting margins, orientation, and size of the physical pages", "Designing icons", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's 'Page Background' vs 'Watermark'?", "options": ["Color of the whole background vs faint text/image behind text", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Line Numbers' feature?", "options": ["Adding numbers next to each line of text specifically for reference", "Adding page numbers", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Hyphenation' in Word?", "options": ["Automatically breaking long words at the end of a line with a dash", "Writing notes", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's the benefit of 'Auto-Save' (OneDrive)?", "options": ["Saving your work automatically every few seconds to prevent loss", "Saving after an hour", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's the meaning of 'Read Mode'?", "options": ["Hiding most editing tools specifically for comfortable reading", "A mode for people in darkness", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "How can you view two parts of a long doc at once?", "options": ["Using the 'Split Window' feature", "Using two monitors", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's 'Side-By-Side' view?", "options": ["Viewing two different Word docs together on the screen", "Couples in Word", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "How can you navigate to a specific page quickly?", "options": ["Ctrl + G (Go To) -> enter page number", "Scrolling very fast", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'Draft' view versus 'Print Layout'?", "options": ["Draft hides headers/images for fast editing; Print shows final look", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Word Count' significance?", "options": ["Tracking number of words, pages, and characters in a doc", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's 'Find' shortcut?", "options": ["Ctrl + F", "Ctrl + S", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "How to center a text quickly?", "options": ["Ctrl + E", "Ctrl + C", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "How to justify a paragraph?", "options": ["Ctrl + J", "Ctrl + L", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Bookmark' in Word?", "options": ["Saving a specific location in a document for quick access late", "A book accessory", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What's the meaning of 'Cross-reference'?", "options": ["Linking to another headline or figure within the same document", "Linking to a different book", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary benefit of MS Word?", "options": ["Creating professional documents efficiently with many tools", "Having more TV channels", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
