import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_networksecurity_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Network Security'?", "options": ["Increasing internet speed", "Protecting a networking infrastructure from unauthorized access or misuse", "Deleting a computer virus", "None"], "correct": 1},
        {"id": 2, "question": "What is a 'Firewall'?", "options": ["A type of battery", "A network security system that monitors and filters incoming/outgoing traffic", "A physical wall", "None"], "correct": 1},
        {"id": 3, "question": "What is 'VPN' (Virtual Private Network)?", "options": ["A very fast network", "A secure tunnel between your device and the internet", "A type of database", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Encryption'?", "options": ["Deleting data", "The process of encoding information so only authorized parties can read it", "A type of table", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Decryption'?", "options": ["Decoding encrypted data", "Increasing data size", "None of the above", "None"], "correct": 0},
        {"id": 6, "question": "What is 'DDoS Attack'?", "options": ["Distributed Denial of Service", "Dynamic Data optimization system", "Design of data systems", "None"], "correct": 0},
        {"id": 7, "question": "What is 'Phishing'?", "options": ["Catching real fish", "An attempt to gain sensitive info by pretending to be a trustworthy source", "A type of network error", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Malware'?", "options": ["A brand of hardware", "Malicious software (viruses, worms, etc.) intended to damage computers", "A security feature", "None"], "correct": 1},
        {"id": 9, "question": "What is an 'IDS' (Intrusion Detection System)?", "options": ["A security guard", "A system that monitors a network for malicious activity or policy violations", "A type of chart", "None"], "correct": 1},
        {"id": 10, "question": "What is an 'IPS' (Intrusion Prevention System)?", "options": ["A tool for hardware", "A system that monitors and actively stops identified threats", "A type of data table", "None"], "correct": 1},
        {"id": 11, "question": "What is 'SSL/TLS'?", "options": ["Protocols for securing communication over a computer network", "A type of network protocol", "Both A and B", "Neither"], "correct": 2},
        {"id": 12, "question": "What is 'Public Key Infrastructure' (PKI)?", "options": ["A list of servers", "A set of policies and procedures for managing digital certificates", "A computer network", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Zero Trust' architecture?", "options": ["Trusting no one by default", "A security model that requires strict identity verification for everyone", "Both A and B", "Neither"], "correct": 2},
        {"id": 14, "question": "What is 'MFA'?", "options": ["Multi-Factor Authentication", "Multi-File Access", "Managing Folder Automation", "None"], "correct": 0},
        {"id": 15, "question": "What is 'Two-Factor Authentication' (2FA)?", "options": ["Providing two pieces of evidence to prove identity", "Double internet speed", "A security log", "None"], "correct": 0},
        {"id": 16, "question": "What a 'Proxy Server' in network security?", "options": ["A backup server", "An intermediary between a client and a server to manage traffic", "A type of browser", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Eavesdropping' in networking?", "options": ["Listening to a physical room", "Intercepting private communication without permission", "A type of error", "None"], "correct": 1},
        {"id": 18, "question": "What is 'DNS Poisoning'?", "options": ["Poisoning a person in the cloud", "Corrupting Domain Name System data to redirect users to malicious sites", "A technical specification", "None"], "correct": 1},
        {"id": 19, "question": "What is 'IP Spoofing'?", "options": ["Creating a funny IP", "Masquerading as another computer by mimicking its IP address", "A security log", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Social Engineering'?", "options": ["Building a society", "Manipulating people into giving away confidential information", "A marketing strategy", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Packet Sniffing'?", "options": ["Hunting for data packets", "Monitoring and capturing all data packets passing through a given network", "None of the above", "None"], "correct": 1},
        {"id": 22, "question": "What is 'WPA2' in the context of Wi-Fi?", "options": ["A security protocol for wireless networks", "A type of network router", "An internet speed test", "None"], "correct": 0},
        {"id": 23, "question": "What is 'Firewall Rule'?", "options": ["A law for internet firewalls", "A specific condition to allow or block matching traffic on a network", "A decorative part of code", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Security Audit'?", "options": ["Watching a movie", "A systematic evaluation of the security of a company's info system", "A financial report", "None"], "correct": 1},
        {"id": 25, "question": "Which of these is a popular network security tool?", "options": ["Wireshark", "Nmap", "Snort", "All of the above"], "correct": 3},
        {"id": 26, "question": "What is 'Ransomware'?", "options": ["A type of memory", "Malware that encrypts your files and demands payment for the key", "A type of browser", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Botnet'?", "options": ["A group of bots on social media", "A network of private computers infected with malicious software and controlled as a group", "A network of robots", "None"], "correct": 1},
        {"id": 28, "question": "What is 'SIEM' (Security Information and Event Management)?", "options": ["Integrated Access Monitor", "Software that provides real-time analysis of security alerts", "A technical manual", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Identity Theft'?", "options": ["Stealing a secret ID", "Assuming someone else's identity to commit fraud or other crimes", "A type of movie", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Access Control List' (ACL)?", "options": ["A list of all users", "A list of permissions attached to a resource", "A type of database indexing", "None"], "correct": 1},
        {"id": 31, "question": "What is 'HTTPS'?", "options": ["Secure version of HTTP using SSL/TLS encryption for web traffic", "High speed transfer protocol", "A type of web server", "None"], "correct": 0},
        {"id": 32, "question": "What is 'SSH' (Secure Shell)?", "options": ["Protocol for secure remote login and command execution over a network", "A decorative shell script", "A database name", "None"], "correct": 0},
        {"id": 33, "question": "What is 'SFTP'?", "options": ["Secure File Transfer Protocol using SSH for data protection", "A fast file protocol", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'WPA3'?", "options": ["The latest and most secure Wi-Fi security protocol", "A third-party antenna", "A types of network speed", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Encryption at Rest'?", "options": ["Protecting data specifically when it is stored on a disk or database", "Encrypting while the computer is off", "A type of backup", "None"], "correct": 0},
        {"id": 36, "question": "What is 'Encryption in Transit'?", "options": ["Protecting data specifically while it is being sent over a network", "Encrypting files on a thumb drive", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'VLAN' (Virtual LAN) for security?", "options": ["Segmenting a network into logically isolated groups for better security", "A very large network", "A visual layout", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Port Scanning'?", "options": ["Checking which ports are open on a network for vulnerability assessment", "Scanning a computer port physically", "A types of transport", "None"], "correct": 0},
        {"id": 39, "question": "What is 'Honeypot' in network security?", "options": ["A trap set to detect, deflect, or counteract attempts at unauthorized access", "A sweet food online", "A database of passwords", "None"], "correct": 0},
        {"id": 40, "question": "What is 'Penetration Testing' for networking?", "options": ["Authorized simulated attack to find and fix security gaps", "A physical test of cables", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Least Privilege' principle?", "options": ["Giving users only the minimum access needed for their job", "Giving everyone full access", "A type of political theory", "None"], "correct": 0},
        {"id": 42, "question": "What is 'Data Loss Prevention' (DLP)?", "options": ["Strategies to ensure sensitive data is not lost or misused", "Deleting data manually", "None of the above", "None"], "correct": 0},
        {"id": 43, "question": "What is 'MAC Filtering'?", "options": ["Allowing or blocking devices based on their physical hardware addresses", "Filtering apples", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'ARP Spoofing'?", "options": ["Redirecting network traffic by sending fake ARP messages to a LAN", "Changing a computer name", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Brute Force Attack' on passwords?", "options": ["Trying all possible combinations until the correct one is found", "Hitting a keyboard", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Dictionary Attack'?", "options": ["Using a list of common words or passwords to crack security", "Looking at a book", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Rainbow Table Attack'?", "options": ["Using a precomputed table of hashes to crack passwords fast", "A colorful chart", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's the meaning of 'End-to-End Encryption'?", "options": ["Data is encrypted on sender side and decrypted only on receiver side", "Encrypting the ends of a file", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Rootkit'?", "options": ["Malicious software designed to hide its presence on a system", "A kit for plants", "A types of computer design", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Trojan Horse'?", "options": ["Malicious software disguised as a legitimate program", "A wooden horse", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Adware'?", "options": ["Software that automatically displays or downloads advertising material", "Software for drawing", "A security virus", "None"], "correct": 0},
        {"id": 52, "question": "What is 'Spyware'?", "options": ["Malware specifically to gather info about a person or company secretely", "A secret agent", "None", "None"], "correct": 0},
        {"id": 53, "question": "What is 'Social Engineering' via Phishing?", "options": ["Tricking users with fake emails to steal information", "Building a website", "None of the above", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Spear Phishing'?", "options": ["Highly targeted phishing attack aimed at a specific individual or group", "Fishing with a spear", "A types of sport", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Whaling' in cyber security?", "options": ["Targeting high-ranking executives with phishing attacks", "Catching big fish", "None", "None"], "correct": 0},
        {"id": 56, "question": "What is 'Backdoor' in a system?", "options": ["A hidden entrance that bypasses normal authentication", "The back entrance of a house", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Packet Filtering'?", "options": ["Checking header info of packets specifically to allow or block them", "Smelling a package", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Stateful Inspection' firewall?", "options": ["Monitors the state of active network connections for better filtering", "A fire sensor", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Proxy Firewall'?", "options": ["A firewall that acts as an intermediary between client and server", "A types of router", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Next-Generation Firewall' (NGFW)?", "options": ["Integrated firewall with advanced features like deep packet inspection", "A new computer wall", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'DMZ' (Demilitarized Zone)?", "options": ["A buffer zone in a network between a private net and the internet", "A war zone", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Sandboxing'?", "options": ["Running programs in an isolated environment for security testing", "Playing with sand", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Antivirus' software?", "options": ["Program to detect and remove malicious software", "Hardware for a PC", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Heuristic Analysis' in antivirus?", "options": ["Detecting new viruses by looking for suspicious patterns or code", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What's the meaning of 'Zero-Day Vulnerability'?", "options": ["A flaw unknown to the developer and has no current patch", "A virus on day one", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'CVE'?", "options": ["Common Vulnerabilities and Exposures", "Computer Viral Error", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'CIA Triad'?", "options": ["Confidentiality, Integrity, Availability", "Computer, Internet, Access", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What represents the 'Confidentiality'?", "options": ["Ensuring only authorized individuals can access sensitive data", "Telling a secret", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What represents the 'Integrity'?", "options": ["Ensuring data is accurate and has not been tampered with", "Being honest", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What represents the 'Availability'?", "options": ["Ensuring systems and data are accessible to users when needed", "Starting a computer", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Compliance' in network security?", "options": ["Meeting legal and regulatory security requirements", "Doing a favor", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'GDPR'?", "options": ["General Data Protection Regulation", "Global Data Privacy Rules", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'PCI DSS'?", "options": ["Security standards for protecting credit card data", "A personal computer ID", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Cybersecurity Awareness Training'?", "options": ["Educating employees specifically to recognize and avoid cyber threats", "Teaching how to code", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "How many factors in 'Multi-Factor Authentication'?", "options": ["Two or more", "Only one", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What represents top-level security policy document?", "options": ["Overall strategy for protecting organizational information", "A list of users", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Endpoint Security'?", "options": ["Protecting individual devices like PCs, laptops, and mobiles", "Protecting the end of a line", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Cloud Security'?", "options": ["Protecting data and systems hosted in a cloud environment", "Security for weather", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Incident Response'?", "options": ["A planned reaction to a security breach or cyberattack", "Answering a call", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is network security a continuous process?", "options": ["Threats and vulnerabilities are constantly evolving and changing", "Because code is long", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
