import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_nodejs_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Node.js?", "options": ["A JavaScript library", "A JavaScript runtime environment", "A JavaScript framework", "A database"], "correct": 1},
        {"id": 2, "question": "Which engine does Node.js use?", "options": ["SpiderMonkey", "Chakra", "V8", "SpiderV8"], "correct": 2},
        {"id": 3, "question": "Which of the following is true about Node.js?", "options": ["It is single-threaded", "It is multi-threaded", "It is synchronous", "All of the above"], "correct": 0},
        {"id": 4, "question": "What does NPM stand for?", "options": ["Node Package Manager", "New Package Manager", "Node Programming Module", "None of the above"], "correct": 0},
        {"id": 5, "question": "How can you read a file as an asynchronous stream in Node.js?", "options": ["fs.read()", "fs.readFileSync()", "fs.createReadStream()", "fs.open()"], "correct": 2},
        {"id": 6, "question": "Which command is used to initialize a new Node project?", "options": ["npm start", "npm init", "npm install", "node init"], "correct": 1},
        {"id": 7, "question": "What is the Buffer class in Node.js used for?", "options": ["Handling binary data", "Caching data", "File system management", "Network routing"], "correct": 0},
        {"id": 8, "question": "What module is used to create a web server in Node.js?", "options": ["url", "fs", "http", "path"], "correct": 2},
        {"id": 9, "question": "Which of the following describes the event loop in Node.js?", "options": ["It allows multi-threading", "It handles asynchronous callbacks", "It is a blocking process", "It is a CPU-intensive task"], "correct": 1},
        {"id": 10, "question": "What is the command to install a package globally in NPM?", "options": ["npm install -g <name>", "npm install <name> -global", "npm get -g <name>", "npm install --save <name>"], "correct": 0},
        {"id": 11, "question": "Which method is used to import a module in Node.js (CommonJS)?", "options": ["import", "require", "using", "include"], "correct": 1},
        {"id": 12, "question": "What is the purpose of 'module.exports'?", "options": ["To define a new module", "To export functions/objects from a module", "To import modules", "To stop a module"], "correct": 1},
        {"id": 13, "question": "Which core module is used for path manipulation?", "options": ["dir", "folder", "path", "url"], "correct": 2},
        {"id": 14, "question": "What is 'EventEmitter'?", "options": ["A class to manage system logs", "A class to handle and trigger events", "A database connector", "A network protocol"], "correct": 1},
        {"id": 15, "question": "What happens if an error is not caught in an asynchronous function?", "options": ["Node.js continues running", "Node.js process crashes", "Node.js skips the function", "Nothing happens"], "correct": 1},
        {"id": 16, "question": "Which method on the 'fs' module checks if a file exists synchronously?", "options": ["fs.exists()", "fs.existsSync()", "fs.stat()", "fs.access()"], "correct": 1},
        {"id": 17, "question": "What is the default port for most Node.js tutorials?", "options": ["80", "443", "3000", "8080"], "correct": 2},
        {"id": 18, "question": "What does libuv do in Node.js?", "options": ["Handles UI components", "Handles the event loop and asynchronous I/O", "Manages dependencies", "Compiles JavaScript code"], "correct": 1},
        {"id": 19, "question": "Which of these is NOT a built-in module?", "options": ["os", "crypto", "express", "dns"], "correct": 2},
        {"id": 20, "question": "How do you start a debugger in Node.js?", "options": ["node --debug app.js", "node inspect app.js", "node --inspect app.js", "node run debug"], "correct": 2},
        {"id": 21, "question": "What is 'callback hell'?", "options": ["Multiple nested callbacks", "An infinite loop", "A memory leak", "A slow server response"], "correct": 0},
        {"id": 22, "question": "Which method converts a buffer to a string?", "options": ["buffer.getString()", "buffer.toString()", "buffer.convert()", "buffer.text()"], "correct": 1},
        {"id": 23, "question": "What is the purpose of 'process.env'?", "options": ["Accessing system memory", "Accessing environment variables", "Stopping the process", "Changing the OS settings"], "correct": 1},
        {"id": 24, "question": "What does Node.js do when it receives a blocking I/O request?", "options": ["Wait for it to finish", "Spawns a new thread automatically", "Delegates it to worker threads (libuv) and continues", "Refuses the request"], "correct": 2},
        {"id": 25, "question": "Which command displays the version of Node installed?", "options": ["node -v", "node --version", "Both A and B", "node version"], "correct": 2},
        {"id": 26, "question": "What is the extension of Node.js modules by default?", "options": [".node", ".js", ".mjs", ".cjs"], "correct": 1},
        {"id": 27, "question": "How can you update NPM to the latest version?", "options": ["npm update npm", "npm install npm@latest -g", "npm upgrade npm", "node install npm"], "correct": 1},
        {"id": 28, "question": "Which function is used to schedule a function to run after the current event loop cycle?", "options": ["setTimeout()", "setInterval()", "setImmediate()", "process.nextTick()"], "correct": 3},
        {"id": 29, "question": "What is a Stream in Node.js?", "options": ["A way to handle large data in chunks", "A network connection", "A database query", "A UI component"], "correct": 0},
        {"id": 30, "question": "Which of these is a popular Node.js framework for real-time communication?", "options": ["Express", "Socket.io", "React", "Koa"], "correct": 1},
        {"id": 31, "question": "What is 'REPL' in Node.js?", "options": ["Read-Eval-Print-Loop", "Real-time Execution Protocol", "Remote Entry Point List", "None"], "correct": 0},
        {"id": 32, "question": "Which module provides utilities for operating system related tasks?", "options": ["os", "system", "fs", "process"], "correct": 0},
        {"id": 33, "question": "How can you emit a custom event in Node.js?", "options": ["event.emit('name')", "event.trigger('name')", "event.fire('name')", "None"], "correct": 0},
        {"id": 34, "question": "What is the result of 'fs.writeFile()'?", "options": ["Overwrites the file if it exists, or creates a new one", "Appends to the file", "Deletes the file", "None"], "correct": 0},
        {"id": 35, "question": "What is 'fs.appendFile()' used for?", "options": ["Adding data to the end of a file", "Creating a new file only", "Renaming a file", "None"], "correct": 0},
        {"id": 36, "question": "Which module handles cryptographic operations?", "options": ["crypto", "security", "hash", "encrypt"], "correct": 0},
        {"id": 37, "question": "What is 'cluster' module used for?", "options": ["Spawning multiple instances of Node.js to use multiple CPUs", "A types of database", "Clustering UI components", "None"], "correct": 0},
        {"id": 38, "question": "What is the purpose of 'zlib' module?", "options": ["To provide compression and decompression using Gzip and Deflate", "To handle ZIP files only", "Encryption", "None"], "correct": 0},
        {"id": 39, "question": "Which function is used to create a directory in Node.js?", "options": ["fs.mkdir()", "fs.createDir()", "fs.newDir()", "None"], "correct": 0},
        {"id": 40, "question": "How to handle command-line arguments in Node.js?", "options": ["process.argv", "process.args", "console.argv", "None"], "correct": 0},
        {"id": 41, "question": "What is 'package-lock.json' for?", "options": ["Ensuring consistent installation of dependencies by locking versions", "Locking the project for editing", "A backup file", "None"], "correct": 0},
        {"id": 42, "question": "What is the result of 'process.exit(1)'?", "options": ["Exits with an error code", "Successfully finishes the process", "Restarts the server", "None"], "correct": 0},
        {"id": 43, "question": "What is the result of 'process.exit(0)'?", "options": ["Exits successfully", "Exits with error", "Wait for current task", "None"], "correct": 0},
        {"id": 44, "question": "Which module is used for handling URL strings?", "options": ["url", "path", "http", "link"], "correct": 0},
        {"id": 45, "question": "What is 'middleware' in Express terms?", "options": ["Functions that have access to request and response objects", "A type of database", "A secure router", "None"], "correct": 0},
        {"id": 46, "question": "What is 'Pug' or 'EJS' in Node.js?", "options": ["Template engines for generating HTML", "Database names", "JavaScript libraries", "None"], "correct": 0},
        {"id": 47, "question": "What is 'Body-parser' used for?", "options": ["Parsing incoming request bodies in middleware", "Parsing raw code", "Parsing URL", "None"], "correct": 0},
        {"id": 48, "question": "What is 'CORS'?", "options": ["Cross-Origin Resource Sharing", "Computer Origin Redirection System", "None", "None"], "correct": 0},
        {"id": 49, "question": "What does 'npm audit' do?", "options": ["Checks for security vulnerabilities in your project dependencies", "Calculates project cost", "Tests your code", "None"], "correct": 0},
        {"id": 50, "question": "What is the purpose of 'Helmet' in Express apps?", "options": ["Securing HTTP headers for better app safety", "A styling tool", "A protective gear", "None"], "correct": 0},
        {"id": 51, "question": "How do you read a JSON file in Node.js?", "options": ["Using require('./file.json') or fs.readFile()", "Using readJSON()", "None", "None"], "correct": 0},
        {"id": 52, "question": "What is 'JWT'?", "options": ["JSON Web Token", "JavaScript Web Technology", "None", "None"], "correct": 0},
        {"id": 53, "question": "What is 'Passport.js' used for?", "options": ["Authentication for Node.js", "Navigation", "Travelling", "None"], "correct": 0},
        {"id": 54, "question": "Which command installs only production dependencies?", "options": ["npm install --production", "npm install --prod", "npm install dev-only", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Nodemon'?", "options": ["A tool that restarts the Node.js application automatically when file changes are detected", "A type of game", "A security virus", "None"], "correct": 0},
        {"id": 56, "question": "Which of these is used for testing in Node.js?", "options": ["Mocha", "Jest", "Chai", "All of the above"], "correct": 3},
        {"id": 57, "question": "What is 'pm2'?", "options": ["A process manager for production Node.js applications", "A computer manufacturer", "A types of math", "None"], "correct": 0},
        {"id": 58, "question": "What is 'Streams' of type 'Writable'?", "options": ["Streams used for outputting data to a destination", "Streams used for reading only", "Both", "None"], "correct": 0},
        {"id": 59, "question": "What is 'Duplex' stream?", "options": ["A stream that is both Readable and Writable", "A double stream", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is the purpose of 'Pipe' in streams?", "options": ["Connecting the output of a readable stream to the input of a writable stream", "Plumbing code", "A design tool", "None"], "correct": 0},
        {"id": 61, "question": "Which module allows interacting with the DNS server?", "options": ["dns", "network", "url", "internet"], "correct": 0},
        {"id": 62, "question": "What is the command to create an empty file in Node.js?", "options": ["fs.open('file', 'w', callback)", "fs.createFile()", "None", "None"], "correct": 0},
        {"id": 63, "question": "What is 'Morgan' middleware used for?", "options": ["HTTP request logging", "Database query logging", "User auth", "None"], "correct": 0},
        {"id": 64, "question": "Which function allows executing shell commands in Node.js?", "options": ["child_process.exec()", "process.run()", "None", "None"], "correct": 0},
        {"id": 65, "question": "What is 'spawn()' vs 'exec()' in child_process?", "options": ["spawn() is for large outputs (uses streams); exec() is for smaller outputs", "They are identical", "None", "None"], "correct": 0},
        {"id": 66, "question": "Which module is used to handle file uploads?", "options": ["Multer", "Body-parser", "Express-upload", "None"], "correct": 0},
        {"id": 67, "question": "What is 'Mongoose'?", "options": ["Object Data Modeling (ODM) library for MongoDB and Node.js", "A small animal in Node.js", "A design library", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Sequelize'?", "options": ["An ORM for SQL databases like MySQL, Postgres in Node.js", "A task scheduler", "None", "None"], "correct": 0},
        {"id": 69, "question": "What is 'Dotenv' used for?", "options": ["Loading environment variables from a .env file", "Drawing dots", "None", "None"], "correct": 0},
        {"id": 70, "question": "What is 'ESM' (ECMAScript Modules)?", "options": ["The standard module system using import/export (instead of require)", "A list of strings", "None", "None"], "correct": 0},
        {"id": 71, "question": "Which flag is used for ESM in older Node versions?", "options": ["--experimental-modules", "--esm", "--use-import", "None"], "correct": 0},
        {"id": 72, "question": "What is 'Express Router' used for?", "options": ["Creating modular, mountable route handlers", "A hardware router for Node", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Res.send()' vs 'Res.json()'?", "options": ["Res.json() specifically sets JSON headers and converts data", "They are same", "None", "None"], "correct": 0},
        {"id": 74, "question": "How do you handle 404 in Express?", "options": ["A middleware at the end of all routes", "Restarting the app", "Redirecting to Google", "None"], "correct": 0},
        {"id": 75, "question": "What is 'Worker Threads' useful for?", "options": ["Executing heavy, CPU-intensive tasks without blocking the main event loop", "Doing UI work", "Managing databases", "None"], "correct": 0},
        {"id": 76, "question": "Which module provides basic cryptographic hashing?", "options": ["crypto", "security", "hash", "None"], "correct": 0},
        {"id": 77, "question": "What is 'npm start'?", "options": ["A standard script to launch the application", "A command to buy a package", "A design tool", "None"], "correct": 0},
        {"id": 78, "question": "How to delete a file in Node.js?", "options": ["fs.unlink()", "fs.delete()", "fs.remove()", "None"], "correct": 0},
        {"id": 79, "question": "How to rename a file?", "options": ["fs.rename()", "fs.move()", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is 'Event-driven' programming?", "options": ["A paradigm where flow is determined by events such as user actions or sensor outputs", "Writing about events", "None", "None"], "correct": 0},
        {"id": 81, "question": "What is 'Stream' in Node.js?", "options": ["A way to handle asynchronous data in pieces", "A type of database", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Transform' stream?", "options": ["A Duplex stream where the output is computed from the input", "A stream for changing UI", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What does 'fs.createWriteStream()' do?", "options": ["Creates a writable stream for a file", "Reads a file", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "Which module allows creating child processes?", "options": ["child_process", "spawn", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'OS' module primarily used for?", "options": ["Getting system info like memory, CPUs, and uptime", "Designing the OS", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Path' module's 'extname()' used for?", "options": ["Getting the file extension", "Changing the name", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "How to create a buffer from a string?", "options": ["Buffer.from('string')", "Buffer.create()", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What's the meaning of 'Heap' in Node.js memory?", "options": ["Where objects and variables are stored", "A pile of code", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What does 'process.nextTick()' do?", "options": ["Schedules a callback to run immediately after the current operation", "Wait for next day", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Global' object in Node.js?", "options": ["The global namespace equivalent to 'window' in browsers", "A world map", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is '__dirname'?", "options": ["Path to the current directory of the script", "A hidden file", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is '__filename'?", "options": ["Absolute path to the current script file", "The file size", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "Which command checks for outdated packages?", "options": ["npm outdated", "npm check", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'NVM' used for?", "options": ["Managing multiple versions of Node.js", "Node Variable Manager", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "How to handle uncaught exceptions?", "options": ["process.on('uncaughtException', callback)", "The app crashes automatically", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Cluster' module used for?", "options": ["Utilizing multiple CPU cores by running multiple processes", "Group of users", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "Which module provides compression?", "options": ["zlib", "compress", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Assert' module for?", "options": ["Writing unit tests and performing validations", "Naming files", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'v8' module used for?", "options": ["Exposing V8 engine specific APIs and tools", "A car engine", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is the result of 'console.time()'?", "options": ["Starts a timer to measure operation duration", "Displays time", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 20))})
