import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_numpy_api(request):
    questions_pool = [
        {"id": 1, "question": "What does NumPy stand for?", "options": ["Numerical Python", "Number Python", "Numerical Page", "None"], "correct": 0},
        {"id": 2, "question": "What is the primary data structure in NumPy?", "options": ["List", "Dictionary", "ndarray (Many-dimensional array)", "DataFrame"], "correct": 2},
        {"id": 3, "question": "Which function is used to create a NumPy array?", "options": ["np.array()", "np.create()", "np.list()", "None"], "correct": 0},
        {"id": 4, "question": "What is the result of 'np.zeros(5)'?", "options": ["An array of five zeros", "An error", "A type of chart", "None"], "correct": 0},
        {"id": 5, "question": "What is the result of 'np.ones(5)'?", "options": ["An array of five ones", "A list of one", "None", "None"], "correct": 0},
        {"id": 6, "question": "What does 'shape' property represent in NumPy?", "options": ["The size of array", "A tuple representing the dimensions of the array", "A design color", "None"], "correct": 1},
        {"id": 7, "question": "What does 'size' property represent in NumPy?", "options": ["The overall counts of elements in an array", "The size of a laptop", "None", "None"], "correct": 0},
        {"id": 8, "question": "What does 'dtype' represent in NumPy array?", "options": ["Description type", "The data type of array elements (e.g. int64, float32)", "A security log", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Broadcasting' in NumPy context?", "options": ["Streaming radio", "Rules for performing arithmetic on arrays of different shapes", "Neither", "Both"], "correct": 1},
        {"id": 10, "question": "What is 'Reshaping' an array in NumPy?", "options": ["Changing the array's data", "Changing the layout (dimensions) and keeping data intact", "Neither", "Both"], "correct": 1},
        {"id": 11, "question": "What is the result of 'np.arange(1, 5)'?", "options": ["[1, 2, 3, 4, 5]", "[1, 2, 3, 4]", "[0, 1, 2, 3, 4]", "None"], "correct": 1},
        {"id": 12, "question": "What is 'np.linspace(0, 1, 5)' used for?", "options": ["Creating 5 equally spaced values between 0 and 1", "Drawing a line", "None of the above", "None"], "correct": 0},
        {"id": 13, "question": "Which function is used to compute the mean of a NumPy array?", "options": ["np.mean()", "np.average()", "Both A and B", "None"], "correct": 2},
        {"id": 14, "question": "Which function allows you to calculate the dot product of two arrays?", "options": ["np.dot()", "np.mul()", "np.cross()", "None"], "correct": 0},
        {"id": 15, "question": "What is the difference between NumPy arrays and Python lists?", "options": ["NumPy is faster for numerical operations", "Lists can hold mixed data types; NumPy is optimized for same types", "Both A and B", "Neither"], "correct": 2},
        {"id": 16, "question": "What is 'Vectorization' in NumPy?", "options": ["Changing to vector graphics", "Performing operations on an entire array instead of looping over elements", "Both A and B", "Neither"], "correct": 1},
        {"id": 17, "question": "Which function combines multiple arrays vertically?", "options": ["np.vstack()", "np.hstack()", "np.cat()", "None"], "correct": 0},
        {"id": 18, "question": "Which function combines multiple arrays horizontally?", "options": ["np.vstack()", "np.hstack()", "None of the above", "None"], "correct": 1},
        {"id": 19, "question": "What is the result of 'np.transpose(a)'?", "options": ["The transposition of matrix a (swapping rows and columns)", "Deleting the matrix", "Both", "None"], "correct": 0},
        {"id": 20, "question": "How do you calculate sum along a specific axis in NumPy?", "options": ["np.sum(a, axis=0/1)", "np.calculate_sum()", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What's the meaning of 'np.inf' in NumPy?", "options": ["Infinity", "Internal file", "None", "None"], "correct": 0},
        {"id": 22, "question": "What's the result of 'np.nan' in NumPy?", "options": ["Not a Number", "Not a Name", "No Amount Needed", "None"], "correct": 0},
        {"id": 23, "question": "How do you find the maximum value in an array?", "options": ["np.max()", "array.max()", "Both A and B", "None"], "correct": 2},
        {"id": 24, "question": "How do you find the minimum value?", "options": ["np.min()", "array.min()", "Both A and B", "None"], "correct": 2},
        {"id": 25, "question": "Which function tells the indices of max values?", "options": ["np.argmax()", "np.idxmax()", "None", "None"], "correct": 0},
        {"id": 26, "question": "What does 'np.eye(3)' produce?", "options": ["3x3 identity matrix with ones on the diagonal", "An error", "A type of table", "None"], "correct": 0},
        {"id": 27, "question": "What is 'Indexing' in NumPy?", "options": ["A bookmark", "Selecting specific elements of an array using coordinates", "Both", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Slicing' an array (a[start:stop:step])?", "options": ["Cutting a cake", "Selecting a range of elements from an array", "None of the above", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Boolean Indexing'?", "options": ["Filtering array elements using logical conditions (e.g. a > 0)", "A type of table", "None", "None"], "correct": 0},
        {"id": 30, "question": "Which module in NumPy is used for random number generation?", "options": ["np.random", "np.math", "np.generate", "None"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'np.unique()' used for?", "options": ["Finding unique elements in an array", "Deleting duplicates", "Both A and B", "Neither"], "correct": 2},
        {"id": 32, "question": "How can you flatten a multi-dimensional array into 1D?", "options": ["np.flatten()", "array.ravel()", "Both A and B", "Neither"], "correct": 2},
        {"id": 33, "question": "What is the difference between 'flatten()' and 'ravel()'?", "options": ["flatten returns a copy; ravel returns a view whenever possible", "They are identical", "None", "None"], "correct": 0},
        {"id": 34, "question": "Which function computes the standard deviation of an array?", "options": ["np.std()", "np.var()", "np.mean()", "None"], "correct": 0},
        {"id": 35, "question": "Which function computes the variance of an array?", "options": ["np.std()", "np.var()", "np.median()", "None"], "correct": 1},
        {"id": 36, "question": "Which function finds the median value?", "options": ["np.median()", "np.mid()", "None", "None"], "correct": 0},
        {"id": 37, "question": "How do you calculate the cumulative sum of elements in an array?", "options": ["np.cumsum()", "np.sum_all()", "None", "None"], "correct": 0},
        {"id": 38, "question": "How do you calculate the cumulative product of elements?", "options": ["np.cumprod()", "np.product()", "None", "None"], "correct": 0},
        {"id": 39, "question": "What is 'np.where(condition, x, y)' used for?", "options": ["Searching for items", "Vectorized conditional selection (if condition true, x, else y)", "None", "None"], "correct": 1},
        {"id": 40, "question": "What is 'np.copy(a)'?", "options": ["Creates a deep copy of an array 'a'", "Moves a to a new file", "None", "None"], "correct": 0},
        {"id": 41, "question": "What is a 'View' of an array?", "options": ["Watching a movie", "A new array object that looks at the same data as the original", "Neither", "Both"], "correct": 1},
        {"id": 42, "question": "Which constant represents Pi in NumPy?", "options": ["np.pi", "np.math_pi", "np.num_pi", "None"], "correct": 0},
        {"id": 43, "question": "Which constant represents e (base of natural log)?", "options": ["np.e", "np.math_e", "None", "None"], "correct": 0},
        {"id": 44, "question": "Which function computes the exponential (e^x) of all elements in an array?", "options": ["np.exp()", "np.pow()", "None", "None"], "correct": 0},
        {"id": 45, "question": "Which function computes the natural log (ln) of elements?", "options": ["np.log()", "np.ln()", "None", "None"], "correct": 0},
        {"id": 46, "question": "Which function computes the base-10 log of elements?", "options": ["np.log10()", "np.log2()", "None", "None"], "correct": 0},
        {"id": 47, "question": "Which function computes the square root of all elements?", "options": ["np.sqrt()", "np.sqr()", "None", "None"], "correct": 0},
        {"id": 48, "question": "What's the meaning of 'ndmin' parameter in np.array()?", "options": ["Setting the minimum number of dimensions for the resulting array", "A speed test", "None", "None"], "correct": 0},
        {"id": 49, "question": "Which function creates a identity matrix of given size?", "options": ["np.eye()", "np.identity()", "Both A and B", "Neither"], "correct": 2},
        {"id": 50, "question": "How do you check the total memory size used by an array in bytes?", "options": ["array.nbytes", "array.size", "Both", "None"], "correct": 0},
        {"id": 51, "question": "How do you check the size of each element in an array in bytes?", "options": ["array.itemsize", "array.dtype_size", "None", "None"], "correct": 0},
        {"id": 52, "question": "What is 'np.full(shape, value)'?", "options": ["Creating an array of given shape filled with a specific value", "Cleaning the array", "None", "None"], "correct": 0},
        {"id": 53, "question": "What is 'np.empty(shape)'?", "options": ["Starting a blank screen", "Creating an array without initializing its entries (uses random memory garbage)", "Neither", "Both"], "correct": 1},
        {"id": 54, "question": "How can you repeat an array multiple times?", "options": ["np.repeat()", "np.tile()", "Both A and B (context matters)", "None"], "correct": 2},
        {"id": 55, "question": "What is 'np.split()'?", "options": ["Sharing a cost", "Splitting an array into multiple sub-arrays", "None", "None"], "correct": 1},
        {"id": 56, "question": "What is 'np.concatenate()'?", "options": ["Joining arrays along a specified axis", "Merging database tables", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Fancy Indexing' in NumPy?", "options": ["Using decorative indexes", "Using an array of integers as indices to select elements", "Neither", "Both"], "correct": 1},
        {"id": 58, "question": "Which function allows performing bitwise AND on arrays?", "options": ["np.bitwise_and()", "np.and()", "None", "None"], "correct": 0},
        {"id": 59, "question": "Which function allows performing bitwise OR?", "options": ["np.bitwise_or()", "np.or()", "None", "None"], "correct": 0},
        {"id": 60, "question": "How do you sort a NumPy array?", "options": ["np.sort(array)", "array.sort() (in-place)", "Both A and B", "None"], "correct": 2},
        {"id": 61, "question": "Which internal code is NumPy primarily written in for speed?", "options": ["Java", "C and Assembly", "PHP", "None"], "correct": 1},
        {"id": 62, "question": "How do you convert a list to a NumPy array?", "options": ["np.asarray(list)", "np.array(list)", "Both A and B", "Neither"], "correct": 2},
        {"id": 63, "question": "Can you store a custom object in a NumPy array?", "options": ["Only if dtype is object", "No", "Always", "None"], "correct": 0},
        {"id": 64, "question": "Which function returns indices of non-zero elements?", "options": ["np.nonzero()", "np.find_val()", "None", "None"], "correct": 0},
        {"id": 65, "question": "What is 'np.all()' used for?", "options": ["Checking if all elements in array evaluate to true", "Starting a program", "None", "None"], "correct": 0},
        {"id": 66, "question": "What is 'np.any()' used for?", "options": ["Checking if any elements evaluate to true", "Deleting a file", "None", "None"], "correct": 0},
        {"id": 67, "question": "How do you calculate the absolute value for each element?", "options": ["np.abs()", "np.absolute()", "Both A and B", "None"], "correct": 2},
        {"id": 68, "question": "Which function is used for matrix multiplication in NumPy (since 3.5)?", "options": ["@", "np.matmul()", "np.dot()", "All of the above"], "correct": 3},
        {"id": 69, "question": "What is 'np.polynomial'?", "options": ["A module for polynomial operations (fit, roots, objects)", "Drawing circles", "None", "None"], "correct": 0},
        {"id": 70, "question": "What is 'np.linalg'?", "options": ["Library for linear algebra operations (solve, inverse, etc.)", "A list of strings", "None", "None"], "correct": 0},
        {"id": 71, "question": "How do you calculate the inverse of a matrix?", "options": ["np.linalg.inv()", "np.reverse()", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "How do you calculate eigenvalues and eigenvectors?", "options": ["np.linalg.eig()", "np.linalg.value()", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is the effect of 'np.flip()' on an array?", "options": ["Reversing the order of elements along a specified axis", "Deleting elements", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is the result of 'np.clip(a, min, max)'?", "options": ["Clipping a video", "Limiting the values in an array to specified boundaries", "None", "None"], "correct": 1},
        {"id": 75, "question": "How do you find the indices that would sort an array?", "options": ["np.argsort()", "np.sort_id()", "Both", "None"], "correct": 0},
        {"id": 76, "question": "Which function performs rounding to the nearest integer?", "options": ["np.round()", "np.around()", "Both A and B", "None"], "correct": 2},
        {"id": 77, "question": "What is 'np.ceil()'?", "options": ["Taking values to the floor", "Rounding values up to the nearest integer", "Neither", "Both"], "correct": 1},
        {"id": 78, "question": "What is 'np.floor()'?", "options": ["Rounding values down to the nearest integer", "Ceiling values", "None", "None"], "correct": 0},
        {"id": 79, "question": "Which function allows generating a random integer array?", "options": ["np.random.randint()", "np.random.rand()", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is 'Universal Function' (ufunc) in NumPy?", "options": ["A function that operates on ndarrays element-by-element", "Functions for UI", "Both", "None"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
