import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_oopscpp_api(request):
    questions_pool = [
        {"id": 1, "question": "Who developed C++?", "options": ["Dennis Ritchie", "Bjarne Stroustrup", "James Gosling", "Guido van Rossum"], "correct": 1},
        {"id": 2, "question": "What is the primary extension for C++ source files?", "options": [".c", ".cpp", ".py", ".java"], "correct": 1},
        {"id": 3, "question": "What is 'Object-Oriented Programming' (OOP)?", "options": ["A style of code for math only", "A paradigm based on the concept of 'objects' (data and methods)", "A type of chart", "None"], "correct": 1},
        {"id": 4, "question": "What is a 'Class' in C++?", "options": ["A school course", "A user-defined data type (blueprint) to create objects", "A type of table", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Inheritance'?", "options": ["Inheriting money", "The ability of a class to derive features and properties from another class", "A security log", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Polymorphism' in C++?", "options": ["Many shapes of code", "The ability of different classes to respond to the same function call in their own way", "A type of error", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Encapsulation'?", "options": ["Hiding data to protect it from outside interference", "Sharing all data", "Mixing two files", "None"], "correct": 0},
        {"id": 8, "question": "What is 'Abstraction'?", "options": ["Showing only essential details of an object to the user", "Showing everything", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "Which of these is a valid access specifier in C++?", "options": ["Public", "Private", "Protected", "All of the above"], "correct": 3},
        {"id": 10, "question": "What is a 'Constructor'?", "options": ["A tool for building houses", "A special member function invoked automatically when an object is created", "A type of chart", "None"], "correct": 1},
        {"id": 11, "question": "What is a 'Destructor'?", "options": ["A disaster", "A special member function invoked automatically when an object is destroyed", "A design tool", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Friend' function in C++?", "options": ["A function that belongs to another class", "A function that has access to private and protected members of a class", "Both", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Inline' function?", "options": ["A function on one line", "A function that is copied directly into the calling code by the compiler for efficiency", "A type of error", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Virtual' function?", "options": ["A fake function", "A member function that is redefined in derived classes to achieve polymorphism", "A security token", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Pure Virtual Function'?", "options": ["A function that has no body in the base class (marked with = 0)", "A real function", "Both", "None"], "correct": 0},
        {"id": 16, "question": "What is 'Abstract Class' in C++?", "options": ["A class with drawings", "A class that has at least one pure virtual function and cannot be instantiated", "A type of table", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Operator Overloading'?", "options": ["Too many operators in a file", "Giving special meaning to a standard C++ operator for a user-defined type", "A type of view", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Function Overloading'?", "options": ["Calling a function too much", "Two or more functions with the same name but different parameters", "Neither", "Both"], "correct": 1},
        {"id": 19, "question": "What is 'Namespace' for in C++?", "options": ["A name for a project", "To avoid name collisions by organizing code into distinct logical groups", "A security feature", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Standard Template Library' (STL)?", "options": ["A set of library templates for common data structures and algorithms", "A type of table", "A list of strings", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Vector' in STL?", "options": ["A math vector only", "A dynamic array that can change its size", "A type of image", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Pointer' in C++?", "options": ["A mouse cursor", "A variable that stores the memory address of another variable", "Both A and B", "Neither"], "correct": 1},
        {"id": 23, "question": "What is 'Reference' in C++ (&variable)?", "options": ["An alias for an existing variable", "A list of strings", "None of the above", "None"], "correct": 0},
        {"id": 24, "question": "What is 'Static' member in a class?", "options": ["A member that never changes", "A member shared by all objects of that class", "Neither", "Both"], "correct": 1},
        {"id": 25, "question": "What is 'This' pointer?", "options": ["Pointing at a person", "A pointer that points to the current object instance within a class method", "A security log", "None"], "correct": 1},
        {"id": 26, "question": "What is 'C-style String' vs 'String class'?", "options": ["char[] vs std::string object", "Same", "C-style is only for C++", "None"], "correct": 0},
        {"id": 27, "question": "What is 'Exception Handling' (try, catch, throw)?", "options": ["A way to catch computer bugs", "A mechanism to handle runtime errors in code gracefully", "Neither", "Both"], "correct": 1},
        {"id": 28, "question": "Which of these is a multiple inheritance in C++?", "options": ["A class deriving from two or more base classes", "Two children of one parent", "Both A and B", "Neither"], "correct": 0},
        {"id": 29, "question": "What is 'Diamond Problem' in multiple inheritance?", "options": ["A problem with icons", "Ambiguity arising when a class inherits from two classes with a common ancestor", "A security bug", "None"], "correct": 1},
        {"id": 30, "question": "What's the meaning of 'Scope Resolution Operator' (::)?", "options": ["Calculating math", "Accessing a global variable or class member when it is hidden by a local one", "None", "None"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Template' in C++?", "options": ["A design for UI", "A powerful tool to write generic functions and classes", "A security log", "None"], "correct": 1},
        {"id": 32, "question": "What is 'RTTI' (Run-Time Type Information)?", "options": ["A mechanism that allows the type of an object to be determined at runtime", "A fast computer screen", "A type of table", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Dynamic Cast'?", "options": ["Casting a movie", "A type of cast that performs runtime checks for object polymorphism", "Both", "None"], "correct": 1},
        {"id": 34, "question": "What is 'Static Cast'?", "options": ["A simple compile-time cast", "A type of error", "A decorative text", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Const' keyword for a function?", "options": ["A function for constants", "A member function that promise not to modify any member variables of its class", "None", "None"], "correct": 1},
        {"id": 36, "question": "What is 'Mutable' keyword?", "options": ["A property that can be changed within a const function", "A secret function", "A type of table", "None"], "correct": 0},
        {"id": 37, "question": "Which header file is used for input/output in C++?", "options": ["iostream", "stdio.h", "cinout.h", "None"], "correct": 0},
        {"id": 38, "question": "What is the result of 'std::cin'?", "options": ["Used for reading input from the console", "Printing output", "A type of error", "None"], "correct": 0},
        {"id": 39, "question": "What is the result of 'std::cout'?", "options": ["Reading input", "Used for printing output to the console", "Both", "None"], "correct": 1},
        {"id": 40, "question": "What is 'std::endl' for?", "options": ["Starting a program", "Ending a line and flushing the stream buffer", "None of the above", "None"], "correct": 1},
        {"id": 41, "question": "What is 'Copy Constructor'?", "options": ["A constructor for copying files", "A special constructor used to create an object as a copy of an existing object", "Both", "None"], "correct": 1},
        {"id": 42, "question": "What is 'Default Constructor'?", "options": ["A constructor with no arguments", "A constructor for numbers", "None of the above", "None"], "correct": 0},
        {"id": 43, "question": "What is 'Parameterized Constructor'?", "options": ["A constructor with parameters to initialize objects with specific values", "A math result", "Both", "None"], "correct": 0},
        {"id": 44, "question": "What happen to memory if you forget to use 'delete'?", "options": ["Syntax error", "Memory leakage", "Nothing", "None"], "correct": 1},
        {"id": 45, "question": "What is 'Stack' vs 'Heap' memory?", "options": ["In C++, local variables use Stack; dynamic ones use Heap (new keyword)", "Heap is only for C", "Same", "None"], "correct": 0},
        {"id": 46, "question": "What is 'Early Binding'?", "options": ["Binding a book early", "Resolved at compile-time (like static functions)", "Resolved at runtime", "None"], "correct": 1},
        {"id": 47, "question": "What is 'Late Binding' (Dynamic Binding)?", "options": ["Resolved at runtime using virtual functions", "Same as early binding", "None of the above", "None"], "correct": 0},
        {"id": 48, "question": "Which of these allows access to a base class's private members?", "options": ["Inheritance", "Friend function/class", "Public specifier", "None"], "correct": 1},
        {"id": 49, "question": "What is 'Structure' vs 'Class' in C++?", "options": ["Default access in Struct is Public; in Class it is Private", "They are identical in every way", "Both", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Initialization List' in Constructor?", "options": ["A list of files", "Efficient way to initialize member variables before the constructor body runs", "A tech spec", "None"], "correct": 1},
        {"id": 51, "question": "What's the meaning of 'Method Overriding'?", "options": ["Same as overloading", "Providing a specific implementation for a function defined in a base class", "Both", "None"], "correct": 1},
        {"id": 52, "question": "What is 'Template Specialization'?", "options": ["A special type of design for UI", "Providing unique implementation for a template for a specific data type", "Both", "None"], "correct": 1},
        {"id": 53, "question": "What is 'Iterator' in STL?", "options": ["An object used to traverse through elements of a container", "A type of table", "A loop name", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Map' in STL?", "options": ["Used for drawing maps", "A associative container storing key-value pairs (stored sorted by key)", "None", "None"], "correct": 1},
        {"id": 55, "question": "What is 'List' in STL?", "options": ["A dynamic array", "A doubly-linked list collection", "Both", "None"], "correct": 1},
        {"id": 56, "question": "What is 'Set' in STL?", "options": ["A collection of random objects", "A collection of unique elements sorted by value", "None", "None"], "correct": 1},
        {"id": 57, "question": "What is 'Dynamic Memory Allocation' in C++?", "options": ["Allocating memory at runtime using 'new' and 'delete'", "Static sizing only", "Both A and B", "Neither"], "correct": 0},
        {"id": 58, "question": "What is 'Explicit' keyword for constructors?", "options": ["Explicitly defining everything", "Prevents implicit conversion during single-argument construction", "A tech spec", "None"], "correct": 1},
        {"id": 59, "question": "What is 'Virtual Destructor' used for?", "options": ["Ensuring proper cleanup of derived objects when deleted via a base pointer", "A fake cleanup", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Function Pointer'?", "options": ["A pointer on a screen", "A pointer that stores the address of a function instead of a variable", "None", "None"], "correct": 1},
        {"id": 61, "question": "What's 'Typecasting' in C++?", "options": ["Casting a movie name", "Converting one data type to another either implicitly or explicitly", "None of the above", "None"], "correct": 1},
        {"id": 62, "question": "What is 'File Stream' in C++ (fstream)?", "options": ["Streaming videos in C++", "Providing capabilities to read and write to files using stream objects", "None", "None"], "correct": 1},
        {"id": 63, "question": "Which class is used for reading from a file?", "options": ["ifstream", "ofstream", "readstream", "None"], "correct": 0},
        {"id": 64, "question": "Which class is used for writing to a file?", "options": ["ifstream", "ofstream", "writestream", "None"], "correct": 1},
        {"id": 65, "question": "What is 'Stringstream' used for?", "options": ["Streaming music", "Treating a string as a stream for easier manipulation/parsing", "Both", "None"], "correct": 1},
        {"id": 66, "question": "What is 'C++11'?", "options": ["A type of car", "A major version of the C++ standard introducing many modern features", "A security log", "None"], "correct": 1},
        {"id": 67, "question": "What is 'Lambda' in C++11?", "options": ["An anonymous local function that can capture variables in its scope", "An error code", "Both", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Auto' keyword in C++11?", "options": ["Automatic deleting files", "Automatically deducing the type of a variable from its initializer", "None", "None"], "correct": 1},
        {"id": 69, "question": "What is 'nullptr' in C++11?", "options": ["A null pointer keyword to replace older 'NULL' macro", "A decorative text", "None of the above", "None"], "correct": 0},
        {"id": 70, "question": "What's the role of 'Copy Elision' (RVO)?", "options": ["Optimizing away unnecessary copying of objects for performance", "Deleting code", "Both", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Smart Pointer'?", "options": ["A very clever pointer", "An object that manages memory for a raw pointer automatically (e.g. unique_ptr)", "None", "None"], "correct": 1},
        {"id": 72, "question": "What is 'std::unique_ptr'?", "options": ["A shared pointer", "A smart pointer that uniquely owns a resource and cannot be copied", "Neither", "Both"], "correct": 1},
        {"id": 73, "question": "What is 'std::shared_ptr'?", "options": ["A smart pointer that allows multiple owners of a resource (using reference count)", "Only one owner", "None", "None"], "correct": 0},
        {"id": 74, "question": "What is 'std::weak_ptr'?", "options": ["A pointer that is weak", "A companion for shared_ptr that doesn't increase research count (breaks cycles)", "None", "None"], "correct": 1},
        {"id": 75, "question": "What is 'L-value' vs 'R-value'?", "options": ["Object with identity vs Temporary object without identity", "Same", "No meaning in C++", "None"], "correct": 0},
        {"id": 76, "question": "What is 'Move Semantics'?", "options": ["Moving files in C++", "Efficiently transferring resources from one object to another without copying", "Both", "None"], "correct": 1},
        {"id": 77, "question": "What is 'rvalue reference' (&&)?", "options": ["A reference to a temporary (rvalue) object", "Double reference", "None of the above", "None"], "correct": 0},
        {"id": 78, "question": "What is 'constexpr'?", "options": ["A constant error", "Specifies that the value of an expression/function can be evaluated at compile-time", "None", "None"], "correct": 1},
        {"id": 79, "question": "What's the meaning of 'RAII' (Resource Acquisition Is Initialization)?", "options": ["Binding resources to object lifetime for automatic cleanup", "A programming joke", "Both", "None"], "correct": 0},
        {"id": 80, "question": "Which operator is used for dynamic memory allocation in C++?", "options": ["malloc", "new", "alloc", "None"], "correct": 1},
        {"id": 81, "question": "What is 'std::vector'?", "options": ["A geometric vector", "A dynamic array container", "A math library", "None"], "correct": 1},
        {"id": 82, "question": "What is 'std::map'?", "options": ["A geographic map", "An associative container with key-value pairs", "A drawing tool", "None"], "correct": 1},
        {"id": 83, "question": "What is 'std::set'?", "options": ["A collection of unique elements", "A TV set", "A game set", "None"], "correct": 0},
        {"id": 84, "question": "What is 'template' in C++?", "options": ["A web template", "A blueprint for creating generic classes and functions", "A document template", "None"], "correct": 1},
        {"id": 85, "question": "What is 'exception handling' in C++?", "options": ["Handling unexpected events during program execution", "Weather exceptions", "None", "None"], "correct": 0},
        {"id": 86, "question": "What is 'try-catch' block?", "options": ["A fishing technique", "Error handling mechanism", "A game", "None"], "correct": 1},
        {"id": 87, "question": "What is 'virtual function'?", "options": ["A function in virtual reality", "A function that enables runtime polymorphism", "A computer function", "None"], "correct": 1},
        {"id": 88, "question": "What is 'abstract class'?", "options": ["A class with abstract concepts", "A class with at least one pure virtual function", "A theoretical class", "None"], "correct": 1},
        {"id": 89, "question": "What is 'interface' in C++?", "options": ["A user interface", "A class with only pure virtual functions", "A network interface", "None"], "correct": 1},
        {"id": 90, "question": "What is 'multiple inheritance'?", "options": ["Inheriting from multiple base classes", "Multiple children", "None", "None"], "correct": 0},
        {"id": 91, "question": "What is 'diamond problem'?", "options": ["A jewelry problem", "Ambiguity in multiple inheritance", "A shape problem", "None"], "correct": 1},
        {"id": 92, "question": "What is 'virtual inheritance'?", "options": ["Inheritance in virtual reality", "Solving diamond problem", "None", "None"], "correct": 1},
        {"id": 93, "question": "What is 'friend function'?", "options": ["A function that is a friend", "A function that can access private members of a class", "A social function", "None"], "correct": 1},
        {"id": 94, "question": "What is 'friend class'?", "options": ["A friendly class", "A class that can access private members of another class", "A social class", "None"], "correct": 1},
        {"id": 95, "question": "What is 'operator overloading'?", "options": ["Overloading computer operators", "Defining operators for user-defined types", "None", "None"], "correct": 1},
        {"id": 96, "question": "What is 'copy constructor'?", "options": ["A constructor for copying", "A constructor that initializes an object from another object", "None", "None"], "correct": 1},
        {"id": 97, "question": "What is 'destructor'?", "options": ["A destructive function", "A function called when object is destroyed", "None", "None"], "correct": 1},
        {"id": 98, "question": "What is 'static member'?", "options": ["A member that doesn't move", "A member shared by all objects of a class", "None", "None"], "correct": 1},
        {"id": 99, "question": "What is 'const member function'?", "options": ["A constant function", "A function that doesn't modify object state", "None", "None"], "correct": 1},
        {"id": 100, "question": "What is 'mutable' keyword?", "options": ["Something that can change", "Allows modification of member variables even in const functions", "None", "None"], "correct": 1}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
