import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_oracle_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Oracle Database primarily known as?", "options": ["An Object-Oriented Database", "A Document Store", "A Relational Database Management System", "A Graph Database"], "correct": 2},
        {"id": 2, "question": "Which language is used to query Oracle databases?", "options": ["SQL", "Java", "C++", "Python"], "correct": 0},
        {"id": 3, "question": "Which statement is used to retrieve data from a database?", "options": ["EXTRACT", "SELECT", "GET", "FETCH"], "correct": 1},
        {"id": 4, "question": "Which SQL statement is used to update data in a database?", "options": ["MODIFY", "SAVE", "UPDATE", "CHANGE"], "correct": 2},
        {"id": 5, "question": "Which SQL statement is used to insert new data in a database?", "options": ["ADD RECORD", "INSERT INTO", "ADD NEW", "APPEND"], "correct": 1},
        {"id": 6, "question": "Which SQL statement is used to delete data from a database?", "options": ["DELETE", "REMOVE", "DROP", "CLEAR"], "correct": 0},
        {"id": 7, "question": "What does SQL stand for?", "options": ["Structured Query Language", "Strong Question Language", "Structured Question Language", "Standard Query Logic"], "correct": 0},
        {"id": 8, "question": "With SQL, how do you select a column named \"FirstName\" from a table named \"Persons\"?", "options": ["SELECT Persons.FirstName", "SELECT FirstName FROM Persons", "EXTRACT FirstName FROM Persons", "GET FirstName Persons"], "correct": 1},
        {"id": 9, "question": "With SQL, how do you select all the columns from a table named \"Persons\"?", "options": ["SELECT [all] FROM Persons", "SELECT *.Persons", "SELECT * FROM Persons", "SELECT Persons"], "correct": 2},
        {"id": 10, "question": "With SQL, how do you select all the records from a table named \"Persons\" where the value of the column \"FirstName\" is \"Peter\"?", "options": ["SELECT * FROM Persons WHERE FirstName='Peter'", "SELECT [all] FROM Persons WHERE FirstName LIKE 'Peter'", "SELECT FROM Persons WHERE FirstName='Peter'", "SELECT * FROM Persons IF FirstName='Peter'"], "correct": 0},
        {"id": 11, "question": "With SQL, how do you select all the records from a table named \"Persons\" where the value of the column \"FirstName\" starts with an \"a\"?", "options": ["SELECT * FROM Persons WHERE FirstName LIKE 'a%'", "SELECT * FROM Persons WHERE FirstName LIKE '%a'", "SELECT * FROM Persons WHERE FirstName='a'", "SELECT * FROM Persons WHERE FirstName LIKE '*a*'"], "correct": 0},
        {"id": 12, "question": "The OR operator displays a record if ANY conditions listed are true. The AND operator displays a record if ALL of the conditions listed are true", "options": ["True", "False", "Only AND is true", "Only OR is true"], "correct": 0},
        {"id": 13, "question": "With SQL, how do you select all the records from a table named \"Persons\" where the \"FirstName\" is \"Peter\" and \"LastName\" is \"Jackson\"?", "options": ["SELECT FirstName='Peter', LastName='Jackson' FROM Persons", "SELECT * FROM Persons WHERE FirstName<>'Peter' AND LastName<>'Jackson'", "SELECT * FROM Persons WHERE FirstName='Peter' AND LastName='Jackson'", "SELECT * FROM Persons WHERE FirstName='Peter' OR LastName='Jackson'"], "correct": 2},
        {"id": 14, "question": "With SQL, how do you select all the records from a table named \"Persons\" where the \"LastName\" is alphabetically between (and including) \"Hansen\" and \"Pettersen\"?", "options": ["SELECT * FROM Persons WHERE LastName BETWEEN 'Hansen' AND 'Pettersen'", "SELECT * FROM Persons WHERE LastName>'Hansen' AND LastName<'Pettersen'", "SELECT * FROM Persons WHERE LastName IN ('Hansen', 'Pettersen')", "None of the above"], "correct": 0},
        {"id": 15, "question": "Which SQL statement is used to return only different values?", "options": ["SELECT DIFFERENT", "SELECT UNIQUE", "SELECT DISTINCT", "SELECT ONLY"], "correct": 2},
        {"id": 16, "question": "Which SQL keyword is used to sort the result-set?", "options": ["ORDER BY", "SORT BY", "ORDER", "SORT"], "correct": 0},
        {"id": 17, "question": "With SQL, how can you return all the records from a table named \"Persons\" sorted descending by \"FirstName\"?", "options": ["SELECT * FROM Persons ORDER BY FirstName DESC", "SELECT * FROM Persons SORT BY 'FirstName' DESC", "SELECT * FROM Persons ORDER FirstName DESC", "SELECT * FROM Persons SORT 'FirstName' DESC"], "correct": 0},
        {"id": 18, "question": "What is PL/SQL?", "options": ["Procedural Language extension to SQL", "Previous Level SQL", "Programming Logic SQL", "Practical Language SQL"], "correct": 0},
        {"id": 19, "question": "What command is used to change the structure of a database table?", "options": ["UPDATE TABLE", "ALTER TABLE", "MODIFY TABLE", "CHANGE TABLE"], "correct": 1},
        {"id": 20, "question": "Which operator is used to search for a specified pattern in a column?", "options": ["LIKE", "GET", "MATCH", "SEARCH"], "correct": 0},
        {"id": 21, "question": "What does a LEFT JOIN do?", "options": ["Returns all records from the left table, and the matched records from the right table", "Returns all records from the right table", "Returns only matched records", "Returns cross product of tables"], "correct": 0},
        {"id": 22, "question": "How do you count the number of records in a table named \"Customers\"?", "options": ["SELECT NUMBER(*) FROM Customers", "SELECT SUM(*) FROM Customers", "SELECT COUNT(*) FROM Customers", "SELECT TOTAL(*) FROM Customers"], "correct": 2},
        {"id": 23, "question": "What is the role of the primary key?", "options": ["To link two tables", "To uniquely identify each record in a table", "To store passwords", "To encrypt data"], "correct": 1},
        {"id": 24, "question": "What is a foreign key?", "options": ["A key used outside the database", "A key that links two tables together", "An encrypted key", "A password key"], "correct": 1},
        {"id": 25, "question": "Which function returns the current date and time in Oracle SQL?", "options": ["NOW()", "GETDATE()", "SYSDATE", "CURRENT_TIME()"], "correct": 2},
        {"id": 26, "question": "What statement is used to revoke privileges from a user?", "options": ["DENY", "REMOVE", "REVOKE", "DELETE"], "correct": 2},
        {"id": 27, "question": "Which keyword is used to conditionally execute PL/SQL statements?", "options": ["IF", "CASE", "Both", "None"], "correct": 2},
        {"id": 28, "question": "What command is used to permanently save changes in a transaction?", "options": ["SAVE", "COMMIT", "WRITE", "FLUSH"], "correct": 1},
        {"id": 29, "question": "What happens when you issue a ROLLBACK command?", "options": ["Saves changes", "Undoes all changes made in the current transaction", "Drops the table", "Deletes all tables"], "correct": 1},
        {"id": 30, "question": "What does the TRUNCATE statement do?", "options": ["Deletes the table structure", "Deletes all records but keeps the structure", "Deletes specific records", "Backs up a table"], "correct": 1},
        {"id": 31, "question": "Which function is used to handle NULL values by substituting a specific value if a NULL is encountered?", "options": ["ISNULL", "NVL", "IFNULL", "COALESCE"], "correct": 1},
        {"id": 32, "question": "What is an index used for in Oracle?", "options": ["To enforce constraints", "To speed up data retrieval", "To encrypt tables", "To backup data"], "correct": 1},
        {"id": 33, "question": "Which data type is used to store variable-length character strings up to 4000 bytes?", "options": ["VARCHAR", "VARCHAR2", "CHAR", "TEXT"], "correct": 1},
        {"id": 34, "question": "Which set operator returns distinct rows that are output by both the left and right queries?", "options": ["UNION", "INTERSECT", "MINUS", "JOIN"], "correct": 1},
        {"id": 35, "question": "What is a trigger in Oracle?", "options": ["A scheduled job", "An automatic execution of code when a specified event occurs", "A constraint", "An index"], "correct": 1},
        {"id": 36, "question": "What is a view in a database?", "options": ["A physical table", "A virtual table based on the result of an SQL statement", "A stored procedure", "An index"], "correct": 1},
        {"id": 37, "question": "Which group function calculates the average of values?", "options": ["SUM", "MAX", "MEAN", "AVG"], "correct": 3},
        {"id": 38, "question": "Which SQL clause is used to group rows that have the same values?", "options": ["ORDER BY", "GROUP BY", "AGGREGATE", "COLLECT"], "correct": 1},
        {"id": 39, "question": "What clause is used to filter records after a GROUP BY grouping?", "options": ["WHERE", "HAVING", "FILTER", "SORT"], "correct": 1},
        {"id": 40, "question": "What does ACID stand for in database concepts?", "options": ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Complete, Isolation, Data", "Automated, Consistent, Indexed, Data", "Application, Condition, Index, Database"], "correct": 0},
        {"id": 41, "question": "A cursor in PL/SQL is:", "options": ["A pointer to a memory area that context information", "An index", "A function", "A data type"], "correct": 0},
        {"id": 42, "question": "What is a sequence in Oracle?", "options": ["A list of tables", "An object used to generate unique numbers", "A series of queries", "A loop in PL/SQL"], "correct": 1},
        {"id": 43, "question": "Which command removes a table definition and all its data?", "options": ["TRUNCATE TABLE", "DELETE TABLE", "DROP TABLE", "REMOVE TABLE"], "correct": 2},
        {"id": 44, "question": "Which character function converts all letters of a string to uppercase?", "options": ["UPCAP", "TO_UPPER", "UPPER", "CAPITALIZE"], "correct": 2},
        {"id": 45, "question": "What is the purpose of the BETWEEN operator?", "options": ["To search for a pattern", "To select values within a given range", "To compare null values", "To sort the data"], "correct": 1},
        {"id": 46, "question": "What will be the result of this query?\nSELECT COUNT(*) FROM employees WHERE department_id IS NULL;", "options": ["Counts all employees", "Counts employees without a department", "Returns 0", "Throws an error"], "correct": 1},
        {"id": 47, "question": "What does this Oracle query exactly do?\nSELECT * FROM employees WHERE ROWNUM <= 5;", "options": ["Fetches the top 5 employees by salary", "Fetches the first 5 records retrieved by the database", "Throws a syntax error", "Fetches rows older than 5 days"], "correct": 1},
        {"id": 48, "question": "What will be the output of this query?\nSELECT NVL(NULL, 'Default Data') FROM dual;", "options": ["NULL", "Default Data", "Error", "0"], "correct": 1},
        {"id": 49, "question": "In Oracle, what is the output of the following string query?\nSELECT SUBSTR('Database', 1, 4) FROM dual;", "options": ["Data", "base", "Daba", "atab"], "correct": 0},
        {"id": 51, "question": "What is 'Dual' table in Oracle?", "options": ["A special one-row, one-column table used for expressions", "A mirror table", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Rowid' in Oracle?", "options": ["The physical address of a row in a table", "The row number", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Rownum' in Oracle?", "options": ["A pseudocolumn that numbers result rows", "A physical ID", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Tablespace'?", "options": ["A logical storage container for database objects", "Space in a table", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Datafile'?", "options": ["A physical file that stores database data on disk", "A text file", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Control File'?", "options": ["File that stores physical structure and state of database", "A remote control", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Redo Log'?", "options": ["Files that record all changes to database for recovery", "A checklist", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Archive Log'?", "options": ["Stored copies of old redo logs", "A history book", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'SGA' (System Global Area)?", "options": ["Shared memory area for database processes", "A global map", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'PGA' (Program Global Area)?", "options": ["Private memory area for a single process", "Public memory", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Listener' in Oracle?", "options": ["A background process that listens for client connections", "A person", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'TNS' (Transparent Network Substrate)?", "options": ["Oracle's networking architecture", "A lens", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Oracle Home'?", "options": ["The directory where Oracle software is installed", "Owner's house", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'SID' (System ID)?", "options": ["Unique identifier for an Oracle instance", "Student ID", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Flashback' in Oracle?", "options": ["Utility to view or restore past states of data", "A bright light", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Data Pump'?", "options": ["High-speed utility for exporting/importing data", "A physical pump", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'RMAN' (Recovery Manager)?", "options": ["Primary tool for database backup and recovery", "A superhero", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'ASM' (Automatic Storage Management)?", "options": ["Oracle's volume manager and file system", "Manual storage", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Materialized View'?", "options": ["A view whose results are physically stored in a table", "A virtual view", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Synonym' in Oracle?", "options": ["An alias for a database object", "A similar word", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Partitioning'?", "options": ["Dividing large tables into smaller, more manageable pieces", "Splitting code", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Range Partitioning'?", "options": ["Dividing data based on a range of values (e.g. date)", "Picking a random range", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'List Partitioning'?", "options": ["Dividing data based on a specific list of values", "A list of items", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Hash Partitioning'?", "options": ["Dividing data using a hashing algorithm", "Scrambling data", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Global Index'?", "options": ["An index that covers the entire table (all partitions)", "A world index", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Local Index'?", "options": ["An index that is partitioned identically to the table", "A nearby index", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Constraint' in Oracle?", "options": ["Rule applied to columns (Primary Key, Unique, etc.)", "A tight space", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Check Constraint'?", "options": ["Ensures values in a column meet a boolean condition", "Checking a box", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is 'Self-Referencing' Foreign Key?", "options": ["A foreign key that points to the same table's primary key", "Talking to yourself", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'B-Tree Index'?", "options": ["Balanced tree index used for normal lookups", "A literal tree", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Bitmap Index'?", "options": ["Index used for columns with low cardinality (few distinct values)", "A picture", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Clustered Table'?", "options": ["Tables that share blocks based on a common key", "Messy tables", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'IOT' (Index Organized Table)?", "options": ["A table where rows are stored in B-Tree index structure", "Internet of Things", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'LOB' (Large Object)?", "options": ["Data type for large unstructured data (BLOB, CLOB)", "A lob in tennis", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'BLOB'?", "options": ["Binary Large Object (images, video)", "A mess", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'CLOB'?", "options": ["Character Large Object (long text)", "A club icon", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'EXPLAIN PLAN'?", "options": ["Shows the execution path the database will take for a query", "Talking to users", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Optimizer' in Oracle?", "options": ["Subsystem that determines the most efficient way to run SQL", "A math tool", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Hint' in Oracle SQL?", "options": ["Instructions passed to the optimizer", "A clue", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'TKPROF'?", "options": ["Tool for formatting trace files", "A professor", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'V$Views'?", "options": ["Dynamic performance views in Oracle", "Visual views", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'DBA_Views'?", "options": ["Data dictionary views for all objects in the database", "Admin views", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Grant' command?", "options": ["Used to give permissions to users", "A person's name", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Roles' in Oracle?", "options": ["Named groups of related privileges", "Acting parts", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Profile' in Oracle?", "options": ["Used to limit resources (CPU, idle time) per user", "A social page", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'PFILE' vs 'SPFILE'?", "options": ["PFILE is text-based; SPFILE is binary and persistent", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'In-Memory Column Store'?", "options": ["Oracle feature that stores data in columnar format in SGA", "Storage in brain", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Multi-tenant Architecture'?", "options": ["Consolidated database (CDB) with multiple pluggable databases (PDBs)", "Multiple houses", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Oracle GoldenGate'?", "options": ["Real-time data integration and replication software", "A golden gate", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, 25)})
