import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_pandas_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Pandas?", "options": ["A types of animal", "An open-source library for data manipulation and analysis in Python", "A web browser", "None"], "correct": 1},
        {"id": 2, "question": "What are the two primary data structures in Pandas?", "options": ["Array and List", "Series and DataFrame", "Table and Record", "None"], "correct": 1},
        {"id": 3, "question": "What is a 'Series' in Pandas?", "options": ["A TV show", "A 1D labeled array capable of holding any data type", "A 2D table", "None"], "correct": 1},
        {"id": 4, "question": "What is a 'DataFrame' in Pandas?", "options": ["A 2D labeled data structure representing a table with columns and rows", "A photo frame", "A 1D list", "None"], "correct": 0},
        {"id": 5, "question": "Which function is used to load a CSV file into a DataFrame?", "options": ["pd.read_csv()", "pd.open_csv()", "Both", "None"], "correct": 0},
        {"id": 6, "question": "How can you view the first 5 rows of a DataFrame?", "options": ["df.first()", "df.head()", "df.top()", "None"], "correct": 1},
        {"id": 7, "question": "How can you view the last 5 rows of a DataFrame?", "options": ["df.last()", "df.tail()", "df.bottom()", "None"], "correct": 1},
        {"id": 8, "question": "What's the meaning of 'df.info()'?", "options": ["Giving personal info", "Returning a summary of a DataFrame (columns, types, memory usage)", "None", "None"], "correct": 1},
        {"id": 9, "question": "Which method returns summary statistics of numeric columns in a DataFrame?", "options": ["df.describe()", "df.summary()", "df.stats()", "None"], "correct": 0},
        {"id": 10, "question": "How do you select a single column from a DataFrame 'df'?", "options": ["df['column_name']", "df.column_name", "Both A and B", "Neither"], "correct": 2},
        {"id": 11, "question": "What is 'Loc' in Pandas indexing?", "options": ["Location of a file", "Label-based indexing (selecting by label of a row/column)", "A type of view", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Iloc'?", "options": ["Integer-location based indexing (selecting by the position index)", "A list of integers", "Both", "None"], "correct": 0},
        {"id": 13, "question": "Which method is used to remove a column or row?", "options": ["df.remove()", "df.drop()", "df.delete()", "None"], "correct": 1},
        {"id": 14, "question": "How can you rename columns in a DataFrame?", "options": ["df.rename(columns={'old': 'new'})", "df.change_name()", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'df.isnull().sum()' used for?", "options": ["To count missing values in each column", "To delete the database", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "How do you remove rows with missing values?", "options": ["df.dropna()", "df.clean_null()", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "How do you fill missing values with a specific value?", "options": ["df.fillna(value)", "df.add_value()", "None", "None"], "correct": 0},
        {"id": 18, "question": "What is 'Groupby' used for in Pandas?", "options": ["Sorting a table", "Splitting data into groups based on some criteria for aggregate analysis", "Both", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Pivot Table' for?", "options": ["Summarizing and reshaping a DataFrame based on columns of interest", "Rotating an image", "A security log", "None"], "correct": 0},
        {"id": 20, "question": "How do you sort a DataFrame by a specific column?", "options": ["df.sort_values(by='column')", "df.arrange()", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What is 'pd.merge()'?", "options": ["Merging files", "Combining two DataFrames on a common key (similar to SQL JOIN)", "Neither", "Both"], "correct": 1},
        {"id": 22, "question": "What is 'df.append()'?", "options": ["Adding a suffix", "Appending a new row to an existing DataFrame (legacy, now concat preferred)", "Neither", "Both"], "correct": 1},
        {"id": 23, "question": "What does 'Axis=0' represent in Pandas operations?", "options": ["Columns", "Rows (Index)", "Both", "None"], "correct": 1},
        {"id": 24, "question": "What does 'Axis=1' represent?", "options": ["Columns", "Rows", "None", "None"], "correct": 0},
        {"id": 25, "question": "How can you find unique values in a column?", "options": ["df['col'].unique()", "df['col'].single()", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'df['col'].value_counts()'?", "options": ["Counts the frequency of each unique value in a column", "Lists all values", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "How do you save a DataFrame to a CSV file?", "options": ["df.to_csv('filename')", "df.save('filename')", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "How do you save a DataFrame to an Excel file?", "options": ["df.to_excel('filename')", "df.save_excel()", "Both", "None"], "correct": 0},
        {"id": 29, "question": "What is 'pd.to_datetime()' used for?", "options": ["Getting current time", "Converting a column of strings or numbers into actual Pandas datetime objects", "Both", "None"], "correct": 1},
        {"id": 30, "question": "Which keyword is used for adding a new column to a DataFrame?", "options": ["df['new_col'] = ...", "df.add_col(...)", "df.insert(...)", "Both A and C"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'MultiIndex' in Pandas?", "options": ["Using multiple bookmarks", "Providing hierarchical/nested indexing levels in a DataFrame", "Neither", "Both"], "correct": 1},
        {"id": 32, "question": "What's the meaning of 'inplace=True' in many methods?", "options": ["Modifies original DataFrame directly without returning new one", "Stops the program", "None", "None"], "correct": 0},
        {"id": 33, "question": "What is 'df.T' attribute for?", "options": ["Transpose of the DataFrame (switching rows and columns)", "A text result", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "How do you apply a function to every element in a or Series?", "options": ["df.apply(func)", "df.map(func)", "Both (depending on context)", "None"], "correct": 2},
        {"id": 35, "question": "What is 'df.applymap(func)' used for?", "options": ["Applying a function to each individual element of a DataFrame", "Charting a map", "None", "None"], "correct": 0},
        {"id": 36, "question": "How can you select multiple columns from 'df'?", "options": ["df[['col1', 'col2']]", "df['col1', 'col2']", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'pd.concat()'?", "options": ["Joining arrays/frames along an axis", "Merging database tables", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is the result of 'df.duplicated()'?", "options": ["Duplicates all data", "Returns a boolean series identifying duplicate rows", "Neither", "Both"], "correct": 1},
        {"id": 39, "question": "How do you remove duplicate rows?", "options": ["df.drop_duplicates()", "df.unique_rows()", "None", "None"], "correct": 0},
        {"id": 40, "question": "What is 'df.isin([list])' used for?", "options": ["Filtering rows based on multiple values in a list", "Checking file contents", "None", "None"], "correct": 0},
        {"id": 41, "question": "Can you use SQL-like 'Joins' in Pandas?", "options": ["Yes, using pd.merge() with 'how' parameter (inner, outer, left, right)", "No", "Only for tiny DataFrames", "None"], "correct": 0},
        {"id": 42, "question": "What is an 'Outer Join' in pd.merge()?", "options": ["Combining rows that don't match at all", "Returning all records from both when there's a match in either", "Both", "None"], "correct": 1},
        {"id": 43, "question": "What is an 'Inner Join' in pd.merge()?", "options": ["Returning only the rows that have matching values in both DataFrames", "All data", "None", "None"], "correct": 0},
        {"id": 44, "question": "How can you change the data type of a column?", "options": ["df['col'].astype('new_type')", "df['col'].convert('new_type')", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'df.query('condition')'?", "options": ["Searching for items", "A way to filter rows using a string-based query expression (like a SQL WHERE)", "Neither", "Both"], "correct": 1},
        {"id": 46, "question": "How do you filter rows where column 'age' is over 30?", "options": ["df[df['age'] > 30]", "df.filter(age > 30)", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'pd.get_dummies()'?", "options": ["Making a fake person", "Converting categorical data into one-hot encoded dummy variables", "Neither", "Both"], "correct": 1},
        {"id": 48, "question": "What's the meaning of 'NaN'?", "options": ["Not a Number (missing or undefined value)", "Next available name", "None", "None"], "correct": 0},
        {"id": 49, "question": "How can you check if a value is NaN?", "options": ["pd.isna(value)", "value == NaN", "Both", "None"], "correct": 0},
        {"id": 50, "question": "What's the advantage of using 'timedelta' objects?", "options": ["Easy calculation of time differences (e.g. subtracting two dates)", "A type of table", "None", "None"], "correct": 0},
        {"id": 51, "question": "Which method resets the row index of a DataFrame?", "options": ["df.reset_index()", "df.new_index()", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "Which method sets a specific column as the DataFrame index?", "options": ["df.set_index('col')", "df.use_index('col')", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'df.sample(n=5)'?", "options": ["A types of drink", "Picking 5 random rows from the DataFrame", "Both", "None"], "correct": 1},
        {"id": 54, "question": "How do you find the maximum value of a Series?", "options": ["s.max()", "np.max(s)", "Both A and B", "Neither"], "correct": 2},
        {"id": 55, "question": "How do you find the index of the maximum value in a Series?", "options": ["s.idxmax()", "s.argmax()", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'df.memory_usage()' for?", "options": ["Showing total memory used by each column", "A security log", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'pd.pivot()' versus 'pd.pivot_table()'?", "options": ["pivot_table can aggregate data; pivot cannot (can only reshape)", "Same", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Stack' versus 'Unstack' in Pandas context?", "options": ["Pivoting between a wide and long format by rotating index levels", "Merging tables", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'df.explode('col')' used for?", "options": ["Blowing up a server", "Transforms each element of a list-like column to a separate row", "Neither", "Both"], "correct": 1},
        {"id": 60, "question": "Can you use Pandas to read data from a SQL database?", "options": ["Yes, using pd.read_sql()", "No", "Only for CSVs", "None"], "correct": 0},
        {"id": 61, "question": "What is 'pd.date_range()' used for?", "options": ["Generating a series of dates at a specific frequency", "A time machine", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What does a 'DatetimeIndex' facilitate?", "options": ["Time-series analysis and easy slicing/grouping by various time components", "Deleting files", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "How do you resample time-series data to a different frequency (e.g. daily to monthly)?", "options": ["df.resample('M').mean()", "df.change_freq('M')", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Rolling' operation (e.g. df.rolling(window=3))?", "options": ["Rotating a screen", "Performing window-based calculations (like moving averages)", "Neither", "Both"], "correct": 1},
        {"id": 65, "question": "What is 'Expanding' operation?", "options": ["Similar to rolling, but window expands from the first row to the current one", "Bigger tables", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is the result of 'df.shape'?", "options": ["Returns a tuple (rows, cols)", "Returns the overall count", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is the result of 'df.columns'?", "options": ["Returns index of column names", "Removes all columns", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is the result of 'df.size'?", "options": ["Total number of elements (rows * cols)", "Overall memory size", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'Boolean Mask' in Pandas?", "options": ["A series of True/False values used to filter a DataFrame", "A decorative text", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "How can you combine multiple conditions in a filter?", "options": ["Using & (AND) and | (OR) with parentheses", "Using AND and OR keywords", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'pd.cut()' used for?", "options": ["Cutting a file", "Binning continuous data into discrete categories (intervals)", "Neither", "Both"], "correct": 1},
        {"id": 72, "question": "What is 'pd.qcut()' used for?", "options": ["Quantile-based binning (equal number of points in each bin)", "Sorting a list", "None of the above", "None"], "correct": 0},
        {"id": 73, "question": "Can you use Pandas with big data frameworks like Dask or PySpark?", "options": ["Yes, they provide Pandas-like APIs for distributed data processing", "No", "Only for CSVs", "None"], "correct": 0},
        {"id": 74, "question": "What is the default index type in Pandas if not specified?", "options": ["RangeIndex (starting from 0)", "StringIndex", "None", "None"], "correct": 0},
        {"id": 75, "question": "What is 'df.idxmin()'?", "options": ["Index of a person", "Returns the index of the first occurrence of the minimum over an axis", "Neither", "Both"], "correct": 1},
        {"id": 76, "question": "How can you see only unique values in a Series?", "options": ["s.unique()", "s.drop_duplicates()", "Both A and B", "Neither"], "correct": 2},
        {"id": 77, "question": "Which method is used for cross-tabulation in Pandas?", "options": ["pd.crosstab()", "pd.pivot()", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Categorical' data type benefit in Pandas?", "options": ["Saves memory and improves performance for columns with repeat values", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'df.agg({'col': 'mean'})' for?", "options": ["Aggregating columns with specific functions", "Deleting a record", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary benefit of vectorization in Pandas?", "options": ["Simpler code and significantly faster execution than regular loops", "Designing graphics", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
