import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_penetrationtesting_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Penetration Testing' (Pen-testing)?", "options": ["Testing if a phone works", "Authorized simulated cyberattack on a computer system to find vulnerabilities", "Deleting a computer virus", "None"], "correct": 1},
        {"id": 2, "question": "What is the goal of a penetration test?", "options": ["To break a computer", "To identify and document security weaknesses before attackers do", "To install a new OS", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Black Box' testing?", "options": ["A black computer", "Testing with no knowledge of the target's internal workings", "Testing a high-speed network", "None"], "correct": 1},
        {"id": 4, "question": "What is 'White Box' testing?", "options": ["Testing from a white room", "Testing with full knowledge of the target's internal workings and source code", "A design tool", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Grey Box' testing?", "options": ["A mixture of black and white box testing with partial knowledge", "A decorative color for code", "A type of database", "None"], "correct": 0},
        {"id": 6, "question": "What is 'Reconnaissance' in pen-testing?", "options": ["Designing a new server", "The process of gathering information about a target before an attack", "Cleaning the keyboard", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Footprinting'?", "options": ["Measuring a person's foot", "Gathering as much info as possible about a target's network/infrastructure", "A type of network error", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Vulnerability Scanning'?", "options": ["Scanning a document", "Using specialized tools to identify potential security weaknesses", "A security log", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Exploitation' in pen-testing context?", "options": ["A business strategy", "Taking advantage of an identified vulnerability to gain access or perform an action", "A type of chart", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Post-Exploitation'?", "options": ["Identifying a vulnerability", "The phase after gaining access where attackers try to maintain control and gather info", "A financial report", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Reporting' in pen-testing?", "options": ["A news headline", "Documenting the findings, successful exploits, and recommendations for the client", "A technical specification", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Social Engineering' in pen-testing?", "options": ["Building a society", "Attempting to manipulate people into revealing sensitive information", "A marketing plan", "None"], "correct": 1},
        {"id": 13, "question": "Which of these is a popular pen-testing tool?", "options": ["Metasploit", "Nmap", "Wireshark", "All of the above"], "correct": 3},
        {"id": 14, "question": "What is 'SQL Injection' (SQLi)?", "options": ["Injecting a liquid into a computer", "A type of vulnerability where attackers inject malicious SQL into input fields", "A type of table", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Cross-Site Scripting' (XSS)?", "options": ["Designing a website", "Injecting malicious scripts into web pages viewed by other users", "A security feature", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Brute Force' attack?", "options": ["A physical attack", "Attempting to gain access by trying all possible combinations of passwords", "A type of speed test", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Credential Stuffing'?", "options": ["Stuffing a physical wallet", "Automatically testing stolen login credentials on multiple websites", "A type of server", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Burp Suite'?", "options": ["A type of dress", "A popular tool for web application security testing", "A type of browser", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Nmap' used for in pen-testing?", "options": ["Watching a movie", "Network discovery and vulnerability scanning", "A security log", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Wireshark' used for?", "options": ["Capturing and analyzing network protocol traffic", "Identifying sharks online", "A technical manual", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Privilege Escalation'?", "options": ["Getting a promotion at work", "Gaining higher levels of access than originally permitted", "Replacing a computer keyboard", "None"], "correct": 1},
        {"id": 22, "question": "What is 'OSINT'?", "options": ["Open Source Intelligence (gathering data from public resources)", "One Secret Internal Network Tool", "Operating System Integrated Technology", "None"], "correct": 0},
        {"id": 23, "question": "What is 'Buffer Overflow'?", "options": ["Overflow of data buffer", "Overwriting memory beyond its boundary to execute malicious code", "Both A and B", "Neither"], "correct": 2},
        {"id": 24, "question": "What is 'Eavesdropping' in pen-testing?", "options": ["Listening to a physical room", "Intercepting network communication between two parties", "A type of network error", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Man-in-the-Middle' (MITM) attack?", "options": ["A social meeting", "A type of cyberattack where an attacker relays and alters communication", "A security feature", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Fuzzing'?", "options": ["A type of decoration", "Providing unexpected or random data as input to an application to find bugs", "A type of chart", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Backdoor'?", "options": ["The entrance to a house", "A hidden point of entry that bypasses normal authentication in a system", "A security feature", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Remediation'?", "options": ["Fixing syntax errors", "The process of fixing security vulnerabilities discovered during a test", "A technical specification", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Compliance' testing?", "options": ["Watching a movie", "Verifying that a system adheres to a specific set of security standards/regulations", "A list of reports", "None"], "correct": 1},
        {"id": 30, "question": "What is the difference between an ethical hacker and a malicious one?", "options": ["Ethical hackers have permission and follow a code of conduct", "Nothing", "Malicious hackers use newer computers", "None"], "correct": 0},
        {"id": 31, "question": "What is 'Netcat' in pen-testing?", "options": ["A type of cat online", "A versatile tool used for reading from and writing to network connections", "A types of computer virus", "None"], "correct": 1},
        {"id": 32, "question": "What is 'John the Ripper' used for?", "options": ["Historical documentation", "Password cracking and security auditing", "A types of movie", "None"], "correct": 1},
        {"id": 33, "question": "What is 'Hydra' used for?", "options": ["A Greek mythological monster", "A fast login cracker supporting numerous protocols (SSH, HTTP, etc.)", "A security log", "None"], "correct": 1},
        {"id": 34, "question": "What is 'The Social-Engineer Toolkit' (SET)?", "options": ["A types of book", "An open-source framework specifically for simulating social engineering attacks", "None", "None"], "correct": 1},
        {"id": 35, "question": "What is 'Phishing'?", "options": ["A sport in a boat", "Deceiving individuals into revealing sensitive info through fake emails/sites", "Neither", "Both"], "correct": 1},
        {"id": 36, "question": "What is 'Vishing'?", "options": ["Phishing carried out specifically through voice calls or VoIP", "A types of vision", "None", "None"], "correct": 0},
        {"id": 37, "question": "What is 'Smishing'?", "options": ["Phishing specifically through SMS text messages", "A types of small bug", "None", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Banner Grabbing'?", "options": ["Collecting info specifically from an open port including service and version name", "Taking a poster from a wall", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Packet Sniffing'?", "options": ["Smelling a package", "Intercepting and logging network traffic as it passes over a network", "Neither", "Both"], "correct": 1},
        {"id": 40, "question": "What is 'Insecure Direct Object Reference' (IDOR)?", "options": ["Accessing data by manipulating a parameter or object ID in a request", "A type of furniture", "A routing name", "None"], "correct": 0},
        {"id": 41, "question": "What is 'Zero-Day' vulnerability?", "options": ["A vulnerability that is unknown to the vendor and has no patch available", "A virus on day zero", "None", "None"], "correct": 0},
        {"id": 42, "question": "What is 'Local File Inclusion' (LFI)?", "options": ["Vulnerability allowing an attacker specifically to read local files on a server", "Adding a file to a folder", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Remote File Inclusion' (RFI)?", "options": ["Vulnerability allowing an attacker to load and execute a remote file", "Deleting a remote file", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Information Disclosure'?", "options": ["When an application unintentionally reveals sensitive data (e.g. error messages)", "A press release", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Session Hijacking'?", "options": ["Stealing a user's session token to impersonate them", "Closing a computer", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Broken Authentication'?", "options": ["Weak login systems specifically allowing attackers to compromise passwords/names", "A broken table", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Clickjacking'?", "options": ["Tricking a user into clicking something different from what they see", "Stealing a mouse", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What's the meaning of 'Payload' in exploitation?", "options": ["The actual code or script specifically executed on the target after an exploit", "The money paid for a job", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What's the meaning of 'Shell' in pen-testing?", "options": ["A command-line interface gained specifically on a target system", "A types of sea animal", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Bind Shell'?", "options": ["Listening on a port on target for an attacker to connect to", "Binding a book", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Reverse Shell'?", "options": ["The target connects back to the attacker's listening port", "A types of shoe", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Exfiltration'?", "options": ["The unauthorized transfer specifically of data from a target system", "Filtering water", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'War Driving'?", "options": ["Driving around with a list", "Searching specifically for unsecured Wi-Fi networks from a moving vehicle", "Neither", "Both"], "correct": 1},
        {"id": 54, "question": "What's the effect of 'Rogue Access Point'?", "options": ["An unauthorized Wi-Fi hotspot specifically set up to trap users", "A types of coffee shop", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Bluesnarfing'?", "options": ["Unauthorized access specifically to information on a device via Bluetooth", "A blue cartoon character", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Steganography'?", "options": ["Hiding information specifically within another file (like an image) secretely", "Building a stadium", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Cryptography' for security?", "options": ["The practice of protecting info through encryption and decryption", "The study of maps", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What represents the 'Golden Ticket' in Active Directory?", "options": ["A forged Ticket Granting Ticket specifically for full domain access", "A winning lottery ticket", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What's 'Pass-the-Hash' (PtH) attack?", "options": ["Authenticating using a hashed password specifically without needing the plaintext", "Passing a ball", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'CVE' (Common Vulnerabilities and Exposures)?", "options": ["A public list specifically of known security vulnerabilities", "A types of car", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'CVSS' used for?", "options": ["Scoring specifically the severity of vulnerabilities (e.g. 10.0 is critical)", "CV of a person", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's 'OWASP Top 10'?", "options": ["A regularly updated report specifically of the top 10 web security risks", "A types of music chart", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Penetration Testing Framework' (PTES)?", "options": ["A standard procedure specifically for conducting a professional pen-test", "A types of building", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'NIST' for security?", "options": ["Agency that provides standards and guidelines specifically for cybersecurity", "A types of bird", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Red Team' testing?", "options": ["Full-scope attack simulation specifically to evaluate defense readiness", "A sports team in red", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Blue Team'?", "options": ["Security team specifically responsible for defending and responding to attacks", "A sports team in blue", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Purple Team'?", "options": ["Collaboration between Red and Blue teams specifically to improve security", "A team in purple", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Social Engineering Toolkit' (SET)?", "options": ["A collection specifically of tools for social engineering simulations", "A dictionary", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What's 'Social Engineering via Email' (Scam)?", "options": ["Sending fake emails specifically to steal logins (Phishing)", "Talking to a person", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Dictionary Attack'?", "options": ["Trying words specifically from a list or dictionary to crack a password", "Looking at a dictionary", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's 'Rainbow Table' significance?", "options": ["A pre-computed table specifically for reversing cryptographic hash functions", "A table in a park", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What represents the 'Salt' in cryptography?", "options": ["Random data added specifically to hashing process to prevent rainbow attacks", "Putting salt in food", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Directory Traversal'?", "options": ["Exploiting server file paths specifically to access restricted files", "Going through a phone book", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Insecure Deserialization'?", "options": ["Vulnerability where untrusted data specifically is used to execute malicious code", "Opening a heavy box", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Cross-Site Request Forgery' (CSRF)?", "options": ["Tricking a logged-in user specifically into executing unwanted actions", "A types of sport", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Malware'?", "options": ["Malicious software specifically designed to damage or gain access", "Buying things online", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What's 'Ransomware'?", "options": ["Malware specifically that encrypts files and demands payment for the key", "A types of news", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Trojan' in cyber terms?", "options": ["Malware disguised specifically as legitimate software", "A types of horse", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What's 'Spyware'?", "options": ["Software designed to secretly gather info specifically from a device", "Taking photos of people", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Pen-testing vital for modern businesses?", "options": ["Enables proactive identification of security gaps specifically to protect data", "Increases social media presence", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
