import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_powerpoint_api(request):
    questions_pool = [
        {"id": 1, "question": "What is MS PowerPoint?", "options": ["A types of table", "An application for creating and delivering professional presentations via slides", "A list of strings", "None"], "correct": 1},
        {"id": 2, "question": "What is the file extension for MS PowerPoint?", "options": [".pptx", ".ppt", ".pdf", ".ppsx"], "correct": 0},
        {"id": 3, "question": "What is a 'Slide'?", "options": ["A physical playground slide", "A single page/canvas in a PowerPoint presentation for and content", "Neither", "Both"], "correct": 1},
        {"id": 4, "question": "What is 'Slide Show' (F5)?", "options": ["Displaying the slides one by one from the start to the audience", "Starting a movie", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "What is 'Transition' in PowerPoint?", "options": ["The visual effect specifically when moving from one slide to another (e.g. Fade)", "A styles of clothes", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is 'Animation'?", "options": ["Visual effects applied to individual objects within a slide (e.g. fly in)", "A movie in a slide", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is 'Ribbon'?", "options": ["The toolbar at the top that contains all groups and commands", "A physical ribbon", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is 'Layout' for a slide?", "options": ["The arrangement of placeholders for text, images, and charts on a slide", "A design for a room", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Placeholder'?", "options": ["Pre-formatted box specifically for entering text or inserting content on a slide", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "Which constant is used to add a new slide?", "options": ["Ctrl + M", "Ctrl + N", "Ctrl + S", "None"], "correct": 0},
        {"id": 11, "question": "Which constant is used for a new file (Presentation)?", "options": ["Ctrl + M", "Ctrl + N", "Neither", "Both"], "correct": 1},
        {"id": 12, "question": "What is 'Slide Master' significance?", "options": ["The source slide that controls the layout and theme for the whole deck", "A master of slides", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Theme' in PowerPoint?", "options": ["A coordinated set specifically for fonts, colors, and backgrounds", "A musical score", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What's 'Presenter View' used for?", "options": ["Presenter seeing notes and next slide while audience sees the main view", "Watching a movie", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Notes Pane' for?", "options": ["Adding extra text for the presenter specifically to use during the speech", "Writing a letter", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "How to start a slide show from the current slide?", "options": ["Shift + F5", "Ctrl + F5", "Neither", "Both"], "correct": 0},
        {"id": 17, "question": "What is 'SmartArt'?", "options": ["Intelligent graphics specifically to represent info and processes visually", "An intelligent person", "Neither", "Both"], "correct": 0},
        {"id": 18, "question": "What is 'WordArt' for titles?", "options": ["Applying decorative effects specifically to text in a slide", "A types of painting", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Slide Sorter' view?", "options": ["Visual overview of all slides specifically for rearranging them quickly", "A sorting box", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "How to stop a slide show quickly?", "options": ["ESC key", "Ctrl + Q", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "How can you duplicate a slide?", "options": ["Right-click slide -> Duplicate Slide (or Ctrl+D)", "Ctrl + C and Ctrl + V", "Both A and B", "Neither"], "correct": 2},
        {"id": 22, "question": "What is 'Hyperlink' in PowerPoint?", "options": ["A clickable link specifically to another slide, file or website", "A fast link", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "What is 'Action Button'?", "options": ["Buttons on a slide that perform actions (like 'Next Slide') when clicked", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What is 'Eye dropper' tool?", "options": ["Picking an exact color from any object specifically on the screen to match it", "Medicine for eye", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What is 'Design Ideas' (Designer)?", "options": ["AI-driven feature specifically to automatically suggest better layouts and styles", "Asking for advice", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Export as MP4 Video' significance?", "options": ["Turning your entire slide deck specifically into a stand-alone movie file", "Making it faster", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What's '.pdf' export in PowerPoint?", "options": ["Saving slides as static images for easy viewing without PowerPoint app", "Making for a bank", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Photo Album' feature?", "options": ["Quickly creating a presentation specifically by importing many photos at once", "A physical album", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What's the meaning of 'Grouping' objects?", "options": ["Combining several items (images/shapes) specifically to treat them as one unit", "Grouping students", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Who created MS PowerPoint?", "options": ["Microsoft", "Google", "Apple", "IBM"], "correct": 0},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Slide Transition Duration'?", "options": ["Setting specifically how long the transition effect between slides lasts", "A timer for a clock", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Animation Delay'?", "options": ["Pausing specifically before an animation starts for a set time", "Waiting for a bus", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'Animation Trigger'?", "options": ["Defining an event (like a click) that starts a specific animation", "A types of gun", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Rehearse Timings' useful for?", "options": ["Recording specifically how long you spend on each slide during practice", "Buying a watch", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What is 'Record Slide Show'?", "options": ["Capturing your voice and slide movements specifically to make a narrated video", "Recording a phone call", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Section' specifically for slides?", "options": ["Grouping related slides into labeled groups for easier management", "A section of a room", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What's the effect of 'Ruler' and 'Guides'?", "options": ["Positioning and aligning objects with professional precision on a slide", "Measuring roads", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "How to lock an object on a slide (in some versions)?", "options": ["Preventing it from being moved or edited accidentally", "Using a physical lock", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What's the meaning of 'Hide Slide'?", "options": ["Keeping a specific slide in the deck specifically without showing it in show", "Moving things back", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Slide Sorter' vs 'Normal' view?", "options": ["Overview vs Single slide for detailed editing", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Outline' view for?", "options": ["Displaying only the text of the slides specifically to organize flow rapidly", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Handout Master'?", "options": ["Managing how your slides will look specifically when printed as handouts", "A master of hands", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Notes Master'?", "options": ["Setting the physical layout of presenter notes when printed", "A types of music", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's the meaning of 'Save As' versus 'Save'?", "options": ["Creating a new copy with different name/filetype vs updating current", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Cloud Sharing' in PowerPoint?", "options": ["Allowing multiple people specifically to edit slides together in real-time online", "Talking on phone", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Auto-Save' (OneDrive)?", "options": ["Automatically saving every few seconds specifically to prevent data loss online", "Saving once a week", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "Which constant is used for 'Bold'?", "options": ["Ctrl + B", "Ctrl + I", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "Which constant is used for 'Italic' text?", "options": ["Ctrl + I", "Ctrl + U", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "Which constant is used for 'Underline'?", "options": ["Ctrl + U", "Ctrl + P", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'Alignment' (Left, Right, Center)?", "options": ["Positioning text relative to its placeholder", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Font Size' unit?", "options": ["Points (e.g. 24 pt)", "Pixels", "Both", "None"], "correct": 0},
        {"id": 52, "question": "How to change a slide's aspect ratio (4:3 vs 16:9)?", "options": ["Design -> Slide Size", "Home -> Resize", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Aspect Ratio' significance?", "options": ["Matching the dimensions specifically of the slides to the display screen", "Measuring a road", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What's the meaning of 'Widescreen' in presentations?", "options": ["Standard modern 16:9 layout for LCD monitors and projectors", "A large TV", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "How to add a table in PowerPoint?", "options": ["Insert -> Table", "Drawing by hand", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Excel Spreadsheet' insertion in PowerPoint?", "options": ["Embedding a live Excel sheet specifically inside a slide for data", "Making a link", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's 'Audio' insertion for?", "options": ["Adding bGM or narration specifically to play during the slide show", "A video file", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What's 'Video' insertion for?", "options": ["Adding movies specifically (like YouTube or local file) onto a slide", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "How can you loop a video in PowerPoint?", "options": ["Playback -> Loop until Stopped", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How can you trim a video clip in PowerPoint?", "options": ["Playback -> Trim Video (allows cutting start/end of clip)", "Cutting a tape", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Morph' transition context?", "options": ["A types of chemical name", "Advanced transition specifically creating smooth move between same objects on slides", "Neither", "Both"], "correct": 1},
        {"id": 62, "question": "What is 'Zoom' feature (Summary Zoom)?", "options": ["Making things bigger", "Adding interactive links specifically that zoom into specific slides/sections", "Neither", "Both"], "correct": 1},
        {"id": 63, "question": "What's 'Ink to Shape' tool?", "options": ["Converting hand-drawn shapes specifically into perfect digital ones", "A types of ball", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's 'Ink to Text' feature?", "options": ["Converting handwriting specifically into standard typed text automatically", "Drawing on book", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "How do you check for accessibility issues?", "options": ["Review -> Check Accessibility", "Guessing", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Translate' tool inside PowerPoint?", "options": ["Translating slide text into multiple other languages automatically", "Moving slides", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's the benefit of the 'Thesaurus' in PowerPoint?", "options": ["Finding identical words specifically for better slide impact", "A book name", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "How to find specific words in a presentation?", "options": ["Ctrl + F", "Ctrl + S", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "How to replace multiple words at once?", "options": ["Ctrl + H", "Ctrl + J", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Custom Slide Show'?", "options": ["Presenting specifically only certain slides for specific audiences in one deck", "Designing a new show", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "Can you protect a PowerPoint deck with password?", "options": ["Yes, using File -> Info -> Protect Presentation", "No", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's the 'Loop Continuously until ESC' setting for?", "options": ["Making the show automatically restart after the last slide", "Restarting a car", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "How to change the background for all slides by once?", "options": ["Changing it on the 'Slide Master'", "Changing each slide", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Grayscale' / 'Black and White' view?", "options": ["Seeing how slides look specifically without color specifically for printing", "A movie style", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's the meaning of 'Transparency' for objects?", "options": ["Making items see-through for better overlay effects", "Opening a window", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What's 'Align to Middle' significance?", "options": ["Centering an object vertically within the slide", "Positioning a ball", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What represents the 'Bring to Front'?", "options": ["Moving an object specifically above all others in the stack", "Moving people to line", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents the 'Send to Back'?", "options": ["Moving an object specifically behind all others in the stack", "Going back to home", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What's 'Selection Pane' usefulness?", "options": ["Viewing and naming all objects on a slide for easier management", "Choosing a book", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary benefit of MS PowerPoint?", "options": ["Providing powerful tools specifically for communicating ideas and info visually", "Having more TV channels", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
