import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_probasics_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Programming?", "options": ["Talking to people", "Writing instructions for a computer to execute specific tasks", "A types of TV", "None"], "correct": 1},
        {"id": 2, "question": "What is a 'Program'?", "options": ["A list of notes", "A sequence of instructions written in a programming language", "A search for files", "None"], "correct": 1},
        {"id": 3, "question": "What is 'Syntax' in programming?", "options": ["Rules governing how code is written and structured", "A tax on computers", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Variable'?", "options": ["Something that changes", "A named storage location in memory for holding data", "Both A and B", "Neither"], "correct": 1},
        {"id": 5, "question": "What is 'Data Type'?", "options": ["The kind of value a variable can hold (e.g. integer, string)", "A styles of typing", "Neither", "Both"], "correct": 0},
        {"id": 6, "question": "What is an 'Integer' (int)?", "options": ["A whole number (like 1, -5, 100)", "A types of bread", "Neither", "Both"], "correct": 0},
        {"id": 7, "question": "What is a 'String' (str)?", "options": ["A sequence of characters (text like 'Hello')", "A types of rope", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What is a 'Boolean' (bool)?", "options": ["A types of ball", "A data type that can only be True or False", "Neither", "Both"], "correct": 1},
        {"id": 9, "question": "What is 'Algorithm'?", "options": ["A step-by-step procedure or set of rules to solve a problem", "Calculating math with code", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is a 'Loop' in programming?", "options": ["A physical circle", "Repeating a block of code multiple times based on a condition", "A security log", "None"], "correct": 1},
        {"id": 11, "question": "What is 'Conditional Statement' (If/Else)?", "options": ["Code that runs only if a certain condition is met", "A types of logic for math", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What is 'Function' (or Method)?", "options": ["A types of math equation only", "A reusable block of code designed to perform a specific task", "Neither", "Both"], "correct": 1},
        {"id": 13, "question": "What is 'Parameter' versus 'Argument'?", "options": ["Variable in function definition vs actual value passed during call", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Input' in a program?", "options": ["Data provided to the program (e.g. keyboard, mouse, file)", "Producing results", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What is 'Output'?", "options": ["Providing results of the program (e.g. screen, printer, file)", "Taking values", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "What is 'Compiler'?", "options": ["A types of book", "A program specifically for translating code from one source to machine code", "Neither", "Both"], "correct": 1},
        {"id": 17, "question": "What is 'Interpreter'?", "options": ["Translating languages for people", "Executing code line-by-line without pre-compiling the entire file", "Neither", "Both"], "correct": 1},
        {"id": 18, "question": "What is 'Source Code'?", "options": ["Writing code with a pen", "The human-readable code written by a programmer", "Neither", "Both"], "correct": 1},
        {"id": 19, "question": "What is 'Machine Code'?", "options": ["Hardware for computers", "The fundamental language (binary) that a computer's CPU actually executes", "Neither", "Both"], "correct": 1},
        {"id": 20, "question": "What is 'Debugging'?", "options": ["Looking for bugs in nature", "Finding and fixing errors in a program", "Neither", "Both"], "correct": 1},
        {"id": 21, "question": "What's 'Binary' system (0 and 1)?", "options": ["The fundamental language of computers based on two states", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "How many states are in binary?", "options": ["Two (0 and 1)", "Ten", "Sixteen", "None"], "correct": 0},
        {"id": 23, "question": "What's 'Logical AND' (&&)?", "options": ["Returns true ONLY if both conditions are true", "Returns true if one is true", "Neither", "Both"], "correct": 0},
        {"id": 24, "question": "What's 'Logical OR' (||)?", "options": ["Returns true if at least one of the conditions is true", "Returns true if both are false", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "What's 'Logical NOT' (!)?", "options": ["Inverts the boolean value (True to False, False to True)", "Giving a negative answer", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Operator' (e.g. +, -, *, /)?", "options": ["Symbols used to perform operations on variables and values", "A person working at a company", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Array' (or List)?", "options": ["A group of people", "A collection of multiple items stored in a single variable location", "Neither", "Both"], "correct": 1},
        {"id": 28, "question": "What's the 'Index' in an array?", "options": ["A pointer to a specific position in an array (usually starting from 0)", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'Comment' in code?", "options": ["Text for the machine only", "Notes for humans that are ignored by the compiler/interpreter", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "What is 'Pseudocode'?", "options": ["Programming code that is almost complete", "Informal way to describe an algorithm without strict programming syntax", "Neither", "Both"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Infinite Loop'?", "options": ["A loop that never ends accidentally (causing crashes)", "A very long loop", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What is 'Variable Naming Convention'?", "options": ["Standardized rules for naming variables for readability (e.g. camelCase)", "A types of book", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What's 'Constant' variable (const)?", "options": ["A variable whose value cannot be changed after assignment", "A variable that always changes", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "What is 'Recursion'?", "options": ["A function that calls itself to solve smaller pieces of a problem", "Restarting a program", "Neither", "Both"], "correct": 0},
        {"id": 35, "question": "What's 'IDE' (Integrated Development Environment)?", "options": ["A types of table", "Software (e.g. VS Code, PyCharm) providing tools for writing and testing code", "Neither", "Both"], "correct": 1},
        {"id": 36, "question": "What is 'Library' in programming?", "options": ["A building for books", "A collection of pre-written code for common tasks to save time", "Neither", "Both"], "correct": 1},
        {"id": 37, "question": "What is 'Framework'?", "options": ["A structure for a house", "A larger foundation/skeleton specifically for building complex applications", "Neither", "Both"], "correct": 1},
        {"id": 38, "question": "What is 'API' (Application Programming Interface)?", "options": ["A tool for people only", "A set of rules allowing different software programs to communicate", "Neither", "Both"], "correct": 1},
        {"id": 39, "question": "What is 'Frontend' development?", "options": ["Working on the part of an app the user directly sees and interacts with", "Designing icons only", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Backend' development?", "options": ["Designing a room with code", "Working on logic, databases and servers behind the scenes", "Neither", "Both"], "correct": 1},
        {"id": 41, "question": "What is 'Database' role in programming?", "options": ["Securely storing and organizing data for programs to use", "Writing notes", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Relational Database' (SQL)?", "options": ["Database using tables and relationships to organize data", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What's 'Non-relational Database' (NoSQL)?", "options": ["Database specifically designed for high-performance without strict tables", "No database at all", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What's 'Object-Oriented Programming' (OOP)?", "options": ["Organizing code around data objects rather than just functions", "Working with objects in nature", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'Class' in OOP?", "options": ["A classroom", "A blueprint or template specifically for creating objects", "Neither", "Both"], "correct": 1},
        {"id": 46, "question": "What is 'Object' in OOP?", "options": ["A physical item", "A specific individual instance of a class", "Neither", "Both"], "correct": 1},
        {"id": 47, "question": "What's 'Encapsulation' in OOP?", "options": ["The mechanism for hiding data and protecting it from outside access", "Opening a window", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Inheritance'?", "options": ["Allowing a class to take on properties and methods from another parents class", "Receiving money from family", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Polymorphism'?", "options": ["A types of chemical name", "The ability of different objects to respond differently to the same message/call", "Neither", "Both"], "correct": 1},
        {"id": 50, "question": "What is 'Abstraction'?", "options": ["Thinking really hard", "Simplifying complex systems by hiding technical details from the user", "Neither", "Both"], "correct": 1},
        {"id": 51, "question": "What is 'Version Control' (e.g. Git)?", "options": ["System for tracking and managing changes to code over time", "A version of a book", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What's 'Documentation' importance?", "options": ["Creating a guide specifically explaining HOW to use and build with your code", "Writing notes for home", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Scripting Language' (e.g. Python, JS)?", "options": ["Writing a play using code", "Languages often interpreted and used for automation or web logic", "Neither", "Both"], "correct": 1},
        {"id": 54, "question": "What is 'Compiled Language' (e.g. C, C++)?", "options": ["Languages that must be pre-converted to machine code before execution", "Deleting code", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What's 'Web Development'?", "options": ["Building websites and web-based applications", "Drawing icons", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Mobile App Development'?", "options": ["Building apps specifically for phones and tablets", "A speed test", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What's 'Game Development'?", "options": ["Designing and building video games and simulations", "Playing games", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Open Source' software?", "options": ["Opening a door with code", "Software whose source code is available for anyone to see, study, and change", "Neither", "Both"], "correct": 1},
        {"id": 59, "question": "What's 'Commercial Software'?", "options": ["Proprietary software that must be purchased to use", "A types of TV", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Bug' in software?", "options": ["An insect", "An error, flaw, or fault in code causing unintended results", "Neither", "Both"], "correct": 1},
        {"id": 61, "question": "What is 'Patch' for software?", "options": ["Fixing a hole in clothes", "A small update specifically intended to fix a bug or security hole", "Neither", "Both"], "correct": 1},
        {"id": 62, "question": "What's 'Logic Error' versus 'Syntax Error'?", "options": ["Code runs but produces wrong result vs Code won't even start", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's 'Runtime Error'?", "options": ["Errors that happen while a program is actually running", "Errors while writing code", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Testing' in programming?", "options": ["Reviewing a book", "Systematically checking code to ensure it meets requirements and has no bugs", "Both", "None"], "correct": 1},
        {"id": 65, "question": "What is 'Unit Testing'?", "options": ["Testing individual pieces of code for correctness", "A test for units", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's 'Integration Testing'?", "options": ["Checking how different modules of an application work together", "A long test", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's 'Regression Testing'?", "options": ["Ensuring that new updates didn't break existing working features", "Deleting old code", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What's the meaning of 'End-to-End' (E2E) testing?", "options": ["Testing the whole system from start to finish like a real user", "From one end of a room to other", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Deployment'?", "options": ["Writing code", "The process specifically of making your software available for others to use", "Both", "None"], "correct": 1},
        {"id": 70, "question": "What is 'Staging' environment?", "options": ["A pre-production copy of the app for final testing", "A theater stage", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Production' environment?", "options": ["The live version of the software used by real customers", "Where things are made", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What's the meaning of 'Scalability' for apps?", "options": ["The ability to handle increasing numbers of users or data without failing", "Measuring size", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's 'Performance' in software?", "options": ["How fast and efficiently a program uses system resources", "Directing a show", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's 'Code Quality'?", "options": ["How well-written, secure, and maintainable the code is", "The thickness of paper", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Refactoring'?", "options": ["Re-writing code to improve structure and quality without changing behavior", "Building a factory", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'Big O' notation used for?", "options": ["A types of circle", "Measuring the efficiency of an algorithm in terms of time and space", "Neither", "Both"], "correct": 1},
        {"id": 77, "question": "What's 'Tech Stack'?", "options": ["A stack of computer books", "The set of languages and tools used to build a specific software project", "Neither", "Both"], "correct": 1},
        {"id": 78, "question": "How do you become a better programmer?", "options": ["Practice, persistent learning, and problem solving", "Watching more TV", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Is computer programming a team sport?", "options": ["Yes, modern development usually happens in teams using collaboration tools", "No, it is for individuals only", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is the primary result of good programming?", "options": ["Reliable, secure apps that solve real problems efficiently", "Having more social media followers", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
