import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_py_datascience_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Python for Data Science?", "options": ["A tool for drawings", "Using Python and its libraries (Pandas, NumPy, etc.) to analyze and interpret data", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "Which of these is a core library for Data Science in Python?", "options": ["Pandas", "NumPy", "Matplotlib", "All of the above"], "correct": 3},
        {"id": 3, "question": "What is the primary function of Pandas?", "options": ["Drawing complex graphs", "Data manipulation and analysis using DataFrames", "A search engine", "None"], "correct": 1},
        {"id": 4, "question": "What is NumPy primarily used for?", "options": ["Writing raw HTML", "High-performance numerical computations and many-dimensional arrays", "A security log", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Jupyter Notebook'?", "options": ["A types of physical notebook", "An interactive web-based environment for writing and running code", "Both A and B", "Neither"], "correct": 1},
        {"id": 6, "question": "Which library is used for basic data visualization in Python?", "options": ["Matplotlib", "Seaborn", "Both A and B", "None"], "correct": 2},
        {"id": 7, "question": "What is 'DataFrame' in Pandas?", "options": ["A photo frame", "A 2D labeled data structure representing a table", "A list of strings", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Series' in Pandas?", "options": ["A TV show", "A 1D labeled data structure (similar to an array)", "A routing engine", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Pip' used for?", "options": ["Drinking water", "Python package manager for installing libraries", "A design tool", "None"], "correct": 1},
        {"id": 10, "question": "Which library is commonly used for Machine Learning in Python?", "options": ["Scikit-learn", "Requests", "Bottle", "None"], "correct": 0},
        {"id": 11, "question": "What is 'Anaconda' in Data Science context?", "options": ["A snake", "A distribution of Python and R for data science and package management", "A search tool", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Exploratory Data Analysis' (EDA)?", "options": ["A legal term", "The process of analyzing datasets to summarize their main characteristics", "None of the above", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Data Cleaning'?", "options": ["Wiping physical server", "The process of fixing or removing incorrect, corrupted, formatted incorrectly data", "Both", "None"], "correct": 1},
        {"id": 14, "question": "Which command is used to install pandas?", "options": ["pip install pandas", "python install pandas", "None", "None"], "correct": 0},
        {"id": 15, "question": "What are 'List Comprehensions' in Python?", "options": ["A concise way to create lists using a single line of code", "A type of table", "A list of errors", "None"], "correct": 0},
        {"id": 16, "question": "What is 'Dictionary' in Python?", "options": ["A book of definitions", "A collection of key-value pairs used for mapping and storage", "Both", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Tuples' in Python?", "options": ["A group of items", "An ordered and immutable collection of elements", "A tech spec", "None"], "correct": 1},
        {"id": 18, "question": "What is 'PEP 8' in Python?", "options": ["A type of soda", "A style guide for writing Python code", "A mobile OS", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Virtual Environment' in Python?", "options": ["A fake laptop", "An isolated workspace that prevents dependency conflicts between projects", "Both", "None"], "correct": 1},
        {"id": 20, "question": "What is 'List' in Python?", "options": ["A collection of random objects", "An ordered and mutable collection of items", "A security log", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Lambda Function'?", "options": ["An anonymous, one-liner function without a name", "A complex class", "Both", "None"], "correct": 0},
        {"id": 22, "question": "What is 'Map' function used for?", "options": ["Drawing a physical map", "Applying a specific function to all elements in a list/iterable", "Both", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Filter' function used for?", "options": ["A way to clean data", "Extracting elements of an iterable that meet a specific condition", "A routing name", "None"], "correct": 1},
        {"id": 24, "question": "Which of these is a popular data visualization library based on Matplotlib?", "options": ["Seaborn", "Plotly", "ggplot", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Scipy' built upon?", "options": ["NumPy", "Pandas", "Matplotlib", "None"], "correct": 0},
        {"id": 26, "question": "What's the meaning of 'Markdown' in Jupyter?", "options": ["A lightweight markup language to format text descriptions and notes", "A design tool", "None", "None"], "correct": 0},
        {"id": 27, "question": "How can you read a CSV file into a DataFrame in Pandas?", "options": ["pd.read_csv('filename')", "pd.open_csv('filename')", "Both", "None"], "correct": 0},
        {"id": 28, "question": "What is 'Head()' method in Pandas used for?", "options": ["Returning top rows of a DataFrame (default is 5)", "Returning headers", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'Tail()' method in Pandas?", "options": ["Returning bottom rows of a DataFrame (default is 5)", "Deleting rows", "None of the above", "None"], "correct": 0},
        {"id": 30, "question": "What is 'Concat' in Pandas?", "options": ["Merging tables", "A method for joining or concatenating multiple DataFrames along an axis", "Both", "None"], "correct": 1},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Python' used for in AI development?", "options": ["It is the primary language for building AI and ML models due to its libraries", "Creating physical robots only", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "Which function is used to check the shape of a NumPy array?", "options": ["np.shape()", "array.shape", "Both A and B", "None"], "correct": 2},
        {"id": 33, "question": "What is 'Broadcasting' in NumPy?", "options": ["Sending radio signals", "A mechanism that allows NumPy to perform operations on arrays of different shapes", "Neither", "Both"], "correct": 1},
        {"id": 34, "question": "What does a 'Pandas Index' represent?", "options": ["A bookmark", "Labels for the rows of a DataFrame", "A type of table", "None"], "correct": 1},
        {"id": 35, "question": "What is 'Loc' vs 'Iloc' in DataFrames?", "options": ["Label-based vs Integer-based indexing", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Conda' package manager?", "options": ["An alternative to pip specifically for scientific computing environments", "A social media brand", "None", "None"], "correct": 0},
        {"id": 37, "question": "What is 'Matplotlib Pyplot'?", "options": ["A module of Matplotlib used for creating plots and charts", "Drawing icons", "None", "None"], "correct": 0},
        {"id": 38, "question": "Which function allows getting descriptive statistics in Pandas?", "options": ["df.describe()", "df.stat()", "df.info()", "None"], "correct": 0},
        {"id": 39, "question": "What is 'Missing Value' represented as in Pandas?", "options": ["NaN (Not a Number)", "NULL", "EMPTY", "None"], "correct": 0},
        {"id": 40, "question": "Which method removes missing values in Pandas?", "options": ["df.dropna()", "df.clean()", "df.remove()", "None"], "correct": 0},
        {"id": 41, "question": "Which method fills missing values in Pandas?", "options": ["df.fillna(value)", "df.add(value)", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Groupby' in Pandas used for?", "options": ["Sorting a table", "Splitting the data into groups for analysis/aggregation", "Neither", "Both"], "correct": 1},
        {"id": 43, "question": "What is 'Pivot Table' in Pandas?", "options": ["A table for rotation", "A powerful way to summarize and reshape data by aggregating values", "None", "None"], "correct": 1},
        {"id": 44, "question": "What is 'Scikit-learn' (sklearn)?", "options": ["A library for machine learning algorithms and tools", "A book name", "None", "None"], "correct": 0},
        {"id": 45, "question": "Which of these is a machine learning algorithm in sklearn?", "options": ["Random Forest", "Logistic Regression", "K-Means", "All of the above"], "correct": 3},
        {"id": 46, "question": "What is 'One-Hot Encoding'?", "options": ["Cooking data", "Converting categorical variables into a binary matrix for machine learning", "A search tool", "None"], "correct": 1},
        {"id": 47, "question": "What is 'Normalization' in data processing?", "options": ["Rescaling values between a specific range, usually 0 and 1", "Adding values", "None", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Standardization' in Data Science?", "options": ["Rescaling data to have a mean of 0 and standard deviation of 1", "Formatting text", "None", "None"], "correct": 0},
        {"id": 49, "question": "What is 'Training Set'?", "options": ["Data used to build and train a machine learning model", "A group of employees", "None", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Test Set'?", "options": ["A set of physical tests", "An independent subset of data used to evaluate model performance", "A routing name", "None"], "correct": 1},
        {"id": 51, "question": "Which function computes the correlation matrix in Pandas?", "options": ["df.corr()", "df.relate()", "df.matrix()", "None"], "correct": 0},
        {"id": 52, "question": "What is 'Feature Engineering'?", "options": ["Designing hardware parts", "The process of creating new features or modifying existing ones to improve model precision", "None", "None"], "correct": 1},
        {"id": 53, "question": "What is 'Underfitting' in ML?", "options": ["Model is too simple and learns neither training nor test data well", "Too many features", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Overfitting' in ML?", "options": ["A very large model", "Model learns the training data too well, including its noise, failing on new test data", "None", "None"], "correct": 1},
        {"id": 55, "question": "What is 'Cross-Validation'?", "options": ["A way to validate across servers", "A technique to assess how a model will generalize to an independent dataset", "None of the above", "None"], "correct": 1},
        {"id": 56, "question": "What is 'Supervised Learning'?", "options": ["Watching someone learn", "Training a model on labeled data where the output is known", "Neither", "Both"], "correct": 1},
        {"id": 57, "question": "What is 'Unsupervised Learning'?", "options": ["Learning with a teacher", "Finding hidden patterns in data that doesn't have labels", "None of the above", "None"], "correct": 1},
        {"id": 58, "question": "What is 'Clustering'?", "options": ["Grouping people together", "Groupings of similar data points together based on specific features", "None", "None"], "correct": 1},
        {"id": 59, "question": "What is 'Regression' primarily used for?", "options": ["Predicting categorical labels", "Predicting continuous numerical outcomes (like home price)", "Sorting a list", "None"], "correct": 1},
        {"id": 60, "question": "What is 'Classification' for?", "options": ["Predicting continuous values", "Predicting discrete class labels (e.g. Spam or Not Spam)", "A search tool", "None"], "correct": 1},
        {"id": 61, "question": "What is 'Precision' in model evaluation?", "options": ["The accuracy for correctly predicted positive observations", "A list of strings", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Recall' (Sensitivity)?", "options": ["Bringing back a memory", "The ratio of correctly predicted positive observations to all actual positives", "Both", "None"], "correct": 1},
        {"id": 63, "question": "What is 'F1-Score'?", "options": ["A car racing name", "The harmonic mean of precision and recall", "Neither", "Both"], "correct": 1},
        {"id": 64, "question": "What is 'Confusion Matrix'?", "options": ["A matrix that makes you confused", "A table used to describe the performance of a classification model", "Both", "None"], "correct": 1},
        {"id": 65, "question": "What is 'Mean Squared Error' (MSE)?", "options": ["An error in code", "A measure of the average of the squares of errors in regression", "None", "None"], "correct": 1},
        {"id": 66, "question": "What is 'Logarithm' transformation used for in Data Science?", "options": ["Reducing skewness in data", "Calculating interest", "None", "None"], "correct": 0},
        {"id": 67, "question": "Which of these is a Python deep learning library?", "options": ["TensorFlow", "PyTorch", "Keras", "All of the above"], "correct": 3},
        {"id": 68, "question": "What is 'Neural Network'?", "options": ["A group of brain cells only", "A system inspired by biological brains, designed to recognize patterns", "Both", "None"], "correct": 1},
        {"id": 69, "question": "What is 'Epoch' in deep learning?", "options": ["A large amount of time", "One complete pass through the entire training dataset", "None of the above", "None"], "correct": 1},
        {"id": 70, "question": "What is 'Batch Size'?", "options": ["The size of a batch of cookies", "The number of training examples used in one iteration", "None", "None"], "correct": 1},
        {"id": 71, "question": "What is 'Learning Rate'?", "options": ["The speed of learning", "A parameter controlling how much to change the model's weights during training", "Both", "None"], "correct": 1},
        {"id": 72, "question": "What is 'Activation Function' (e.g. ReLU)?", "options": ["Starting an app", "A mathematical function added to neural networks to help learn complex patterns", "Neither", "Both"], "correct": 1},
        {"id": 73, "question": "What is 'Data Wrangling'?", "options": ["Controlling data animals", "The process of cleaning and transforming raw data into a usable format", "None", "None"], "correct": 1},
        {"id": 74, "question": "Which keyword is used to handle data with many dimensions in NumPy?", "options": ["ndarray", "multi", "Both", "None"], "correct": 0},
        {"id": 75, "question": "What is 'Principal Component Analysis' (PCA)?", "options": ["Analysis of principals", "A dimensionality reduction technique that retains most information", "None", "None"], "correct": 1},
        {"id": 76, "question": "What is the purpose of 'Plotly'?", "options": ["Building interactive, web-based graphs and charts", "Deleting records", "Both", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Imputation' in Data Science?", "options": ["Changing all data to 0", "A method for replacing missing data with substituted values", "Deleting a database", "None"], "correct": 1},
        {"id": 78, "question": "Which command-line tool allows interactive data exploration?", "options": ["IPython", "Jupyter", "Both A and B", "None"], "correct": 2},
        {"id": 79, "question": "What is the result of '1 / 0' in Python?", "options": ["0", "ZeroDivisionError", "Infinity", "None"], "correct": 1},
        {"id": 80, "question": "What is 'Pickle' in Python context?", "options": ["A type of food", "A module used for serializing and de-serializing objects", "Neither", "Both"], "correct": 1},
        {"id": 81, "question": "What is 'Pickle' in Python context?", "options": ["A type of food", "A module used for serializing and de-serializing objects", "Neither", "Both"], "correct": 1},
        {"id": 82, "question": "What is 'Matplotlib'?", "options": ["A plotting library for data visualization", "A math library", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Seaborn'?", "options": ["A statistical data visualization library", "A type of fish", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Plotly'?", "options": ["Building interactive, web-based graphs and charts", "Deleting records", "Both", "None"], "correct": 0},
        {"id": 85, "question": "What is 'Jupyter Notebook'?", "options": ["An interactive web environment for data analysis", "A type of paper", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Pandas'?", "options": ["A library for data manipulation and analysis", "A type of bear", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'NumPy'?", "options": ["A library for numerical computing in Python", "A number library", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Scikit-learn'?", "options": ["Machine learning library for Python", "A learning kit", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'TensorFlow'?", "options": ["Deep learning framework by Google", "A flow of data", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Keras'?", "options": ["High-level neural network API for Python", "A type of fish", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'PyTorch'?", "options": ["Deep learning framework for Python", "A torch for data", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'XGBoost'?", "options": ["Gradient boosting algorithm for structured data", "A type of boost", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'LightGBM'?", "options": ["Gradient boosting framework for efficient training", "A light boosting method", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'CatBoost'?", "options": ["Gradient boosting algorithm that handles categorical features", "A cat boost", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Random Forest'?", "options": ["Ensemble learning method using multiple decision trees", "A forest with random trees", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Support Vector Machine' (SVM)?", "options": ["Classification algorithm finding optimal hyperplane", "A machine for support", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'K-Means'?", "options": ["Unsupervised clustering algorithm", "A clustering method", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'DBSCAN'?", "options": ["Density-based clustering algorithm", "A scanning method", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Hierarchical Clustering'?", "options": ["Building clusters from bottom-up", "A tree-based clustering", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Cross-Validation'?", "options": ["Evaluating model performance on different data splits", "Testing multiple times", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
