import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_qaprocesses_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Quality Assurance' (QA)?", "options": ["Testing code only", "Systematic process of ensuring that a product meets required quality standards", "Designing the UI only", "None"], "correct": 1},
        {"id": 2, "question": "What is 'Quality Control' (QC)?", "options": ["A reactive process of finding defects in a finished product", "Preventative measures", "None of the above", "None"], "correct": 0},
        {"id": 3, "question": "What is 'SDLC'?", "options": ["Software Development Life Cycle", "System Design Life Cycle", "State Development Life Cycle", "None"], "correct": 0},
        {"id": 4, "question": "What is 'STLC'?", "options": ["Software Testing Life Cycle", "Standard Thinking Life Cycle", "None of the above", "None"], "correct": 0},
        {"id": 5, "question": "What is 'Waterfall Model'?", "options": ["A waterfall in nature", "A linear-sequential software development model", "A design tool", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Agile' in software testing?", "options": ["Fast moving software", "An iterative and incremental approach to software development and testing", "A type of chart", "None"], "correct": 1},
        {"id": 7, "question": "What is a 'Bug' (Defect)?", "options": ["An insect", "An error, flaw, or failure in a computer program that produces an incorrect result", "A feature that users like", "None"], "correct": 1},
        {"id": 8, "question": "What is a 'Test Case'?", "options": ["A document detailing a specific test scenario with steps and expected results", "A physical box for tests", "None of the above", "None"], "correct": 0},
        {"id": 9, "question": "What is a 'Test Suite'?", "options": ["A set of related test cases", "A high-end room for testing", "A technical specification", "None"], "correct": 0},
        {"id": 10, "question": "What is 'Unit Testing'?", "options": ["Testing individual pieces of code or functions", "Testing the entire system", "None of the above", "None"], "correct": 0},
        {"id": 11, "question": "What is 'Integration Testing'?", "options": ["Testing how different modules of an application work together", "Testing the internet connection", "A type of backup", "None"], "correct": 0},
        {"id": 12, "question": "What is 'System Testing'?", "options": ["Testing the operating system", "Validating the complete and integrated software as a whole", "A type of speed test", "None"], "correct": 1},
        {"id": 13, "question": "What is 'User Acceptance Testing' (UAT)?", "options": ["Final testing performed by end-users to ensure it meets their needs", "Testing the UI design only", "A type of audit", "None"], "correct": 0},
        {"id": 14, "question": "What is 'Regression Testing'?", "options": ["Testing only new features", "Retesting a software application after changes to ensure old features still work", "Deleting all tests", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Smoke Testing'?", "options": ["Testing fire alarms", "Basic tests carried out to check if the essential features are working", "None of the above", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Sanity Testing'?", "options": ["Checking the developer's mental health", "Testing to check if a specific bug fix or change works as expected", "None of the above", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Black Box Testing'?", "options": ["Testing only the code", "Testing based on functionalities without knowledge of internal code structure", "Both A and B", "Neither"], "correct": 1},
        {"id": 18, "question": "What is 'White Box Testing'?", "options": ["Testing only the labels", "Testing with full knowledge of the internal code and architecture", "None of the above", "None"], "correct": 1},
        {"id": 19, "question": "What is the result of 'Verification'?", "options": ["Are we building the product right?", "Are we building the right product?", "None of the above", "None"], "correct": 0},
        {"id": 20, "question": "What is the result of 'Validation'?", "options": ["Are we building the product right?", "Are we building the right product?", "Checking for syntax errors", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Defect Life Cycle' (Bug Life Cycle)?", "options": ["The life of an insect", "The sequence of states a bug goes through from discovery to fix/closure", "A type of table", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Test Plan'?", "options": ["Planning a party", "A master document detailing the strategy, scope, resources, and schedule for testing", "A tech spec", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Automation Testing'?", "options": ["Manual testing in a fast car", "Using specialized software to control test execution and compare results automatically", "Starting a database", "None"], "correct": 1},
        {"id": 24, "question": "What is the purpose of 'Traceability Matrix'?", "options": ["Mapping test cases to requirements specifically", "Tracing a user ID", "Sorting a list", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Static Testing'?", "options": ["Testing while stationary", "Evaluating code/documents without actually running them", "A type of chart", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Dynamic Testing'?", "options": ["Testing with energy", "Testing an application while it is running", "A search engine", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Performance Testing'?", "options": ["How fast a person works", "Determining the speed, responsiveness, and stability of a system under workload", "A technical specification", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Usability Testing'?", "options": ["Testing how easy it is for an end-user to use the software", "Measuring file size", "A type of error", "None"], "correct": 0},
        {"id": 29, "question": "Which of these represents a 'Critical' bug priority?", "options": ["Fix soon", "Fix immediately as it blocks the whole application", "None of the above", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Shift-left' testing?", "options": ["Testing on the left side of a building", "Incorporating testing early in the software development life cycle", "None of the above", "None"], "correct": 1},
        {"id": 31, "question": "What is 'Boundary Value Analysis'?", "options": ["Testing at the limits of input ranges specifically where errors often occur", "Testing in a big room", "Testing randomly", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Equivalence Partitioning'?", "options": ["Dividing test inputs into groups that are expected to behave the same way", "Dividing food", "A types of math", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Exploratory Testing'?", "options": ["Testing while traveling", "Informal testing where testers design and run tests on the fly as they explore", "A search for files", "None"], "correct": 1},
        {"id": 34, "question": "What is 'Ad-hoc Testing'?", "options": ["Formal testing with a plan", "Informal testing without a specific test plan or documentation", "Testing a car", "None"], "correct": 1},
        {"id": 35, "question": "What is 'Beta Testing'?", "options": ["Testing a product by real users in a real-world environment before release", "Testing with bugs", "A Greek test", "None"], "correct": 0},
        {"id": 36, "question": "What is 'Alpha Testing'?", "options": ["Testing done in-house by the QA team before release to beta users", "Testing the very first line", "A types of alphabet", "None"], "correct": 0},
        {"id": 37, "question": "What is 'V-Model' specifically in testing?", "options": ["Extension of waterfall model that couples each development phase with a test phase", "A car shape", "A design for a valley", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Gray Box Testing'?", "options": ["Testing only the color gray", "A combination of black box and white box testing techniques", "A types of cloud", "None"], "correct": 1},
        {"id": 39, "question": "What is 'Load Testing'?", "options": ["Testing if a truck is heavy", "Testing how a system performs under an expected volume of traffic", "A types of math", "None"], "correct": 1},
        {"id": 40, "question": "What is 'Stress Testing'?", "options": ["Pushing a system beyond its normal operational limits to find breaking points", "Giving a test during an exam", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Scalability Testing'?", "options": ["Testing if the system can grow to handle more users/data efficiently", "Measuring an area", "A types of climbing", "None"], "correct": 0},
        {"id": 42, "question": "What is 'Spike Testing'?", "options": ["A sharp increase in load to test how the system handles sudden traffic bursts", "Testing with sharp tools", "A types of sport", "None"], "correct": 0},
        {"id": 43, "question": "What is 'Reliability Testing'?", "options": ["How long a system can run without failing", "Testing if a person is honest", "A types of story", "None"], "correct": 0},
        {"id": 44, "question": "What is 'Security Testing' specifically?", "options": ["Identifying vulnerabilities specifically to protect data and resources", "Locking doors in office", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's the meaning of 'End-to-End' (E2E) testing?", "options": ["Testing the system from start to finish as per the user journey", "Testing only the beginning", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What is 'Test Environment'?", "options": ["A types of nature", "The physical or virtual setup where tests are executed (Stage, Dev)", "A types of school", "None"], "correct": 1},
        {"id": 47, "question": "What is 'Test Data'?", "options": ["Data used for input during test execution", "Information about a person", "A list of strings", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Test Lead' role?", "options": ["Managing the testing team, strategy and test reporting", "Leading a race", "A types of chemical name", "None"], "correct": 0},
        {"id": 49, "question": "What is 'Product Owner' in Agile?", "options": ["Responsible for representing the business and defining requirements", "The owner of a company", "A types of database", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Scrum Master'?", "options": ["A facilitator specifically who helps the team follow Agile/Scrum practices", "A master of drums", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "What is 'Sprint' in Agile context?", "options": ["A short, fixed-duration period (usually 2-4 weeks) for finishing work", "Running very fast", "A types of season", "None"], "correct": 0},
        {"id": 52, "question": "What is 'User Story'?", "options": ["An informal description of a software feature from an end-user perspective", "A bedtime story", "A types of book", "None"], "correct": 0},
        {"id": 53, "question": "What is 'Backlog' in Agile?", "options": ["A prioritized list of work for the development team", "A log of trees", "A types of error", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Defect Density'?", "options": ["The number of defects per project size (e.g. per 1000 lines of code)", "A heavy bug", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Test Execution' phase?", "options": ["Killing a test", "The actual phase of running test cases and recording results", "A types of law", "None"], "correct": 1},
        {"id": 56, "question": "What is 'Exit Criteria' for testing?", "options": ["The conditions that must be met to stop testing", "A types of door", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Entry Criteria'?", "options": ["The conditions that must be met to start testing", "A types of hall", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Monkey Testing'?", "options": ["Testing with bananas", "Randomly testing the application with varied inputs to find crashes", "A types of animal study", "None"], "correct": 1},
        {"id": 59, "question": "What's 'Mutation Testing'?", "options": ["Changing the code slightly to test if your tests actually catch bugs", "A biological change", "A types of film", "None"], "correct": 0},
        {"id": 60, "question": "What is 'Error Guessing'?", "options": ["A technique where testers guess where bugs might be based on experience", "Randomly choosing answers", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Test Maturity Model' (TMM)?", "options": ["Framework for improving the testing process in maturity levels", "A types of model", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What's the meaning of 'Severity' of a bug?", "options": ["The impact of the defect on the system functionality", "The importance of fixing it quickly", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's the meaning of 'Priority' of a bug?", "options": ["The order in which a defect should be fixed relative to others", "The impact on the system", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What represents top-level QA document?", "options": ["Test Strategy", "Test Case", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Fuzz Testing'?", "options": ["A types of soft toy", "Providing random/invalid/unexpected data as inputs to find crashes", "A security feature", "Neither", "Both"], "correct": 1},
        {"id": 66, "question": "What's the meaning of 'Negative Testing'?", "options": ["Testing with incorrect or invalid inputs to see if errors are handled", "Testing in a bad mood", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What's the meaning of 'Positive Testing'?", "options": ["Testing specifically with valid inputs to ensure expected outputs appear", "Being optimistic", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Cyclomatic Complexity'?", "options": ["A measure of the number of independent paths through a program", "A types of math", "A circular path", "None"], "correct": 0},
        {"id": 69, "question": "What is 'Heuristic Evaluation' specifically for UI?", "options": ["Reviewing an interface based on recognized usability principles", "A types of medicine", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's the benefit of 'Independent Testing'?", "options": ["Testers are not influenced by the developers, leading to unbiased results", "Testing alone in a room", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Crowd Testing'?", "options": ["Testing specifically by a large group of diverse real-world users", "Testing in a busy mall", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'A/B Testing'?", "options": ["Comparing two versions specifically of a webpage/feature with users", "Testing letters", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's the meaning of 'Accessibility Testing'?", "options": ["Ensuring software can be used by people specifically with disabilities", "Testing if doors are open", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Localization Testing'?", "options": ["Ensuring software specifically works correctly in a specific location/language", "Finding a place", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's 'Internationalization Testing' (i18n)?", "options": ["Ensuring a product's code can easily support multiple locales", "Testing abroad", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "How many states in standard defect lifecycle?", "options": ["Multiple (New, Open, Fixed, Closed, etc.)", "Only two", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Maintenance Testing'?", "options": ["Testing an existing system after it is in production and updated", "Cleaning a database", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What represents the 'Cost of Quality'?", "options": ["Expenses incurred in preventing, finding and repairing defects", "The price of code", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Bug Triage'?", "options": ["A meeting where bugs are prioritized for fixing by several stakeholders", "Writing about bugs", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is QA essential for every project?", "options": ["Ensuring customer satisfaction and high-quality software with fewer issues", "Having more social media likes", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Quality Assurance' vs 'Quality Control'?", "options": ["QA focuses on preventing defects; QC focuses on process consistency", "They are the same", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Test Case'?", "options": ["Set of conditions and steps to verify functionality", "A test box", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Test Plan'?", "options": ["Document outlining scope, approach, resources, and schedule", "A plan for testing", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Test Matrix'?", "options": ["Table showing test coverage across different scenarios", "A test matrix", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Traceability'?", "options": ["Ability to track requirements and changes through development lifecycle", "Following changes", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Peer Review'?", "options": ["Process where team members review each other's work", "Team review", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Inspection'?", "options": ["Formal examination of work products or processes", "Checking quality", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Audit'?", "options": ["Systematic examination of processes and compliance", "Financial review", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Risk Assessment'?", "options": ["Identifying and evaluating potential risks", "Finding dangers", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Compliance Testing'?", "options": ["Verifying adherence to standards and regulations", "Following rules", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Usability Testing'?", "options": ["Testing how easily users can accomplish tasks", "Testing ease of use", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Accessibility Testing'?", "options": ["Testing for users with disabilities", "Testing access", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Performance Testing'?", "options": ["Measuring system speed and resource usage", "Testing speed", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Security Testing'?", "options": ["Finding vulnerabilities and security flaws", "Testing security", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Regression Testing'?", "options": ["Re-testing after changes to ensure no new bugs", "Testing again", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Integration Testing'?", "options": ["Testing how components work together", "Testing parts", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'End-to-End Testing'?", "options": ["Testing complete user workflows", "Testing everything", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Continuous Testing'?", "options": ["Automated testing throughout development lifecycle", "Testing continuously", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Chaos Testing'?", "options": ["Testing system resilience under random failure conditions", "Testing chaos", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Exploratory Testing'?", "options": ["Investigative testing to discover unknown issues", "Finding problems", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
