from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_reasoning_api(request):
    questions_pool = [
        {"id": 1, "question": "Look at this series: 2, 1, (1/2), (1/4), ... What number should come next?", "options": ["(1/3)", "(1/8)", "(2/8)", "(1/16)"], "correct": 1},
        {"id": 2, "question": "Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?", "options": ["7", "10", "12", "13"], "correct": 1},
        {"id": 3, "question": "Look at this series: 36, 34, 30, 28, 24, ... What number should come next?", "options": ["20", "22", "23", "26"], "correct": 1},
        {"id": 4, "question": "Look at this series: 22, 21, 23, 22, 24, 23, ... What number should come next?", "options": ["22", "24", "25", "26"], "correct": 2},
        {"id": 5, "question": "Look at this series: 53, 53, 40, 40, 27, 27, ... What number should come next?", "options": ["12", "14", "27", "53"], "correct": 1},
        {"id": 6, "question": "SCD, TEF, UGH, ____, WKL", "options": ["CMN", "UJI", "VIJ", "IJT"], "correct": 2},
        {"id": 7, "question": "B2CD, ____, BCD4, B5CD, BC6D", "options": ["B2C2D", "BC3D", "B3CD", "BC3D2"], "correct": 1},
        {"id": 8, "question": "FAG, GAF, HAI, IAH, ____", "options": ["JAK", "HAL", "HAK", "JAI"], "correct": 0},
        {"id": 9, "question": "ELFA, GLHA, ILJA, ____, MLNA", "options": ["OLPA", "KLMA", "LLMA", "KLLA"], "correct": 3},
        {"id": 10, "question": "CMM, EOO, GQQ, ____, KUU", "options": ["GRR", "GSS", "ISS", "ITT"], "correct": 2},
        {"id": 11, "question": "Cup is to Coffee as Bowl is to:", "options": ["Dish", "Soup", "Spoon", "Food"], "correct": 1},
        {"id": 12, "question": "Act is to Stage as Play is to:", "options": ["Theatre", "Actor", "Drama", "Audience"], "correct": 0},
        {"id": 13, "question": "Pedestrian is to Road as Hangar is to:", "options": ["Aeroplane", "Water", "Air", "Train"], "correct": 0},
        {"id": 14, "question": "Conductor is to Orchestra as Captain is to:", "options": ["Team", "Ship", "Soldier", "Flight"], "correct": 0},
        {"id": 15, "question": "Odometer is to mileage as compass is to:", "options": ["speed", "hiking", "needle", "direction"], "correct": 3},
        {"id": 16, "question": "Marathon is to race as hibernation is to:", "options": ["winter", "bear", "dream", "sleep"], "correct": 3},
        {"id": 17, "question": "Window is to pane as book is to:", "options": ["novel", "glass", "cover", "page"], "correct": 3},
        {"id": 18, "question": "Yard is to inch as quart is to:", "options": ["gallon", "ounce", "milk", "liquid"], "correct": 1},
        {"id": 19, "question": "Optimist is to cheerful as pessimist is to:", "options": ["gloomy", "mean", "petty", "helpful"], "correct": 0},
        {"id": 20, "question": "Pen is to poet as needle is to:", "options": ["thread", "button", "tailor", "sewing"], "correct": 2},
        {"id": 21, "question": "Choose the word that does not belong with the others:", "options": ["parsley", "basil", "dill", "mayonnaise"], "correct": 3},
        {"id": 22, "question": "Choose the word that does not belong with the others:", "options": ["tulip", "rose", "bud", "daisy"], "correct": 2},
        {"id": 23, "question": "Choose the word that does not belong with the others:", "options": ["guitar", "violin", "flute", "cello"], "correct": 2},
        {"id": 24, "question": "Choose the word that does not belong with the others:", "options": ["dodge", "flee", "duck", "avoid"], "correct": 1},
        {"id": 25, "question": "Choose the word that does not belong with the others:", "options": ["branch", "dirt", "leaf", "root"], "correct": 1},
        {"id": 26, "question": "If in a certain language, MADRAS is coded as NBESBT, how is BOMBAY coded in that code?", "options": ["CPNCBX", "CPNCBZ", "CPOCBZ", "CQOCBZ"], "correct": 1},
        {"id": 27, "question": "If TRUTH is coded as SUQTVSUGDFGI, then what is the code for FALSE?", "options": ["EGZKMTRTDF", "EGZKMTRTDFDF", "EGZKMTRTDFGI", "None of these"], "correct": 0},
        {"id": 28, "question": "Pointing to a photograph, a man said, 'I have no brother or sister but that man's father is my father's son.' Whose photograph was it?", "options": ["His own", "His son's", "His father's", "His nephew's"], "correct": 1},
        {"id": 29, "question": "A is B's sister. C is B's mother. D is C's father. E is D's mother. Then, how is A related to D?", "options": ["Grandmother", "Grandfather", "Daughter", "Granddaughter"], "correct": 3},
        {"id": 30, "question": "Introducing a boy, a girl said, 'He is the son of the daughter of the father of my uncle.' How is the boy related to the girl?", "options": ["Brother", "Nephew", "Uncle", "Son-in-law"], "correct": 0},
        {"id": 31, "question": "A man walks 5 km toward south and then turns to the right. After walking 3 km he turns to the left and walks 5 km. Now in which direction is he from the starting place?", "options": ["West", "South", "North-East", "South-West"], "correct": 3},
        {"id": 32, "question": "Rahul put his timepiece on the table in such a way that at 6 P.M. hour hand points to North. In which direction the minute hand will point at 9.15 P.M.?", "options": ["East", "West", "North", "South"], "correct": 1},
        {"id": 33, "question": "A is B's brother. C is A's mother. D is C's father. F is A's son. How is B related to F's son?", "options": ["Uncle", "Grandfather", "Great Grandfather", "Grandmother"], "correct": 1},
        {"id": 34, "question": "Statements: All bags are pockets. All pockets are pouches. Conclusions: I. All bags are pouches. II. Some pouches are bags.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 35, "question": "Statements: Some keys are locks. Some locks are numbers. Conclusions: I. Some keys are numbers. II. All numbers are locks.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 3},
        {"id": 36, "question": "Six books are kept one on top of the other. History is just above Civics. Geography is between Maths and English. Science is at the bottom. English is below Civics. Which book is at the top?", "options": ["Maths", "History", "Civics", "English"], "correct": 0},
        {"id": 37, "question": "In a row of trees, one tree is fifth from either end of the row. How many trees are there in the row?", "options": ["8", "9", "10", "11"], "correct": 1},
        {"id": 38, "question": "If '+' means '*', '-' means '/', '*' means '-' and '/' means '+', then 16 + 8 - 4 * 2 / 4 = ?", "options": ["34", "36", "38", "40"], "correct": 0},
        {"id": 39, "question": "Which of the following is a leap year?", "options": ["1900", "1994", "2000", "2010"], "correct": 2},
        {"id": 40, "question": "On 8th Dec, 2007 Saturday falls. What day of the week was it on 8th Dec, 2006?", "options": ["Sunday", "Thursday", "Friday", "Tuesday"], "correct": 2},
        {"id": 41, "question": "If Friday is the first day of a non-leap year, what day is the last day of the year?", "options": ["Friday", "Saturday", "Sunday", "Thursday"], "correct": 0},
        {"id": 42, "question": "At what angle the hands of a clock are inclined at 15 minutes past 5?", "options": ["58.5 degrees", "64 degrees", "67.5 degrees", "72.5 degrees"], "correct": 2},
        {"id": 43, "question": "How many times are the hands of a clock at right angle in a day?", "options": ["22", "24", "44", "48"], "correct": 2},
        {"id": 44, "question": "Look at this series: F2, __, D8, C16, B32. What should fill the blank?", "options": ["E4", "E3", "F4", "G4"], "correct": 0},
        {"id": 45, "question": "Look at this series: V, VIII, XI, XIV, __, XX. What should fill the blank?", "options": ["XV", "XVI", "XVII", "XVIII"], "correct": 2},
        {"id": 46, "question": "Look at this series: VI, 10, V, 11, IV, 12, ... What number should come next?", "options": ["III", "13", "IV", "14"], "correct": 0},
        {"id": 47, "question": "Statements: All flowers are trees. No tree is a house. Conclusions: I. No flower is a house. II. Some trees are flowers.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 48, "question": "Statements: All pens are roads. All roads are houses. Conclusions: I. All pens are houses. II. Some houses are pens.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 49, "question": "If 'light' is called 'morning', 'morning' is called 'dark', 'dark' is called 'night', 'night' is called 'sunshine', where do we sleep?", "options": ["morning", "night", "dark", "sunshine"], "correct": 3},
        {"id": 50, "question": "If A is to the South of B and C is to the East of B, in what direction is A with respect to C?", "options": ["North-East", "North-West", "South-East", "South-West"], "correct": 3},
        {"id": 51, "question": "Choose the word that does not belong with the others:", "options": ["CorelDraw", "Photoshop", "Linux", "Illustrator"], "correct": 2},
        {"id": 52, "question": "Choose the word that does not belong with the others:", "options": ["Kilometer", "Meter", "Yard", "Acre"], "correct": 3},
        {"id": 53, "question": "If in a code language, PAINT is written as 74128 and EXCEL is written as 93596, then how will ACCEPT be written?", "options": ["455978", "459785", "455987", "455975"], "correct": 0},
        {"id": 54, "question": "Pointing to a lady, a man said, 'The son of her only brother is the brother of my wife.' How is the lady related to the man?", "options": ["Mother's sister", "Grandmother", "Sister of father-in-law", "Maternal Aunt"], "correct": 2},
        {"id": 55, "question": "If South-East becomes North, North-East becomes West and so on. What will West become?", "options": ["North-East", "North-West", "South-East", "South-West"], "correct": 2},
        {"id": 56, "question": "Statements: Some bags are hot. All hot things are cakes. Conclusions: I. All cakes are hot. II. Some bags are cakes.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 1},
        {"id": 57, "question": "A, B, C, D and E are sitting on a bench. A is sitting next to B, C is sitting next to D, D is not sitting with E who is on the left end of the bench. C is on the second position from the right. A is to the right of B and E. A and C are sitting together. In which position is A sitting?", "options": ["Between B and D", "Between B and C", "Between E and D", "Between C and E"], "correct": 1},
        {"id": 58, "question": "What is the next number in the sequence: 4, 9, 19, 39, ...?", "options": ["59", "69", "79", "89"], "correct": 2},
        {"id": 59, "question": "If 'red' means 'green', 'green' means 'yellow', 'yellow' means 'blue', 'blue' means 'black', what is the color of clear sky?", "options": ["green", "blue", "black", "yellow"], "correct": 2},
        {"id": 60, "question": "Pointing to a man, a woman says, 'His mother is the only daughter of my mother.' How is the woman related to the man?", "options": ["Mother", "Sister", "Daughter", "Grandmother"], "correct": 0},
        {"id": 61, "question": "Statements: All ants are insects. All insects are bugs. Conclusions: I. All ants are bugs. II. Some bugs are ants.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 62, "question": "Look at this series: 8, 4, 12, 6, 18, ... What number should come next?", "options": ["9", "12", "15", "24"], "correct": 0},
        {"id": 63, "question": "Look at this series: 2, 4, 8, 16, 32, ... What number should come next?", "options": ["48", "64", "72", "96"], "correct": 1},
        {"id": 64, "question": "Choose the word that does not belong with the others:", "options": ["Jupiter", "Mars", "Neptune", "Moon"], "correct": 3},
        {"id": 65, "question": "Choose the word that does not belong with the others:", "options": ["Book", "Paper", "Pencil", "Library"], "correct": 3},
        {"id": 66, "question": "If GALAXY is coded as LFPFDC, how is ORBIT coded?", "options": ["TWGNY", "TWHNY", "TXGNY", "TWGNZ"], "correct": 0},
        {"id": 67, "question": "Introducing a man, a woman said, 'He is the only son of my mother's mother.' How is the woman related to the man?", "options": ["Sister", "Mother", "Niece", "Aunt"], "correct": 2},
        {"id": 68, "question": "A person walks 10 km north, then turns east and walks 5 km, then turns south and walks 10 km. How far is he from the starting point?", "options": ["5 km", "10 km", "15 km", "20 km"], "correct": 0},
        {"id": 69, "question": "If 1st January of a certain non-leap year is a Monday, what day is 31st December of the same year?", "options": ["Monday", "Tuesday", "Sunday", "Saturday"], "correct": 0},
        {"id": 70, "question": "At what time between 3 and 4 o'clock will the hands of a clock be opposite to each other?", "options": ["45 min past 3", "49 1/11 min past 3", "50 min past 3", "54 6/11 min past 3"], "correct": 1},
        {"id": 71, "question": "If '+' means '-', '-' means '*', '*' means '/' and '/' means '+', then 20 * 4 - 3 + 2 / 5 = ?", "options": ["16", "18", "20", "22"], "correct": 1},
        {"id": 72, "question": "Statements: All windows are doors. All doors are walls. Conclusions: I. All windows are walls. II. Some walls are windows.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 73, "question": "Choose the word that does not belong with the others:", "options": ["Caterpillar", "Butterfly", "Lizard", "Cocoon"], "correct": 2},
        {"id": 74, "question": "If in a certain code language, COMPUTER is written as OCPMTURE, how will SOFTWARE be written?", "options": ["OSFTAWER", "OSTFWAER", "OSTFAWER", "OSTFWARE"], "correct": 1},
        {"id": 75, "question": "Pointing to a girl in the photograph, Amar said, 'Her mother's brother is the only son of my mother's father.' How is the girl's mother related to Amar?", "options": ["Mother", "Sister", "Aunt", "Grandmother"], "correct": 0},
        {"id": 76, "question": "A man walks 6 km north, then turns left and walks 4 km, then turns left and walks 6 km. In which direction is he now from his starting point?", "options": ["East", "West", "North", "South"], "correct": 1},
        {"id": 77, "question": "What is the angle between the hands of a clock at 4 o'clock?", "options": ["90 degrees", "100 degrees", "120 degrees", "150 degrees"], "correct": 2},
        {"id": 78, "question": "How many leap years are there in a century?", "options": ["24", "25", "26", "28"], "correct": 0},
        {"id": 79, "question": "Look at this series: 1.5, 2.3, 3.1, 3.9, ... What number should come next?", "options": ["4.2", "4.4", "4.7", "5.1"], "correct": 2},
        {"id": 80, "question": "Statements: Some papers are pens. All pens are pencils. Conclusions: I. Some papers are pencils. II. Some pencils are papers.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 81, "question": "Choose the word that does not belong with the others:", "options": ["Diamond", "Ruby", "Emerald", "Coal"], "correct": 3},
        {"id": 82, "question": "If in a code, HEAD is written as 37 and TAIL is written as 42, how will BODY be written?", "options": ["40", "42", "44", "46"], "correct": 3},
        {"id": 83, "question": "Pointing to a man, a woman says, 'He is the son of the husband of my mother.' How is the man related to the woman?", "options": ["Brother", "Son", "Husband", "Nephew"], "correct": 0},
        {"id": 84, "question": "A person walks 5 km south, then turns left and walks 5 km, then turns left and walks 5 km. In which direction is he now from the starting point?", "options": ["East", "West", "North", "South"], "correct": 0},
        {"id": 85, "question": "At what time between 1 and 2 o'clock will the hands of a clock be together?", "options": ["5 min past 1", "5 5/11 min past 1", "6 min past 1", "6 2/11 min past 1"], "correct": 1},
        {"id": 86, "question": "Statements: All roads are streets. No street is a highway. Conclusions: I. No road is a highway. II. Some streets are roads.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 87, "question": "Look at this series: 1, 3, 9, 27, ... What number should come next?", "options": ["36", "45", "81", "90"], "correct": 2},
        {"id": 88, "question": "Choose the word that does not belong with the others:", "options": ["Iron", "Copper", "Gold", "Wood"], "correct": 3},
        {"id": 89, "question": "If COLD is coded as DPME, how is HOT coded?", "options": ["IPU", "IQU", "IPV", "IQV"], "correct": 0},
        {"id": 90, "question": "Pointing to a lady, Vivek said, 'She is the sister of my father's wife.' How is the lady related to Vivek?", "options": ["Mother", "Aunt", "Sister", "Grandmother"], "correct": 1},
        {"id": 91, "question": "A man walks 4 km east, then turns right and walks 3 km. How far is he from the starting point?", "options": ["5 km", "6 km", "7 km", "8 km"], "correct": 0},
        {"id": 92, "question": "At what angle are the hands of a clock inclined at 3 o'clock?", "options": ["45 degrees", "90 degrees", "180 degrees", "270 degrees"], "correct": 1},
        {"id": 93, "question": "Statements: All houses are buildings. No building is a tent. Conclusions: I. No house is a tent. II. Some buildings are houses.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2},
        {"id": 94, "question": "Look at this series: 100, 95, 85, 70, ... What number should come next?", "options": ["50", "55", "60", "65"], "correct": 0},
        {"id": 95, "question": "Choose the word that does not belong with the others:", "options": ["Apple", "Orange", "Banana", "Potato"], "correct": 3},
        {"id": 96, "question": "If FAST is coded as GBTU, how is SLOW coded?", "options": ["TMPX", "TNPX", "TNPW", "TMOW"], "correct": 0},
        {"id": 97, "question": "Pointing to a boy, Ramesh says, 'He is the son of the brother of my father.' How is the boy related to Ramesh?", "options": ["Brother", "Cousin", "Uncle", "Nephew"], "correct": 1},
        {"id": 98, "question": "A person walks 8 km west, then turns left and walks 6 km. How far is he from the starting point?", "options": ["10 km", "12 km", "14 km", "16 km"], "correct": 0},
        {"id": 99, "question": "What is the angle between the hands of a clock at 6 o'clock?", "options": ["90 degrees", "120 degrees", "180 degrees", "360 degrees"], "correct": 2},
        {"id": 100, "question": "Statements: All animals are pets. All pets are domestic. Conclusions: I. All animals are domestic. II. Some domestic are animals.", "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], "correct": 2}
    ]
    return Response({"success": True, "data": questions_pool})
