import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_reports_api(request):
    questions_pool = [
        {"id": 1, "question": "What is a Power BI Report?", "options": ["A types of book", "A multi-page collection of interactive visualizations and data analyses", "A list of notes", "None"], "correct": 1},
        {"id": 2, "question": "What's the difference between a Report and a Dashboard?", "options": ["Reports have multiple pages; Dashboards are single-page summaries", "Reports are interactive; Dashboards usually just show summaries", "Both A and B", "Neither"], "correct": 2},
        {"id": 3, "question": "What is 'Canvas' in report design?", "options": ["The physical workspace where you add and arrange visuals", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 4, "question": "What is 'Visual' in a Power BI report?", "options": ["Individual chart or element representing data (e.g. Bar, Line, Table)", "A spectacles brand", "Neither", "Both"], "correct": 0},
        {"id": 5, "question": "Which view in Power BI Desktop is used to create actual report pages?", "options": ["Report View", "Data View", "Model View", "Neither"], "correct": 0},
        {"id": 6, "question": "What is 'Slicer' used for in a report?", "options": ["Cutting images into smaller bits", "Providing interactive on-page filtering for users to explore data", "Both", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Filter' (Report, Page, Visual level)?", "options": ["Mechanisms to restrict or narrow down the data shown in part or all of a report", "Cleaning physical filters", "Neither", "Both"], "correct": 0},
        {"id": 8, "question": "What's 'Cross-Filtering' in a report?", "options": ["When selecting data in one visual automatically filters related data in others", "A physical road crossing", "Neither", "Both"], "correct": 0},
        {"id": 9, "question": "What is 'Cross-Highlighting'?", "options": ["Selecting a piece of a visual that highlights related categories in others on same page", "Highlighting a physical page", "Neither", "Both"], "correct": 0},
        {"id": 10, "question": "What is 'Drill Mode' (Drill down/up)?", "options": ["Entering a physical hole in ground", "Navigating hierarchical levels of data like Year -> Month -> Day in a visual", "Neither", "Both"], "correct": 1},
        {"id": 11, "question": "What is 'Drill Through' in a report?", "options": ["Going between different pages of a report to see details of a specific item", "Drilling a wall", "Neither", "Both"], "correct": 0},
        {"id": 12, "question": "What's 'ToolTip' in a Power BI report?", "options": ["Small pop-up showing more data when you hover over a data point in a visual", "A tip for a tool", "Neither", "Both"], "correct": 0},
        {"id": 13, "question": "What is 'Custom Tooltip Page'?", "options": ["A report page designed specifically to appear as a tooltip for another visual", "A help guide", "Neither", "Both"], "correct": 0},
        {"id": 14, "question": "What is 'Report Page'?", "options": ["A single tab within a Power BI report file", "A book page", "Neither", "Both"], "correct": 0},
        {"id": 15, "question": "What's the role of 'Themes' in report design?", "options": ["Defining colors/fonts for consistency and brand alignment across the report", "Musical background", "Neither", "Both"], "correct": 0},
        {"id": 16, "question": "Which visual is best for comparing discrete category metrics?", "options": ["Bar Chart", "Line Chart", "Area Chart", "None"], "correct": 0},
        {"id": 17, "question": "Which visual is best for identifying trends over time?", "options": ["Line Chart", "Pie Chart", "Histogram", "None"], "correct": 0},
        {"id": 18, "question": "What is a 'Matrix' visual different from a Table?", "options": ["Allows grouping by both rows and columns like a pivot table", "Table is bigger", "Neither", "Both"], "correct": 0},
        {"id": 19, "question": "What is 'Conditional Formatting'?", "options": ["Changing visual appearance (like background color) based on data values", "A tech spec", "Neither", "Both"], "correct": 0},
        {"id": 20, "question": "What's 'Data Label' for a visual?", "options": ["Displaying exact numerical values directly on data points in a chart", "A list of notes", "Neither", "Both"], "correct": 0},
        {"id": 21, "question": "What's 'Axis' on a chart (X and Y)?", "options": ["Reference lines for horizontal (usually categories/time) and vertical (metrics)", "An error", "Neither", "Both"], "correct": 0},
        {"id": 22, "question": "What is 'Legend' on a chart?", "options": ["A key explaining what colors or shapes represent in the visual", "A story about charts", "Neither", "Both"], "correct": 0},
        {"id": 23, "question": "Which of these is a popular data visualization company?", "options": ["Microsoft (Power BI)", "Tableau", "Qlik", "All of the above"], "correct": 3},
        {"id": 24, "question": "What is 'Data Storytelling'?", "options": ["Arranging visuals and narrative to communicate insights to an audience effectively", "Writing fiction", "Neither", "Both"], "correct": 0},
        {"id": 25, "question": "How can you hide a report page from being seen by end users in the Service?", "options": ["Right-click page tab -> Hide", "Deleting the page", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Pin to Dashboard'?", "options": ["Adding a report visual to the high-level summary single-page dashboard", "A physical pin", "Neither", "Both"], "correct": 0},
        {"id": 27, "question": "What is 'Power BI Desktop' used for?", "options": ["Designing the actual reports and data models locally on a PC", "Running servers", "Neither", "Both"], "correct": 0},
        {"id": 28, "question": "What is 'Power BI Service' (the web portal)?", "options": ["Sharing, viewing, and collaborating on reports online with others", "A search for BI", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'RLS' (Row-Level Security) in reports?", "options": ["Restricting which rows of data a user can see based on their identity", "Safeguarding physical files", "Neither", "Both"], "correct": 0},
        {"id": 30, "question": "Which visual represents parts of a whole well?", "options": ["Pie Chart", "Treemap", "Donut Chart", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Report Tooltip'?", "options": ["A small info pop-up that appears when hovering over a visual component", "An error message", "Neither", "Both"], "correct": 0},
        {"id": 32, "question": "What's 'Drill-through' filter?", "options": ["When a user drills from a visual to a destination page specifically for more detail", "A physical drill", "Neither", "Both"], "correct": 0},
        {"id": 33, "question": "What is 'AI Visual' in Power BI (e.g. Decomposition Tree)?", "options": ["Visual that uses built-in AI models to analyze data root causes/patterns", "A visual generated by OpenAI", "None", "None"], "correct": 0},
        {"id": 34, "question": "What is 'Key Influencers' visual for in Power BI?", "options": ["To identify what factors are most likely to drive a certain metric/outcome", "Finding social media stars", "None", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Smart Narrative' visual?", "options": ["Automatic text summary of the key findings in a report based on the data", "Reading stories", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'Decomposition Tree'?", "options": ["A visual used for ad-hoc exploration of several dimensions leading to a total", "A physical tree", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "Which button allows you to download a report from Service to Desktop?", "options": ["Download .pbix", "Save draft", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Power BI Mobile App'?", "options": ["Mobile application for viewing interactive reports and dashboards on the go", "A phone brand", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Bookmark' in a report?", "options": ["Saving the current state of a report page (filters, visibility, etc.) for quick access", "A book accessory", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'Selection Pane'?", "options": ["Managing visibility and layering order of various visuals on one report page", "Selecting people", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "What is 'Page Background' vs 'Wallpaper'?", "options": ["Background is for the canvas; Wallpaper is the area outside the canvas", "They are identical", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "How do you align multiple visuals perfectly in Desktop?", "options": ["Using the Align and Distribute functions in Format tab", "By eye", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "What is 'Z-order' of visuals?", "options": ["The order in which visuals are layered on top of each other", "A types of order", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "What is 'Focus Mode' (Expand) for a visual?", "options": ["Expanding a single chart to the full report size for detailed view", "Focusing a camera", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What's 'Export to PDF' used for?", "options": ["Generating a static copy of the report for sharing offline", "Making it faster", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "What's 'Export to PowerPoint' useful for?", "options": ["Quickly converting report pages into presentation slides with snapshots", "Buying furniture", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "What is 'Analyze in Excel' for?", "options": ["Pivoting report data using familiar Excel pivot tables securely in cloud", "Moving to a new file", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "What is 'Usage Metrics' report?", "options": ["Built-in report showing views, viewers, and adoption of another report in workspace", "A metrics for cars", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "What is 'Paginated Report' (RDL)?", "options": ["High-pixel-perfect, printable multi-page reports (often for invoices/bills)", "Reports for pages", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What does 'Screentip' represent in web reports?", "options": ["Extra help text when a cursor hovers over a button or control", "A tip on screen", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "Which visual is best for comparing targets to actuals (e.g. Sales vs Goal)?", "options": ["Gauge Chart", "KPI Card", "Thermometer", "All of the above"], "correct": 3},
        {"id": 52, "question": "What is 'Interactive Header' in Power BI Service?", "options": ["The bar at the top of a visual allowing filtering and drilling", "A website header", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What's 'Full Screen Mode'?", "options": ["Hiding all browser UI to show only the report content to the audience", "Starting a program", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "How do you share a specific report page with a colleague?", "options": ["By generating a link with the 'Current Page' option", "Downloading the file", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Comment' feature in reports for?", "options": ["Starting a chat discussion directly on the report regarding specific data", "A note for code", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What's 'Data Refresh' in a report context?", "options": ["Updating the charts with the latest data from the backend model", "Starting a movie over", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Scheduled Refresh' for reports?", "options": ["Setting the online service to update report data automatically at set intervals", "Cleaning the house", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "Which visual allows showing data across multiple geographic regions?", "options": ["Map", "Filled Map", "Shape Map", "All of the above"], "correct": 3},
        {"id": 59, "question": "What's the meaning of 'Scatter Chart' convergence?", "options": ["Showing if there's a relationship between two metrics (e.g. Price vs Demand)", "Two roads meeting", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Bubble Chart' specifically?", "options": ["Visualizing bubbles", "A scatter chart where a third metric is shown via bubble size", "Neither", "Both"], "correct": 1},
        {"id": 61, "question": "What is 'Slicer Header' used for?", "options": ["Adding a title/instruction to a slicer (e.g. 'Select Year')", "A header for a file", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "How do you enable multi-select on a Slicer?", "options": ["Usually Ctrl + Click or via the Slicer Settings format pane", "You cannot", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Search' box on a Slicer useful for?", "options": ["Handling very long lists of items by letting users type to find an entry", "Searching on google", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Visual interactions' setting?", "options": ["Manually defining if one visual should filter, highlight or do nothing to another", "Starting a game", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Report View' compared to 'Edit Mode'?", "options": ["Report view is for users to consume; Edit mode is for tweaking visuals", "Same", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What's the meaning of 'Publishing to Web' (Public)?", "options": ["Generating a public link that anyone can see without logging in (Caution!)", "A social media post", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is 'Power BI Apps'?", "options": ["Bundling related reports into one easy-to-install package for an organization", "Phone apps", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is a 'Workspace' in the service?", "options": ["Shared playground for team collaboration on reports and datasets", "A room for people", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What's the benefit of 'Themes Galery'?", "options": ["Downloading professional-looking report styles created by community", "Watching movies", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's 'Accessibility' in report design?", "options": ["Making charts readable for all, including those with visual impairments (colors, alt-text)", "Opening a door", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Alt Text' for visuals?", "options": ["Description of a chart read by screen readers for accessibility", "Alternate text design", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "Which of these is a popular color-blind friendly theme?", "options": ["High Contrast", "Color Blind Safe themes in gallery", "Both", "None"], "correct": 2},
        {"id": 74, "question": "What is 'Q&A' visual used for in a report?", "options": ["Providing users a way to double-check data by typing questions in natural language", "Sending emails", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What's 'Power BI Desktop for RS'?", "options": ["Special version for use with Power BI Report Server (on-premises)", "A faster desktop", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "Can you use R or Python for custom visualizations in reports?", "options": ["Yes, through specific R and Python visual components", "No", "Only through special extensions", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Dribble through' versus 'Drill through'?", "options": ["Dribble is not a term; Drill through is for page navigation based on data", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What's 'Waterfall Chart' best for?", "options": ["Visualizing categorical changes summing to a total (e.g. monthly profit changes)", "A waterfall", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "Which visual is best for showing process stages and conversion rates?", "options": ["Funnel Chart", "Line Chart", "Both", "None"], "correct": 0},
        {"id": 80, "question": "What's 'Matrix' visual benefit over a regular Table?", "options": ["Support for subtotals and cross-tabulation in a grouped view", "It is smaller", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'KPI Dashboard'?", "options": ["Visual interface showing key performance indicators", "A dashboard for cars", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Executive Summary'?", "options": ["High-level overview for stakeholders", "A business summary", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Drill-Through'?", "options": ["Navigation to detailed data by clicking on summary elements", "Making holes in data", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Data Storytelling'?", "options": ["Presenting data as narrative with context", "Telling data stories", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Geospatial Analysis'?", "options": ["Analyzing location-based data patterns", "Studying geography", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Predictive Analytics' in reports?", "options": ["Forecasting future trends based on historical data", "Guessing future", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Cohort Analysis'?", "options": ["Grouping users by behavior patterns for insights", "Analyzing groups", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Root Cause Analysis'?", "options": ["Identifying fundamental causes of problems in data", "Finding problems", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Benchmarking' in reports?", "options": ["Comparing performance against standards or competitors", "Testing speed", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'A/B Testing' in reports?", "options": ["Comparing different report versions for effectiveness", "Testing report versions", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Data Quality' assessment?", "options": ["Evaluating accuracy, completeness, and consistency of data", "Checking data quality", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'User Behavior Analytics'?", "options": ["Analyzing how users interact with reports and dashboards", "Studying user actions", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Conversion Funnel'?", "options": ["Visualizing user journey from awareness to action", "A funnel for users", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Heatmap' in reports?", "options": ["Visual showing where users click/scroll most", "A temperature map", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Cohort Retention'?", "options": ["Measuring how well you keep user groups over time", "Keeping groups together", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Churn Analysis'?", "options": ["Analyzing why users leave or stop using service", "Studying user departure", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Lifetime Value' (LTV)?", "options": ["Predicting future revenue from a customer", "Customer lifetime value", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Segmentation' in reports?", "options": ["Dividing users into groups for targeted analysis", "Breaking into segments", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Personalization'?", "options": ["Customizing content based on user preferences", "Making personal", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Multi-variant Testing'?", "options": ["Testing different report versions simultaneously", "Testing multiple versions", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
