import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_selenium_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Selenium?", "options": ["A programming language", "A powerful framework for testing web applications with automation", "A browser", "None"], "correct": 1},
        {"id": 2, "question": "What is 'Selenium WebDriver'?", "options": ["A physical driver", "A component of Selenium that interacts directly with browser drivers", "A type of table", "None"], "correct": 1},
        {"id": 3, "question": "Which of these is a supported language in Selenium?", "options": ["Java", "Python", "C#", "All of the above"], "correct": 3},
        {"id": 4, "question": "What is 'Selenium Grid'?", "options": ["A list of servers", "A tool for parallel test execution on different machines/browsers", "A type of chart", "None"], "correct": 1},
        {"id": 5, "question": "What is 'Selenium IDE'?", "options": ["A browser extension for record-and-playback of tests", "A powerful compiler", "A technical specification", "None"], "correct": 0},
        {"id": 6, "question": "Which locator is the most reliable and fastest in Selenium?", "options": ["ID", "Name", "XPath", "CSS Selector"], "correct": 0},
        {"id": 7, "question": "Which locator is commonly used when IDs and Names are not available?", "options": ["CSS Selector", "XPath", "Both A and B", "Neither"], "correct": 2},
        {"id": 8, "question": "What is an 'Implicit Wait' in Selenium?", "options": ["Waiting for a specific time", "Instructing the WebDriver to poll the DOM for a certain amount of time for all elements", "A type of error", "None"], "correct": 1},
        {"id": 10, "question": "Which command is used to launch a URL in a browser using WebDriver?", "options": ["driver.get('url')", "driver.navigate.to('url')", "Both A and B", "Neither"], "correct": 2},
        {"id": 11, "question": "Which method is used to find a single element by its locator?", "options": ["findElement()", "findElements()", "getElement()", "None"], "correct": 0},
        {"id": 12, "question": "Which method is used to find multiple elements matching a locator?", "options": ["findElement()", "findElements()", "getElements()", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Page Object Model' (POM) in Selenium?", "options": ["A type of design flow", "A design pattern used to create a repository for web elements as classes", "A type of database", "None"], "correct": 1},
        {"id": 14, "question": "Which command is used to click a button or link?", "options": ["element.press()", "element.click()", "element.go()", "None"], "correct": 1},
        {"id": 15, "question": "Which command is used to type text into an input field or text area?", "options": ["element.typeKeys()", "element.sendKeys()", "element.write()", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Actions class' used for in Selenium?", "options": ["Performing complex gestures like drag and drop, hover", "Deleting code", "A technical specification", "None"], "correct": 0},
        {"id": 17, "question": "How do you handle alert popups in Selenium?", "options": ["Using the Alert interface (accept, dismiss)", "Using a screen reader", "Ignoring it", "None"], "correct": 0},
        {"id": 18, "question": "Which method is used to get the title of the current page?", "options": ["driver.getTitle()", "driver.currentTitle()", "driver.fetchTitle()", "None"], "correct": 0},
        {"id": 19, "question": "How do you close the current browser window specifically?", "options": ["driver.close()", "driver.quit()", "Both A and B", "Neither"], "correct": 0},
        {"id": 20, "question": "How do you close all browser windows and end the driver session?", "options": ["driver.close()", "driver.quit()", "driver.stop()", "None"], "correct": 1},
        {"id": 21, "question": "What is 'Select' class used for?", "options": ["Selecting a value", "Interacting with drop-down menus (select tags)", "A type of list", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Capability' (DesiredCapabilities) in Selenium context?", "options": ["Internet speed limit", "A class used to configure various environment properties for browser testing", "A type of storage", "None"], "correct": 1},
        {"id": 23, "question": "What is a 'Snapshot' or 'Screenshot' in Selenium?", "options": ["A photo for social media", "Capturing an image of the browser at a specific time for evidence/debugging", "None of the above", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Log4j' commonly used for in Selenium frameworks?", "options": ["Deleting code", "Recording test logs during execution for audit and debugging", "A technical manual", "None"], "correct": 1},
        {"id": 25, "question": "Which test framework is most popular for organizing Selenium tests in Java?", "options": ["JUnit", "TestNG", "Both A and B", "Cucumber"], "correct": 2},
        {"id": 26, "question": "What is 'Cucumber'?", "options": ["A vegetable and software tool", "A behavior-driven development (BDD) tool using Gherkin syntax", "Both A and B", "None"], "correct": 2},
        {"id": 27, "question": "What is 'Extent Reports' used for?", "options": ["A financial report", "Creating high-quality, interactive, and customizable test execution reports", "A tech spec", "None"], "correct": 0},
        {"id": 28, "question": "Which method is used to clear text within an input field?", "options": ["element.clear()", "element.delete()", "element.remove()", "None"], "correct": 0},
        {"id": 29, "question": "What is 'Headless Browser' testing?", "options": ["Testing without a computer keyboard", "Testing on a browser that runs without a graphical user interface", "Both A and B", "None"], "correct": 1},
        {"id": 30, "question": "Which of these is a major advantage of automation over manual testing?", "options": ["Speed and efficiency", "Repeatability", "Accuracy and broad coverage", "All of the above"], "correct": 3},
        {"id": 31, "question": "What is 'Selenium Remote Control' (RC)?", "options": ["Old version of Selenium that allowed injecting JavaScript for automation", "A remote for a TV", "A type of database", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Automation' in Selenium?", "options": ["Manually clicking items", "Executing tests using software tools to improve efficiency and speed", "A types of computer part", "None"], "correct": 1},
        {"id": 33, "question": "What is 'driver.get()' function?", "options": ["Navigating the browser specifically to a provided URL", "Deleting history", "A routing name", "None"], "correct": 0},
        {"id": 34, "question": "What is 'driver.navigate().to()'?", "options": ["Equivalent to driver.get()", "Loading a new webpage", "Both A and B", "Neither"], "correct": 2},
        {"id": 35, "question": "What is 'driver.navigate().back()'?", "options": ["Going back to previous page in browser history", "Closing the tab", "Neither", "Both"], "correct": 0},
        {"id": 36, "question": "What is 'driver.navigate().forward()'?", "options": ["Moving forward in browser history", "Starting a new session", "Neither", "Both"], "correct": 0},
        {"id": 37, "question": "What is 'driver.navigate().refresh()'?", "options": ["Reloading the current page", "Clearing cookies", "Neither", "Both"], "correct": 0},
        {"id": 38, "question": "What is 'Absolute XPath' in Selenium?", "options": ["XPath starting from the root of the HTML document (from /html)", "XPath from current node", "Neither", "Both"], "correct": 0},
        {"id": 39, "question": "What is 'Relative XPath'?", "options": ["XPath starting from a specific element anywhere in the DOM (from //)", "A path for files", "Neither", "Both"], "correct": 0},
        {"id": 40, "question": "What is 'CSS Selector'?", "options": ["A way to find elements based on CSS attributes (e.g. class, id)", "A styles only", "Neither", "Both"], "correct": 0},
        {"id": 41, "question": "Which command checks if an element is currently displayed on the page?", "options": ["element.isDisplayed()", "element.isVisible()", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "Which command checks if an element (like a checkbox) is selected?", "options": ["element.isSelected()", "element.isChecked()", "Neither", "Both"], "correct": 0},
        {"id": 43, "question": "Which command checks if an element is enabled for interaction?", "options": ["element.isEnabled()", "element.isActive()", "Neither", "Both"], "correct": 0},
        {"id": 44, "question": "How to handle multiple windows (Tabs) in Selenium?", "options": ["Using window handles (driver.getWindowHandles())", "Closing all windows", "Neither", "Both"], "correct": 0},
        {"id": 45, "question": "What is 'iFrame' handling in Selenium?", "options": ["Switching specifically using driver.switchTo().frame()", "Ignoring the frame", "Neither", "Both"], "correct": 0},
        {"id": 46, "question": "How to move mouse over an element (Hover)?", "options": ["Actions.moveToElement(element).perform()", "Actions.hover(element)", "Neither", "Both"], "correct": 0},
        {"id": 47, "question": "How to perform a right-click manually in Selenium?", "options": ["Actions.contextClick(element).perform()", "Actions.rightClick()", "Neither", "Both"], "correct": 0},
        {"id": 48, "question": "How to perform a double-click?", "options": ["Actions.doubleClick(element).perform()", "Actions.clickTwo()", "Neither", "Both"], "correct": 0},
        {"id": 49, "question": "How to drag and drop an element?", "options": ["Actions.dragAndDrop(src, dest).perform()", "Actions.moveItem()", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'JavaScriptExecutor' used for?", "options": ["Executing raw JavaScript directly in the browser during tests", "Calculations", "Neither", "Both"], "correct": 0},
        {"id": 51, "question": "How to scroll down a page specifically in Selenium?", "options": ["Using JavaScriptExecutor (window.scrollBy)", "Pressing arrow keys manually", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'Fluent Wait' significance?", "options": ["Allows setting poll interval and ignoring specific exceptions during wait", "A fast wait", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "Which browser is NOT natively supported by Selenium itself?", "options": ["Chrome", "Firefox", "Safari", "Tor"], "correct": 3},
        {"id": 54, "question": "What is 'GeckoDriver'?", "options": ["Driver for Firefox browser", "Driver for Chrome", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'ChromeDriver'?", "options": ["Driver specifically for Google Chrome browser", "Neither", "Both", "All"], "correct": 0},
        {"id": 56, "question": "Which method gets the current page URL?", "options": ["driver.getCurrentUrl()", "driver.getUrl()", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is the result of 'driver.getPageSource()'?", "options": ["Getting the raw HTML source code of the current page", "Saving a page", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "How can you read text from a web element?", "options": ["element.getText()", "element.read()", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "How can you get the value of an attribute (e.g. href)?", "options": ["element.getAttribute('name')", "element.fetchValue()", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "How can you get the size of an element?", "options": ["element.getSize()", "element.measure()", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "How can you get the location of an element on screen?", "options": ["element.getLocation()", "element.getPos()", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Assert' in testing terms?", "options": ["A way to verify that a condition is true (e.g. pass/fail test)", "A design item", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What's the meaning of 'Hard Assert'?", "options": ["Stops test execution immediately if the assertion fails", "A difficult test", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What's the meaning of 'Soft Assert'?", "options": ["Continues test execution even if the assertion fails (records it)", "A types of text", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is '@Test' annotation in TestNG?", "options": ["Marks a method as part of a technical test case", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is '@BeforeMethod' in TestNG?", "options": ["Method that runs BEFORE every single @Test method", "Method that runs after", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "What is '@AfterMethod' in TestNG?", "options": ["Method that runs AFTER every single @Test method", "Neither", "Both", "All"], "correct": 0},
        {"id": 68, "question": "What is 'Data Provider' in TestNG?", "options": ["Allows running the same test with multiple sets of data automatically", "A types of cars", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Parameterization' in Selenium tests?", "options": ["Passing data to test methods via XML or property files", "Measuring code", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Maven' in Selenium automation?", "options": ["A build tool for managing project dependencies (jars)", "A types of bird", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What's the function of 'pom.xml' in Maven?", "options": ["Project Object Model file for project configuration and dependencies", "A routing name", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Jenkins' significance in Selenium context?", "options": ["CI tool specifically for scheduling and running automation tests", "A new computer CPU", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What's the meaning of 'Continuous Integration' (CI)?", "options": ["Automatically building and testing code as changes are committed", "A types of math", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What's the benefit of 'Headless testing' on servers?", "options": ["Running tests faster without needing a GUI screen", "Ignoring bugs", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'GhostDriver' / 'PhantomJS'?", "options": ["Deprecated headless browser drivers", "A security feature", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "How many browser windows can Selenium open?", "options": ["Multiple", "Only one", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "Which constant is used for 'FirefoxOptions'?", "options": ["Configuring Firefox profile specifically during Selenium initiation", "Firefox speed", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "Which constant is used for 'ChromeOptions'?", "options": ["Setting flags like --incognito or --headless for Chrome", "Chrome speed", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'WebDriverManager' tool (by Boni Garcia)?", "options": ["Automatically managing browser driver executables without manual setup", "A list of users", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Why is Selenium preferred over manual testing for regression?", "options": ["Ensuring that old features still work correctly after changes efficiently", "It's free", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'Selenium Grid'?", "options": ["Parallel test execution across multiple machines", "A grid of selenium", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Selenium IDE'?", "options": ["Integrated development environment for Selenium", "Selenium programming environment", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Page Object Model' (POM)?", "options": ["Design pattern representing web pages as objects", "A model of web pages", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Data-Driven Testing'?", "options": ["Using external data sources for test inputs", "Testing with data", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Keyword-Driven Testing'?", "options": ["Using keywords to identify test objects", "Testing with keywords", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Behavior-Driven Testing'?", "options": ["Testing based on user behavior patterns", "Testing behavior", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Cross-Browser Testing'?", "options": ["Ensuring compatibility across different browsers", "Testing multiple browsers", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Headless Browser Testing'?", "options": ["Running tests without GUI", "Testing without heads", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Visual Testing'?", "options": ["Validating visual appearance and layout", "Testing visuals", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'API Testing' with Selenium?", "options": ["Testing REST APIs and web services", "Testing APIs", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Mobile Testing' with Selenium?", "options": ["Testing on mobile devices and browsers", "Testing mobile apps", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Performance Testing'?", "options": ["Measuring application speed and resource usage", "Testing speed", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Accessibility Testing'?", "options": ["Testing for users with disabilities", "Testing access", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Localization Testing'?", "options": ["Testing in different languages and regions", "Testing locations", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Security Testing'?", "options": ["Finding vulnerabilities and security flaws", "Testing security", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Regression Testing'?", "options": ["Re-testing after changes to ensure no new bugs", "Testing again", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Integration Testing'?", "options": ["Testing how components work together", "Testing parts", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'End-to-End Testing'?", "options": ["Testing complete user workflows", "Testing everything", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Continuous Testing'?", "options": ["Automated testing throughout development lifecycle", "Testing continuously", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Test Reporting'?", "options": ["Documenting and communicating test results", "Writing test reports", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
