import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_smartcontracts_api(request):
    questions_pool = [
        {"id": 1, "question": "What is a 'Smart Contract'?", "options": ["A digital signature only", "A self-executing contract with terms written into code", "A computer chip", "None"], "correct": 1},
        {"id": 2, "question": "Which language is primarily used for Ethereum smart contracts?", "options": ["Python", "Solidity", "TypeScript", "Vyper"], "correct": 1},
        {"id": 3, "question": "What is the result of 'Immutability' in smart contracts?", "options": ["Code can be easily updated", "Code cannot be modified once deployed", "Code is hidden from users", "None"], "correct": 1},
        {"id": 4, "question": "What is 'EVM'?", "options": ["Ethereum Virtual Machine", "Ethereum Virtual Monitor", "Empty Virtual Module", "None"], "correct": 0},
        {"id": 5, "question": "What are 'Gas Fees' in smart contract execution?", "options": ["Monthly subscription costs", "Resource costs paid to validators for processing transactions", "Design costs", "None"], "correct": 1},
        {"id": 6, "question": "What is a 'Constructor' in a smart contract?", "options": ["A method specifically used for creating an object", "A special function that runs only once during deployment", "A technical specification", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Event' in Solidity?", "options": ["A formal party", "A way for smart contracts to log data that frontend apps can listen for", "A error code", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Modifier' in Solidity?", "options": ["Changing the font", "A reusable piece of code that changes the behavior of a function (e.g. onlyAdmin)", "A button", "None"], "correct": 1},
        {"id": 9, "question": "What is 'Inheritance' in smart contracts?", "options": ["Inheriting money", "The ability for one contract to inherit functions and variables of another", "A link to a website", "None"], "correct": 1},
        {"id": 10, "question": "What is a 'Contract Address'?", "options": ["A physical address", "A unique identifier assigned when a contract is deployed", "The developer's name", "None"], "correct": 1},
        {"id": 11, "question": "What is 'ABI' (Application Binary Interface)?", "options": ["A type of table", "The interface used to interact with a smart contract from external software", "A password", "None"], "correct": 1},
        {"id": 12, "question": "What is 'OpenZeppelin'?", "options": ["A brand of hardware", "A library for secure, community-tested smart contract templates", "A design tool", "None"], "correct": 1},
        {"id": 13, "question": "What was 'The DAO' hack in Ethereum history?", "options": ["A software update", "A major security vulnerability where millions were stolen from a smart contract", "A server crash", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Security Audit' for smart contracts?", "options": ["Checking code for bugs and vulnerabilities before deployment", "A financial report", "A list of users", "None"], "correct": 0},
        {"id": 15, "question": "What is 'Reentrancy' attack?", "options": ["A type of loop problem", "When a contract makes a call to an external contract and is recursively re-entered", "An internet speed test", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Solc'?", "options": ["The Solidity compiler", "A type of crypto coin", "A technical manual", "None"], "correct": 0},
        {"id": 17, "question": "What is 'Private' state variable in Solidity?", "options": ["Variable only accessible within the same contract", "Variable visible globally", "A hidden file", "None"], "correct": 0},
        {"id": 18, "question": "What is 'Public' state variable?", "options": ["Accessible by everyone via a getter function", "A secret variable", "A type of chart", "None"], "correct": 0},
        {"id": 19, "question": "What is 'External' function access?", "options": ["Can only be called by other contracts and via transactions", "Can only be called within the same contract", "None", "None"], "correct": 0},
        {"id": 20, "question": "What is 'Internal' function access?", "options": ["Visible to the same contract and contracts inheriting from it", "A secret function", "A decorative part of code", "None"], "correct": 0},
        {"id": 21, "question": "What is 'Gas Limit' for a smart contract call?", "options": ["Maximum computer power allowed", "The maximum gas a user allows a transaction to consume", "None of the above", "None"], "correct": 1},
        {"id": 22, "question": "What is 'Wei'?", "options": ["The smallest unit of Ether (1 ETH = 10^18 Wei)", "A type of coin", "A brand of computer", "None"], "correct": 0},
        {"id": 23, "question": "What is 'Gwei'?", "options": ["A unit of Ether used to price gas (1 ETH = 10^9 Gwei)", "A type of cryptosystem", "A security log", "None"], "correct": 0},
        {"id": 24, "question": "What is 'Fallback' function in Solidity?", "options": ["A function that starts the computer", "A special function called when none of the others match or no data is provided", "A technical manual", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Truffle' used for?", "options": ["Deploying, testing, and managing smart contract development", "A type of table", "A security feature", "None"], "correct": 0},
        {"id": 26, "question": "What is 'Ganache'?", "options": ["A type of chocolate", "A personal blockchain for local Ethereum development", "A design tool", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Oracle' in blockchain context?", "options": ["A database company only", "A service that provides external data to smart contracts (e.g., Chainlink)", "A security company", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Self-destruct' in a smart contract?", "options": ["Deleting a document", "Permanently removing the contract code and remaining balance from the blockchain", "Stopping a computer", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Contract Deployment' in simple words?", "options": ["Creating a new data table", "The process of uploading and starting a smart contract on the blockchain", "Starting a database", "None"], "correct": 1},
        {"id": 30, "question": "What is the primary benefit of smart contracts?", "options": ["Transparency and Trustlessness", "Efficiency and speed", "Cost reduction through middleman elimination", "All of the above"], "correct": 3},
        {"id": 31, "question": "What is 'Vyper'?", "options": ["A contract-oriented, pythonic programming language for the EVM", "A type of snake", "A secure network protocol", "None"], "correct": 0},
        {"id": 32, "question": "What are 'Mapping' types in Solidity?", "options": ["Key-value data structures used to store and associate data efficiently", "Cartographic maps for navigation", "A list of strings", "None"], "correct": 0},
        {"id": 33, "question": "What is an 'Address' type?", "options": ["A 20-byte value specifically representing an Ethereum account", "A physical home address", "A types of internet speed", "None"], "correct": 0},
        {"id": 34, "question": "What is 'msg.sender' in Solidity?", "options": ["The address of the account or contract that called the current function", "The text of a message", "A types of computer code", "None"], "correct": 0},
        {"id": 35, "question": "What is 'msg.value'?", "options": ["The amount of Wei sent along with the current call", "The time of the transaction", "A hidden file", "None"], "correct": 0},
        {"id": 36, "question": "What is 'block.timestamp'?", "options": ["The current block's timestamp as seconds since unix epoch", "A clock on the wall", "A decorative text", "None"], "correct": 0},
        {"id": 37, "question": "What is 'require()' statement used for?", "options": ["To validate inputs and conditions before executing rest of the function", "To import a library", "To print data", "None"], "correct": 0},
        {"id": 38, "question": "What is 'assert()' statement used for?", "options": ["Checking for internal errors and invariant conditions (reserves all gas if fails)", "Asking a question", "Starting a loop", "None"], "correct": 0},
        {"id": 39, "question": "What is 'revert()' explicitly?", "options": ["Canceling execution and undoing all state changes explicitly", "Going back to a previous page", "A type of error in formatting", "None"], "correct": 0},
        {"id": 40, "question": "What are 'Pure' functions in Solidity?", "options": ["Functions that do not read or modify the contract state", "Functions that are clean from bugs", "A types of health drink", "None"], "correct": 0},
        {"id": 41, "question": "What are 'View' functions in Solidity?", "options": ["Functions that can read state but cannot modify it", "Functions for watching videos", "A types of chart", "None"], "correct": 0},
        {"id": 42, "question": "What is 'Constant' variable in a contract?", "options": ["A variable whose value cannot be changed after compilation", "A variable that always changes", "A types of storage", "None"], "correct": 0},
        {"id": 43, "question": "What is 'Immutable' variable in a contract?", "options": ["A variable whose value is set once during deployment and cannot be changed", "A variable that cannot move", "A types of memory", "None"], "correct": 0},
        {"id": 44, "question": "What is 'Fixed Point' numbers in Solidity?", "options": ["Numbers with a fixed decimal point (not fully supported by EVM yet)", "Whole numbers only", "A math constant", "None"], "correct": 0},
        {"id": 45, "question": "What is 'Array Slicing'?", "options": ["Taking a subset of an array for processing", "Cutting a pizza", "A types of data encryption", "None"], "correct": 0},
        {"id": 46, "question": "What is 'External' function access?", "options": ["Visible only to external calls and cannot be called internally without 'this.'", "Visible to everyone including hackers", "A types of routing", "None"], "correct": 0},
        {"id": 47, "question": "What are 'Library' contracts?", "options": ["Reusable pieces of code that can be deployed once and called by other contracts", "A place to borrow books", "A types of database schema", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Delegatecall'?", "options": ["Running code from another contract but using the current contract's storage", "A phone call to a delegate", "A types of load balancer", "None"], "correct": 0},
        {"id": 49, "question": "What is 'Storage' vs 'Memory' in Solidity?", "options": ["Persistent on-chain storage vs temporary execution-only memory", "Same as computer RAM", "Cloud storage names", "None"], "correct": 0},
        {"id": 50, "question": "What is 'CallData'?", "options": ["A temporary, non-modifiable area specifically for function arguments", "A log of phone calls", "A database name", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Proxy' pattern?", "options": ["A design pattern to make smart contracts upgradeable", "A types of internet filter", "A security guard", "None"], "correct": 0},
        {"id": 52, "question": "What is 'ERC-20' standard?", "options": ["The standard interface for fungible tokens on Ethereum", "A type of car", "A computer monitor", "None"], "correct": 0},
        {"id": 53, "question": "What is 'ERC-721' standard?", "options": ["The standard interface for non-fungible tokens (NFTs)", "A list of strings", "A new internet speed", "None"], "correct": 0},
        {"id": 54, "question": "What is 'ERC-1155' standard?", "options": ["A multi-token standard for managing both fungible and non-fungible tokens", "A set of design rules", "A type of game console", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Gas Price' currently?", "options": ["The amount of Gwei per unit of gas a user is willing to pay", "The price of gasoline", "A fixed system cost", "None"], "correct": 0},
        {"id": 56, "question": "What is 'Overload' in Solidity functions?", "options": ["Having multiple functions with same name but different parameters", "A power surge", "A computer virus", "None"], "correct": 0},
        {"id": 57, "question": "What is 'Shadowing' variable problem?", "options": ["When a local variable has same name as a state variable, hiding it", "A dark spot in code", "A decorative text effect", "None"], "correct": 0},
        {"id": 58, "question": "What is 'Block Gas Limit'?", "options": ["The maximum total gas that can be spent by all transactions in one block", "A limit on blocks in a game", "A user's spending limit", "None"], "correct": 0},
        {"id": 59, "question": "What is 'Hardhat' for contracts?", "options": ["An Ethereum development environment to compile, deploy, test, and debug", "A protective hat", "A building tool", "None"], "correct": 0},
        {"id": 60, "question": "What is 'Foundry' in contract development?", "options": ["A toolkit for Ethereum application development written in Rust", "A factory for metal", "A types of font", "None"], "correct": 0},
        {"id": 61, "question": "What is 'Slither' tool?", "options": ["A static analysis framework for Solidity to find vulnerabilities", "A type of snake game", "A fast internet", "None"], "correct": 0},
        {"id": 62, "question": "What is 'Echidna'?", "options": ["A fuzzing tool for smart contracts", "A small animal", "A mythological creature", "None"], "correct": 0},
        {"id": 63, "question": "What's 'Mythril' tool?", "options": ["A security analysis tool for Ethereum smart contracts", "A fantasy metal", "A list of files", "None"], "correct": 0},
        {"id": 64, "question": "What is 'Upgradeable Contract' concept?", "options": ["Using proxy patterns to swap logic contracts while keeping the state", "Rewriting code on blockchain", "A new software version", "None"], "correct": 0},
        {"id": 65, "question": "What is 'Timelock'?", "options": ["A smart contract feature that delays execution of a function for a set time", "A watch accessory", "A type of safe", "None"], "correct": 0},
        {"id": 66, "question": "What is 'Multisig' (Multi-signature) wallet?", "options": ["A wallet requiring multiple private keys to authorize a transaction", "A fast internet connection", "A design of a box", "None"], "correct": 0},
        {"id": 67, "question": "What is 'Gnosis Safe'?", "options": ["A popular multisig smart contract wallet", "A Greek myth", "A medical safe", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Zero Knowledge Proof' (ZKP)?", "options": ["Method to prove you know something without revealing what it is", "A student with no knowledge", "A type of encryption", "None"], "correct": 0},
        {"id": 69, "question": "What is 'ZK-SNARK'?", "options": ["An acronym for Zero-Knowledge Succinct Non-Interactive Argument of Knowledge", "A type of shark", "A fast computer", "None"], "correct": 0},
        {"id": 70, "question": "What is 'Layer 1' (L1) blockchain?", "options": ["The fundamental underlying blockchain (e.g. Ethereum, Bitcoin)", "The first layer of a cake", "A type of foundation", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Layer 2' (L2) blockchain?", "options": ["Scalability solutions built on top of L1 (e.g. Rollups)", "The second story of a house", "A types of internet", "None"], "correct": 0},
        {"id": 72, "question": "What is 'Sidechain'?", "options": ["A separate blockchain connected to a main one for faster transactions", "A chain on a bike", "A secondary link", "None"], "correct": 0},
        {"id": 73, "question": "What is 'Bridge' for smart contracts?", "options": ["A tool to transfer assets between different blockchains", "A dental tool", "A physical bridge", "None"], "correct": 0},
        {"id": 74, "question": "What is 'Governance' in smart contracts?", "options": ["Allowing token holders to vote on changes to the protocol", "Government laws", "A type of steering for cars", "None"], "correct": 0},
        {"id": 75, "question": "What's the meaning of 'Total Value Locked' (TVL)?", "options": ["Amount of assets deposited in a protocol's smart contracts", "A locked door", "A security cost", "None"], "correct": 0},
        {"id": 76, "question": "What is 'Yield Farming' in smart contracts?", "options": ["Staking or lending crypto in a DeFi protocol for high returns", "Growing crops", "A types of park", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Liquid Staking'?", "options": ["Receiving a liquid token in exchange for staked assets (e.g. stETH)", "Diving in water", "A types of chemistry", "None"], "correct": 0},
        {"id": 78, "question": "What is 'Frontrunning' in crypto?", "options": ["Execution of a trade based on knowledge of pending transactions", "Running in front of a race", "A types of sports betting", "None"], "correct": 0},
        {"id": 79, "question": "What is 'MEV' (Maximal Extractable Value)?", "options": ["Profit derived by including/reordering transactions in a block", "A type of medicine", "A video file", "None"], "correct": 0},
        {"id": 80, "question": "What is 'Smart Contract Vulnerability'?", "options": ["A bug in contract code that can be exploited (e.g. reentrancy, overflow)", "A types of physical injury", "A weak internet connection", "None"], "correct": 0},
        {"id": 81, "question": "What is 'ERC-20'?", "options": ["Standard for fungible tokens on Ethereum", "A type of cryptocurrency", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'ERC-721'?", "options": ["Standard for non-fungible tokens (NFTs) on Ethereum", "A type of document", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Gas Optimization'?", "options": ["Writing efficient code to minimize transaction costs", "Making gas cheaper", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Proxy Contract'?", "options": ["Contract that delegates calls to other contracts", "A contract helper", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Upgradeable Contract'?", "options": ["Contract that can be upgraded with new logic", "A better contract", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Immutable Contract'?", "options": ["Contract that cannot be modified after deployment", "A permanent contract", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Library Contract'?", "options": ["Reusable contract code deployed as library", "A book of contracts", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Factory Contract'?", "options": ["Contract that creates other contracts", "A manufacturing contract", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Multisig Wallet'?", "options": ["Wallet requiring multiple signatures for transactions", "A wallet with many signatures", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Time-lock Contract'?", "options": ["Contract that releases funds after specific time", "A clock contract", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Oracle Contract'?", "options": ["Contract that provides external data to blockchain", "A fortune teller", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Payable Contract'?", "options": ["Contract that can receive and store cryptocurrency", "A payment contract", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'View Contract'?", "options": ["Contract that only reads data without modifying state", "A reading contract", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Abstract Contract'?", "options": ["Contract template that cannot be deployed directly", "A theoretical contract", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Interface Contract'?", "options": ["Contract defining standard functions", "A communication contract", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Storage Contract'?", "options": ["Contract for storing data on blockchain", "A warehouse contract", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Token Contract'?", "options": ["Contract implementing fungible tokens", "A money contract", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Governance Contract'?", "options": ["Contract for managing protocol rules", "A government contract", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Crowdsale Contract'?", "options": ["Contract for group token purchases", "A group sale contract", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Bridge Contract'?", "options": ["Contract for connecting different blockchains", "A physical bridge", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
