import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_spring_api(request):
    questions_pool = [
        {"id": 1, "question": "What is Spring Framework?", "options": ["A seasonal event", "An open-source Java application framework with dependency injection", "A type of table", "None"], "correct": 1},
        {"id": 2, "question": "What is 'Dependency Injection' (DI)?", "options": ["Manually creating objects", "A design pattern where objects receive their dependencies from an external source (Inversion of Control)", "A literal medicine injection", "None"], "correct": 1},
        {"id": 3, "question": "What is 'IoC' (Inversion of Control)?", "options": ["User controls everything", "Handing over the control of object creation and lifecycle to the framework", "A routing engine", "None"], "correct": 1},
        {"id": 4, "question": "Which of these is a module in Spring Framework?", "options": ["Spring Core", "Spring MVC", "Spring DAO", "All of the above"], "correct": 3},
        {"id": 5, "question": "What is 'Spring Boot'?", "options": ["Spring's shoe product", "An opinionated framework built on Spring to simplify microservices and standalone apps", "A technical specification", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Aspect-Oriented Programming' (AOP)?", "options": ["Writing code with aspects", "Separating cross-cutting concerns (like logging, security) from business logic", "Both", "None"], "correct": 1},
        {"id": 7, "question": "What is a 'Spring Bean'?", "options": ["A types of vegetable", "An object that is instantiated, assembled, and managed by a Spring IoC container", "A database record", "None"], "correct": 1},
        {"id": 8, "question": "What is 'ApplicationContext'?", "options": ["Managing context for apps", "The central interface to the Spring IoC container", "A type of chart", "None"], "correct": 1},
        {"id": 9, "question": "What is 'autowiring' (@Autowired)?", "options": ["Automatic wiring of electrical components", "A feature that automatically provides dependency for a Spring bean without manual configuration", "None", "None"], "correct": 1},
        {"id": 10, "question": "What is 'Spring MVC'?", "options": ["Spring Multi-Video Creator", "A web framework built on the Servlet API that implements MVC pattern", "Both", "None"], "correct": 1},
        {"id": 11, "question": "What is '@Controller' annotation for?", "options": ["Mapping to a specific database", "Marking a class as a web controller to handle requests", "A design tool", "None"], "correct": 1},
        {"id": 12, "question": "What is '@RequestMapping'?", "options": ["Mapping a physical road", "A way to map HTTP requests to specific handler methods in a controller", "A security log", "None"], "correct": 1},
        {"id": 13, "question": "What is '@RestController'?", "options": ["A controller for restaurants", "Combined @Controller and @ResponseBody for building RESTful APIs", "Both", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Spring Data JPA'?", "options": ["Managing database access via a special Spring library using JPA", "A literal physical storage", "None", "None"], "correct": 0},
        {"id": 15, "question": "What is 'Spring Security'?", "options": ["Guarding a Spring building", "A powerful authentication and access-control framework for Java apps", "Both", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Thymeleaf' in Spring context?", "options": ["A type of leaf", "A popular server-side template engine used with Spring MVC", "A database company", "None"], "correct": 1},
        {"id": 17, "question": "What is 'DispatcherServlet'?", "options": ["A server component", "The front controller in Spring MVC that receives all requests and directs them to handlers", "None", "None"], "correct": 1},
        {"id": 18, "question": "Which annotation starts a Spring Boot application?", "options": ["@SpringBootApplication", "@MainApp", "@InitSpring", "@RunWithSpring"], "correct": 0},
        {"id": 19, "question": "What is '@Service' annotation for?", "options": ["Providing internet service", "Marking a bean as a service layer component for business logic", "A type of view", "None"], "correct": 1},
        {"id": 20, "question": "What is '@Repository' annotation for?", "options": ["Sharing a person's code", "Marking a bean as a data access object (DAO) for DB communication", "Both", "None"], "correct": 1},
        {"id": 21, "question": "What is '@Component' in Spring?", "options": ["A basic building block", "A generic annotation to indicate that a class is a Spring-managed component", "None", "None"], "correct": 1},
        {"id": 22, "question": "What is '@Configuration' for?", "options": ["Configuring a computer Screen", "Indicates that a class is a source of bean definitions", "None of the above", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Spring Profiles'?", "options": ["User profile on social media", "A feature to isolate beans in certain environments (dev, prod, test)", "None", "None"], "correct": 1},
        {"id": 24, "question": "What is '@Value' annotation used for?", "options": ["Setting cost for an item", "Injecting values from configuration properties into Spring beans", "Both", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Hibernate' relation to Spring?", "options": ["Spring's owner", "Spring uses ORM frameworks like Hibernate for database mapping", "They are identical", "None"], "correct": 1},
        {"id": 26, "question": "What is 'Microservices' context in Spring?", "options": ["Small computer parts", "Architectural style where applications are composed of small independent services", "None", "None"], "correct": 1},
        {"id": 27, "question": "What is 'Spring Cloud'?", "options": ["A cloud in the sky in spring", "A suite of tools to help developers build common patterns in distributed systems", "Both", "None"], "correct": 1},
        {"id": 28, "question": "What's the meaning of 'Starters' in Spring Boot (e.g. spring-boot-starter-web)?", "options": ["A meal before dinner", "Convenient dependency descriptors to pre-configure libraries for specific tasks", "None", "None"], "correct": 1},
        {"id": 29, "question": "What is 'Embedded Server' in Spring Boot (e.g. Tomcat)?", "options": ["Hosting without a separate install", "When a container (like Tomcat) is included directly in the application JAR", "Neither", "Both"], "correct": 1},
        {"id": 30, "question": "Which of these is used for building and managing Spring projects?", "options": ["Maven", "Gradle", "Both A and B", "Neither"], "correct": 2},
        # Adding 50 more questions...
        {"id": 31, "question": "What is 'Bean Scope' in Spring?", "options": ["The size of a bean", "The lifecycle and visibility of a bean (e.g. singleton, prototype)", "A security log", "None"], "correct": 1},
        {"id": 32, "question": "What is the result of 'Singleton' scope (default)?", "options": ["Only one bean instance is created per Spring IoC container", "Daily creation", "Both", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Prototype' scope?", "options": ["A new instance is created every time the bean is requested from the container", "Sharing one copy", "Neither", "Both"], "correct": 0},
        {"id": 34, "question": "Which annotation creates a custom bean within a @Configuration class?", "options": ["@Bean", "@Setup", "@NewObject", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Lombok' commonly used for in Spring apps?", "options": ["A styling tool", "Reducing boilerplate code like getters, setters, and constructors using annotations", "None", "None"], "correct": 1},
        {"id": 36, "question": "What is 'Spring Test' and '@SpringBootTest' for?", "options": ["Deleting the app", "Providing features to run integration tests with a full application context", "Both", "None"], "correct": 1},
        {"id": 37, "question": "What's 'DevTools' in Spring Boot?", "options": ["Tools for developers", "A set of tools providing automatic restarts and live reload for faster development", "A security feature", "None"], "correct": 1},
        {"id": 38, "question": "What is '@PathVariable' for?", "options": ["Binding to a URL segment", "Identifying a secret file", "None", "None"], "correct": 0},
        {"id": 39, "question": "What is '@RequestParam'?", "options": ["Request symbols from user", "Binding a query parameter from the URL to a method parameter", "A decorative text", "None"], "correct": 1},
        {"id": 40, "question": "What is '@RequestBody'?", "options": ["Reading a person's body", "Binding the entire HTTP request JSON/XML body to a Java object", "A design tool", "None"], "correct": 1},
        {"id": 41, "question": "What is '@ResponseBody' used for?", "options": ["Printing a body", "Converting a return value into an HTTP response body (like JSON)", "Both", "None"], "correct": 1},
        {"id": 42, "question": "What is 'ResponseEntity'?", "options": ["A list of web users", "A generic class representing an entire HTTP response (status, headers, body)", "A routing name", "None"], "correct": 1},
        {"id": 43, "question": "What is 'Model' object in Spring MVC controller method?", "options": ["A view blueprint", "Used to pass data/attributes from a controller to a rendering view (like Thymeleaf)", "None", "None"], "correct": 1},
        {"id": 44, "question": "What is 'ModelAndView'?", "options": ["A video for web developers", "A single object that contains both the model data and the view to be rendered", "A security log", "None"], "correct": 1},
        {"id": 45, "question": "What is 'BeanPostProcessor'?", "options": ["A way to process beans after they are created and initialized by the container", "A decorative name", "A tool for math", "None"], "correct": 0},
        {"id": 46, "question": "What is '@PostConstruct' used for?", "options": ["Calling a method after dependency injection and bean initialization is complete", "Starting a database", "Both", "None"], "correct": 0},
        {"id": 47, "question": "What is '@PreDestroy' used for?", "options": ["Calling a method right before a bean is removed from the container", "A final cleanup", "Both", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Spring Expression Language' (SpEL)?", "options": ["A language for math only", "Powerful expression language that supports querying and manipulating an object graph", "A design tool", "None"], "correct": 1},
        {"id": 49, "question": "What's the meaning of 'Circular Dependency'?", "options": ["Infinite loop of code", "When two or more beans depend on each other, causing a container creation failure", "Neither", "Both"], "correct": 1},
        {"id": 50, "question": "Which annotation tells Spring to ignore a property during JSON serialization?", "options": ["@JsonIgnore", "@Skip", "@Hide", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Spring Boot Actuator'?", "options": ["A robotic component", "A module providing production-ready features like health checks and metrics", "None", "None"], "correct": 1},
        {"id": 52, "question": "What's the meaning of 'Advice' in AOP?", "options": ["Giving advice to a person", "The action taken at a specific join point (e.g. before, after, around)", "None", "None"], "correct": 1},
        {"id": 53, "question": "What's the meaning of 'Join Point' in AOP?", "options": ["A specific point in program execution like method call or exception throwing", "A link in code", "None", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Pointcut' in AOP?", "options": ["A physical cut", "An expression that matches join points to determine where advice should be applied", "A tech spec", "None"], "correct": 1},
        {"id": 55, "question": "What is 'Aspect' in AOP?", "options": ["A way something looks", "The combination of advice and pointcuts for a specific concern (e.g. logging)", "Neither", "Both"], "correct": 1},
        {"id": 56, "question": "What is 'Spring Resource' abstraction?", "options": ["A common way to access resources (files, URLs, classpath items) uniformly", "A list of developers", "None", "None"], "correct": 0},
        {"id": 57, "question": "What is 'Spring Cloud Gateway'?", "options": ["A cloud server only", "A high-performance API gateway built for microservices architecture", "A decorative text", "None"], "correct": 1},
        {"id": 58, "question": "What is 'Eureka' in Spring Cloud?", "options": ["A social media app", "A Service Discovery server where microservices register themselves", "Both", "None"], "correct": 1},
        {"id": 59, "question": "What is 'Feign Client' in Spring?", "options": ["A declarative REST client for microservices communication", "Deleting a record", "Formatting text", "None"], "correct": 0},
        {"id": 60, "question": "What is 'Hystrix' (now Resilience4j)?", "options": ["A medicine", "A circuit breaker library to handle failures in distributed systems", "A security log", "None"], "correct": 1},
        {"id": 61, "question": "What's '@Qualifier' used for in Spring?", "options": ["Qualifying for a job", "Disambiguating dependencies when multiple beans of the same type exist", "None", "None"], "correct": 1},
        {"id": 62, "question": "What is '@Primary' annotation?", "options": ["First person", "Marking a bean that should be taken by default if multiple match", "Both", "None"], "correct": 1},
        {"id": 63, "question": "What is '@Scope' parameter for prototype?", "options": ["Defining custom life cycle", "Setting the bean scope explicitly", "Both", "None"], "correct": 1},
        {"id": 64, "question": "What's the meaning of 'Statelessness' in REST APIs?", "options": ["No user accounts", "Every request contains all info needed to process it, with no server-side context", "None", "None"], "correct": 1},
        {"id": 65, "question": "What is 'Spring Batch'?", "options": ["Batching physical cookies", "A lightweight, robust framework for building background bulk processing tasks", "None", "None"], "correct": 1},
        {"id": 66, "question": "What is 'ApplicationEvent' in Spring?", "options": ["A party for apps", "A way for beans to communicate by sending and listening for specific events", "None", "None"], "correct": 1},
        {"id": 67, "question": "Which annotation handles global exceptions in Spring MVC?", "options": ["@ControllerAdvice", "@HandleError", "@GlobalException", "None"], "correct": 0},
        {"id": 68, "question": "Which annotation handles exception for a single controller?", "options": ["@ExceptionHandler", "@ControllerAdvice", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Spring WebFlux'?", "options": ["A website for flux", "Spring's reactive-stack web framework built on Project Reactor", "None", "None"], "correct": 1},
        {"id": 70, "question": "What is 'Project Reactor'?", "options": ["A nuclear project", "A reactive library for building non-blocking applications on the JVM", "Neither", "Both"], "correct": 1},
        {"id": 71, "question": "What's 'Mono' in reactive programming?", "options": ["One sound only", "A reactive stream returning 0 or 1 item", "Both", "None"], "correct": 1},
        {"id": 72, "question": "What's 'Flux' in reactive programming?", "options": ["A continuous stream", "A reactive stream returning 0 to N items", "None", "None"], "correct": 1},
        {"id": 73, "question": "What is 'Netty'?", "options": ["A sports equipment", "A popular non-blocking I/O client-server framework used by WebFlux", "None", "None"], "correct": 1},
        {"id": 74, "question": "What is '@EnableAutoConfiguration'?", "options": ["Automatically starting a car", "A core annotation that enables Spring Boot's automatic configuration mechanism", "None", "None"], "correct": 1},
        {"id": 75, "question": "What's the meaning of 'Opinionated' in framework context?", "options": ["Having many opinions", "Providing sensible defaults so developers can start quickly without much setup", "None", "None"], "correct": 1},
        {"id": 76, "question": "What is 'Spring Cache' abstraction?", "options": ["A bridge to various caching providers (Redis, Ehcache) using annotations (@Cacheable)", "A type of table", "None", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Spring Session'?", "options": ["Managing user sessions transparently across multiple instances using external store", "A login session", "Both", "None"], "correct": 0},
        {"id": 78, "question": "What is 'Jackson' in Spring context?", "options": ["A famous person name", "The default library used to convert Java objects to/from JSON", "None", "None"], "correct": 1},
        {"id": 79, "question": "Which status code represents 'OK' for a successful request?", "options": ["200", "404", "500", "201"], "correct": 0},
        {"id": 80, "question": "Which status code represents 'Not Found'?", "options": ["404", "401", "400", "500"], "correct": 0},
        {"id": 81, "question": "What is '@SpringBootApplication'?", "options": ["Annotation marking main class as Spring Boot app", "Spring application boot", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Spring Data JPA'?", "options": ["ORM framework for database operations", "Java persistence API", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Spring Security'?", "options": ["Framework for authentication and authorization", "Security for Spring apps", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Spring AOP'?", "options": ["Aspect-oriented programming for cross-cutting concerns", "Advanced Spring programming", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Spring Cloud'?", "options": ["Set of tools for cloud-native applications", "Spring in the cloud", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Spring Batch'?", "options": ["Framework for batch processing", "Processing in batches", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Spring Integration'?", "options": ["Pattern for integrating enterprise systems", "Integrating systems", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Spring WebSocket'?", "options": ["WebSocket support in Spring", "Web socket for Spring", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Spring Kafka'?", "options": ["Integration with Apache Kafka", "Kafka for Spring", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Spring GraphQL'?", "options": ["GraphQL support in Spring", "GraphQL for Spring", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Spring WebFlux'?", "options": ["Reactive web framework", "Web flux for Spring", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Spring Retry'?", "options": ["Mechanism for retrying failed operations", "Trying again", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Spring Circuit Breaker'?", "options": ["Pattern for preventing cascading failures", "Breaking circuits", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Spring Sleuth'?", "options": ["Distributed tracing for Spring applications", "Investigating Spring apps", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Spring Config'?", "options": ["External configuration management", "Spring configuration", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Spring Profile'?", "options": ["Environment-specific configuration", "Spring user profiles", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Spring Actuator'?", "options": ["Production-ready features for monitoring apps", "Spring monitoring", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Spring Native'?", "options": ["Compile-time configuration processor", "Native Spring apps", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Spring Shell'?", "options": ["Interactive shell for Spring applications", "Command line for Spring", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Spring Roo'?", "options": ["RAD tool for Spring development", "A kangaroo tool", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
