import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_ui_api(request):
    """
    General UI/UX and Frontend Design Assessment Questions.
    """
    questions_pool = [
        {"id": 1, "question": "What does UI stand for?", "options": ["User Interface", "User Integration", "Universal Interface", "User Interaction"], "correct": 0},
        {"id": 2, "question": "Which of these is a core principle of UX design?", "options": ["Complexity", "Usability", "Opacity", "Rigidity"], "correct": 1},
        {"id": 3, "question": "What is 'White Space' in UI design?", "options": ["Empty space between elements", "White background only", "Space for text only", "Error space"], "correct": 0},
        {"id": 4, "question": "What does 'Responsive Design' mean?", "options": ["Fast loading", "Layout adapts to different screen sizes", "Design with many buttons", "Design that responds to clicks"], "correct": 1},
        {"id": 5, "question": "What is a 'Wireframe'?", "options": ["A high-fidelity mockup", "A low-fidelity structural sketch of a page", "A type of code", "A CSS framework"], "correct": 1},
        {"id": 6, "question": "Which color is often used to signify 'Success' or 'Go'?", "options": ["Red", "Green", "Blue", "Yellow"], "correct": 1},
        {"id": 7, "question": "What is 'Typography'?", "options": ["The art of arranging type (fonts)", "A type of map", "A printing process", "Writing code"], "correct": 0},
        {"id": 8, "question": "What does 'Affordance' mean in UI?", "options": ["Cost of design", "The visual clue to an element's function", "Speed of interface", "Size of screen"], "correct": 1},
        {"id": 9, "question": "What is a 'Call to Action' (CTA)?", "options": ["A phone call", "A button or link that encourages a specific user action", "A design meeting", "A CSS class"], "correct": 1},
        {"id": 10, "question": "What is 'Accessibility' in UI design?", "options": ["Fast internet access", "Making designs usable by people with disabilities", "Price of the app", "Login speed"], "correct": 1},
        {"id": 11, "question": "What is a 'Grid System' used for?", "options": ["Drawing lines", "Consistent layout and alignment of elements", "Database storage", "Networking"], "correct": 1},
        {"id": 12, "question": "What is 'F-Pattern' in web design?", "options": ["A letter F", "The common way users scan content visually", "A type of error", "A coding pattern"], "correct": 1},
        {"id": 13, "question": "What is 'Visual Hierarchy'?", "options": ["A list of colors", "Arranging elements to show their importance", "A server structure", "A type of font"], "correct": 1},
        {"id": 14, "question": "What does 'RGB' stand for?", "options": ["Red Green Blue", "Red Gray Brown", "Real Great Blue", "Right Green Base"], "correct": 0},
        {"id": 15, "question": "What is 'Hex Code' in colors?", "options": ["A 6-digit code for errors", "A 6-digit code representing a color (e.g. #FFFFFF)", "A type of encrypted text", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Dark Mode'?", "options": ["An error state", "A color scheme that uses light text on a dark background", "A hidden feature", "A design failure"], "correct": 1},
        {"id": 17, "question": "What is 'Contrast Ratio'?", "options": ["Comparison of image sizes", "The difference in luminance between text and background", "A type of font weight", "Design speed"], "correct": 1},
        {"id": 18, "question": "Which of these is a popular UI design tool?", "options": ["Figma", "Excel", "Notepad", "Calculator"], "correct": 0},
        {"id": 19, "question": "What is 'Micro-interaction'?", "options": ["A large animation", "Subtle functional animations that provide feedback", "A small database", "A short code snippet"], "correct": 1},
        {"id": 20, "question": "What is 'User Journey'?", "options": ["Going to the office", "The path a user takes to complete a task in an app", "A physical trip", "A design sprint"], "correct": 1},
        # Adding more to reach 50...
        {"id": 21, "question": "What is 'Sans-serif'?", "options": ["Fonts with decorative lines at ends", "Fonts without decorative lines at ends", "A type of code", "A color palette"], "correct": 1},
        {"id": 22, "question": "What is 'Kerning'?", "options": ["Spacing between lines", "Spacing between individual characters", "Drawing shapes", "Size of text"], "correct": 1},
        {"id": 23, "question": "What is 'Leading' in typography?", "options": ["Spacing between lines of text", "The first word", "A bold font", "A CSS property"], "correct": 0},
        {"id": 24, "question": "What is 'Flat Design'?", "options": ["Design with no colors", "Minimalist design with no 3D effects/shadows", "A boring design", "A simple sketch"], "correct": 1},
        {"id": 25, "question": "What is 'Skeuomorphism'?", "options": ["Simplified design", "Design that mimics real-world objects and textures", "Modern design", "A type of error"], "correct": 1},
        {"id": 26, "question": "What is 'Card UI'?", "options": ["Using playing cards", "Organizing content into rectangular containers", "A small screen", "A type of menu"], "correct": 1},
        {"id": 27, "question": "What is 'Hamburger Menu'?", "options": ["A food icon", "The three-line icon for toggling a sidebar menu", "A circular menu", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Breadcrumb' navigation?", "options": ["Eating bread", "Showing the user's location in a site hierarchy", "A map of the city", "A list of links"], "correct": 1},
        {"id": 29, "question": "What is 'Modal' (or Popup)?", "options": ["A new web page", "An overlay window that requires interaction before returning to the main page", "A footer", "A sidebar"], "correct": 1},
        {"id": 30, "question": "What is 'Skeleton Screen'?", "options": ["A screen with bones", "A placeholder screen shown while content is loading", "A design template", "An error page"], "correct": 1},
        {"id": 31, "question": "What is 'Color Theory'?", "options": ["A study of painting", "The study of how colors interact and their psychological impacts", "A list of RGB codes", "None"], "correct": 1},
        {"id": 32, "question": "What is 'Primary Color'?", "options": ["The most expensive color", "The dominant color in a design's brand identity", "Black and white", "None"], "correct": 1},
        {"id": 33, "question": "What is 'Shadow' (Elevation) used for?", "options": ["Cool effects only", "Providing depth and indicating layered elements", "Hiding content", "None"], "correct": 1},
        {"id": 34, "question": "What is 'User Feedback' in UI?", "options": ["Users complaining", "Visual or auditory response to user actions (e.g. success message)", "A ratings page", "None"], "correct": 1},
        {"id": 35, "question": "What is 'A/B Testing'?", "options": ["Testing from A to B", "Comparing two versions of a design to see which performs better", "Testing for bugs", "None"], "correct": 1},
        {"id": 36, "question": "What is 'Heuristic Evaluation'?", "options": ["Counting buttons", "Expert review based on usability principles", "A user survey", "None"], "correct": 1},
        {"id": 37, "question": "What is 'Information Architecture' (IA)?", "options": ["Designing buildings", "Organizing and structuring content for navigation and clarity", "A database schema", "None"], "correct": 1},
        {"id": 38, "question": "What is 'SVG' primarily used for?", "options": ["Video", "Scalable vector graphics (icons, illustrations)", "Audio", "Database"], "correct": 1},
        {"id": 39, "question": "What is 'Persona' in UX?", "options": ["A real person", "A fictional character representing a user type", "A design lead", "None"], "correct": 1},
        {"id": 40, "question": "What is 'Empathy' in design?", "options": ["Being sad", "Understanding the user's needs, frustrations, and goals", "A types of font", "None"], "correct": 1},
        {"id": 41, "question": "What is 'Low Fidelity' mockup?", "options": ["Low quality image", "Quick, rough design for rapid iteration", "The final version", "None"], "correct": 1},
        {"id": 42, "question": "What is 'High Fidelity' mockup?", "options": ["Detailed design that looks like the final product", "A sketch", "A wireframe", "None"], "correct": 0},
        {"id": 43, "question": "What is 'Prototype' level?", "options": ["A sketch", "An interactive simulation of the final design", "A code snippet", "None"], "correct": 1},
        {"id": 44, "question": "What is 'Steppers' UI component?", "options": ["A stairs icon", "Control for inputting numbers or moving through steps", "A scrollbar", "None"], "correct": 1},
        {"id": 45, "question": "What is 'Pagination'?", "options": ["Writing a page", "Dividing content into discrete pages (e.g. 1, 2, 3...)", "A list scroll", "None"], "correct": 1},
        {"id": 46, "question": "What is 'Input Validation'?", "options": ["Counting words", "Checking that user input meets required format/constraints", "A search engine", "None"], "correct": 1},
        {"id": 47, "question": "What is 'Tooltip'?", "options": ["A tool for design", "Contextual help message shown when hovering over an element", "A footer link", "None"], "correct": 1},
        {"id": 48, "question": "What is 'Accordion' menu?", "options": ["A musical instrument", "A vertically stacked list of headers that expand to reveal content", "A horizontal menu", "None"], "correct": 1},
        {"id": 49, "question": "What is 'Empty State'?", "options": ["An error page", "Design shown when there is no content/data yet", "A blank screen", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Flexbox' primarily used for?", "options": ["Creating 1D layouts (rows or columns)", "Creating 3D objects", "Neither", "Both"], "correct": 0},
        {"id": 52, "question": "What is 'CSS Grid' used for?", "options": ["Creating 2D layouts (rows and columns simultaneously)", "Drawing grid lines", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Media Query'?", "options": ["Applying CSS styles based on device characteristics like width", "Querying a media database", "Neither", "Both"], "correct": 0},
        {"id": 54, "question": "What is 'Mobile-First' design?", "options": ["Designing for mobile screens before desktop", "Buying a phone first", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Progressive Enhancement'?", "options": ["Core content first, then advanced features for better browsers", "Improving everything at once", "Neither", "Both"], "correct": 0},
        {"id": 56, "question": "What is 'Graceful Degradation'?", "options": ["Complex design first, with fallbacks for older browsers", "Breaking the site", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Specificity' in CSS?", "options": ["Rules that determine which CSS selector 'wins' a conflict", "Being very specific", "Neither", "Both"], "correct": 0},
        {"id": 58, "question": "What is 'Box Model'?", "options": ["Content, Padding, Border, and Margin of an element", "A cardboard box", "Neither", "Both"], "correct": 0},
        {"id": 59, "question": "What is 'Margin' vs 'Padding'?", "options": ["Margin is outside the border; Padding is inside", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 60, "question": "What is 'Z-index'?", "options": ["Stacking order of elements along the z-axis (depth)", "A types of index", "Neither", "Both"], "correct": 0},
        {"id": 61, "question": "What is 'Opacity'?", "options": ["Transparency level of an element", "The thickness of an element", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Position: Absolute'?", "options": ["Relative to nearest positioned ancestor", "Fixed to screen", "Neither", "Both"], "correct": 0},
        {"id": 63, "question": "What is 'Position: Fixed'?", "options": ["Relative to the browser window (viewport)", "Stuck to back", "Neither", "Both"], "correct": 0},
        {"id": 64, "question": "What is 'Position: Sticky'?", "options": ["Toggles between relative and fixed based on scroll", "A sticky note", "Neither", "Both"], "correct": 0},
        {"id": 65, "question": "What is 'Pseudo-class' like ':hover'?", "options": ["Styles based on element state", "A fake class", "Neither", "Both"], "correct": 0},
        {"id": 66, "question": "What is 'Pseudo-element' like '::before'?", "options": ["Styles a specific part of an element", "Neither", "Both", "An image"], "correct": 0},
        {"id": 67, "question": "What is 'CSS Variable' (Custom Property)?", "options": ["Reusable values defined with --", "A JS variable", "Neither", "Both"], "correct": 0},
        {"id": 68, "question": "What is 'Sass'?", "options": ["CSS preprocessor with variables, nesting, and mixins", "Aggressive behavior", "Neither", "Both"], "correct": 0},
        {"id": 69, "question": "What is 'Tailwind CSS'?", "options": ["Utility-first CSS framework", "A types of wind", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'Bootstrap'?", "options": ["Popular CSS framework using pre-defined component classes", "Starting a computer", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Hero Section'?", "options": ["Prominent top area of a website (large text/image)", "A comic book area", "Neither", "Both"], "correct": 0},
        {"id": 72, "question": "What is 'Favicon'?", "options": ["Small icon in browser tab", "Favorite icon", "Neither", "Both"], "correct": 0},
        {"id": 73, "question": "What is 'Lazy Loading' images?", "options": ["Loading images only when they enter viewport", "Not loading images", "Neither", "Both"], "correct": 0},
        {"id": 74, "question": "What is 'Alt Text'?", "options": ["Description of an image for accessibility/SEO", "Alternative music", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Semantic HTML'?", "options": ["Using tags that describe their meaning (e.g. <header>, <article>)", "Smart HTML", "Neither", "Both"], "correct": 0},
        {"id": 76, "question": "What is 'SEO' in web design?", "options": ["Search Engine Optimization", "Super Easy Operation", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Web Performance'?", "options": ["Speed and efficiency of a website", "A show", "Neither", "Both"], "correct": 0},
        {"id": 78, "question": "What is 'Critical Path CSS'?", "options": ["Minimizing CSS required for initial screen render", "A dangerous path", "Neither", "Both"], "correct": 0},
        {"id": 79, "question": "What is 'Minification'?", "options": ["Removing whitespace/comments from code for speed", "Making something tiny", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "What is 'Service Worker'?", "options": ["Script for offline support and background tasks", "A janitor", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is 'PWA' (Progressive Web App)?", "options": ["Web app that provides app-like experience (offline, install)", "A professional app", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'User Engagement'?", "options": ["How much users interact with your site", "A promise to marry", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Bounce Rate'?", "options": ["Percentage of users who leave after viewing one page", "Speed of a ball", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Conversion Rate'?", "options": ["Percentage of users who complete a desired action", "Math conversion", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Heatmap'?", "options": ["Visual of where users click/scroll most", "A temperature map", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Usability Testing'?", "options": ["Observing real users using your interface", "Checking if code works", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'User Interview'?", "options": ["Talking to users about their needs", "A job interview", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Card Sorting'?", "options": ["UX method to design site structure", "Magic tricks", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Mood Board'?", "options": ["Collection of visuals representing design direction", "A board of feelings", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Style Guide'?", "options": ["Document defining design standards (colors, type)", "A fashion magazine", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Design System'?", "options": ["Library of reusable components and standards", "A computer system", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Component Library'?", "options": ["Collection of pre-built UI pieces", "A literal library", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Pattern Library'?", "options": ["Library of common UI design patterns", "A book of patterns", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'User-Centered Design' (UCD)?", "options": ["Design process focusing on user needs", "Putting users in the center", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Wireframing' vs 'Prototyping'?", "options": ["Wireframe is static layout; Prototype is interactive", "They are same", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Figma'?", "options": ["Leading cloud-based UI design and prototyping tool", "A types of fruit", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Adobe XD'?", "options": ["Vector-based UI design tool by Adobe", "An emoji", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Sketch'?", "options": ["MacOS-based design tool primarily for UI", "A quick drawing", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Iterative Design'?", "options": ["Cyclical process of refining and improving based on testing", "Repeating a mistake", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "Why is 'User Delight' important?", "options": ["It creates a memorable and positive impact", "It makes people laugh", "Neither", "Both"], "correct": 0},
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, 25)})
