import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_virtualreality_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Virtual Reality' (VR)?", "options": ["Enhancing real world", "A computer-generated environment with scenes/objects that appear real, immersing the user", "Watching a movie", "None"], "correct": 1},
        {"id": 2, "question": "What is 'Immersion' in VR context?", "options": ["The feeling of being physically present in a non-physical world", "Diving in water", "A tech spec", "None"], "correct": 0},
        {"id": 3, "question": "What is 'HMD'?", "options": ["Head-Mounted Display (a device like a headset for VR)", "High-speed Media Device", "Hardware Monitor Design", "None"], "correct": 0},
        {"id": 4, "question": "Which of these is a popular VR headset?", "options": ["Meta Quest", "PlayStation VR", "Valve Index", "All of the above"], "correct": 3},
        {"id": 5, "question": "What is 'Field of View' (FoV) in VR?", "options": ["The size of a farm field", "The angle of view exposed to the user (e.g. 110 degrees)", "A decorative part of code", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Refresh Rate'?", "options": ["How fast a user refreshes the page", "The number of times a display updates per second (e.g. 90Hz)", "A type of chart", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Latency' in VR context?", "options": ["The delay between head movement and display update (motion-to-photon latency)", "The speed of light", "Both A and B", "Neither"], "correct": 0},
        {"id": 8, "question": "What is 'Motion Tracking'?", "options": ["Following a car", "Tracking the movement of a user's head or hands within a VR space", "None", "None"], "correct": 1},
        {"id": 9, "question": "What is '6DOF' (Six Degrees of Freedom)?", "options": ["Rotation and translation tracking", "Only rotation tracking", "A type of table", "None"], "correct": 0},
        {"id": 10, "question": "What is '3DOF' (Three Degrees of Freedom)?", "options": ["Only rotation tracking", "Only translation tracking", "Neither", "Both"], "correct": 0},
        {"id": 11, "question": "What is 'Haptic Feedback' for VR?", "options": ["Sound effects", "Using touch sensations (vibrations) to simulate physical contact", "A type of box", "None"], "correct": 1},
        {"id": 12, "question": "What is 'Tethered VR'?", "options": ["VR connected to a PC or console with internal cables", "Wireless VR", "None", "None"], "correct": 0},
        {"id": 13, "question": "What is 'Standalone VR'?", "options": ["VR that doesn't need a PC or phone to function (e.g. Quest 2)", "VR connected with a cable", "A tech spec", "None"], "correct": 0},
        {"id": 14, "question": "Which engine is most popular for VR game development?", "options": ["Unity", "Unreal Engine", "Both A and B", "None"], "correct": 2},
        {"id": 15, "question": "What is 'Motion Sickness' (VR Sickness)?", "options": ["Nausea caused by a mismatch between physical movement and visual inputs", "Being sick on a plane", "A malware name", "None"], "correct": 0},
        {"id": 16, "question": "What is 'Foveated Rendering'?", "options": ["A type of error", "A technique that renders the area at which the user is looking with higher quality", "None of the above", "None"], "correct": 1},
        {"id": 17, "question": "What is 'Eye Tracking' in VR?", "options": ["Tracking if users are sleeping", "A system that identifies where a user is looking in the headset", "A security log", "None"], "correct": 1},
        {"id": 18, "question": "What is 'Gaze-based interaction'?", "options": ["Interacting by looking at an object for a specific duration", "Interacting with a mouse", "A tech spec", "None"], "correct": 0},
        {"id": 19, "question": "What is 'Spatial Audio'?", "options": ["Audio from a speaker", "3D audio that sound like it is coming from a specific direction within the VR space", "None", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Avatar' in VR context?", "options": ["A movie name", "A digital representation of a user in a virtual world", "A type of database", "None"], "correct": 1},
        {"id": 21, "question": "What's the meaning of 'Locomotion' in VR?", "options": ["Moving from one place to another within a virtual world", "Starting a train", "A decorative part of code", "None"], "correct": 0},
        {"id": 22, "question": "What is 'Teleportation' in VR?", "options": ["Instantly moving between points by pointing a controller", "Walking physically", "Both A and B", "Neither"], "correct": 0},
        {"id": 23, "question": "What is 'Omnidirectional Treadmill'?", "options": ["A physical device allowing the user to walk in any direction while staying in place", "Moving with a controller", "None", "None"], "correct": 0},
        {"id": 24, "question": "What is 'AR vs VR'?", "options": ["VR replaces your view; AR overlays on your view", "Both are identical", "None of the above", "None"], "correct": 0},
        {"id": 25, "question": "Which company developed the 'Oculus Rift'?", "options": ["Apple", "Google", "Facebook (Oculus/Meta)", "Microsoft"], "correct": 2},
        {"id": 26, "question": "What is 'Google Cardboard'?", "options": ["A very expensive VR headset", "A low-cost VR viewer made primarily of cardboard", "A design tool", "None"], "correct": 1},
        {"id": 27, "question": "What is 'SteamVR'?", "options": ["A list of servers", "A VR platform and store for PC-based VR games by Valve", "A type of table", "None"], "correct": 1},
        {"id": 28, "question": "What's the function of 'Base Stations' in older VR systems?", "options": ["Providing power", "Tracking the positions of the headset and controllers in a physical room", "A security feature", "None"], "correct": 1},
        {"id": 29, "question": "What is 'VRChat'?", "options": ["A social VR game", "A meeting on Zoom", "None of the above", "None"], "correct": 0},
        {"id": 30, "question": "What is the primary goal of VR training?", "options": ["To play games", "To simulate high-risk or complex environments for safer learning", "None for now", "None"], "correct": 1},
        {"id": 31, "question": "What is the 'Oculus Rift S' primarily used for?", "options": ["PC-tethered VR gaming", "Watching TV only", "Standalone gaming", "None"], "correct": 0},
        {"id": 32, "question": "What is 'Inside-out tracking'?", "options": ["Sensors on the headset track the environment and movement without external base stations", "Tracking inside the body", "Tracking the user's mind", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Outside-in tracking'?", "options": ["Using external cameras or sensors to track user movement", "Watching from outside a room", "Tracking data only", "None"], "correct": 0},
        {"id": 34, "question": "What is 'Lighthouse' tracking system?", "options": ["Valve's external laser tracking system used by HTC Vive and Index", "A light on a ship", "A type of internet connection", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Passthrough' mode in VR headsets?", "options": ["Viewing the real world through integrated cameras without taking off the headset", "Passing through a wall", "A type of level design", "None"], "correct": 0},
        {"id": 36, "question": "What is a 'Guardian' or 'Chaperone' system?", "options": ["Virtual boundaries that alert the user when they are near physical walls", "A person who watches the user", "A security guard", "None"], "correct": 0},
        {"id": 37, "question": "What is 'Mixed Reality' (MR)?", "options": ["A blend of physical and virtual worlds where digital objects interact with real ones", "Just another name for VR", "A mixture of two colors", "None"], "correct": 0},
        {"id": 38, "question": "What is 'WebVR' or 'WebXR'?", "options": ["Standard for experiencing VR and AR directly in a web browser", "A search engine for VR", "A types of website design", "None"], "correct": 0},
        {"id": 39, "question": "What is 'Beat Saber'?", "options": ["A highly popular VR rhythm game involving sabers and music", "A martial arts game", "A types of cooking", "None"], "correct": 0},
        {"id": 40, "question": "What is 'Half-Life: Alyx'?", "options": ["Critically acclaimed VR flagship game developed by Valve", "A science textbook", "A type of drug", "None"], "correct": 0},
        {"id": 41, "question": "What is the 'Screen Door Effect' in VR?", "options": ["Visual artifact where the gaps between display pixels are visible like a screen door", "A type of door design", "A computer virus", "None"], "correct": 0},
        {"id": 42, "question": "What is 'IPD' adjustment?", "options": ["Inter-Pupillary Distance (distance between eyes) adjustment for visual comfort", "A internet protocol", "A database name", "None"], "correct": 0},
        {"id": 43, "question": "What are 'God Rays' in VR lenses?", "options": ["Light streaks emanating from bright objects in dark scenes, often seen in Fresnel lenses", "Weather phenomenon", "A religious term", "None"], "correct": 0},
        {"id": 44, "question": "What is a 'Fresnel Lens'?", "options": ["A types of lens that is lighter/thinner with ridge-like patterns commonly used in VR", "A magnifying glass", "A new type of camera", "None"], "correct": 0},
        {"id": 45, "question": "What is 'Asynchronous Timewarp' (ATW)?", "options": ["A technique that reduces perceived judder when a game's framerate drops in VR", "A types of time travel", "A video editing tool", "None"], "correct": 0},
        {"id": 46, "question": "What is 'Oculus Link'?", "options": ["Feature allowing Meta Quest headsets to be used as PC VR headsets via USB cable", "A hyperlink to Facebook", "A chain for a car", "None"], "correct": 0},
        {"id": 47, "question": "What is 'Air Link'?", "options": ["Wireless version of Oculus Link using Wi-Fi for PC VR on Quest headsets", "A types of airline", "A radio station", "None"], "correct": 0},
        {"id": 48, "question": "What is the 'Meta Quest 3' known for?", "options": ["Greatly improved Mixed Reality capabilities with color passthrough", "Being the very first VR headset", "Having no screen", "None"], "correct": 0},
        {"id": 49, "question": "What is the 'Apple Vision Pro'?", "options": ["Apple's spatial computer/headset focused on high-end productivity and media", "A new iPhone model", "A types of glasses", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Viveport'?", "options": ["HTC's VR app store and subscription service", "A seaport in Vive", "A type of transport", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Tilt Brush'?", "options": ["Google's VR painting application that lets users paint in 3D space", "A types of cleaning tool", "A car part", "None"], "correct": 0},
        {"id": 52, "question": "What is 'VREducation' used for primarily?", "options": ["Teaching subjects like history, science, and medical surgery in virtual worlds", "Playing video games", "Social media browsing", "None"], "correct": 0},
        {"id": 53, "question": "What's the meaning of 'Photogrammetry' in VR design?", "options": ["Creating 3D models from numerous 2D photographs of real-world objects", "A type of photography", "A study of plants", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Presence' in VR?", "options": ["The subjective psychological state of being in a virtual environment", "A gift given to someone", "Being in a classroom", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Proprioception' in VR design consideration?", "options": ["The body's ability to sense its own position and movement", "A memory test", "A type of medicine", "None"], "correct": 0},
        {"id": 56, "question": "What is 'Vestibular system'?", "options": ["Part of the inner ear that influences balance and spatial orientation", "A respiratory organ", "A computer system", "None"], "correct": 0},
        {"id": 57, "question": "What is a 'VR Treadmill'?", "options": ["Device for infinite walking in virtual space while remaining physically stationary", "A standard gym treadmill", "A mobile app", "None"], "correct": 0},
        {"id": 58, "question": "What is 'Hand Tracking' without controllers?", "options": ["Using computer vision to detect and track finger movements as inputs", "Holding a controller", "A type of sport", "None"], "correct": 0},
        {"id": 59, "question": "What is 'Steam Deck''s relationship with VR?", "options": ["While not for VR, it's Valve's handheld console from the same ecosystem", "It is the best VR headset", "It has no relation", "None"], "correct": 0},
        {"id": 60, "question": "What is 'Oculus Go'?", "options": ["A discontinued lightweight standalone VR headset focused on media viewing", "A types of shoes", "A sports car", "None"], "correct": 0},
        {"id": 61, "question": "What is 'Minecraft VR'?", "options": ["Popular block-building game adapted for immersive 3D VR environment", "A movie about mining", "A types of math", "None"], "correct": 0},
        {"id": 62, "question": "What is 'Rec Room' in VR?", "options": ["Social VR experience where players create and play mini-games together", "A room for cleaning", "A hospital ward", "None"], "correct": 0},
        {"id": 63, "question": "What is the 'Blue-Light Filter' in VR used for?", "options": ["Reducing eye strain and improving sleep quality during prolonged use", "Filtering water", "Changing the screen to blue", "None"], "correct": 0},
        {"id": 64, "question": "What is 'Varifocal' display?", "options": ["Future VR tech that dynamically adjusts focus based on eye tracking", "A types of camera lens only", "A blurry screen", "None"], "correct": 0},
        {"id": 65, "question": "What is 'Haptic Suit' (e.g. Teslasuit)?", "options": ["A full-body wearable delivering physical sensations for deep VR immersion", "A types of dress", "A diving suit", "None"], "correct": 0},
        {"id": 66, "question": "What is 'Spatial Computing'?", "options": ["General term for human interaction with computers in a 3D environment", "Counting stars", "A type of cloud", "None"], "correct": 0},
        {"id": 67, "question": "What is the 'Resolution' of a VR headset?", "options": ["The total number of pixels on the screen (e.g. 1832x1920 per eye)", "The speed of the processor", "The weight of the device", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Screen Latency'?", "options": ["The time it takes for pixels to change color on the screen", "The speed of the internet", "The time to turn on a TV", "None"], "correct": 0},
        {"id": 69, "question": "What is 'FOV' in AR context?", "options": ["The area where digital information can be projected onto the real world", "The size of a laptop", "The speed of light", "None"], "correct": 0},
        {"id": 70, "question": "What is 'VR Archery'?", "options": ["Simulating bow and arrow shooting with hand-tracked controllers", "A type of real sport", "A decorative design", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Sim Racing' in VR?", "options": ["Highly realistic automobile racing simulations played in VR headsets", "Racing with horses", "A types of game only", "None"], "correct": 0},
        {"id": 72, "question": "What is 'Flight Simulation' in VR?", "options": ["Immersive experience of piloting aircraft in various conditions", "Flying a drone", "A types of math", "None"], "correct": 0},
        {"id": 73, "question": "What's the meaning of 'Sweet Spot' in lenses?", "options": ["The small area in the lens center where the image is perfectly clear", "A types of candy", "A location on a map", "None"], "correct": 0},
        {"id": 74, "question": "What is 'VR Comfort Settings'?", "options": ["Options like vignetting to reduce motion sickness during movement", "Adjusting the seat", "Adjusting the volume", "None"], "correct": 0},
        {"id": 75, "question": "What is 'Godot' for VR?", "options": ["An open-source game engine that supports VR/AR development", "A play title", "A computer language", "None"], "correct": 0},
        {"id": 76, "question": "What is 'WebXR Device API'?", "options": ["Software interface for web browsers to access VR/AR hardware features", "A type of website", "A secure query log", "None"], "correct": 0},
        {"id": 77, "question": "What's 'OpenXR'?", "options": ["An open, royalty-free standard for high-performance access to VR and AR", "A types of internet browser", "A game company", "None"], "correct": 0},
        {"id": 78, "question": "What is 'Inside-out' vs 'Outside-in' tracking for VR?", "options": ["On-headset sensors vs external sensors positioned around a room", "They are identical", "None", "None"], "correct": 0},
        {"id": 79, "question": "What's 'Pancake Lenses'?", "options": ["New thinner, flatter VR lenses allowing for more compact headset designs", "Lenses made for cooking", "A types of food", "None"], "correct": 0},
        {"id": 80, "question": "Why is VR a growing industry for training and therapy?", "options": ["Safe, repeatable, and realistic environments for practice without risk", "It's cheap to buy", "Neither", "Both"], "correct": 0},
        {"id": 81, "question": "What is '6DOF' vs '3DOF' tracking?", "options": ["6 degrees of freedom vs 3 degrees (more natural movement)", "They are the same", "None", "None"], "correct": 0},
        {"id": 82, "question": "What is 'Eye Tracking' in VR?", "options": ["Following gaze to control interfaces", "Tracking eye movement", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Hand Tracking'?", "options": ["Following hand position for interaction", "Tracking hand movement", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Haptic Feedback'?", "options": ["Vibration and touch responses in VR controllers", "Sound feedback", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Room-Scale' VR?", "options": ["VR that tracks physical room movement", "VR room size", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'Spatial Audio'?", "options": ["3D positional sound in VR environments", "Audio in space", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'VR Sickness'?", "options": ["Motion sickness from VR headset use", "Being sick in VR", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Passthrough' VR?", "options": ["See-through view of real world through headset", "Passing through VR", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'Foveated Rendering'?", "options": ["High-detail rendering where user looks", "Focused rendering", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'Mixed Reality' (MR)?", "options": ["Combining VR/AR with real world view", "Mixed reality", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Cloud Rendering'?", "options": ["Processing VR graphics in the cloud", "VR in clouds", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'WebXR'?", "options": ["Web standard for VR/AR experiences", "A type of website", "A secure query log", "None"], "correct": 0},
        {"id": 93, "question": "What is 'Light Field Display'?", "options": ["Technology projecting images directly to eyes", "Light field display", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Varifocal'?", "options": ["Adjustable focus lenses in VR headsets", "Variable focus", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Inside-Out' vs 'Outside-In' tracking?", "options": ["On-headset sensors vs external sensors positioned around a room", "They are identical", "None", "None"], "correct": 0},
        {"id": 96, "question": "What is 'Haptic Feedback'?", "options": ["Vibration and touch responses in VR controllers", "Sound feedback", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Room-Scale' VR?", "options": ["VR that tracks physical room movement", "VR room size", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Spatial Audio'?", "options": ["3D positional sound in VR environments", "Audio in space", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'VR Sickness'?", "options": ["Motion sickness from VR headset use", "Being sick in VR", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'Passthrough' VR?", "options": ["See-through view of real world through headset", "Passing through VR", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
