import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_web3_api(request):
    questions_pool = [
        {"id": 1, "question": "What is 'Web3'?", "options": ["A version of the web with fast internet", "A decentralized web powered by blockchain and community ownership", "A type of browser", "None"], "correct": 1},
        {"id": 2, "question": "What is the primary difference between Web2 and Web3?", "options": ["Web2 is centralized (controlled by few companies); Web3 is decentralized", "Web3 is only for crypto", "Web2 is for mobile apps; Web3 is for desktops", "None"], "correct": 0},
        {"id": 3, "question": "What is a 'Wallet' in Web3?", "options": ["A leather card holder", "Software or hardware that stores a user's private keys and interacts with dApps", "A security feature", "None"], "correct": 1},
        {"id": 4, "question": "What is 'Metamask' used for in Web3?", "options": ["A cryptocurrency developer", "A browser extension and wallet for interacting with the Ethereum ecosystem", "A type of robot", "None"], "correct": 1},
        {"id": 5, "question": "What is a 'dApp'?", "options": ["A desktop app", "A decentralized application that runs on a peer-to-peer network like a blockchain", "A mobile app", "None"], "correct": 1},
        {"id": 6, "question": "What is 'Smart Contract'?", "options": ["A physical contract", "Self-executing code that automatically carries out agreements on a blockchain", "A type of table", "None"], "correct": 1},
        {"id": 7, "question": "What is 'Decentralization'?", "options": ["Splitting a company", "Distributing control and data across a network instead of a single entity", "Deleting code", "None"], "correct": 1},
        {"id": 8, "question": "What is 'Web3.js' or 'Ethers.js'?", "options": ["A website builder", "JavaScript libraries that allow frontend apps to communicate with Ethereum", "A design tool", "None"], "correct": 1},
        {"id": 9, "question": "What is an 'NFT' (Non-Fungible Token) in Web3?", "options": ["A type of coin", "Unique digital asset stored on a blockchain that represents ownership of an item", "A type of chart", "None"], "correct": 1},
        {"id": 10, "question": "What is 'IPFS'?", "options": ["Integrated Power File System", "InterPlanetary File System (a peer-to-peer protocol for decentralized storage)", "A type of browser", "None"], "correct": 1},
        {"id": 11, "question": "What is 'DAO' in Web3 context?", "options": ["Decentralized Autonomous Organization (community-led group ruled by smart contracts)", "A type of database", "Digital Access Online", "None"], "correct": 0},
        {"id": 12, "question": "What is 'Metaverse'?", "options": ["A space ship", "A collective virtual shared space where people interact in digital reality", "A type of movie", "None"], "correct": 1},
        {"id": 13, "question": "What is 'Bridging' in Web3?", "options": ["Building a bridge in a game", "Connecting two different blockchains to allow data and asset transfer", "A technical manual", "None"], "correct": 1},
        {"id": 14, "question": "What is 'Staking'?", "options": ["Locked assets in a contract to support a network and earn rewards", "Spending crypto for fun", "A type of gambling", "None"], "correct": 0},
        {"id": 15, "question": "What is 'Gas' in Web3?", "options": ["A type of fuel", "Fees required to process transactions and execute smart contracts on blockchain", "An internet speed", "None"], "correct": 1},
        {"id": 16, "question": "What is 'DeFi'?", "options": ["Decentralized Finance (financial tools like lending and trading on blockchain)", "Digital Finance", "Design of files", "None"], "correct": 0},
        {"id": 17, "question": "What is the result of 'Mining' or 'Validation'?", "options": ["Securing the blockchain and adding new blocks by processing data", "Creating a new website", "None of the above", "None"], "correct": 0},
        {"id": 18, "question": "What's the meaning of 'Self-sovereign Identity'?", "options": ["A user's identity name", "The concept that individuals have full ownership and control over their own digital identities", "A security card", "None"], "correct": 1},
        {"id": 19, "question": "What is 'Web3 Developer' primarily focused on?", "options": ["Writing raw C code", "Developing dApps, smart contracts, and decentralized systems", "A security log", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Moralis' / 'Alchemy'?", "options": ["A type of crypto project", "Platforms providing Web3 infrastructure and backend and tools for developers", "None of the above", "None"], "correct": 1},
        {"id": 21, "question": "What's 'ENS' (Ethereum Name Service)?", "options": ["A decentralized naming system for Ethereum addresses (e.g. name.eth)", "A type of internet speed", "A technical manual", "None"], "correct": 0},
        {"id": 22, "question": "What is 'Play-to-Earn' (P2E) in Web3 gaming?", "options": ["Paying for games to win", "Games where players earn real-world value (NFTs, crypto) as rewards", "None of the above", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Governance Token'?", "options": ["A token for money", "A type of token that gives owners voting power in a DAO", "A security token", "None"], "correct": 1},
        {"id": 24, "question": "What is 'Permissionless' in Web3?", "options": ["Anyone can join and use the network without needing approval from an authority", "Everyone has a password", "A tech spec", "None"], "correct": 0},
        {"id": 25, "question": "What is 'Blockchain Interoperability'?", "options": ["Connecting two different blockchains for communication", "Using two internet providers", "A design tool", "None"], "correct": 0},
        {"id": 26, "question": "What is 'HODL' in Web3 slang?", "options": ["Holding on for dear life (not selling crypto assets)", "Buying crypto randomly", "A type of game", "None"], "correct": 0},
        {"id": 27, "question": "What is 'Whale' in Web3 slang?", "options": ["A large sea animal", "An individual or entity holding a massive amount of specific cryptocurrency", "A type of server", "None"], "correct": 1},
        {"id": 28, "question": "What is 'Liquidity Pool'?", "options": ["A pool of water", "A collection of funds locked in a smart contract for trading and lending", "A technical specification", "None"], "correct": 1},
        {"id": 29, "question": "What's the meaning of 'Decentralized Exchange' (DEX)?", "options": ["A stock exchange", "A crypto exchange where users trade directly without an intermediary (e.g. Uniswap)", "A type of database", "None"], "correct": 1},
        {"id": 30, "question": "What is 'Hard Fork'?", "options": ["A physical tool for eating", "A major software update that is not backwards-compatible with older versions", "None of the above", "None"], "correct": 1},
        {"id": 31, "question": "What is a 'Cold Wallet'?", "options": ["A wallet stored offline, like on paper or a USB device, for maximum security", "A frozen wallet", "A type of bank account", "None"], "correct": 0},
        {"id": 32, "question": "What is a 'Hot Wallet'?", "options": ["A wallet connected to the internet, allowing for quick transactions", "A stolen wallet", "A wallet with high temperature", "None"], "correct": 0},
        {"id": 33, "question": "What is 'Layer 2' (L2) in blockchain?", "options": ["A secondary blockchain built on top of Layer 1 to improve scalability", "The second block in a chain", "A type of backup", "None"], "correct": 0},
        {"id": 34, "question": "What is 'Polygon' (MATIC) in Web3?", "options": ["A Layer 2 scaling solution for Ethereum", "A geometrical shape", "A video game character", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Solana' known for?", "options": ["High throughput and low transaction costs using Proof of History", "Being the first blockchain", "Slow performance", "None"], "correct": 0},
        {"id": 36, "question": "What is 'Sushiswap'?", "options": ["A decentralized exchange (DEX) and automated market maker (AMM)", "A food delivery app", "A type of game", "None"], "correct": 0},
        {"id": 37, "question": "What is 'Web3 Foundation'?", "options": ["An organization nurturing technologies for a decentralized web (creators of Polkadot)", "A makeup brand", "A construction company", "None"], "correct": 0},
        {"id": 38, "question": "What is 'Oracle' in blockchain?", "options": ["A service that provides real-world data to smart contracts", "A Greek myth", "A database company only", "None"], "correct": 0},
        {"id": 39, "question": "What is 'Chainlink'?", "options": ["A decentralized oracle network providing data to smart contracts", "A heavy chain", "A type of jewelry", "None"], "correct": 0},
        {"id": 40, "question": "What is 'Yield Farming'?", "options": ["Earning rewards by providing liquidity to DeFi protocols", "Growing vegetables", "A type of investment in stocks", "None"], "correct": 0},
        {"id": 41, "question": "What is 'Total Value Locked' (TVL)?", "options": ["The total amount of assets currently being held in a specific DeFi protocol", "A locked chest", "Total security cost", "None"], "correct": 0},
        {"id": 42, "question": "What is 'Stablecoin'?", "options": ["A cryptocurrency designed to have a stable value, pinned to a fiat currency", "A coin that doesn't move", "A new type of gold", "None"], "correct": 0},
        {"id": 43, "question": "What is 'USDC' or 'USDT'?", "options": ["Popular stablecoins pegged 1:1 with the US Dollar", "US government tokens", "A type of computer code", "None"], "correct": 0},
        {"id": 44, "question": "What is 'Aave'?", "options": ["A decentralized lending and borrowing protocol", "A greeting in another language", "A type of cloud", "None"], "correct": 0},
        {"id": 45, "question": "What is 'Compound' protocol?", "options": ["A DeFi protocol for algorithmic interest rate markets", "A chemical mixture", "A type of complex number", "None"], "correct": 0},
        {"id": 46, "question": "What is 'Impermanent Loss'?", "options": ["A temporary loss of funds when providing liquidity due to price changes", "Losing a key temporarily", "A small mistake in code", "None"], "correct": 0},
        {"id": 47, "question": "What is 'Airdrop' in crypto?", "options": ["Distribution of a cryptocurrency token or coin, for free, to numerous wallet addresses", "Dropping a phone from a plane", "A cloud storage feature", "None"], "correct": 0},
        {"id": 48, "question": "What is 'Mainnet'?", "options": ["The primary blockchain where actual transactions take place using real value", "A testing network", "A home internet name", "None"], "correct": 0},
        {"id": 49, "question": "What is 'Testnet' (e.g. Goerli, Sepolia)?", "options": ["Alternative blockchains for testing without using real-money assets", "A fast internet", "A type of web server", "None"], "correct": 0},
        {"id": 50, "question": "What is 'Faucet' in Web3 development?", "options": ["A service that provides free testnet tokens for development and testing", "A water tap", "A type of hardware wallet", "None"], "correct": 0},
        {"id": 51, "question": "What is 'Web3.py'?", "options": ["A Python library for interacting with Ethereum", "A web design tool", "A new search engine", "None"], "correct": 0},
        {"id": 52, "question": "What is 'Solidity'?", "options": ["Object-oriented programming language for writing smart contracts", "A physical state", "A type of security firm", "None"], "correct": 0},
        {"id": 53, "question": "What is 'OpenZeppelin'?", "options": ["A library of secure and community-vetted smart contract templates", "A heavy metal band", "A type of airship", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Hardhat'?", "options": ["A development environment for Ethereum software", "A protective gear", "A type of database", "None"], "correct": 0},
        {"id": 55, "question": "What is 'Foundry' in Web3?", "options": ["A fast toolkit for Ethereum application development written in Rust", "A factory for metal", "A type of font", "None"], "correct": 0},
        {"id": 56, "question": "What is 'Truffle'?", "options": ["A development framework for Ethereum (one of the oldest)", "A chocolate sweet", "A type of mushroom", "None"], "correct": 0},
        {"id": 57, "question": "What is 'Ganache'?", "options": ["A personal blockchain for Ethereum development for testing", "A cake topping", "A type of fabric", "None"], "correct": 0},
        {"id": 58, "question": "What is 'Rug Pull' in Web3?", "options": ["A malicious maneuver where developers abandon a project and run with funds", "Pulling a carpet", "A type of cleaning service", "None"], "correct": 0},
        {"id": 59, "question": "What is 'Slippage' in trading?", "options": ["Difference between expected price and the price when the trade is executed", "Falling on ice", "A coding error", "None"], "correct": 0},
        {"id": 60, "question": "What is 'Minting' an NFT?", "options": ["Process of publishing a unique token on a blockchain to make it buyable", "Making a mint chocolate", "Printing money only", "None"], "correct": 0},
        {"id": 61, "question": "What is 'Burning' a token?", "options": ["Permanently removing a token from circulation by sending it to a zero address", "Setting fire to paper", "A fast transaction", "None"], "correct": 0},
        {"id": 62, "question": "What is 'Web3 Bridge'?", "options": ["A tool to transfer assets between different blockchain networks", "A dental tool", "A types of router", "None"], "correct": 0},
        {"id": 63, "question": "What is 'Arbitrum'?", "options": ["A Layer 2 optimistic rollup for Ethereum scaling", "A type of court", "A video game", "None"], "correct": 0},
        {"id": 64, "question": "What is 'Optimism' in blockchain?", "options": ["A Layer 2 scaling solution using optimistic rollups", "A positive mindset", "A type of cloud", "None"], "correct": 0},
        {"id": 65, "question": "What is 'Zk-Rollup'?", "options": ["Zero-knowledge rollup for high scalability and security", "A type of exercise", "A snack", "None"], "correct": 0},
        {"id": 66, "question": "What is 'Proof of Stake' (PoS)?", "options": ["Consensus mechanism where validators are chosen based on held tokens", "A bet on a horse", "A physical test", "None"], "correct": 0},
        {"id": 67, "question": "What is 'Proof of Work' (PoW)?", "options": ["Consensus mechanism requiring computational power to mine blocks", "A job interview", "A written exam", "None"], "correct": 0},
        {"id": 68, "question": "What is 'Whitepaper'?", "options": ["Document explaining the tech and purpose of a new crypto project", "A blank piece of paper", "A government law", "None"], "correct": 0},
        {"id": 69, "question": "What is 'Litepaper'?", "options": ["A shorter, simplified version of a whitepaper", "A very thin paper", "A digital book", "None"], "correct": 0},
        {"id": 70, "question": "What is 'Tokenomics'?", "options": ["The economics and distribution model of a cryptocurrency token", "The study of coins only", "A type of math", "None"], "correct": 0},
        {"id": 71, "question": "What is 'Seed Phrase'?", "options": ["A series of words that act as a master key to your crypto wallet", "A phrase used in gardening", "A catchy slogan", "None"], "correct": 0},
        {"id": 72, "question": "What is 'Private Key'?", "options": ["A secret code that allows you to access and spend your crypto", "A key for your house", "A password for your email only", "None"], "correct": 0},
        {"id": 73, "question": "What is 'Public Key'?", "options": ["A code used to receive crypto, like an email address for your wallet", "A key given to everyone", "A social media bio", "None"], "correct": 0},
        {"id": 74, "question": "What is 'The Merge' in Ethereum history?", "options": ["The transition from Proof of Work to Proof of Stake", "Merging two companies", "A road intersection", "None"], "correct": 0},
        {"id": 75, "question": "What is 'Gwei'?", "options": ["A small unit of Ether used for gas fees (1 Gwei = 10^-9 ETH)", "A type of tea", "A cryptocurrency name", "None"], "correct": 0},
        {"id": 76, "question": "What is 'Faucet'?", "options": ["A tool to get free testnet ETH", "A kitchen tap", "A fast miner", "None"], "correct": 0},
        {"id": 77, "question": "What is 'Etherscan'?", "options": ["A blockchain explorer for the Ethereum network", "A medical scanner", "A search engine for files only", "None"], "correct": 0},
        {"id": 78, "question": "What is 'Snapshot' in DAOs?", "options": ["An off-chain voting platform used by many crypto projects", "A quick photo", "A type of backup", "None"], "correct": 0},
        {"id": 79, "question": "What is 'Social Token'?", "options": ["A cryptocurrency based on an individual or community's reputation", "A like on Facebook", "A credit for games", "None"], "correct": 0},
        {"id": 80, "question": "What is 'Phishing' in Web3?", "options": ["Scam to steal seed phrases or private keys through fake websites", "Catching fish", "A type of sport", "None"], "correct": 0},
        {"id": 81, "question": "What is 'Smart Contract Wallet'?", "options": ["Application for managing crypto assets and interacting with dApps", "A wallet for smart contracts", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Hardware Wallet'?", "options": ["Physical device for storing crypto keys offline", "A wallet made of hardware", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'Paper Wallet'?", "options": ["Physical document containing private keys", "A wallet made of paper", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Cold Storage'?", "options": ["Offline storage not connected to internet", "Storage in cold place", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'Hot Storage'?", "options": ["Online storage connected to internet", "Storage in hot place", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'MetaMask'?", "options": ["Browser extension for Ethereum wallet access", "A mask for metamaterials", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'Trust Wallet'?", "options": ["Wallet requiring multiple signatures for transactions", "A trustworthy wallet", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'Multi-sig Wallet'?", "options": ["Wallet requiring multiple parties to sign transactions", "A wallet with many signatures", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'DEX' (Decentralized Exchange)?", "options": ["Peer-to-peer crypto trading platform", "A stock exchange", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'CEX' (Centralized Exchange)?", "options": ["Traditional crypto exchange with central authority", "A centralized exchange", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'Liquidity Pool'?", "options": ["Collection of funds for trading in DeFi", "A pool of liquid assets", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Yield Farming'?", "options": ["Earning rewards by providing liquidity", "Farming crops for yield", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Staking'?", "options": ["Locking crypto to support network security", "Planting stakes", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'Gas' in Ethereum?", "options": ["Fee for computational operations", "Fuel for transactions", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'Block Explorer'?", "options": ["Tool for viewing blockchain transactions", "A block explorer", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Oracle' in blockchain?", "options": ["Service providing external data to smart contracts", "A fortune teller", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Layer 2' Solution?", "options": ["Scaling solution built on Ethereum", "Second layer of blockchain", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'Sidechain'?", "options": ["Separate blockchain connected to main chain", "A chain on the side", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'Bridge' in crypto?", "options": ["Protocol connecting different blockchains", "A physical bridge", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'NFT Marketplace'?", "options": ["Platform for trading non-fungible tokens", "A market for NFTs", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
