import random
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response

@api_view(['GET'])
@permission_classes([AllowAny])
def playground_questions_webapis_api(request):
    questions_pool = [
        {"id": 1, "question": "What does API stand for?", "options": ["Application Programming Interface", "Advanced Program Install", "Access Parallel Interface", "None"], "correct": 0},
        {"id": 2, "question": "What is the primary purpose of a Web API?", "options": ["Creating graphics", "Allowing software systems to communicate over HTTP", "Managing desk space", "None"], "correct": 1},
        {"id": 3, "question": "What is 'REST' (Representational State Transfer)?", "options": ["A way to sleep", "An architectural style for designing networked applications over HTTP", "A type of chart", "None"], "correct": 1},
        {"id": 4, "question": "What is 'SOAP' in Web Services context?", "options": ["A cleaning product", "Simple Object Access Protocol (a protocol for exchanging structured information)", "None", "None"], "correct": 1},
        {"id": 5, "question": "What is 'JSON'?", "options": ["JavaScript Object Notation (a lightweight data format)", "Java Standard Object Network", "None", "None"], "correct": 0},
        {"id": 6, "question": "What is 'XML'?", "options": ["A video format", "eXtensible Markup Language (a common data format for APIs)", "Neither", "Both"], "correct": 1},
        {"id": 7, "question": "What is an 'Endpoint' in a Web API?", "options": ["The end of a program", "A specific URL where a service can be accessed", "A button", "None"], "correct": 1},
        {"id": 8, "question": "What's the difference between GET and POST?", "options": ["GET retrieves data; POST sends new data to create/update", "POST is only for files", "Both", "None"], "correct": 0},
        {"id": 9, "question": "What is the 'PUT' method used for?", "options": ["Deleting a record", "Updating (replacing) an existing resource completely", "None", "None"], "correct": 1},
        {"id": 10, "question": "What is the 'PATCH' method used for?", "options": ["A quick fix", "Partially updating an existing resource", "A security log", "None"], "correct": 1},
        {"id": 11, "question": "What is the 'DELETE' method used for?", "options": ["Removing a resource", "Creating a new record", "A type of chart", "None"], "correct": 0},
        {"id": 12, "question": "What does a '200 OK' status code mean?", "options": ["Error", "The request was successful", "Authentication failed", "None"], "correct": 1},
        {"id": 13, "question": "What does a '404 Not Found' status code mean?", "options": ["A server error", "The requested resource could not be found on the server", "None", "None"], "correct": 1},
        {"id": 14, "question": "What does a '500 Internal Server Error' mean?", "options": ["Everything is fine", "An unexpected error occurred on the server", "A type of table", "None"], "correct": 1},
        {"id": 15, "question": "What is 'Authentication' for API?", "options": ["Wiping physical server", "Verifying the identity of the user/client making a request", "Both", "None"], "correct": 1},
        {"id": 16, "question": "What is 'Authorization' for API?", "options": ["Verifying permissions to perform a specific action on a resource", "A list of files", "None", "None"], "correct": 0},
        {"id": 17, "question": "What is 'API Key'?", "options": ["A physical key for the office", "A unique identifier used to authenticate and throttle API callers", "Both", "None"], "correct": 1},
        {"id": 18, "question": "What is 'OAuth 2.0'?", "options": ["A social media site", "A widely used authorization framework allowing apps to access data on behalf of users", "None", "None"], "correct": 1},
        {"id": 19, "question": "What is 'JWT' (JSON Web Token)?", "options": ["A type of coin", "A compact, self-contained way to securely transmit information as JSON", "A decorative text", "None"], "correct": 1},
        {"id": 20, "question": "What is 'Rate Limiting'?", "options": ["Fast internet speed", "Restricting the number of requests a client can make in a given timeframe", "A secure log", "None"], "correct": 1},
        {"id": 21, "question": "What is 'API Documentation'?", "options": ["A legal document", "Instructions on how to use the API (endpoints, params, responses)", "Neither", "Both"], "correct": 1},
        {"id": 22, "question": "What is 'Swagger' / 'OpenAPI'?", "options": ["A clothing brand", "Standard tools for designing, building, and documenting RESTful APIs", "Both", "None"], "correct": 1},
        {"id": 23, "question": "What is 'Postman' commonly used for?", "options": ["Sending physical mail", "Testing and developing APIs by sending various requests and analyzing responses", "None", "None"], "correct": 1},
        {"id": 24, "question": "What is 'GraphQL'?", "options": ["A graph drawing tool", "A query language for APIs that allows clients to request exactly the data they need", "Both", "None"], "correct": 1},
        {"id": 25, "question": "What is 'Microservices Architecture'?", "options": ["Building apps with small, independent, communicate-via-API components", "A very small computer", "Neither", "Both"], "correct": 0},
        {"id": 26, "question": "What is 'Idempotency' in APIs?", "options": ["Making a request multiple times has the same result as making it once (e.g. GET)", "Generating a new key Every time", "None", "None"], "correct": 0},
        {"id": 27, "question": "What is 'Statelessness' factor in REST?", "options": ["No user can join", "The server doesn't store client session info between requests", "None", "None"], "correct": 1},
        {"id": 28, "question": "What is 'CORS' (Cross-Origin Resource Sharing)?", "options": ["A browser security feature allowing selective access across domains", "An internet protocol", "Neither", "Both"], "correct": 0},
        {"id": 29, "question": "What is 'HATEOAS'?", "options": ["Hypermedia as the Engine of Application State", "A type of table", "Designing icons", "None"], "correct": 0},
        {"id": 30, "question": "Which of these is a typical HTTP Header?", "options": ["Content-Type", "Authorization", "User-Agent", "All of the above"], "correct": 3},
        # Adding 50 more questions...
        {"id": 31, "question": "What is @api_view decorator in Django Rest Framework (DRF)?", "options": ["Used for UI", "Ensures a function handles HTTP requests correctly in DRF", "Both", "None"], "correct": 1},
        {"id": 32, "question": "What is '@RestController' in Spring Boot for Web API?", "options": ["A combining annotation for @Controller and @ResponseBody", "A food service", "None", "None"], "correct": 0},
        {"id": 33, "question": "What is the purpose of 'API Versioning'?", "options": ["Changing numbers for fun", "Allowing system evolution without breaking existing client integrations", "Neither", "Both"], "correct": 1},
        {"id": 34, "question": "Which format is more human-readable between JSON and XML?", "options": ["JSON", "XML", "They are identical", "None"], "correct": 0},
        {"id": 35, "question": "What is 'Webhook' in API context?", "options": ["Triggering an action in another system automatically when an event occurs in yours", "Getting mail", "None", "None"], "correct": 0},
        {"id": 36, "question": "What is the status code for 'Created' successfully?", "options": ["201", "200", "204", "202"], "correct": 0},
        {"id": 37, "question": "What does status code '204 No Content' mean?", "options": ["Request failed", "Request succeeded but has no body for the response", "Neither", "Both"], "correct": 1},
        {"id": 38, "question": "What is status code '401 Unauthorized'?", "options": ["Access denied due to missing or invalid authentication", "Forbidden action", "Both", "None"], "correct": 0},
        {"id": 39, "question": "What is status code '403 Forbidden'?", "options": ["Authenticated but lacks permissions for the resource", "Missing login", "None", "None"], "correct": 0},
        {"id": 40, "question": "What is status code '400 Bad Request'?", "options": ["The server could not understand the request due to invalid syntax", "Authentication failed", "A server error", "None"], "correct": 0},
        {"id": 41, "question": "What is 'gRPC'?", "options": ["High-performance RPC framework by Google using Protocol Buffers", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 42, "question": "What is 'Protocol Buffers' (Protobuf)?", "options": ["Binary serialization format used by gRPC", "Designing data", "Both", "None"], "correct": 0},
        {"id": 43, "question": "What is 'API Gateway' architecture?", "options": ["A tool for servers", "A single entry point for all API requests which then routes to microservices", "Neither", "Both"], "correct": 1},
        {"id": 44, "question": "What is 'Serverless API'?", "options": ["API without a server", "An API where infrastructure is managed by cloud provider (like Lambda)", "Neither", "Both"], "correct": 1},
        {"id": 45, "question": "What is 'Reverse Proxy' (e.g. Nginx)?", "options": ["Taking a picture", "A server that sits in front of backend servers and forwards requests to them", "None", "None"], "correct": 1},
        {"id": 46, "question": "What is 'Load Balancer' role in API delivery?", "options": ["Balancing furniture", "Distributing incoming API traffic across multiple backend servers", "Both", "None"], "correct": 1},
        {"id": 47, "question": "Which of these is a popular API testing tool besides Postman?", "options": ["Insomnia", "Apigee", "SoapUI", "All of the above"], "correct": 3},
        {"id": 48, "question": "What is 'BSON'?", "options": ["Binary JSON (used by MongoDB)", "Basic SQL Object Notation", "A type of table", "None"], "correct": 0},
        {"id": 49, "question": "What is 'CURL' in command line context?", "options": ["Used to send data to/from a server via various protocols", "A decorative text", "Neither", "Both"], "correct": 0},
        {"id": 50, "question": "What is 'API Mocking'?", "options": ["Making fun of an API", "Creating a simulated version of an API for testing/development", "Both", "None"], "correct": 1},
        {"id": 51, "question": "What is 'Payload' of an API request?", "options": ["The data actually sent in the body of the request (e.g. JSON data)", "The cost of request", "None", "None"], "correct": 0},
        {"id": 52, "question": "What is the result of 'Gzip Compression' for APIs?", "options": ["Reducing payload size to speed up data transfer", "A password manager", "Neither", "Both"], "correct": 0},
        {"id": 53, "question": "What is 'Query String' context?", "options": ["A key-value pair after a '?' in a URL for data filtering/passing", "A type of chart", "Both", "None"], "correct": 0},
        {"id": 54, "question": "What is 'Matrix Parameter' (e.g. /users;id=1)?", "options": ["Rare way to pass parameters tied to path segments", "Drawing a matrix", "Neither", "Both"], "correct": 0},
        {"id": 55, "question": "What is 'Richardson Maturity Model' used to measure?", "options": ["The maturity and quality of a RESTful API implementation", "Developer's age", "Both", "None"], "correct": 0},
        {"id": 56, "question": "What is 'Level 0' in Richardson model?", "options": ["Using one URI and one HTTP method for everything (The Swamp of POX)", "Fully RESTful", "Neither", "Both"], "correct": 0},
        {"id": 57, "question": "What is 'Level 1' (Resources) in Richardson model?", "options": ["Introducing multiple URIs for different entities", "Same as level 0", "None of the above", "None"], "correct": 0},
        {"id": 58, "question": "What is 'Level 2' (HTTP Verbs) in Richardson model?", "options": ["Using multiple URIs AND correct HTTP verbs (GET, POST, etc.)", "Mapping files", "None", "None"], "correct": 0},
        {"id": 59, "question": "What is 'Level 3' (HATEOAS) in Richardson model?", "options": ["The most mature level introducing hypermedia links for state navigation", "Designing icons", "Both", "None"], "correct": 0},
        {"id": 60, "question": "What's the meaning of 'Uniform Interface' in REST?", "options": ["Making all buttons same color", "A standardized way to interact with resources (e.g. using URIs, HTTP methods)", "None", "None"], "correct": 1},
        {"id": 61, "question": "What is 'Semantic Versioning' (SemVer)?", "options": ["Major.Minor.Patch versioning system to track API changes", "A type of table", "Neither", "Both"], "correct": 0},
        {"id": 62, "question": "What is 'Breaking Change' in an API context?", "options": ["Breaking a computer", "A change that's not backward-compatible with existing client code", "Neither", "Both"], "correct": 1},
        {"id": 63, "question": "Which header is used for client-server language negotiation?", "options": ["Accept-Language", "User-Agent", "Language-Code", "None"], "correct": 0},
        {"id": 64, "question": "Which header identifies the client's software (browser or tool)?", "options": ["User-Agent", "Referer", "Host", "None"], "correct": 0},
        {"id": 65, "question": "What is status code '429 Too Many Requests' linked to?", "options": ["Rate limiting / Quotas", "Authentication failure", "Server crash", "None"], "correct": 0},
        {"id": 66, "question": "What is status code '503 Service Unavailable'?", "options": ["Server is temporarily unable to handle request (e.g. maintenance, overload)", "Bad login", "Neither", "Both"], "correct": 0},
        {"id": 67, "question": "Which of these is a design-first API approach benefit?", "options": ["Better collaboration", "Consistent design before code", "Parallel development", "All of the above"], "correct": 3},
        {"id": 68, "question": "What is 'API Throttling'?", "options": ["A speed limit for people", "Restricting the speed or number of calls based on priority/capacity", "None", "None"], "correct": 1},
        {"id": 69, "question": "What's 'WebSockets' compared to HTTP REST?", "options": ["Full-duplex, real-time communication channel over a single TCP connection", "Same", "Neither", "Both"], "correct": 0},
        {"id": 70, "question": "What is 'SSE' (Server-Sent Events)?", "options": ["A one-way push of events from server to client over HTTP", "Downloading files", "Neither", "Both"], "correct": 0},
        {"id": 71, "question": "What is 'Long Polling' in API communication?", "options": ["A technique where server holds a request open until new data is available", "Asking users questions", "Both", "None"], "correct": 0},
        {"id": 72, "question": "Can APIs return formats other than JSON or XML?", "options": ["Yes, e.g. text, html, images, pdf", "No", "Only for special browsers", "None"], "correct": 0},
        {"id": 73, "question": "What's 'Binary API'?", "options": ["API for 0s and 1s", "An API that communicates using binary data instead of text (like ProtoBuf)", "Neither", "Both"], "correct": 1},
        {"id": 74, "question": "What is 'Resource Collection' versus 'Resource Instance'?", "options": ["Group of users vs A single user (e.g. /users vs /users/1)", "Same", "Neither", "Both"], "correct": 0},
        {"id": 75, "question": "What is 'Query Language' attribute for APIs (e.g. ?sort=name)?", "options": ["A specific grammar for filtering/sorting resources", "Calculating results", "None", "None"], "correct": 0},
        {"id": 76, "question": "What is 'Base Path' for an API?", "options": ["The initial segment of the URL (e.g. /api/v1/)", "The help center home", "Neither", "Both"], "correct": 0},
        {"id": 77, "question": "What is 'Stateless' in terms of scalability?", "options": ["Makes horizontal scaling easier because any server can handle any request", "Makes it slower", "Both", "None"], "correct": 0},
        {"id": 78, "question": "Which protocol is primarily used by the Web?", "options": ["HTTP", "FTP", "SSH", "Telnet"], "correct": 0},
        {"id": 79, "question": "What is 'JSONP' (JSON with Padding)?", "options": ["An old technique to bypass cross-domain restrictions in browsers", "A newer format", "Neither", "Both"], "correct": 0},
        {"id": 80, "question": "Which of these is used for secure transmission of API data?", "options": ["HTTPS", "HTTP", "FTP", "None"], "correct": 0},
        {"id": 81, "question": "What is 'API Gateway'?", "options": ["Single entry point for multiple microservices", "A gate for APIs", "Neither", "Both"], "correct": 0},
        {"id": 82, "question": "What is 'Rate Limiting'?", "options": ["Controlling API request frequency", "Limiting speed", "Neither", "Both"], "correct": 0},
        {"id": 83, "question": "What is 'API Versioning'?", "options": ["Managing different versions of API simultaneously", "Version control for APIs", "Neither", "Both"], "correct": 0},
        {"id": 84, "question": "What is 'Webhook'?", "options": ["HTTP callback triggered by specific events", "A fishing hook", "Neither", "Both"], "correct": 0},
        {"id": 85, "question": "What is 'CORS' (Cross-Origin Resource Sharing)?", "options": ["Security feature allowing cross-domain requests", "A types of wine", "Neither", "Both"], "correct": 0},
        {"id": 86, "question": "What is 'JWT' (JSON Web Token)?", "options": ["Compact token for API authentication", "A type of web token", "Neither", "Both"], "correct": 0},
        {"id": 87, "question": "What is 'OAuth 2.0'?", "options": ["Authorization framework for third-party access", "A version of OAuth", "Neither", "Both"], "correct": 0},
        {"id": 88, "question": "What is 'GraphQL'?", "options": ["Query language for APIs with flexible data fetching", "A graph query language", "Neither", "Both"], "correct": 0},
        {"id": 89, "question": "What is 'REST' API?", "options": ["Architectural style using HTTP methods", "A restful API", "Neither", "Both"], "correct": 0},
        {"id": 90, "question": "What is 'SOAP' API?", "options": ["Protocol using XML for structured messaging", "A cleaning protocol", "Neither", "Both"], "correct": 0},
        {"id": 91, "question": "What is 'API Documentation'?", "options": ["Technical guide for API usage", "Instructions for APIs", "Neither", "Both"], "correct": 0},
        {"id": 92, "question": "What is 'Postman'?", "options": ["API testing and development tool", "A mail delivery service", "Neither", "Both"], "correct": 0},
        {"id": 93, "question": "What is 'Swagger'?", "options": ["Tool for API documentation", "A type of clothing", "Neither", "Both"], "correct": 0},
        {"id": 94, "question": "What is 'OpenAPI'?", "options": ["Specification for REST APIs", "An open API", "Neither", "Both"], "correct": 0},
        {"id": 95, "question": "What is 'API Testing'?", "options": ["Verifying API functionality and performance", "Testing APIs", "Neither", "Both"], "correct": 0},
        {"id": 96, "question": "What is 'Load Balancing'?", "options": ["Distributing API traffic across multiple servers", "Balancing loads", "Neither", "Both"], "correct": 0},
        {"id": 97, "question": "What is 'Caching'?", "options": ["Storing responses to reduce database load", "Hiding data", "Neither", "Both"], "correct": 0},
        {"id": 98, "question": "What is 'CDN' (Content Delivery Network)?", "options": ["Distributed servers for fast content delivery", "A network for content", "Neither", "Both"], "correct": 0},
        {"id": 99, "question": "What is 'API Monitoring'?", "options": ["Tracking API performance and availability", "Watching APIs", "Neither", "Both"], "correct": 0},
        {"id": 100, "question": "What is 'API Analytics'?", "options": ["Analyzing API usage patterns and metrics", "Studying APIs", "Neither", "Both"], "correct": 0}
    ]
    return Response({'success': True, 'data': random.sample(questions_pool, min(len(questions_pool), 25))})
